### ISSUE TITLE
[Android] WebP stickers with DigitalSourceType XMP metadata are rejected

### ISSUE THREAD

**Issue by zackee12** [WhatsApp/stickers#1001]
**Specifications**  
OS Version: Any
Device Manufacturer: Any

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
There appears to be some internal validator code that is rejecting a sticker with a valid [IPTC DigitalSourceType](https://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#digital-source-type) entry. The IPTC spec provides a list of [valid URI values](https://cv.iptc.org/newscodes/digitalsourcetype/) such as `http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia`. I tinkered with it a bit and observed that the image would be accepted with no metadata or with non-standard values like `digsrctype:positiveFilm`. However, the more recent values added in 2022/2023 are not supported. Would it be possible to update it to match the latest spec with URIs?

**Reproduction Steps**  
1. Find any valid `sticker.webp` that previously works
2. Create a local `metadata.xmp` file setting the field 
```
<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.1.0-jc003">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about=""
        xmlns:Iptc4xmpExt="http://iptc.org/std/Iptc4xmpExt/2008-02-29/"
      Iptc4xmpExt:DigitalSourceType="http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia"/>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="r"?>
```
3. Use `webpmux -set xmp metadata.xmp sticker.webp -o sticker_with_metadata.webp` to add the metadata
4. Observe the image is no longer accepted

**Comment by zackee12** [comment]
> Hi @zackee12, what whatsapp version are you able to reproduce this on?

I'm on v2.24.2.76

**Comment by Korogba** [comment]
This has been fixed. Please re-open if you can still repro in the latest beta version
