### ISSUE TITLE
[Android]Caused by: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by viztushar** [WhatsApp/stickers#103]
**1). Caused by: java.lang.UnsatisfiedLinkError**

[logcat](https://gist.github.com/viztushar/8e70e1b8daa01a91ef70bb76671eac8a)

this occurs **23** times in **android 9.0,8.1,6.0,5.1**

**2). Caused by: java.lang.NullPointerException**

[logcat](https://gist.github.com/viztushar/f5b3e2e042f09dfb2a9cd06e39c3fcbf)

this occurs **28** times in **android 6.0,5.0,51,4.4**

**3). Caused by: java.util.concurrent.TimeoutException**

logcat:
```
java.util.concurrent.TimeoutException: 
  at java.lang.Daemons$Daemon.isRunning (Daemons.java:79)
  at java.lang.Daemons$FinalizerDaemon.run (Daemons.java:174)
  at java.lang.Thread.run (Thread.java:818)
```
this occurs **2** times in **android 5.1**

**Comment by simonzhexu** [comment]
For 1) and 2)hat indicates, Fresco (a library we use to handle webp image decoding) is not loading its native library. What changes have you made to your code? 

3) need more information to debug.

**Comment by viztushar** [comment]
@simonzhexu i change nothing. I got all those logs from play Console.

**Comment by simonzhexu** [comment]
Should be fixed now with the latest commit.
