### ISSUE TITLE
Work Friends's Chat 

### ISSUE THREAD

**Issue by DU01313** [WhatsApp/stickers#1035]
**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ ] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for stickers.

**Problem Description**  
[FILL IN WITH DETAILED DESCRIPTION OF THE PROBLEM]

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? 
![2](https://github.com/user-attachments/assets/c533b2c5-6890-4e53-a3c9-aa7d4320d473)
![3](https://github.com/user-attachments/assets/55691423-1960-466f-a334-e1490be20f49)
![4](https://github.com/user-attachments/assets/6062b275-3166-4a86-a38c-1eebc39e9251)
![5](https://github.com/user-attachments/assets/ac9e6f1e-4cc9-4e8e-a0aa-08f368a50d64)
![6](https://github.com/user-attachments/assets/e4d99953-de4b-4ec0-a2fe-84e97034911f)
![7](https://github.com/user-attachments/assets/fa1155cf-b250-4dbf-8099-0853ee27e03a)
![8](https://github.com/user-attachments/assets/51522321-2366-4e71-b906-40af22b05737)
![9](https://github.com/user-attachments/assets/c6adf756-48ff-4624-86f2-d802adcfd1f6)
![12](https://github.com/user-attachments/assets/55135237-05d4-40d1-b48f-abbee610f91b)
![13](https://github.com/user-attachments/assets/8ebf8d44-c559-4da4-b9d2-597a3ec8b1e4)
![14](https://github.com/user-attachments/assets/af589c5b-5fc5-470d-a54c-f7e914f6e879)
![15](https://github.com/user-attachments/assets/37af3108-259d-43aa-a2ef-86035ca228a0)
![16](https://github.com/user-attachments/assets/75004a41-473f-43de-bb47-afcaa92d9f57)
![17](https://github.com/user-attachments/assets/12c6738b-8377-4140-87d5-8ca074e2b2df)
![18](https://github.com/user-attachments/assets/6a30ac14-8d4a-47df-bb44-fa694ab789de)
![19](https://github.com/user-attachments/assets/705f97d2-18b6-4153-875f-0ab3aeca4455)
![20](https://github.com/user-attachments/assets/32e1ad4a-6f4f-4f10-8383-e00353dedd4c)
![21](https://github.com/user-attachments/assets/e0ac809a-d87b-4676-bc37-e517a31d53c4)
![22](https://github.com/user-attachments/assets/a549ec4b-e698-4b92-9563-0c9038909ceb)
![23](https://github.com/user-attachments/assets/1694b13a-aaae-4781-9916-c5a7ea19632d)
![24](https://github.com/user-attachments/assets/9e574dae-d146-4daf-a674-ca30afa7bf9a)
![1](https://github.com/user-attachments/assets/5a6ac4a6-eb8b-4192-9c65-529d6cbca42f) not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN PLAY STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by cpinan** [comment]
Can you upload them together as a zip with numbers for each frame? I can give a try to see what it's happening

**Comment by DU01313** [comment]
rar file not support

**Comment by DU01313** [comment]
can you help me add this this stickers  whats app
