### ISSUE TITLE
How to include more than one stickers pack in ios

### ISSUE THREAD

**Issue by edmundhei** [WhatsApp/stickers#106]
I would like to add more then one pack of stickers into the sample ios app

I saw that on the [readme.md](https://github.com/WhatsApp/stickers/blob/master/iOS/README.md) for ios 

> If your app has more than 1 sticker pack, you will need to reference it in sticker_packs.wasticker. Simply create a second array within the "sticker_packs" section of the file and include all the metadata (name, identifier, etc) along with all the references to the sticker files.

I did add a second array with in the sticker_pack section but when I run the app it said that the sticker_packs.wasticker 

> Thread 1: Fatal error: The data couldn’t be read because it isn’t in the correct format.

.

**sticker_packs.wasticke**
```
{
"ios_app_store_link" : "",
"android_play_store_link" : "",
"sticker_packs" : [
{
"identifier": "ltestingID",
"name": "testing",
"publisher": "testing",
"tray_image_file" : "icon.png",
"publisher_website" : "",
"privacy_policy_website" : "",
"license_agreement_website" : "",
"stickers": [
{
"image_file": "1.png",
"emojis": ["👋","🤗"]
},
{
"image_file": "2.png",
"emojis": ["❤️","😍"]
},
{
"image_file": "3.png",
"emojis": ["👌"]
},
{
"image_file": "4.png",

}

]

}
{
"identifier": "ltestjjjngID",
"name": "testing",
"publisher": "testing",
"tray_image_file" : "icon.png",
"publisher_website" : "",
"privacy_policy_website" : "",
"license_agreement_website" : "",
"stickers": [
{
"image_file": "1.png",
"emojis": ["👋","🤗"]
},
{
"image_file": "2.png",
"emojis": ["❤️","😍"]
},
{
"image_file": "3.png",
"emojis": ["👌"]
},
{
"image_file": "4.png",

}

]

}






]


}

```

**Comment by viztushar** [comment]
{

"ios_app_store_link" : "",

"android_play_store_link" : "",

"sticker_packs" : [

{

"identifier": "cuppyID",

"name": "Cuppy",

"publisher": "Jane Doe",

"tray_image_file" : "tray_Cuppy.png",

"publisher_website" : "",

"privacy_policy_website" : "",

"license_agreement_website" : "",

"stickers": [

{

"image_file": "01_Cuppy_smile.png",

"emojis": ["☕","🙂"]

},

{

"image_file": "02_Cuppy_lol.png",

"emojis": ["😄","😀"]

},

{

"image_file": "03_Cuppy_rofl.png",

"emojis": ["😆","😂"]

},

{

"image_file": "04_Cuppy_sad.png",

"emojis": ["😃", "😍"]

},

{

"image_file": "05_Cuppy_cry.png",

"emojis": ["😭","💧"]

}]

},
{

"identifier": "cuppyID",

"name": "Cuppy",

"publisher": "Jane Doe",

"tray_image_file" : "tray_Cuppy.png",

"publisher_website" : "",

"privacy_policy_website" : "",

"license_agreement_website" : "",

"stickers": [

{

"image_file": "01_Cuppy_smile.png",

"emojis": ["☕","🙂"]

},

{

"image_file": "02_Cuppy_lol.png",

"emojis": ["😄","😀"]

},

{

"image_file": "03_Cuppy_rofl.png",

"emojis": ["😆","😂"]

},

{

"image_file": "04_Cuppy_sad.png",

"emojis": ["😃", "😍"]

},

{

"image_file": "05_Cuppy_cry.png",

"emojis": ["😭","💧"]

}]

}
]

}

**Comment by lwangeli** [comment]
Thank you!! But actually it will crash if didnt use diffrent "identifier".

**Comment by viztushar** [comment]
@lwangeli actually I forgot to change that😅.

**Comment by Mithil86** [comment]
{
    "ios_app_store_link" : "",
    "android_play_store_link" : "",
    "sticker_packs" : [
    {
        "identifier": "Pack1",
        "name": "Testing",
        "publisher": "Test",
        "tray_image_file" : "tray_Cuppy.png",
        "publisher_website" : "",
        "privacy_policy_website" : "",
        "license_agreement_website" : "",
        "stickers": [
        {
            "image_file": "t1.png",
            "emojis": ["☕","🙂"]
        },
        {
            "image_file": "t2.png",
            "emojis": ["😄","😀"]
        },
        {
            "image_file": "t3.png",
            "emojis": ["😆","😂"]
        }]
    },
    {
        "identifier": "Pack2",
        "name": "Testing",
        "publisher": "Test",
        "tray_image_file" : "tray_Cuppy.png",
        "publisher_website" : "",
        "privacy_policy_website" : "",
        "license_agreement_website" : "",
        "stickers": [
        {
        "image_file": "t6.png",
        "emojis": ["☕","🙂"]
        },
        {
        "image_file": "t7.png",
        "emojis": ["😄","😀"]
        },
        {
        "image_file": "t8.png",
        "emojis": ["😆","😂"]
        }]
    }
 ]
}
