### ISSUE TITLE
Remove sticker limit

### ISSUE THREAD

**Issue by viztushar** [WhatsApp/stickers#107]
I published my app to the play store and now all my user want more sticker but I can't add because of the 30 sticker limit please help me here.

**Comment by MarvinJWendt** [comment]
The current limitation is: 

- 30 stickers per pack
- 10 packs per app

So summed up you can add up to 300 Stickers into one app.

**Comment by viztushar** [comment]
@MarvinJWendt yeah that's true but when you think about user point of view it's not a great idea to do that. because user have to install again and again. That's not work well.

**Comment by tetyanab** [comment]
It's reasonable to have about 30 max limit of stickers per pack. But an app which is just a container of possible sticker packs could contain more than 10 packs (a user comes back to such an app only to browse possible packs and import them, a one-time action per pack). Has anyone tried removing the limit of 10 packs per app and publishing it (Android/iOS)?

**Comment by tkbstudios** [comment]
This is not closed.

Excuse my but people should be able to add as much stickers as they want I guess, I mean that needing to create 2 packs to add 60 stickers and the limit of 10 packs, it isn't so much.
