### ISSUE TITLE
.java problems

### ISSUE THREAD

**Issue by shineeasley** [WhatsApp/stickers#110]
C:\Users\Xeqk\Downloads\stickers-master\stickers-master\android\app\src\main\java\com\example\samplestickerapp\StickerPackListActivity.java:
uses unchecked or unsafe operations.
Recompile with -Xlint:unchecked for details.

Plz help me :(

**Comment by simonzhexu** [comment]
I will fix it, but this doesn't prevent you from building and installing the app. It is just a warning.
