### ISSUE TITLE
Your applicationId is currently com.example.samplestickerapp, please change your applicationId to a different string in app/build.gradle

### ISSUE THREAD

**Issue by Sapu98** [WhatsApp/stickers#113]
When I launch my app using I get this error, probably this is easily fixable but i don't know how...

**Comment by tbschff** [comment]
Like the error message states: Edit app/buils.gradle in __line 16__ (appicationId).
Naming convention for package name can be found here: [Wikipedia - Java package naming conventions](https://en.wikipedia.org/wiki/Java_package#Package_naming_conventions)

**Comment by crazy123098** [comment]
org.gradle.api.GradleException: Your applicationId is currently com.example.tamilfunsticker, please change your applicationId to a different string in app/build.gradle in line 10

**Comment by MarvinJWendt** [comment]
Hi @crazy123098 please change the value of `applicationId` to something different.
[More](https://developer.android.com/studio/build/application-id)
