### ISSUE TITLE
Add Stickers to existing App

### ISSUE THREAD

**Issue by derN3rd** [WhatsApp/stickers#115]
Hey there, just wanted to know if there is anything against adding a sticker pack to a existing app.
Could I just add the Provider to my existing android app and release them with a new app update? Would it also work for ios?

Thanks in advance

**Comment by simonzhexu** [comment]
Yes. You can add a provider to your existing android app, as a way to provider stickers into WhatsApp. For iOS, as long as you have a way to export the wasticker file following the advanced development section. You are good.
