### ISSUE TITLE
emoji and share button

### ISSUE THREAD

**Issue by setanindo** [WhatsApp/stickers#120]
emotion categories (love, happy, sad, and angry)

what active emoji right now ??
and how add share button

ðŸ˜”,A_sad1
ðŸ˜Œ,A_sad2
ðŸ˜’,A_sad3
ðŸ˜ž,A_sad4
ðŸ˜£,A_sad5
ðŸ˜¢,A_sad6
ðŸ˜‚,A_sad7
ðŸ˜­,A_sad8
ðŸ˜ª,A_sad9
ðŸ˜¥,A_sad10
ðŸ˜°,A_sad11
ðŸ˜…,A_sad12
ðŸ˜“,A_sad13
ðŸ˜©,A_sad14
ðŸ˜«,A_sad15

**Comment by amricanooo** [comment]
Sad
