### ISSUE TITLE
Your applicationId is currently com.goodapp.stickers, please change your applicationId to a different string in app/build.gradle 

### ISSUE THREAD

**Issue by youssefom** [WhatsApp/stickers#123]
when i try to build my app they say that Your applicationId is currently com.goodapp.stickers, please change your applicationId to a different string in app/build.gradle 
Already i have change applicationId

**Comment by simonzhexu** [comment]
You should only change it at line 16 of build.gradle. That is the only place. If you change it in line 62 and line 63. You will get this error.
