### ISSUE TITLE
stickers not showing in whatsapp, but are showing in the stickers app itself

### ISSUE THREAD

**Issue by RobinDew** [WhatsApp/stickers#125]
I can not see my custom stickers in whatsapp but they are visible in the stickers app itself. What could be causing this? I made sure they are under 100kb each, are 512x512 sized and that they are webp files. The naming in the json is also correct.

**Comment by amrit-1901** [comment]
What do you mean by "can not see my custom stickers in whatsapp"? Are you not able to import them or do they not show in the picker?

**Comment by RobinDew** [comment]
They do not show in the picker

**Comment by cremus** [comment]
I have exactly the same problem.

**Comment by kalyanbhanushali** [comment]
I have too

**Comment by cornelg7** [comment]
After a dozen hours of 'try-again's I've managed to solve this for me.  When converting from png to webp, be careful not to save any metadata.  If you're using the same photoshop plugin as I am ( https://github.com/fnordware/AdobeWebM#download ), then you must have unchecked the "Save Metadata" box.
![image](https://user-images.githubusercontent.com/13762182/48237168-21860700-e3ce-11e8-94ef-047b8abda492.png)

Hope this helps.

**Comment by BJack123** [comment]
I have this issue too

**Comment by mumayank** [comment]
### SOLVED !
I found the reason for this. Working solution here:
https://github.com/WhatsApp/stickers/issues/167#issuecomment-437684615

Please put a thumbs up ( :+1: ) if the answer worked for you. I'd highly appreciate it :)
