### ISSUE TITLE
upload sticker

### ISSUE THREAD

**Issue by superteacher2019** [WhatsApp/stickers#126]
I have publish webp file as sticker how  can I upload it?

**Comment by IbnAldolah** [comment]
![abusultan sticker 1](https://user-images.githubusercontent.com/44698761/47910400-2c133e80-deac-11e8-8b16-714918ab3141.png)

**Comment by superteacher2019** [comment]
? can you explain more


مرسل من Outlook<http://aka.ms/weboutlook>

________________________________
من: Alkathiri <notifications@github.com>
‏‏تم الإرسال: 24/صفر/1440 10:46 ص
إلى: WhatsApp/stickers
نسخة: superteacher2019; Author
‏‏الموضوع: Re: [WhatsApp/stickers] upload sticker (#126)


[abusultan sticker 1]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F44698761%2F47910400-2c133e80-deac-11e8-8b16-714918ab3141.png&data=02%7C01%7C%7Ca7a7c14858544158d0ec08d640b06aef%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636767523776565001&sdata=sQ6ivOUIJxQckja7UMGQQ06eGDUVyvUApmarFEpJNxM%3D&reserved=0>

**Comment by simonzhexu** [comment]
Question is not clear. Please clarify.
