### ISSUE TITLE
[iOS] Error: There's a problem with this sticker pack and it can't be added to WhatsApp

### ISSUE THREAD

**Issue by ameralzarouni** [WhatsApp/stickers#127]
I have a problem, the app launches and works, the Add to WhatsApp button works, but WhatsApp gives the following error on iPhone X: There's a problem with this sticker pack and it can't be added to WhatsApp. I've checked and all the stickers are less than 50 kb. The tray icon is 11 kb.

**Comment by Alex193a** [comment]
Have you checked that all stickers are 512x512px and the tray icon is 96x96px?

**Comment by ameralzarouni** [comment]
Yes, and they are all below 50 kB even though the requirement is under 100 kb

**Comment by lonesnipers** [comment]
Is there a solution to this problem? Anyone? I don't think it's complicated problem. We just need to know what could be the problem...

**Comment by amrit-1901** [comment]
What version of iOS are you using?

**Comment by ameralzarouni** [comment]
I am using iOS 11.x

**Comment by hamaddev** [comment]
> I have a problem, the app launches and works, the Add to WhatsApp button works, but WhatsApp gives the following error on iPhone X: There's a problem with this sticker pack and it can't be added to WhatsApp. I've checked and all the stickers are less than 50 kb. The tray icon is 11 kb.

@ameralzarouni 

i'm using Jailbroken device with IOS 9.x having the same error, basically its a UIPasteboard problem, to fix that you have to clear the Clipboard History, and it'll work smoothly, i'm using Action Menu Tweak from cydia,

**Comment by pchirag** [comment]
i have same issues " there's a problem with this sticker pack and it can't be added to WhatsApp to [iOS]There's a problem with this sticker pack and it can't be added to WhatsApp "

**Comment by ameralzarouni** [comment]
My device is not jailbroken. Just checked again, the WebP framework is in the project. I am still getting this error for both of my sticker packs. If it helps, I am using WebP images. I am on iOS and using Xcode.

**Comment by ameralzarouni** [comment]
I tried it on an iPhone 6S running iOS 10.x and I have the same problem.

**Comment by ameralzarouni** [comment]
To all that say theWebP framework not being imported is the problem, it is not the problem for us, nor is the file or image sizes The WebP framework has already been loaded and the images are under 100 kB.

**Comment by ameralzarouni** [comment]
@WhatsApp This is taking too long to solve!

**Comment by lonesnipers** [comment]
Seriously! Does anybody have a clue what might be the problem?

**Comment by wsimf** [comment]
This happened when running the provided pack without any modifications (apart from changing the bundle identifier)

**Comment by amrit-1901** [comment]
To everyone having this issue, we need logs to debug this:
- Right after you see the "There's a problem with this sticker pack and it can't be added to WhatsApp" alert, tap OK
- While still remaining in WhatsApp, go to Settings->Help->Contact Us
- Describe this issue and make sure to write the word "GitHub" somewhere in your description (this will make sure we can prioritize your support tickets)

**Comment by lonesnipers** [comment]
@amrit-1901 yeah done. Hopefully this gets resolved at the earliest. Thank you.

**Comment by ameralzarouni** [comment]
@amrit-1901 Done

**Comment by amrit-1901** [comment]
@ameralzarouni Your WEBP image fails our integrity check. Did you use a PNG image and let the app do the conversion or did you use a straight WEBP image?

**Comment by amrit-1901** [comment]
The other ticket I've got is about the stickers count being more than 30 (31 to be exact). I'm not sure if it was @lonesnipers since the names were different.

**Comment by lonesnipers** [comment]
@amrit-1901 I've sent a screenshot for a football club sticker app. What is the issue with mine? I've used png images and converted them to webp in Android sdk.

**Comment by amrit-1901** [comment]
I have not received your ticket. Can you try send it again? In the meantime, can you try using your original PNG images and let the app do the conversion?

**Comment by lonesnipers** [comment]
Hi, I've sent it again with the word github specified twice. The description starts with:

[Android]Error: There's a problem with this sticker pack and it can't be added to WhatsApp

email: dsouzasanford@hotmail.com

I tried using the original png images, but 
the app doesn't get installed. It gives an error: App not installed.

**Comment by guharakesh** [comment]
@amrit-1901 I sent my logs as well, hope you can help. The description is `Getting the "problem with this sticker pack" error as noted in GitHub. Trying to package stickers with our native app. Would love some guidance, thanks!`

email: rakesh@startincle.com

**Comment by ameralzarouni** [comment]
@amrit-1901 I am using Paint.Net to edit the images with a plugin to save as WebP.

**Comment by ameralzarouni** [comment]
Update: I managed to get the stickers working by uploading them as png in Xcode and not as WebP.

**Comment by chr0m1ng** [comment]
PNG is working fine, the problem only appears when using webp. Still waiting fixes for that...

**Comment by guharakesh** [comment]
@ameralzarouni or @chr0m1ng was this on Android? How were you able to avoid getting this error: `contents.json file has some issues: image file for stickers should be webp files, image file is: 01.png`? The app failed to start after that error.

**Comment by amrit-1901** [comment]
Also, I noticed that some of you are complaining about Android instead of iOS. @simonzhexu can take care of that issue. However, please for anyone new having this issue, please create a separate issue for Android: it makes it much easier to manage.

**Comment by lonesnipers** [comment]
There is a separate one for Android, but nobody is replying there. So, we are writing about it here.

**Comment by simonzhexu** [comment]
For Android, follow this, https://github.com/WhatsApp/stickers/issues/104#issuecomment-437459131 and comment in https://github.com/WhatsApp/stickers/issues/104

**Comment by simonzhexu** [comment]
> @ameralzarouni or @chr0m1ng was this on Android? How were you able to avoid getting this error: `contents.json file has some issues: image file for stickers should be webp files, image file is: 01.png`? The app failed to start after that error.

your sticker files need to be in webp. Follow the read me to convert png to webp please.

**Comment by ameralzarouni** [comment]
@simonzhexu I tried using WebP images in the app but they give the error this issue is about. When I used PNG images without converting them, they worked perfectly well and I didn’t get any error.

**Comment by Zandor300** [comment]
Also having this problem, just sent logs. I have 2 own stickers in webp using the suggested Photoshop plugin. Both are under 100 kb and are exactly 512x512. Then I also have one of the sample stickers added to the pack in png as the artist isn't done with the rest yet.

**Comment by ameralzarouni** [comment]
I used 8-bit PNG and it worked perfectly

**Comment by simonzhexu** [comment]
> @simonzhexu I tried using WebP images in the app but they give the error this issue is about. When I used PNG images without converting them, they worked perfectly well and I didn’t get any error.

Your content.json should reference the file in .webp not .png, if those are sticker files.

**Comment by lackern** [comment]
Seems like the import statement at YYImageCoder.m is case sensitive.

Changing from webp to WebP for all the imports in this class works for me.

**Comment by aal89** [comment]
I also had this problem and fixed it by changing the bundle identifier to something completely different. Apparently they are doing a `contains`, so simply adding one character (like I did before) won't help.

**Comment by ameralzarouni** [comment]
@simonhexu By using PNG images and referencing them as .png worked perfectly on iOS, when I used webp, it didn’t work.

**Comment by sanestani** [comment]
My problem was uploading the app to the itunes connect. Do this happened to you?

**Comment by Alex193a** [comment]
Apple has started removing all WhatsApp stickers apps from the store because they violate their guidelines.

**Comment by sanestani** [comment]
@Alex193a Yes, I know, but is there any way to fix this?

**Comment by Alex193a** [comment]
@sanestani I don't think, WhatsApp will have to create a universal app, probably.
The current method of adding stickers is totally wrong, it surprises me that they have not figured it out yet.

**Comment by BhaktiKarva** [comment]
I am facing the same error. I am opening what's app from my iMessage extension. I am following the advanced development tutorial and successfully created a sticker pack. It opens what's app, I get the message, importing sticker pack and then it says "There's a problem importing this sticker pack."
I am using png images and all images are less than 50kb and are 512x512. I know there is no problem in images because the same work for android. But I am not able to get them to work on ios.

**Comment by thyagotosin** [comment]
same problem with me, @BhaktiKarva and the others. Waiting WhatsApp's Team.

**Comment by Zandor300** [comment]
>If you build a debug version of sticker app, and try to add to WhatsApp. When the add fails, you will get a dialog that tells you what was wrong. In order to build a debug version, change your build variants in Android studio, and click run.
>
https://github.com/WhatsApp/stickers/issues/104#issuecomment-437459131

@amrit-1901 Is it possible to also get this on the iOS version of WhatsApp?

**Comment by BhaktiKarva** [comment]
> To anyone having this issue, we need logs to debug this:
> 
> * Right after you see the "There's a problem with this sticker pack and it can't be added to WhatsApp" alert, tap OK
> * While still remaining in WhatsApp, go to Settings->Help->Contact Us
> * Describe this issue and make sure to write the word "GitHub" somewhere in your description (this will make sure we can prioritize your support tickets)

I did what you asked and it generated a log file, attached it in the mail and was sent. I went trough the generated log file and found this : 
```
2018-11-20 11:57:14.818 [ 363501] [main-thread   ] [F] LL_A* third-party-sticker-validating//failed to verify sticker image webp file
2018-11-20 11:57:14.854 [ 363501] [main-thread   ] [F] LL_A* app/open-url/third-party-sticker: invalid sticker pack
2018-11-20 11:57:14.856 [ 363501] [main-thread   ] [F] LL_A* alert: [‎There's a problem with this sticker pack and it can't be added to ‎WhatsApp.] [(null)]
```
I am not sure as to what is this error, but one or more of my stickers is not proper, that is why I think I am facing error. What do you think?

**Comment by BhaktiKarva** [comment]
I was finally able to solve my problem!
This is what I did 
1. Removed all files that I had added. Download the project from GitHub again. 
2. Added all the required files in my project again.
3. After running the app for the first time, I got the same error. I clicked on "ok", while still remaining in Whats App, went to Setting->Help->Contact Us. Typed anything until the "next" button got enabled, clicked next->This does not solve my issue. It opened mail, and attached my logs in that mail. I just saved the mail in drafts and accessed the logs from there.
4. I went through the logs and found out that my tray image was not being rendered properly into webp format. Modified my tray image and it worked for me.

Note : I am opening this from my iMessage extension and not from a container app and it still works for me.
You may be getting different errors, but this helps in getting the logs and identifying why it is not importing packs.

Hope this helps!

**Comment by ameralzarouni** [comment]
@BhaktiKarva Using 8-bit PNG images instead of webp should work.

**Comment by thyagotosin** [comment]
I tried with 8-bit PNG, doesn't worked.

**Comment by abokhalel2** [comment]
I had the same issue today, and the only thing that fixed it is adding "WebP.framework" properly to my project.

**Comment by Androidsignal** [comment]
im getting this error plzz help me:

exception fetching input stream uri:content://ne.stickers.whatsapp.com.whatsappstickers.WhatsAppLicensedCode.StickerContentProvider/stickers_asset/b7a29678-e7ae-4182-87d0-f1e9fa66e7e6/0, exception message: fd must not be null

**Comment by parthmodi605** [comment]
operation couldn't be completed (com.third-party-stickers error 1000) what is this error?

**Comment by markkorput** [comment]
I'm trying to add stickers, having translated the necessary logic from you swift example application to objective-c (I can't use swift for unrelated reasons).

I'm getting the dreaded failure message and as per above instructions managed to get the logs, which aren't much more informative;

```
2020-02-24 11:38:28.933 [2778334] [main-thread   ] [F] LL_A* third-party-sticker-parsing//invalid sticker image data

2020-02-24 11:38:29.146 [2778334] [main-thread   ] [F] LL_A* app/open-url/third-party-sticker: invalid sticker pack
```

I'm using the same png images from the example app (that app works fine by the way) and translated the webp conversion logic as directly as possible from swift to objective-c. I'm able to load the png images at runtime, convert them to a webp string, and re-decode that string into a UIImage which shows up fine in my test app, so technically the webp data I'm giving _should_ be fine. 

I had similar issues on Android (See #606) where there was a minor issue with the file, even though they loaded fine into the app's UI. Your opaque validation policy isn't helping much with finding issues though.

Help would be appreciated.

**Comment by Teja-Batchu** [comment]
I am also getting same issue with Animated stickers. Normal stickers working fine, when i am trying to add Animated stickers i am getting alert from WhatsApp like "There's a problem with this sticker pack and it can't be added to WhatsApp". 

Is there any way to figure out this issues? Same animated stickers working fine in android project.

**Comment by b14554124** [comment]
> 

please cheak yor json have Key: "animated_sticker_pack"
if your webp Image from GIF  is  true  ,    png:"  false

**Comment by rajivbudhiraja13** [comment]
I am able to add sticker pack to whatsapp and whatsapp business but while adding to parallel whatsapp, it's giving error "There's a problem..."
Can anyone give any solution?

**Comment by axeleszu** [comment]
I solve the problem by changing webp to png. Some forums suggest using a different webp converter tool.
