### ISSUE TITLE
[iOS] Sending to Whatsapp but crashing

### ISSUE THREAD

**Issue by enzyme69** [WhatsApp/stickers#133]
I can see the app keeps on crashing from XCode and pointing into this line:
                fatalError("Your bundle identifier must not include the default one.");

Is this because I have to change the name of Sticker, not to use Cuppy? I have Cuppy Stickers official from WA already?

**Comment by enzyme69** [comment]
Ok seems to be working after I rename a couple of things...

**Comment by marlosirapuan** [comment]
@enzyme69 what did you do? here also gave this error

**Comment by marlosirapuan** [comment]
I found the error. Can not contain "WA" in the identifier.
