### ISSUE TITLE
[iOS]Xcode usage being rejected by apple

### ISSUE THREAD

**Issue by ranrinc** [WhatsApp/stickers#135]
Apple seems to reject the code, saying that I copied someone program. Anyone having this same problem? How can I submit my sticker without getting rejected by apple?  Thanks in Advance.

**Comment by sguidobono** [comment]
I have the same problem and I do not know how I can solve it. If anyone knows what can be done, it would be great.

**Comment by arnemoor** [comment]
I got my [app](https://itunes.apple.com/app/real-orchid-stickers/id1441354968) approved, but I also included an iMessage extension.

**Comment by ranrinc** [comment]
@arnemoor can u colaborate how to put in the iMessage extension??

**Comment by arnemoor** [comment]
@ranrinc Just take the working WAStickers:
1. Press command + 1 to open the project navigator
2. Select the top root (WAStickersThirdParty) in Navigator 
3. Press + or select "Edit / Add Target
4. Select Sticker Pack Extension
5. Next

<img width="1117" alt="screenshot 2018-11-09 at 19 04 37" src="https://user-images.githubusercontent.com/8458214/48280134-07dad300-e453-11e8-9b35-4425fce341fa.png">

6. Give a project name (best to take the same as for the WA Stickers)

<img width="735" alt="screenshot 2018-11-09 at 19 08 29" src="https://user-images.githubusercontent.com/8458214/48280182-2b058280-e453-11e8-9464-29a4cb2cc101.png">

7. Activate the Project schema
8. Drop iMessage Stickers (206px @3 = 618px) into the stickers folder
9. Drop the needed iMessage Icons (different size than the AppIcons)

Hope this helps

**Comment by lwangeli** [comment]
Hi there. Anyone can give some help? Apple rejected my sticker app for whatsapp, just because I have the same one for iMessage, but I cant rebuild the original one because it will not validate as you can see on the image. So, how can I pass the review or rebuild the original one to pass validation? 
![validation](https://user-images.githubusercontent.com/22224336/48323273-2800c280-e60a-11e8-86dd-ced48d879609.png)

**Comment by ranrinc** [comment]
@Iwangeli check apple server, sometimes its down during a maintenance process.

**Comment by ranrinc** [comment]
@arnemoor Thank you for the information..very helpfull

**Comment by arnemoor** [comment]
@lwangeli A "sticker only" package can not be upgraded to contain executable code / an app (This is an apple restriction). You need to follow the above steps and create a new package with slightly changed bundle identifier. As a side not, the supported iOS version needs to be set to 10.0 (iMessage stickers where then introduced).

**Comment by lwangeli** [comment]
@arnemoor Thanks. Apple did not explain the rejection, just do it over 4.3 guidelines, and this last time they threatened me by closing Dev Account.

**Comment by Zandor300** [comment]
Closed in favor of a more active issue: https://github.com/WhatsApp/stickers/issues/230
