### ISSUE TITLE
m.ys0

### ISSUE THREAD

**Issue by meys0** [WhatsApp/stickers#143]
![img_1195](https://user-images.githubusercontent.com/44747152/47964869-d29a4380-e054-11e8-8c3a-9a57dc0ffe37.png)
![img_1197](https://user-images.githubusercontent.com/44747152/47964874-e3e35000-e054-11e8-90e7-e35a95e6653a.png)
![img_1196](https://user-images.githubusercontent.com/44747152/47964881-f198d580-e054-11e8-930b-dda997e753f1.png)
![img_1198](https://user-images.githubusercontent.com/44747152/47964882-f78eb680-e054-11e8-9c4a-5bab6c6d00ee.png)
![04259a5475f149bf10c139e8a8101c4a1e344f631fb0-r3z07g_fw658](https://user-images.githubusercontent.com/44747152/47964890-04aba580-e055-11e8-8ec3-c335d48b00fd.png)

**Comment by simonzhexu** [comment]
spam reported.
