### ISSUE TITLE
[Android]"View More" button not displayed

### ISSUE THREAD

**Issue by davidmarinangeli** [WhatsApp/stickers#147]
Hello, I've published my stickers pack but the popup that appears when you click on my stickers doesn't display "View More" button. 

Why?

(I've updated my description on Play Store with the tag but it still doesn't work )

**Comment by davidmarinangeli** [comment]
Just figure it out. 

My app's link was wrong 🙈. Thanks for your help.

**Comment by Aravindhan95** [comment]
where i want to place my app link @davidmarinangeli ?

**Comment by davidmarinangeli** [comment]
I don't speak Spanish sorry, however the link goes in the dedicated field in `contents.json` along with mail and other pack info

**Comment by minuskaira** [comment]
Where can I find the right contents.json? I find a lot of them
