### ISSUE TITLE
[Android]Play Store rejecting the app for using the tag "WAStickerApps"

### ISSUE THREAD

**Issue by nicolasdeory** [WhatsApp/stickers#148]
I got my app rejected (AFTER being published for about 2 days) for using the tag "WAStickerApps" in both the short and long app description. The tag was written just once, so there was no misuse or excessive use.

After reaching out to Google to appeal the rejection ex, they still refused to accept my explanation, that the tag was being used following WhatsApp's guidelines. So I had to remove the tag from all translations.

I advise not to use the tag unless you want to end up having to delete it anyway and lose several days of potential installs.

**Comment by ranrinc** [comment]
oh noooo... both apple and google reject sticker apps..

**Comment by ptkdev** [comment]
My app is publish on [android](https://play.google.com/store/apps/details?id=io.ptkdev.wastickers) and [ios](https://itunes.apple.com/app/ptkdev-stickers-for-wa/id1440418846)

**Comment by nicolasdeory** [comment]
@ptkdev You're not using the tag so you're probably fine.

**Comment by ptkdev** [comment]
@nicolasdeory imho this tag is useless, people don't search "WAStickerApps" but search "stickers whatsapp". I add tags: `stickers`, `stickers whatsapp`, `whatsapp` on metadata tags list.

**Comment by ranrinc** [comment]
@ptkdev could you explain what did you do.. in order to bypass iOS check and android? Cause they keep saying the apps must be unique...

**Comment by ptkdev** [comment]
@ranrinc 
Android: nothing, play store accept all app. I change unique id of app in gradle, import my stickers, refactor directory name in android studio, correct IARC rating for 14 >= age and social network category. 

iOS: i not use whatsapp word in name but WA. I change unique id of app, refactor directory in xcode. When Apple reject my app i write to tester with link of whatsapp FAQ and this repo. Tester switch reject status to review and approve my app. But when i send v1.1 update Apple reject stickers and i wait for approve update again.

On ios is Lucky. Android is easy.

**Comment by nitinjainpy** [comment]
@ptkdev 
"WAStickerApps" is actually an essential tag. Because in the Android readme.md, it is specified that we must us this keyword in order to list our apps in the search.

> To help your app appear in this list, also add the keyword WAStickerApps to app's description when setting up your app in the Google Play Store console. You can use additional keywords, but make sure you at least use this one.

And also, in the sticker section of WhatsApp on Android, when we click the "Get More Stickers" button at the bottom of 'All Stickers', it takes you to a search page where the search keyword is "WAStickerApps".

So, using the keyword "WAStickerApps" is very much essential.

**Comment by ptkdev** [comment]
@nitinjainpy on iPhone and android this button "all stickers" don't exist. Screenshot and What version of whatsapp you use?

**Comment by lemzouri** [comment]
Hi
can someone please give me source code of WAStickerApps
I have try to do Reverse engineering but it don't work for me

Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:58)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:516)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:81)

**Comment by nitinjainpy** [comment]
![whatsapp](https://user-images.githubusercontent.com/43243762/48310938-6e7c0000-e5bd-11e8-95ec-81ab0b8d333c.png)

@ptkdev As you can see in the bottom of this Screenshot from WhatsApp's 'All Stickers' page. There's a button "Get More Stickers". You can navigate to that page by clicking on the plus icon (+) in the stickers menu on WhatsApp.

WhatsApp Version 2.18.342

**Comment by nitinjainpy** [comment]
@lemzouri 
https://github.com/WhatsApp/stickers/tree/master/Android

**Comment by zaidmonis** [comment]
> @ranrinc
> Android: nothing, play store accept all app. I change unique id of app in gradle, import my stickers, refactor directory name in android studio, correct IARC rating for 14 >= age and social network category.
> 
> iOS: i not use whatsapp word in name but WA. I change unique id of app, refactor directory in xcode. When Apple reject my app i write to tester with link of whatsapp FAQ and this repo. Tester switch reject status to review and approve my app. But when i send v1.1 update Apple reject stickers and i wait for approve update again.
> 
> On ios is Lucky. Android is easy.

can you tell me how'd you select the content Rating?

**Comment by ptkdev** [comment]
@zaidmonis nice! i'm happy for you :D

**Comment by ptkdev** [comment]
**SOLVED**: is mandatory IARC rating for 14 >= age in social network category.

**Comment by diepox** [comment]
> **SOLVED**: is mandatory IARC rating for 14 >= age in social network category.

I submitted my app in i go this Issue: Incorrect content rating
Your app’s content rating is incorrect. Our content rating system includes official ratings from the International Age Rating Coalition (IARC) and is designed to help developers communicate locally relevant content ratings to users.

can you help?  which questions you did "YES" & "NO"

**Comment by ptkdev** [comment]
Set violence on YES and on submenu set Little violence on YES. Rating increase from 12  to 14

**Comment by AnasCode** [comment]
> > **SOLVED**: is mandatory IARC rating for 14 >= age in social network category.
> 
> I submitted my app in i go this Issue: Incorrect content rating
> Your app’s content rating is incorrect. Our content rating system includes official ratings from the International Age Rating Coalition (IARC) and is designed to help developers communicate locally relevant content ratings to users.
> 
> can you help? which questions you did "YES" & "NO"
Is your app submitted now ?

**Comment by simonzhexu** [comment]
This issue is gone off topic. Closing it for now, Open new one if you need.

**Comment by Essayad** [comment]
please can someone add admob ads to this project
https://github.com/WhatsApp/stickers/tree/master/Android

**Comment by ptkdev** [comment]
@indrapatel247 when you calc rating, set on YES "little violence" and "little porn" and rating switch from +4 to +14 and you stickers pass.
