### ISSUE TITLE
iOs [Fatal error: The data couldn’t be read because it isn’t in the correct format]

### ISSUE THREAD

**Issue by AlexxaAlbarn** [WhatsApp/stickers#151]
Hey!, so i am kinda really new in all of this. I have been following all of the instructions like 10 times on the [ iOs Article](https://github.com/WhatsApp/stickers/blob/master/iOS/README.md) to find my error, but i cannot find it.

So, i think i had followed all the instructions precisely and don't know what might cause this error when i run the app (whether is on a  simulated ios device or on my ios device] i get the next error: 
> ### _Thread_ 1: Fatal error: The data couldn’t be read because it isn’t in the correct format. <
[See also first attached picture]
![captura de pantalla 2018-11-05 a la s 17 50 42](https://user-images.githubusercontent.com/44790203/48034462-1fe5e600-e125-11e8-85e9-169ed3b4a12a.png)

_
Im working on a Macbook on Xcode 9.3 and i am using the sample app. And Yes, i had upload the PNG files to the SampleStickers Folder and make sure they are less than 100kb.  I’ve also make sure that the PNG files i replaced, where all changed to "Data" on the drop down menu On the identity and type section.
This is my edited sticker_packs.wasticker:

> {
    "ios_app_store_link" : "",
    "android_play_store_link" : "",
    "sticker_packs" : [
    {
        "identifier": "testingID565",
        "name": "BrigitteGrey",
        "publisher": "AxlRoss"",
        "tray_image_file" : "tray_Cuppy.png",
        "publisher_website" : "",
        "privacy_policy_website" : "",
        "license_agreement_website" : "",
        "stickers": [
        {
            "image_file": "01_Logo_Brigitte.png",
            "emojis": ["☕","🙂"]
        },
        {
            "image_file": "02_Logo_Brigitte.png",
            "emojis": ["😄","😀"]
        },
        {
            "image_file": "03_Anioco_Brigitte_Money.png",
            "emojis": ["😆","😂"]
        },
        {
            "image_file": "04_Brigitte_Paz.png",
            "emojis": ["😃", "😍"]
        },
        {
            "image_file": "05_Brigitte_Sad.png",
            "emojis": ["😭","💧"]
        },
        {
            "image_file": "06_Brigitte_Te_Observa.png",
            "emojis": ["😍","♥"]
        },
        {
            "image_file": "07_Calk_Beso.png",
            "emojis": ["💔","👎"]
        },
        {
            "image_file": "08_Cara_Brigitte.png",
            "emojis": ["😍","💑"]
        },
        {
            "image_file": "09_Pablinsky_En_Baño.png",
            "emojis": ["😘","🍪"]
        },
        {
            "image_file": "10_Pablinsky.png",
            "emojis": ["🤔","😐"]
        },
        {
            "image_file": "11_Senpai_Galleta.png",
            "emojis": ["😱","😵"]
        },
        {
            "image_file": "12_Cuppy_angry.png",
            "emojis": ["🖐","👋"]
        }]
    }
]
}

I am getting crazy because i don't know where the error is.

**Comment by amrit-1901** [comment]
It should be "publisher": "AxlRoss" (you put an extra quote)

**Comment by AlexxaAlbarn** [comment]
Wow, now i feel like a stupid. Thankssss a lottt <<33
