### ISSUE TITLE
[Android] Google Play has removed 70% of all Sticker apps overnight

### ISSUE THREAD

**Issue by DaFaack** [WhatsApp/stickers#153]
Hey Developers,
I analyzed the "WhatsApp sticker" niche yesterday and noticed this morning that about 70% of the apps where removed.
I instantly took all of the "whatsapp" keywords out my app title, description, screens etc.
I currently would be very careful with sticker apps.
The fact that confuses me the most is that whatsapp want us to develop sticker apps but the Google Play store removes apps with the tags "WAStickerApps" and "WhatsApp".
Does anyone here got bad experiences and has some idea what to do?

**Comment by simonzhexu** [comment]
Thanks @DaFaack for letting us know. We are going to investigate on this. How can you tell that 70% of the apps are removed? When I search WAStickerApps, I still see a lot of apps that support WhatsApp stickers.

**Comment by DaFaack** [comment]
I took some screenshots of the available sticker apps yesterday. About 50 - 70% of the apps I screenshottet are no longer available in the Google Play store.
For example:
"Meme Stickers for Whatsapp" with 100.000+ downloads
"StickoText - Sticker Packs For Whatsapp" with 1.000.000+ downloads and
"Sticker Packs for WhatsApp" with 50.000+ downloads.

All of these apps are no longer available

**Comment by ptkdev** [comment]
My app is available [io.ptkdev.wastickers](https://play.google.com/store/apps/details?id=io.ptkdev.wastickers)

**Comment by nicolasdeory** [comment]
This happened to me as well. I removed the tag "WAStickerApps" and the app was reinstated at the moment. If it gets deleted again I'll remove "WhatsApp" as well.

**Comment by simonzhexu** [comment]
I have just checked in the latest read me instructing that developers do not use WhatsApp in the app name. Please make changes accordingly. Sorry for the frustrating experience. This is a new area we are exploring so please bear with us.

**Comment by simonzhexu** [comment]
I would not suggest to remove WAStickerApps from the description though because then users won't be able to find your app through play store search.

**Comment by nicolasdeory** [comment]
The thing is my app got deleted for that exact reason: including "WAStickerApps" in the app description.

**Comment by arshikh** [comment]
I have reskinned the app a little bit and published to google playstore. I am using similar keywords in the description and name of the app. Do I need to remove that?
<a href = "https://play.google.com/store/apps/details?id=com.mindonair.wastickerapps">Whatsapp Stickers App</a>

**Comment by ptkdev** [comment]
@simonzhexu if you copy from Telegram, try copy it GOOD! Create a ios app and android app is very shit method. Yes is frustrating experience and yes whatsapp provide very bad experience for developers and users. Use brain next time for create the next feature copied by telegram.

**Comment by JAY0741** [comment]
> The thing is my app got deleted for that exact reason: including "WAStickerApps" in the app description. At least that's what Google said.

You need to build a release version of your app for submission to the Google Play Store. Click Build > Generate Signed Bundle/APK. For more information, visit https://developer.android.com/studio/publish/app-signing#sign-apk. Note that Android Studio saves the APKs you build in project-name/module-name/build/outputs/apk. For more information on building your app, visit https://developer.android.com/studio/run/.


https://github.com/WhatsApp/stickers/tree/master/Android
Submit your app
Importantly, when naming your app, it is strongly advised you do not use "WhatsApp" anywhere in the name of your app or in the name field of your app listing on the Google Play Store. However, when preparing your app for submission in Google Play Store, you'll have the option to add description associated with your app and it's okay to mention WhatsApp in the description. WhatsApp can also launch the Google Play Store and perform a search for other sticker pack apps. To help your app appear in this list, also add the keyword WAStickerApps to app's description when setting up your app in the Google Play Store console. You can use additional keywords, but make sure you at least use this one.

To submit your app to the Google Play Store, follow the instructions here: 
https://developer.android.com/distribute/best-practices/launch/.

report to google

**Comment by 0566055455** [comment]
My app got suspended, can you help?

**Comment by GlowMLG** [comment]
You seem to have been affected by a hoax. Check issue #190 . @simonzhexu please check it out

**Comment by gbougakov** [comment]
I have a similar issue, but with iOS App Store. My app can't pass App Review because Apple sees it as spam. Please check out #230

**Comment by MarsVard** [comment]
> I took some screenshots of the available sticker apps yesterday. About 50 - 70% of the apps I screenshottet are no longer available in the Google Play store.
> For example:
> "Meme Stickers for Whatsapp" with 100.000+ downloads
> "StickoText - Sticker Packs For Whatsapp" with 1.000.000+ downloads and
> "Sticker Packs for WhatsApp" with 50.000+ downloads.
> 
> All of these apps are no longer available

"meme stickers for WhatsApp" was put back up the next day, misunderstanding about "update whatsapp dialog"

**Comment by 0566055455** [comment]
My app had +900K downloads, removed from using WhatsApp in the title. my other app didnt have much downloads but was removed too for using WhatsApp in the title.

**Comment by MarsVard** [comment]
@0566055455 but it seems like you wrote WhatsApp wrong and it's clearly against the WhatsApp brand guidelines.

**Comment by 0566055455** [comment]
Nope.

**Comment by simonzhexu** [comment]
Try removing WhatsApp from your app name.

**Comment by ptkdev** [comment]
@simonzhexu thanks for useless solution

**Comment by 0566055455** [comment]
@simonzhexu My account got terminated, how can I remove WhatsApp from the title now..

Also appdetex support is VERY bad, The worst experience I had ever.

**Comment by Yleader10** [comment]
@ptkdev  please can you share the sticker app source withe me

**Comment by hitendobariya** [comment]
> My app is available [io.ptkdev.wastickers](https://play.google.com/store/apps/details?id=io.ptkdev.wastickers)

very good app
