### ISSUE TITLE
How can I use imageData inside addSticker in iOS? 

### ISSUE THREAD

**Issue by abokhalel2** [WhatsApp/stickers#154]
I've been trying the past 3 hours to implement `imageData` inside `addSticker` in my project without any luck!

Using the recommended `StickerPack` in iOS,  the code has two ways to use `addSticker`: 1) either by using just the name of the image inside `contentsOfFile`, or 2) by using `imageData` inside `addSticker`. The former works well when using one of the image names inside the app. Example:

    stickerPack.addSticker(contentsOfFile: "sample.png", emojis: ["☕"])

However, when I use the second method, it doesn't seem to work. This is my implementation:

    let image = UIImage(named:"sample.png")!
    let imgData = image.pngData()
    stickerPack.addSticker(imageData: imgData, type: "png", emojis: ["☕"])

I'm suspecting that using `pngData()`is the issue, but I'm not sure how to correct it. It gives me this error:

    Cannot invoke 'addSticker' with an argument list of type '(imageData: Data?, type: String, emojis: [String])'

Isn't `imageData` expecting me to convert the image to data? what am I missing here?

**Comment by Usman4Github** [comment]
the issue seems with using "png". try to use ImageDataExtension.png instead and then give a try

eg:

> try stickerPack!.addSticker(imageData: imgData, type: ImageDataExtension.png, emojis: emojis)

**Comment by abokhalel2** [comment]
Thank you so much. This did indeed fixed the issue. I used `.png`, and it worked well. 

    stickerPack.addSticker(imageData: imgData, type: .png, emojis: ["☕"])
