### ISSUE TITLE
About Section

### ISSUE THREAD

**Issue by pixwalls** [WhatsApp/stickers#156]
Any plans to add an "about" section in app? Google is removing apps if the app don't have a privacy policy linked in the about section.

**Comment by rebelholic** [comment]
I guess you can add an about section like screenshot below by yourself:
![badbee_about](https://user-images.githubusercontent.com/6254876/48065439-52fba880-e1fd-11e8-9052-1da193a8e1f7.jpeg)

Its made by my team. More info please check out [this link
](https://play.google.com/store/apps/details?id=com.baysoft.badbeestickers)

**Comment by pixwalls** [comment]
This is for the individual packs, right? I meant for the entire app. I tried using other about libraries but was not successful in integrating this with it.

**Comment by arshikh** [comment]
I have an about page created inside the my app itself with social media links and custom links. <a href="https://play.google.com/store/apps/details?id=com.mindonair.wastickerapps">Whatsapp Sticker Apps</a>

**Comment by pixwalls** [comment]
Can you please share any tutorial or documentation on how it's done?

**Comment by sahqazhar** [comment]
@rebelholic can you please help me out with the about section?

**Comment by rebelholic** [comment]
Guys please check out [this link](https://github.com/WhatsApp/stickers/issues/264)
