### ISSUE TITLE
When Whatsapp android update with stickers 

### ISSUE THREAD

**Issue by ptkdev** [WhatsApp/stickers#159]
On ios whatsapp support stickers in stable version.

On android stickers work only in beta version.

Damn, why?!?!?! This is stupid and not user friendly for users. Android users try use stickers and not work = 1 star on play store.

Please release at the same time whatsapp updates.

**Comment by ptkdev** [comment]
With stable version of 23 october not work

**Comment by Alex193a** [comment]
You should use the latest one 😄

**Comment by ptkdev** [comment]
Version  2.18.341 are not available on most android phone. I try on 10 friends phone. Is in rolling for days...

**Comment by simonzhexu** [comment]
Sorry for the convenience. This problem will be fixed when we fully roll out Android release. There is no way to fix for previous clients.
