### ISSUE TITLE
Error: Asset file doesn’t exist!

### ISSUE THREAD

**Issue by Osama964** [WhatsApp/stickers#162]
When I run the app on Android emulator a page pops up and says:
“Error: Asset file doesn’t exist. pack: ....., sticker: .......webp
See logcat for stack trace.”

**Comment by Alex193a** [comment]
Does the contents.json file contain all the correct information?

**Comment by Osama964** [comment]
Thank you Alex193a
Checked it twice and noticed there was a problem and now it’s fixed.
