### ISSUE TITLE
Display error when the name of the sticker pack is very large

### ISSUE THREAD

**Issue by RodrigoTomeES** [WhatsApp/stickers#165]
Hi,

Can you fix the display error?,

Thanks

![screenshot_20181106-221405](https://user-images.githubusercontent.com/13077343/48121064-39e20e80-e274-11e8-8f8c-a77a626c82e6.jpg)
![photo_2018-11-07_10-02-42](https://user-images.githubusercontent.com/13077343/48121084-46fefd80-e274-11e8-902b-8316a3290638.jpg)

**Comment by simonzhexu** [comment]
Will fix.

**Comment by Zandor300** [comment]
@simonzhexu Has this been fixed? Can this be closed? (Don't have Android device yet)

**Comment by zakesol** [comment]
how can I add my own stickers?

**Comment by Zandor300** [comment]
@zakesol, read the readme. And also, you should’ve created your own issue. Not clutter up other issues.

**Comment by re-LIFE** [comment]
How created the list like this image?

**Comment by RodrigoTomeES** [comment]
@simonzhexu did you fix it? Or when will it be fix?

**Comment by simonzhexu** [comment]
this is now fixed.https://github.com/WhatsApp/stickers/commit/ac9c3bf90fe66d0365513e3cc22dec503813e1b0

**Comment by RodrigoTomeES** [comment]
Thanks!!

**Comment by Androidsignal** [comment]
im getting this error plzz help me:

exception fetching input stream uri:content://ne.stickers.whatsapp.com.whatsappstickers.WhatsAppLicensedCode.StickerContentProvider/stickers_asset/b7a29678-e7ae-4182-87d0-f1e9fa66e7e6/0, exception message: fd must not be null
