### ISSUE TITLE
[iOS] Fatal Error: Your bundle identifier must not include the default one.

### ISSUE THREAD

**Issue by Paras-Chodavadiya** [WhatsApp/stickers#166]
While tapping on button **Add to WhatsApp**, its giving fatal error with message **Your bundle identifier must not include the default one.**

I have also change app bundle identifier

**Comment by enzyme69** [comment]
Hi Paras, what was your solution on this?

**Comment by Paras-Chodavadiya** [comment]
means you can not keep the same bundle ID which is already there.
You have to change and set your unique bundle ID
