### ISSUE TITLE
unable to fetch data from content provider

### ISSUE THREAD

**Issue by akhil1605** [WhatsApp/stickers#172]
Can you explain the changes to be done in the content provider more legibly ?

**Comment by simonzhexu** [comment]
please check the read me advanced section.

**Comment by simonzhexu** [comment]
after that if you still have question, make the question specific.

**Comment by akhil1605** [comment]
I solved the error. Can you please instructions for integrating admob ad (both banner and interstitial) ?
I referred this : 
https://developers.google.com/admob/android/quick-start
But it doesn't work properly.

**Comment by simonzhexu** [comment]
WhatsApp doesn't not provide support for custom add-ons such as Ads. We only provide the base support of the integration of stickers into WhatsApp. You are on your own if you want to add Ads. I would suggest you contact Admob for support.
