### ISSUE TITLE
Sticker got removed after app uninstall

### ISSUE THREAD

**Issue by UniqueJoy** [WhatsApp/stickers#173]
**After adding the stickers to whatsapp, if i uninstall the app why its removing the stickers?
_It should be delete only user delete from my stickers, Not on app uninstallation_..**

**Comment by lonesnipers** [comment]
Yes sticker gets removed after app installation. If you want the app, you need to keep the stickers.

**Comment by arnemoor** [comment]
On which platform are you encountering that issue? Can't reproduce that behaviour on iOS 12.1.

**Comment by simonzhexu** [comment]
on Android, the sticker gets removed when you remove the app
on iOS, the stickers stay even if the app is removed. 

This is because on iOS, we copy the stickers into WhatsApp. on Android, WhatsApp fetches stickers from sticker app.

**Comment by UniqueJoy** [comment]
Then also add this option for android also like the ios

**Comment by darylsze** [comment]
> we copy the stickers into WhatsApp.

are you sure? by that means ALL stickers are removed after app is removed (cuz IOS will also remove corresponding packages). It's the same case  I am facing now! I lose ALL stickers.
