### ISSUE TITLE
Android + iOS sticker pack development

### ISSUE THREAD

**Issue by ranrinc** [WhatsApp/stickers#174]
Hi there,

Is there someone from WA that can give us some insight on how we can create the sticker pack and have it run on both Google Play and Appstore platform without getting rejection? Is there a tip and tricks, since the sticker packs apps considered as violation for both system. My email to developer WA have never got replied and apple seems saying my apps is not original? So, far all question with this issue have no solution what so ever. Any help would be really appreciated. Thanks

**Comment by sharadvermasv** [comment]
Kindly read readme file

**Comment by Zandor300** [comment]
Closing this as there are bigger threads on this for iOS and Android.
