### ISSUE TITLE
[iOS] App crashs if Deployment Info / Devices is set to Universal in XCode

### ISSUE THREAD

**Issue by arnemoor** [WhatsApp/stickers#175]
If the current code is enabled for iPad through setting Deployment Info / Devices to Universal in XCode the App crashs due to different handling of UIAlertController and UIActivityViewController on iPad.

Should be fixed and optimized for iPad with pull request #171 .

**Comment by firstangel999** [comment]
sorry but why offer iPad stickers packs for WhatsApp when WhatsApp itself is not available for iPad?

**Comment by amrit-1901** [comment]
Fixed by [https://github.com/WhatsApp/stickers/pull/171](url)
