### ISSUE TITLE
[Android]What is the 'identifier' variable in the method definition : protected void addStickerPackToWhatsApp(String identifier, String stickerPackName)

### ISSUE THREAD

**Issue by Adarshkl** [WhatsApp/stickers#179]
![image](https://user-images.githubusercontent.com/16320768/48266665-0f4fab80-e456-11e8-856e-b789a8b531fc.png)
What exactly is 'identify' parameter here? When I debug the code, it shows a value of '1'. Is it the folder name where all the stickers are put inside the project?

**Comment by simonzhexu** [comment]
it is the folder name, yes. You also use that in content.json.

**Comment by ansarisufiyan777** [comment]
Can we use a single folder name for multiple sticker packs?

eg:
`
{
  "android_play_store_link": "https://play.google.com/store/apps/details?id\u003dcom.myapp",
  "ios_app_store_link": "https://itunes.apple.com/app/myapp/id123456",
  "sticker_packs": [
    {
      **"identifier": "shared",**
      "license_agreement_website": "https://myproject.com/license",
      "name": "Whatsapp stickers",
      "privacy_policy_website": "https://myproject.com/legal",
      "publisher": "Asna Soft.",
      "publisher_email": "contact@myproject.com",
      "publisher_website": "https://myproject.com",
      "stickers": [],
      "tray_image_file": "picture1169841196712507257png"
    }
    ,
    {
      **"identifier": "shared",**
      "license_agreement_website": "https://myproject.com/license",
      "name": "Whatsapp stickers",
      "privacy_policy_website": "https://myproject.com/legal",
      "publisher": "Asna Soft.",
      "publisher_email": "contact@myproject.com",
      "publisher_website": "https://myproject.com",
      "stickers": [],
      "tray_image_file": "picture1169841196712507257png"
    }
  ]
}
`
