### ISSUE TITLE
App with more than 10 sticker packs

### ISSUE THREAD

**Issue by ayooj** [WhatsApp/stickers#180]
Can i create a sticker app with more than 10 sticker packs included. If i add 20 or 40 stickers. will whatsapp ban my sticker app

In readme.md file i saw """"Stickers are organized into "packs". Your app can contain anywhere from 1 to 10 packs.""""

What does this means? Plz tell me if there is limitation on number of sticker packs can be included in app

**Comment by simonzhexu** [comment]
Please don't create app with more than 10 packs, it is bad experience for user. They may want only one pack out of your 100 packs. But you are occupying 100 packs of disk space for them. You can have separate apps.

**Comment by sanidhya711** [comment]
> Please don't create app with more than 10 packs, it is bad experience for user. They may want only one pack out of your 100 packs. But you are occupying 100 packs of disk space for them. You can have separate apps.

but what if we fetch the stickers from web in our app? then we wont need to store anything on the users device and download only those that the user wants to use.
