### ISSUE TITLE
[Android] Sticker panel bugged. Panel completely blank.

### ISSUE THREAD

**Issue by sharkiller** [WhatsApp/stickers#182]
After adding and deleting some stickers packs, the panel completely bugged and after trying to see the stickers the app start to use full phone resources (cpu) and start heating up until i force close the app.
Tried to delete ALL stickers still nothing. Tried going to whatsapp data and remove "whatsapp stickers" folders and nothing. Tried to delete cache from app and nothing. Panel completely blank and use full cpu after open it. 
After opening the stickers pack I can go to the Plus button to add stickers or see my installed stickers but this panel is really lagged. Even with no stickers installed the panel is lagged and sometimes unresponsive.
The only thing I didn't do was clean app data because I don't want to lose the chats and configurations.

Phone: Sony Xperia Z5
Android: 7.1.1
Whatsapp: 2.18.348

![image](https://user-images.githubusercontent.com/712193/48292312-96058800-e458-11e8-93be-54c22a98db1a.png)

![image](https://user-images.githubusercontent.com/712193/48292324-a4ec3a80-e458-11e8-80d8-56d93aa58511.png)

![image](https://user-images.githubusercontent.com/712193/48292341-b3d2ed00-e458-11e8-8496-75631aff89ba.png)

**Comment by sharkiller** [comment]
Updated to 2.18.354 
Issue persist.

**Comment by simonzhexu** [comment]
If this issue is still happening, please email to android@support.whatsapp.com

This email will include some logs that can help us diagnose the issue.

Please ask to direct that email to Simon Xu on Android team.

**Comment by Zandor300** [comment]
@sharkiller You can send an email with logs attached from settings.

**Comment by dcferreira** [comment]
Is there any update on this? It started happening to me today, on 2.18.361.

**Comment by Cryler** [comment]
i have the same problem, is there any news on how to fix this? 
i cant use @dcferreira method, because i cant find such a file.

**Comment by simonzhexu** [comment]
> @simonzhexu yes issue still persist on 2.18.360
> 
> how do i fetch logs? a few days ago I connected the phone to android studio and saw the logcat. but there wasn't anything related to whatsapp.

Just go to WhatsApp -> Settings -> Contact Us

**Comment by tygin** [comment]
I have this issue too for a week. I noticed that if I parallel whatsapp, I can use stickers in the paralleled version. But it no luck with the original. Is there any hot fix yet?

**Comment by simonzhexu** [comment]
We have finally reproduced a similar scenario and we are putting a fix. But would be great if you could use the WhatsApp -> Settings -> Contact Us flow to send us your logs as well.

**Comment by simonzhexu** [comment]
were you using two WhatsApps when you encounter this?

**Comment by sharkiller** [comment]
wanted to say that with update 2.18.385 the problem fixed itself. now the panel works fine.

even with no pack installed i had some favorites that didnt load, maybe that was the problem in the beginning.
