### ISSUE TITLE
Assets source online instead

### ISSUE THREAD

**Issue by xpcoder123** [WhatsApp/stickers#183]
I am planning to place the stickers on a host online instead of keeping them on asset folder and the user download them on button click. Let's say that on button click list of pictures downloaded. Shall the user download contents.json file with every pictures pack? Please guide me for best practice to do this.
Thank you

**Comment by asfdfdfd** [comment]
Something like #65

**Comment by kilanko** [comment]
@asfdfdfd I tried but its not working. My code is below:

 ```
override fun openAssetFile(uri: Uri, mode: String): AssetFileDescriptor? {
      
         val pathSegments = uri.getPathSegments();
         val fileName = pathSegments.get(pathSegments.size() - 1)
         val  identifier = pathSegments.get(pathSegments.size() - 2)
      
         val dir =  context.filesDir.absolutePath
            val file = File(dir, identifier + "/" + fileName)
            val pfd = ParcelFileDescriptor.open(file, MODE_READ_ONLY)
    return AssetFileDescriptor(pfd, 0, file.length())
}

```
My content.json and sticker folders are stored in the internal storage device so that i can download new sticker packs and also modify the contents.json file programatically.

The problem i have is that i always get "Third party sticker pack cannot be found" error. I think the problem is with the "STICKERS_ASSET" in the Uri.

i've been stuck on this for day :(

Please Help!!

**Comment by viztushar** [comment]
you can check this [ #204](https://github.com/WhatsApp/stickers/issues/204#issuecomment-441016268)  or
this works for me
```
    @Nullable
    @Override
    public ParcelFileDescriptor openFile(@NonNull Uri uri, @NonNull String mode) {
        final List<String> pathSegments = uri.getPathSegments();
       
        if (pathSegments.size() != 3) {
            throw new IllegalArgumentException("path segments should be 3, uri is: " + uri);
        }
        String fileName = pathSegments.get(pathSegments.size() - 1);
        final String identifier = pathSegments.get(pathSegments.size() - 2);

        if (TextUtils.isEmpty(identifier)) {
            throw new IllegalArgumentException("identifier is empty, uri: " + uri);
        }
        if (TextUtils.isEmpty(fileName)) {
            throw new IllegalArgumentException("file name is empty, uri: " + uri);
        }
        try{
            File file = new File(getContext().getFilesDir()+ "/" + identifier, fileName);
            return ParcelFileDescriptor.open(file,ParcelFileDescriptor.MODE_READ_ONLY);
        } catch (FileNotFoundException e){
            e.printStackTrace();
        }
        return null;
    }
```

**Comment by ramsumit** [comment]
I have done something like this but once app remove from background also sticker remove from whatsapp

**Comment by simonzhexu** [comment]
Added some instructions.
https://github.com/WhatsApp/stickers/blob/master/Android/README.md#expose-files-that-are-stored-internally-as-stickers-through-contentprovider
