### ISSUE TITLE
Sticker should not be deleted on app uninstall,Android

### ISSUE THREAD

**Issue by UniqueJoy** [WhatsApp/stickers#184]
**on iOS, the stickers stay even if the app is removed. But in android  sticker is removed when sticker app  uninstalled,
Please solve this issue, so that  sticker dont get deleted like the ios
Bring this feature on android also
It really needed..**

**Comment by simonzhexu** [comment]
Android and iOS are two separate platforms, we have decided to have different behaviors for reasons, and will not change the way Android works. I am sorry.

**Comment by design365** [comment]
i  wan to know how to remove sticker which my app add from whatsapp ?
