### ISSUE TITLE
[ios] How can I fix the error with Failed with exit code 1

### ISSUE THREAD

**Issue by Kittielbdd** [WhatsApp/stickers#185]
I can run the app with simulators, but when i want to archive it, it will show Failed with exit code 1.
Can anyone help me to fix this problem?

Thank you

**Comment by catwwi** [comment]
yea same situation dude really want a help

**Comment by Gabrielm1** [comment]
exit code 1 may appears for many reasons... 
Try to disable the bitecode for the build option.

- Select your the target -> All -> Build options -> Enable Bitecode -> No.

For more details -> [https://stackoverflow.com/a/32466484/4221943](url)

**Comment by MarvinJWendt** [comment]
Hey,
This Issue seems to be inactive. To keep things organized I will close this for now. If this Issue is still relevant, don't hesitate to drop a comment and @Zandor300 or I will reopen it if necessary :)

Sincerely,
Marvin Wendt
