### ISSUE TITLE
[Android] App suspended for using WhatsApp in title

### ISSUE THREAD

**Issue by 0566055455** [WhatsApp/stickers#188]
Hi, 
My app got suspended for using WhatsApp in the title. I would really like some help in resolving the issue and removing the suspension.

**Comment by GlowMLG** [comment]
You seem to have been affected by a hoax. Check issue #190

**Comment by 0566055455** [comment]
@simonzhexu  Would appreciate if you can help me remove the suspension, appdetex said While we appreciate that you wish to, or may have modified your app, we don’t review or consent to republication of apps. so can you do anything to make them review the app?

**Comment by MarsVard** [comment]
@0566055455 what was your app called?

**Comment by simonzhexu** [comment]
It is recommended not to use WhatsApp in your app name as in Android README.
