### ISSUE TITLE
How to pass String from MainActivity to StickerContentProvider 

### ISSUE THREAD

**Issue by Hari-06** [WhatsApp/stickers#192]
**MainActivity.class**
String x = "some text";

**StickerContentProvider.class**
private synchronized void readContentFile(@NonNull Context context)
    {
        CONTENT_FILE_NAME = MainActivity.x
         try (InputStream contentsInputStream = context.getAssets().open(CONTENT_FILE_NAME))
            {
                stickerPackList = ContentFileParser.parseStickerPacks(contentsInputStream);
                System.out.println(MainActivity.getFileName()+" is value");
            } 
           catch (IOException | IllegalStateException e)
            {
                throw new RuntimeException(CONTENT_FILE_NAME + " file has some issues: " + 
                e.getMessage(), e);
            }
       }

but CONTENT_FILE_NAME returns null where as in Main Activity string x holds the values..

**Comment by simonzhexu** [comment]
No, you cannot. ContentProvider can be launched without MainActivity being launched.

**Comment by Hari-06** [comment]
@simonzhexu  so i need to change the CONTENT_FILE_NAME(i.e. i need to change the JSON file)  dynamically based on the input from user is there any possibility to do that
