### ISSUE TITLE
[Android] Error with the Pack

### ISSUE THREAD

**Issue by PONYMODZ** [WhatsApp/stickers#193]
play link: is invalid 

thats what i get also when i click on a sticker pack the app crashes

**Comment by dhamarar** [comment]
Add 
https://play.google.com/store/apps/details?id=YOUR_PACKAGE_NAME
to "android_play_store_link" in contents.json
should fix it

**Comment by PONYMODZ** [comment]
Just fixed it myself XD silly me but thx for you answer/help 

> Add
> https://play.google.com/store/apps/details?id=YOUR_PACKAGE_NAME
> to "android_play_store_link" in contents.json
> should fix it
