### ISSUE TITLE
App doesnt install

### ISSUE THREAD

**Issue by sharadvermasv** [WhatsApp/stickers#194]
App doesnt install on android 7.0 below. Is it anyway to made the app available for android lollipop and marshmallow user?

**Comment by Alex193a** [comment]
When you generate the APK you **must** check both Signature versions: V1 (Jar Signature) and V2 (Full APK Signature).

**Comment by xxxdepy** [comment]
Also, adding to Alex193a's comment, check if the app is already installed on your phone in the process of using the "Build > Run" function from Android Studio, if it is, then go to the app on your phone through Settings > App Lists / Apps > find the app, then tap on the menu icon and select "Uninstall for all users."
