### ISSUE TITLE
[iOS] - App refuses to load

### ISSUE THREAD

**Issue by shadydude** [WhatsApp/stickers#198]
When I import my app on my phone, It keeps showing "loading sticker packs" but never loads it. I have no restrictions on my phone whatsoever. Is there a problem with my code?

**Comment by al3bsi** [comment]
use .png image , webp imge sometime not working

**Comment by Zandor300** [comment]
Does it give you an exception in Xcode? Animations on your iPhone will continue playing when you get one.

Maybe you could also post your json config.

**Comment by MarvinJWendt** [comment]
Hey,
This Issue seems to be inactive. To keep things organized I will close this for now. If this Issue is still relevant, don't hesitate to drop a comment and I will reopen it if necessary.

Sincerly,
Marvin Wendt
