### ISSUE TITLE
Sell WhatsApp stickerpack

### ISSUE THREAD

**Issue by thetommes** [WhatsApp/stickers#2]
Hi, is it allowed to sell a sticker pack on Google Playstore/Apple AppStore?
As seen in this repo, the packs are licensed under BSD, so selling should be no problem. But is it against WhatsApp's Terms of Service?

**Comment by amrit-1901** [comment]
@thetommes. Yes, you can sell your sticker pack app on both platforms, but keep in mind that contacts who receive your stickers can save them without having purchased your app.

**Comment by cioMR** [comment]
How do I put my own stikers in WhatsApp ?

**Comment by Real-Experienes** [comment]
I want to sell one of my sticker packs. How do I stop the receiver from tapping and saving the sticker to their favorites? 
My WhatsApp sticker app is already built per WhatsApp guidelines.

**Comment by MarvinJWendt** [comment]
Hi @Real-Experienes, you cannot disable the `add to favorites` feature. All your stickers can be saved by anyone.
