### ISSUE TITLE
sticker file name is invalid

### ISSUE THREAD

**Issue by AladMocu** [WhatsApp/stickers#203]
every works here, i can see the images :
![image](https://user-images.githubusercontent.com/25905130/48322263-afdbd200-e5f4-11e8-9f3b-ab45b07f16e3.png)
when I click "add to whatsapp" this shows on screen
![image](https://user-images.githubusercontent.com/25905130/48322280-c1bd7500-e5f4-11e8-85c0-635e59d3d007.png)

**Comment by simonzhexu** [comment]
( or ) is not allowed in file name.

**Comment by shishram** [comment]
sticker file name:  is invalid, authority: com.**.stickercontentprovider,identifier: 1545573706

@simonzhexu I am getting this above error. When i debug i have this all the files name like below

/data/user/0/com.**/files/1545573706/sticker_1545573760.webp

**Comment by samyakjain** [comment]
@shishram Did you find any solution for this ?
