### ISSUE TITLE
[Android] How do I load stickers from internal/external storage?

### ISSUE THREAD

**Issue by nguyentuanviet** [WhatsApp/stickers#204]

**Comment by nguyentuanviet** [comment]
Per my understanding of the source code, the content provider only allows loading stickers from asset folder. Is it possible to load from internal/external storage? One of the solutions I am looking at is to implement FileProvider instead. Any guidance on this would be really helpful.

**Comment by GabrielBB** [comment]
Yeah, i'm stuck at this, too :(

**Comment by abdulghani200** [comment]
Even i want to know this thing :(

**Comment by simonzhexu** [comment]
There is,
@Nullable
    @Override
    public ParcelFileDescriptor openFile(@NonNull final Uri uri, @NonNull final String mode) throws FileNotFoundException {
        return super.openFile(uri, mode);
    }

in ContentProvider, are you not able to leverage that?

**Comment by GabrielBB** [comment]
@simonzhexu Thanks for the suggestion. I will try that

**Comment by viztushar** [comment]
@simonzhexu i tried this but not working

**Comment by viztushar** [comment]
this works for me
```
    @Nullable
    @Override
    public ParcelFileDescriptor openFile(@NonNull Uri uri, @NonNull String mode) {
        final List<String> pathSegments = uri.getPathSegments();
       
        if (pathSegments.size() != 3) {
            throw new IllegalArgumentException("path segments should be 3, uri is: " + uri);
        }
        String fileName = pathSegments.get(pathSegments.size() - 1);
        final String identifier = pathSegments.get(pathSegments.size() - 2);

        if (TextUtils.isEmpty(identifier)) {
            throw new IllegalArgumentException("identifier is empty, uri: " + uri);
        }
        if (TextUtils.isEmpty(fileName)) {
            throw new IllegalArgumentException("file name is empty, uri: " + uri);
        }
        try{
            File file = new File(getContext().getFilesDir()+ "/" + identifier, fileName);
            return ParcelFileDescriptor.open(file,ParcelFileDescriptor.MODE_READ_ONLY);
        } catch (FileNotFoundException e){
            e.printStackTrace();
        }
        return null;
    }
```

**Comment by parthdave93** [comment]
Still can not able to use Assets + custom local storage stickers
every time receiving the stickers_asset and calls openAssetFile not openFile,
Anyone resolved or having the same issue?

**Comment by parthdave93** [comment]
It's in Content provider but the issue is that some stickers are in asset some in the local directory I don't know why but my file name with asset URI generated every time and where the actual URI generated in the code I don't know.

**Comment by viztushar** [comment]
@parthdave93  @miladesign  i guess we can't use both Assets and local storage in the same Content provider. you have to make one Content provider for Assets and other one for Local Storage.

if you want to load from internet then you can use this https://github.com/viztushar/stickers-internet
is not complete yet but you can check the code.

**Comment by TheBotBox** [comment]
i have loaded the stickers for whatsapp from both assets folder and from gallery. For that, i have created two different provider in the app.

**Comment by simonzhexu** [comment]
https://github.com/WhatsApp/stickers/blob/master/Android/README.md#expose-files-that-are-stored-internally-as-stickers-through-contentprovider

Here are some instructions
