### ISSUE TITLE
As soon as the sticker app is closed from the background the stickers disappears from WhatsApp

### ISSUE THREAD

**Issue by xxxdepy** [WhatsApp/stickers#205]
The title is self explanatory, what it the fix for this? My users are complaining.

**Comment by louislam** [comment]
Yes, my users are complaining it too. The tray icons become empty. They said that they faced this error after update the WhatsApp to  2.18.341 from Google Play. 

For me, I am using OG Pixel without any problems even update to 2.18.341.

![image](https://user-images.githubusercontent.com/1336778/48343141-91391200-e6ac-11e8-90cd-2628873714ac.png)

**Comment by xxxdepy** [comment]
Yes, this is very frustrating as a user, just to test if it was a problem with only my app I installed some other apps and added the stickers, same thing happened, I don't think users have that much time to go back to the app and keep adding the stickers every time they want to use it.

**Comment by Vipul12Thawre** [comment]
Same issue with me

**Comment by rajtechi** [comment]
How to fix this issue? Its very frustrating to add stickers everytime..

**Comment by Vengat121** [comment]
I am too having same issue in android pie

**Comment by Zandor300** [comment]
All of you guys, please try the quick and dirty solution I mentioned earlier: 
https://github.com/WhatsApp/stickers/issues/167#issuecomment-437684615

**Comment by louislam** [comment]
@Zandor300 Asking my users to that, not even a dirty solution at all. We need code fix. Hope someone who familiar with content provider could fix the problem.

**Comment by simonzhexu** [comment]
Please tell us what phone you have. We are aware of the problem with OnePlus, because of their battery optimization which broke the System ContentProvider. It is OnePlus's problem in this case.

**Comment by abhishekverma3189** [comment]
This is because the 3rd party application you installed for WhatsApp is battery optimised by default in Android OS. Navigate to the battery settings on your app, tap on the app icon from the list of battery optimised apps and choose 'don't optimise'.

**Comment by kevinsnijder** [comment]
![screenshot_20181128-164208_2](https://user-images.githubusercontent.com/22765565/49163141-af4d7600-f32c-11e8-82cc-5271d5f36312.jpg)
For now, just add something like this to your app once people pressed the add to whatsapp button, since there is no other fix (yet?).
I haven't recieved any complaints from my users after adding this.
It seems to be a problem with contentproviders OnePlus should fix.

**Comment by KingKlauz** [comment]
@kevinsnijder Hello mate! May I ask how were you able to add the "If the stickers keep disappearing, turn off battery optimization for this app! :)" message on to the whatsapp? I am seeing the default message "Something went wrong" on my whatsapp, and I am unable to find a way to change this default message.

![whatsapp error msg](https://user-images.githubusercontent.com/39686786/54520557-ef03a080-49a3-11e9-87b6-815b5a3fb6ff.png)

Thank you and cheers!

**Comment by Zandor300** [comment]
@KingKlauz That's not possible without the WhatsApp team implementing this. I don't think that will happen. An alternative solution could be to inform your users about it inside your sticker app.

**Comment by KingKlauz** [comment]
@Zandor300 Ahhh! Alright I understand. Thank you for your help mate!

**Comment by Reston** [comment]
Same issue, why is it closed?

**Comment by Zandor300** [comment]
Please scroll up, I’ve linked a fix

**Comment by ShashiPatel7** [comment]
not fix. i'm using Mi A2

**Comment by catonice** [comment]
There's some weirdness involving adding a specific image:
Repro steps:
-I added an image named "HELLO!"
-The sticker app threw the above error
-After uninstalling reinstalling restarting the phone and Android Studio got the error that the image was invalid

Solution:
-Renamed image to "HELLO"

**Comment by ShashiPatel7** [comment]
> There's some weirdness involving adding a specific image:
> Repro steps:
> 
>     * I added an image named "HELLO!"
> 
>     * The sticker app threw the above error
> 
>     * After uninstalling reinstalling restarting the phone and Android Studio got the error that the image was invalid
> 
> 
> Solution:
> 
>     * Renamed image to "HELLO"
> 
> 
> Guessing certain symbols are invalid and the error isn't specific

my images contains only numbers. i.e. Image names are numeric and it does not contains any special characters
