### ISSUE TITLE
Showing Adds in these Actvities.?

### ISSUE THREAD

**Issue by Narender-350** [WhatsApp/stickers#209]
Can i show Adds in these Activites. Some apps are showing some are not showing.Is there any issue if i show adds in these activites.Thanks in advance:)

**Comment by Narender-350** [comment]
> Adds or ads?

ads...sorry:)

**Comment by renanrhoden** [comment]
@Narender-350  thi issue has nothing to do with this repo. Please, google about how to add ads to your app.

**Comment by Zandor300** [comment]
You won't get support for this here. If you really want this, you will be best of making a question on StackOverflow.
