### ISSUE TITLE
React Native Plugin

### ISSUE THREAD

**Issue by pandanr1** [WhatsApp/stickers#211]
Hi,

i think a react-native plugin would be a very good idea. The React-Native-Community is very big and it would be a nice way to add WhatsApp-Stickers to many new and existing apps.

https://facebook.github.io/react-native/docs/native-modules-ios

https://facebook.github.io/react-native/docs/native-modules-android

Thx for the native-examples.

**Comment by Jobeso** [comment]
Hey,
I'm currently working on a react-native plugin. The common api is not that great yet because of how the native integration from WhatsApp works but it supports android and iOS.
Help is greatly appreciated.

[RNWhatsAppStickers](https://github.com/Jobeso/react-native-whatsapp-stickers)

**Comment by kongupradeep** [comment]
> Hey,
> I'm currently working on a react-native plugin. The common api is not that great yet because of how the native integration from WhatsApp works but it supports android and iOS.
> Help is greatly appreciated.
> 
> [RNWhatsAppStickers](https://github.com/Jobeso/react-native-whatsapp-stickers)

this plugin not working

**Comment by MarvinJWendt** [comment]
Hey,
This Issue seems to be inactive. To keep things organized I will close this for now. If this Issue is still relevant, don't hesitate to drop a comment and I will reopen it if necessary.

Sincerely,
Marvin Wendt

**Comment by pandanr1** [comment]
Just want to say that @Jobeso s Plugin is working. Dont know why its not working for kongupradeep ^^

**Comment by RahulSahani** [comment]
Can we create WhatsApp sticker app using react native ..?
