### ISSUE TITLE
Where to get all emojis?

### ISSUE THREAD

**Issue by cuddee** [WhatsApp/stickers#212]
Hi everyone,

not an issue, just a (maybe stupid) question:
In the template it says
"stickers": [
        {
          "image_file": "01_Cuppy_smile.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "02_Cuppy_lol.webp",
          "emojis": ["😄","😀"]
...

Could anybody please tell me if there is the possibility to choose from the full range of emojis? And where to get it?

Thanks a lot! :)

**Comment by Alex193a** [comment]
Yes, you can use whatever emoji you want (max 3 per sticker). You can copy them from emojipedia.org, for example.

**Comment by cuddee** [comment]
@Alex193a Perfect, thanks a lot! 🥇 Problem solved. :)
