### ISSUE TITLE
On iOS users can update a stickerpack, what about android?

### ISSUE THREAD

**Issue by MarsVard** [WhatsApp/stickers#213]
Do we need to add anything to the intent to allow the user to update the sticker pack on WhatsApp?
for example, I added a sticker to the pack in an update.

**Comment by Alex193a** [comment]
Just add the sticker to the pack, nothing more.

**Comment by MarsVard** [comment]
@Alex193a , cool so it updates via the contentprovider?

**Comment by simonzhexu** [comment]
Yes, @Alex193a  is correct. updates automatically flows into WhatsApp.
