### ISSUE TITLE
Please ,the code is not working to me

### ISSUE THREAD

**Issue by zakesol** [WhatsApp/stickers#214]

**Comment by Alex193a** [comment]
Without more details about your problem no one can help you 😅

**Comment by zakesol** [comment]
thanks, Alex with the reply, I downloaded the source code and then I import it in the android studio but he didn't work.

**Comment by GlowMLG** [comment]
Do you have logs? error codes?

**Comment by zakesol** [comment]
No, it´s android studio 3.0

**Comment by sharadvermasv** [comment]
can you share the logs?
