### ISSUE TITLE
[Android] Stickers don't import (completely) into WhatsApp

### ISSUE THREAD

**Issue by JonasAlpha** [WhatsApp/stickers#215]
First of all this is my first Time posting stuff like this so be kind with me :)
 
After finishing my (first) Sticker Pack I've found myself with the Problem that once I click on add to WhatsApp not all of the Sticker are available in WhatsApp. I don't think I have made any mistakes in Android Studio because all of the Sticker I have made are in the Base Application.

I'd appreciate it if you guys would spare me some of your time to help me and learn from my Mistakes!
ALSO: All Sticker i have made are 512x512 in Webp and all are under 50kb.

![screenshot_20181113-004714_sticker 9c - debug](https://user-images.githubusercontent.com/35976079/48381830-34564f80-e6de-11e8-8634-c669acae560c.jpg)
![20181113_004740](https://user-images.githubusercontent.com/35976079/48381831-35877c80-e6de-11e8-85c4-d7f40d7ab4bf.jpg)

**Comment by Zandor300** [comment]
You should add [Android] at the start of your title. Other than that. I don't know how to help you. @simonzhexu ?

**Comment by nicolasrodf** [comment]
I had the same problem and you can fix this when you export WebP format in Photoshop. You have to uncheck "Save Metada" and it is.

**Comment by simonzhexu** [comment]
Do you have a link to your repo or app? Seems like some webp images are having issues.
