### ISSUE TITLE
Error  not compiling app:debugRuntimeClasspath

### ISSUE THREAD

**Issue by Oportorr** [WhatsApp/stickers#216]
Hi I have Android Studio 3.2.1 on Windows 10 10.0.
I have clone the project from GitHub, but when compiling it´s showing the following error:

Error detail: 

8:41 PM	Gradle sync failed: Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
				Could not determine artifacts for com.facebook.fresco:webpsupport:1.10.0
				Could not get resource 'https://jcenter.bintray.com/com/facebook/fresco/webpsupport/1.10.0/webpsupport-1.10.0.aar'.
				Could not HEAD 'https://jcenter.bintray.com/com/facebook/fresco/webpsupport/1.10.0/webpsupport-1.10.0.aar'.
				jcenter.bintray.com
				Consult IDE log for more details (Help | Show Log) (1 s 748 ms)

Any dependence I'm missing? 
How to add it ?

Thanks,
Oscar

**Comment by simonzhexu** [comment]
is this still a problem? What does it show when you press show log?
