### ISSUE TITLE
can use app without assets folder. 

### ISSUE THREAD

**Issue by Boutannoura** [WhatsApp/stickers#217]
Hi ,

Any idea about how can i the stickers without use the assets folder for example .show the stickers and when user click add to WhatsApp i will download it on local folder and add it on WhatsApp .

if anyone has a solution for that .

Thank you

**Comment by TechPakka** [comment]
viztushar it's nice of you. Do let us know when you upload.

**Comment by Zandor300** [comment]
Does this help? https://github.com/WhatsApp/stickers/issues/183#issuecomment-441017139

**Comment by simonzhexu** [comment]
Added some instructions in : https://github.com/WhatsApp/stickers/blob/master/Android/README.md#expose-files-that-are-stored-internally-as-stickers-through-contentprovider
