### ISSUE TITLE
Sticker packs occasionally disappear from WhatsApp

### ISSUE THREAD

**Issue by nicolasdeory** [WhatsApp/stickers#221]
My users are reporting that sometime after having added the packs from my app, they disappear from WhatsApp and they have to install them again.

Is there any way to prevent this behavior?

**Comment by Zandor300** [comment]
The problem and solution described in here might also apply to you if you are seeing this issue on Android: https://github.com/WhatsApp/stickers/issues/167#issuecomment-437684615

You should add `[iOS]` or `[Android]` to your issue title.

**Comment by simonzhexu** [comment]
This is a OnePlus issue. We are working on it.
