### ISSUE TITLE
General concern - why does adding stickers require an extra app?

### ISSUE THREAD

**Issue by fgimenezm** [WhatsApp/stickers#222]
Seriously... why does this have to be an app?
why not have an icon pack search capability in WhatsApp or to import packs from an URL or something like that? Or a bot?

You should take a look at how your competition does it... it's way more user friendly

**Comment by simonzhexu** [comment]
We have reason that we prefer not to disclose.

**Comment by frodfigu** [comment]
+1 And App Store is rejecting many apps of stickers... It´s very frustrating...
