### ISSUE TITLE
[Android] i don't want to use the image from assets folder

### ISSUE THREAD

**Issue by wayne811** [WhatsApp/stickers#224]
i don't want to use the image from assets folder. 
I want to use my images path from server but not asset folder, i found that the function 'openAssetFile' from 'StickerContentProvider.java' will return the AssetFileDescriptor, but i don't want this result , how can i do.

Many Thanks

**Comment by Alex193a** [comment]
You must write your custom content provider.
If you need help you can open a thread on Stackoverflow.

**Comment by bap94** [comment]
@wayne811 Did you find how to make that possible?

**Comment by bap94** [comment]
@Alex193a I write custom content provider code but first time there is no stickers so **"sticker_packs":[ ]** is empty as per code that throw an exception 

```
java.lang.IllegalStateException: sticker pack list cannot be empty 
 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
```

so If anyone done that please tell me how it's work
