### ISSUE TITLE
[ANDROID] Stickers not loading for others

### ISSUE THREAD

**Issue by Iliasssss** [WhatsApp/stickers#225]
Hello, I just made my sticker app, which is working for me. I see the stickers my self, but for others they keep on loading for ever in whatsapp. Is that because my app isn't in google play? 

Thank you :)

**Comment by Alex193a** [comment]
Is your stickers app still installed on their phones?

**Comment by Iliasssss** [comment]
No, the app is only installed on my phone, so I can sent them en see them in the chats. But my friends see only a loading animation in the chat, sorry if i was unclear

**Comment by sharadvermasv** [comment]
Maybe they are using moded version if WhatsApp or using outdated version

**Comment by Iliasssss** [comment]
But they see the stickers i sent via other apps

**Comment by sharadvermasv** [comment]
Have u converted them into webp and used right size?

**Comment by Zandor300** [comment]
Stickers should be either PNG or WebP, have a resolution of 512x512 and be below 100 KB. Does all of that apply to your stickers?

**Comment by Iliasssss** [comment]
Yes

**Comment by sharadvermasv** [comment]
upload your file in github and lemme know. will see ur code

**Comment by Iliasssss** [comment]
As in what file? The whole project folder?

**Comment by MayurAmipara** [comment]
Same issue for me !!

**Comment by sharadvermasv** [comment]
well emoji assigned to sticker is missing in ur code. try adding emoji

**Comment by sharadvermasv** [comment]
Check original code asset json file

**Comment by Iliasssss** [comment]
Emojis are optional right?

**Comment by Zandor300** [comment]
@Iliasssss 
>`emoji` **(optional)**: add up to a maximum of three emoji for each sticker file. Select emoji that best describe or represent that sticker file. For example, if the sticker is portraying love, you may choose to add a heart emoji like 💕. If your sticker portrays pizza, you may want to add the pizza slice emoji 🍕. In the future, WhatsApp will support a search function for stickers and tagging your sticker files with emoji will enable that. The sticker picker/tray in WhatsApp today already categorizes stickers into emotion categories (love, happy, sad, and angry) and it does this based on the emoji you tag your stickers with.
>
https://github.com/WhatsApp/stickers/blob/master/Android/README.md

**Comment by Iliasssss** [comment]
Yeah its optional, or im i that blind?

**Comment by Zandor300** [comment]
Yes, it is optional because WhatsApp currently doesn't do anything with that data. But I personally would recommend adding them to all stickers because they are planning on adding a search feature using emojis. Adding this from the start will allow this feature for all users when WhatsApp adds this, without your users having to update their packs.

Also, I think @sharadvermasv suggested this as it might fix your problem but I'm not sure. Personally haven't really played around with the Android app that much yet.

**Comment by Iliasssss** [comment]
Ill try it thankss

**Comment by Iliasssss** [comment]
Not working :( although it seems like everyone can see them on whatsappweb, just not on the app

**Comment by vandosky** [comment]
O meu no inicio foi assim e do nada começou a funcionar para outras pessoas acredito que seja a versão de wats dos celulares!

**Comment by bap94** [comment]
**Obfuscation (minifyEnabled true) not working in both Debug and Release**

I can show sticker in list but when i sending them it's just blank ( transparent ) .
minifyEnabled false working perfect

Show any progurad rules or something please tell me

**Comment by nicolasdeory** [comment]
I had the same issue. Fixed it by making sure every image met the criteria: 512x512, <150kb and WebP. I opened up the problematic webp images on photoshop, exported them as PNG (medium compression) and converted them again to webp. Problem solved.

**Comment by Iliasssss** [comment]
@nicolasdeory so is it a probelm with phtoshops webp? Or what do you mean? My files are less ten 512 and 100kb, only the icon isnt

**Comment by nicolasdeory** [comment]
The tray icon must be 96x96 and less than 50kb.

**Comment by Iliasssss** [comment]
Yeah i have that

**Comment by nicolasdeory** [comment]
I did the photoshop thing and I managed to fix it that way. Basically if it won't download for other people it means that there's something wrong with your image, and it's not the image dimensions or size. Try reconverting it to png.

**Comment by vandosky** [comment]
Iliasssss I use the 512px images and convert from png to .webp by Android Studio.

**Comment by Iliasssss** [comment]
Its working!! The problem was photoshops webp
