### ISSUE TITLE
(Android) Firebase push notification

### ISSUE THREAD

**Issue by sharadvermasv** [WhatsApp/stickers#229]
I have implemented everything right even started everything from scratch but still notification wont appear in the app. I hope the dev look into it.

**Comment by Alex193a** [comment]
The issues section must be used only to report problems related to this project. I suggest you to open a thread on stackoverflow 😉

**Comment by sharadvermasv** [comment]
Well it is an issue however i am closing

**Comment by Alex193a** [comment]
It is not a problem of this project since it does not provide notifications, it is something that you have introduced for your personal project 😄
