### ISSUE TITLE
[ANDROID] How should I edit the contents.json file to have more than 2 pack of stickers?

### ISSUE THREAD

**Issue by eduardo626** [WhatsApp/stickers#232]

**Comment by Iliasssss** [comment]
Just make a new array

**Comment by kaditya679** [comment]
You need to add new object of array in the content as already provided, just copy and paste & update the details accordingly.
make sure you change id & create same name folder in assets folder.

**Comment by eduardo626** [comment]
Could you give me an example of how to implement it?

**Comment by Alex193a** [comment]
[...]
"sticker_packs": [
    {
      "identifier": "1",
      "name": "test",
      "publisher": "Alex193a",
      [...]
      "stickers": [
        {
          "image_file": "file_982659.webp",
          "emojis": ["👋🏻", "😉"]
        },
        {
          "image_file": "file_982660.webp",
          "emojis": ["🧐", "😑"]
        }
      ]
    },
    {
      "identifier": "2",
      "name": "test2",
      "publisher": "Alex193a",
      [...]
      "stickers": [
        {
          "image_file": "file_986204.webp",
          "emojis": ["😎", "😵"]
        },
        {
          "image_file": "file_986205.webp",
          "emojis": ["😏"]
        },
      ]
    }
[...]

**Comment by Iliasssss** [comment]
@Alex193a does your sticker paxk work? Because mine doesnt work correctly, in whatsapp the stickers keep loading for ever for others

**Comment by Alex193a** [comment]
Yes, never had any problem.

**Comment by Iliasssss** [comment]
@Alex193a is yours in the playstore?

**Comment by Alex193a** [comment]
Nope, anyway we're getting off topic.

**Comment by Iliasssss** [comment]
Yeah sorry, can you please share youre code? I think this topic is solved already

**Comment by kaditya679** [comment]
@Iliasssss 
You can find an app here : 
WAStickerApps - Mega Sticker Packs
https://play.google.com/store/apps/details?id=com.stickers.whatsappstickers

so go & get some ideas out of it 👍
