### ISSUE TITLE
[Android] In Oxygen OS phones, sticker packs gets removed if WhatsApp is closed. Need to add them again

### ISSUE THREAD

**Issue by sreeharim** [WhatsApp/stickers#233]
In One Plus model phones which runs Oxygen OS, users are reporting that sticker packs get removed when WhatsApp is closed(removed from memory).  User needs to go to the app and add them again everytime.

**Comment by Alex193a** [comment]
I have a OnePlus 5T with OxygenOS 5.1.7 and I do not have this problem 🤔

**Comment by Zandor300** [comment]
Quick and dirty fix mentioned here: https://github.com/WhatsApp/stickers/issues/167#issuecomment-437684615

**Comment by sreeharim** [comment]
@Zandor300 Thanks. This fix seems to be working.
