### ISSUE TITLE
Build Error When Changing Package Name

### ISSUE THREAD

**Issue by shamilp7** [WhatsApp/stickers#236]
Guys,
Why gradle gives Buildconfig and Package R detection errors after changing my package name in manifest and changing application id in gradle file (same as package name)?

**Comment by sharadvermasv** [comment]
Can you share logcat?

**Comment by bbxtudios** [comment]
The best way to change the name of your app in the whole project (not only appears in manifest) is to make a rename with refactor, in the name of your project, com.example.appname, press right button for example in "appname" and search for the option refactor and rename, with this you will rename everything that has the name "appname" in your project, the same with "example".

It is also good to do the same in the hierarchy of your project in the folder that says com.example.appname, rename everything.

I've done it with this whatsapp project and I do not have any mistakes

**Comment by shamilp7** [comment]
That's sounds like a solution..I will try and inform.

**Comment by simonzhexu** [comment]
Changing package name can get nasty. I don't think it is necessary because your app will be referenced by ApplicationId when published.

**Comment by AlexisThink** [comment]
I have the same error, but, in my case the package name its exacly the same (build.gradle, manifest).
The log error its:  **please change your applicationId to a different string in app/build.gradle in line 16**

**The error its triggered by line 57 of build.gradle (app)**

I have no idea how to solve this.
