### ISSUE TITLE
[Android] lossy webp stickers created using android studio not supported.(but using lossless encode works)

### ISSUE THREAD

**Issue by TechPakka** [WhatsApp/stickers#237]

**Comment by Zandor300** [comment]
Could you provide more details? Like what device you are using, which version you are on? Are your stickers sticking to the requirements (512x512, < 100 KB)?

I also recommend you add `[Android]` to the start of the issue title.

**Comment by TechPakka** [comment]
thanks for the suggestion i have changed the title. My stickers meet the requirements as you said above. and its not device specific i tried on various devices and it shows the converted "sticker does not exist in the pack". This is the case when i try android studio's lossy encoding to convert png to webp. but when i encode the same png file using lossless encoding that error disappears!!.

**Comment by Zandor300** [comment]
Are you saving the webp files from Photoshop? If so, this might help you: https://github.com/WhatsApp/stickers/issues/125#issuecomment-437216036

**Comment by TechPakka** [comment]
its didnt solve my issue I was not talking about photoshop. Since im using portable photoshop i cant add webp plugins to it. So im using the android studio's default png to webp converter. and it causes above said problems.

**Comment by Zandor300** [comment]
I believe you can also select if you want to save metadata in the Android Studio WebP converter but don't quote me on that. If I'm right, please try that.
