### ISSUE TITLE
[iOS] ALAssetsLibrary depreceated

### ISSUE THREAD

**Issue by ranrinc** [WhatsApp/stickers#238]
Is there a fixed for this ALAssetsLibrary?

**Comment by Zandor300** [comment]
I don't think this is related to the contents of this repo. Where is this being used?

To still help you out a bit; the notice on the documentation page of ALAssetsLibrary may help you out a bit:
>**Important**
The Assets Library framework is deprecated as of iOS 9.0. Instead, use the Photos framework instead, which in iOS 8.0 and later provides more features and better performance for working with a user’s photo library. For more information, see Photos.<br>
In the Photos framework, the PHPhotoLibrary class manages access to and changes in the photo library, and class methods on the PHAsset and PHCollection classes and related classes provide functionality for finding photo and video assets.
>
Source: https://developer.apple.com/documentation/assetslibrary/alassetslibrary
