### ISSUE TITLE
Method to remove stickers from WhatsApp

### ISSUE THREAD

**Issue by MrOscarvs** [WhatsApp/stickers#239]
Hello, I want to create a method to remove the stickers from WhatsApp that were added from my app.
Is there any way of doing it? I want to remove the stickers from WhatsApp to the users that have an old version of my app, to force them to update it. Is there any way to remove a Sticker Pack from WhatsApp through the Sticker App? Thank you!

**Comment by Zandor300** [comment]
When users click "Add To Whatsapp" again, the sticker pack that is already in WhatsApp will be overwritten automatically. Forcing them to update their sticker packs by removing the sticker pack from WhatsApp isn't good UX design and as far as I know, there is no such API for that probably for that same reason.

**Comment by MrOscarvs** [comment]
The thing is I only want to do that if they have a too old version of my app. And when the user sends a sticker or when the user opena whatsapp, do you know if any method or any task is being executed from the stickers app?

**Comment by Zandor300** [comment]
Not on iOS at least. I'm not sure on Android because of the weird stuff going on here: https://github.com/WhatsApp/stickers/issues/167#issuecomment-437684615

Personally haven't played around with the Android stickers sample app, so I don't know a lot about that.

**Comment by MrOscarvs** [comment]
Okey thanks. Please, if anyone knows if it's there any method or any task that is being executed from the stickers app when the user sends a sticker or when the user opens whatsapp, (on Android), please, let me know :)

**Comment by simonzhexu** [comment]
You cannot remove stickers from WhatsApp. 

You won't know when someone uses the sticker since it is a privacy concern.

**Comment by Zandor300** [comment]
It’s not possible. You could create a background task to check for updates or implement push notifications to notify users of updates but you will never know when the user uses one of your stickers.

**Comment by adityaspt** [comment]
> Whatsapp is not updating the stickers. It keeps saying Sticker pack already added.

Yes i facing the same thing.

**Comment by adnanmacro** [comment]
Can anyone please assist how to get notify if user deleted my sticker pack from whatsapp? Thanks
