### ISSUE TITLE
[Moderation] Users unable to assign people and tags - Clean up the issues - Pull requests

### ISSUE THREAD

**Issue by Zandor300** [WhatsApp/stickers#240]
@amrit-1901 @simonzhexu 

You suggest people assign you to issues in the readme. Except people aren't able to assign you guys to issues.

I already have a pull request running with an issue template which hasn't been looked at in the past day: https://github.com/WhatsApp/stickers/pull/234

Maybe also mention to us what you guys are thinking about the issues with apps not passing review over at both the App Store and Play Store. Are you guys working on this? You guys seem to be very inactive.

The issues are also piling up. Maybe closing unrelated issues to the project and closing solved ones may help clean up the mess that it is currently. Allow users to add tags to the projects. Add tags for both iOS and Android to help sort through the issues.

Maybe give one of the active members here permission to close and moderate issues to help you guys with this if you can't take the workload of moderating the issues.

**Comment by simonzhexu** [comment]
Thank you @Zandor300 , We heard you. 

Sorry. I didn't know you cannot assign issues to people.

We are working with Apple and Google on the app store review problem.

**Comment by simonzhexu** [comment]
Thank you @Zandor300.
