### ISSUE TITLE
How to remove "add to favorites" ?

### ISSUE THREAD

**Issue by kikikdev** [WhatsApp/stickers#241]
How to remove or disable "add to favorites" when i am clicked the sticker?

**Comment by Alex193a** [comment]
It's not possible.

**Comment by Zandor300** [comment]
@simonzhexu Can be closed.

**Comment by kikikdev** [comment]
Yes, if i am sent the sticker for my friends, i want disable or remove "add to favorites" because I will make my application paid. it's possible?

**Comment by Zandor300** [comment]
No.

**Comment by kikikdev** [comment]
Ok thx
