### ISSUE TITLE
[IOS] Stickers do not load on whatsapp

### ISSUE THREAD

**Issue by ImperadorII** [WhatsApp/stickers#244]
the app works fine until I click "Add to WhatsApp", it opens the app, theoretically loads the stickers, but when I click "Save", the app freezes.

![46381378_1432176253586690_7933339061442314240_n](https://user-images.githubusercontent.com/45076117/48569994-51f80480-e8ea-11e8-80b8-0c029be5ab62.jpg)

**Comment by Zandor300** [comment]
Do your stickers comply with the sticker requirements (512x512 and less than 100 KB)? Are you using PNG or WebP images?

**Comment by ImperadorII** [comment]
> Do your stickers comply with the sticker requirements (512x512 and less than 100 KB)? Are you using PNG or WebP images?

As far I checked, yes, they do comply with the requirements, and I am using WebP.

**Comment by Zandor300** [comment]
Did you export the images from Photoshop and are you using the following plugin?  
https://github.com/fnordware/AdobeWebM

If so, did you uncheck the "Save Metadata" checkbox as suggested here:  
https://github.com/WhatsApp/stickers/issues/167#issuecomment-437216044

**Comment by ImperadorII** [comment]
> Did you export the images from Photoshop and are you using the following plugin?
> https://github.com/fnordware/AdobeWebM
> 
> If so, did you uncheck the "Save Metadata" checkbox as suggested here:
> [#167 (comment)](https://github.com/WhatsApp/stickers/issues/167#issuecomment-437216044)

I'll try it in a minute and come with updates

**Comment by ImperadorII** [comment]
> Did you export the images from Photoshop and are you using the recommended plugin?
> https://github.com/fnordware/AdobeWebM
> 
> If so, did you uncheck the "Save Metadata" checkbox as suggested here:
> [#167 (comment)](https://github.com/WhatsApp/stickers/issues/167#issuecomment-437216044)

It worked! Thanks a lot!
