### ISSUE TITLE
[Android] build error

### ISSUE THREAD

**Issue by amine-T** [WhatsApp/stickers#248]
how i can fix this error:

Error:Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/xfato/Desktop/app/stickers-master/Android/app/build.gradle' line: 63

* What went wrong:
Execution failed for task ':app:checkDebug'.
> Your applicationId is currently com.example.samplestickerapp, please change your applicationId to a different string in app/build.gradle in line 16

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

**Comment by sharadvermasv** [comment]
Read the readme file. Changing package name is must.

**Comment by Zandor300** [comment]
No, you have a different error now:

>applicationId in defaultConfig cannot start with com.xplitft.fbstickerbartio, please change your applicationId in app/build.gradle
>

Please read your error messages. Doing exactly what is stated in there, will solve your problem.
