### ISSUE TITLE
How to put a "View More " button in my sticker app and hw i link it with my playstore app

### ISSUE THREAD

**Issue by Nitinundhad** [WhatsApp/stickers#250]

**Comment by Zandor300** [comment]
Please add `[Android]` to the start of your title.

You can find code on how to do this here: https://stackoverflow.com/a/11753070/5544222

**Comment by rishabhdugar** [comment]
Put this line in contents.json

"android_play_store_link": "https://play.google.com/store/apps/details?id=wa.stickers.emoji.app",

**Comment by DevAmal** [comment]
> Put this line in contents.json
> 
> "android_play_store_link": "https://play.google.com/store/apps/details?id=wa.stickers.emoji.app",

can i place my website link instead of playstore link?

**Comment by Zandor300** [comment]
@DevAmal Only supports Google Play links I believe.

**Comment by Ayab14** [comment]
Did you find a solution or not yet?

**Comment by sakib143** [comment]
Have you find any solution for this?

**Comment by OsamaFarooqi** [comment]
> > Put this line in contents.json
> > "android_play_store_link": "https://play.google.com/store/apps/details?id=wa.stickers.emoji.app",
> 
> can i place my website link instead of playstore link?

You can add "publisher_website" for each sticker pack

**Comment by lipepoggers** [comment]
where is the content.json file??????????????????

**Comment by lipepoggers** [comment]
> Put this line in contents.json
> 
> "android_play_store_link": "https://play.google.com/store/apps/details?id=wa.stickers.emoji.app",

where is this man??? 😖😖😖😖😖😖😖😖😖
