### ISSUE TITLE
[Android] Complaints about stickers not being added

### ISSUE THREAD

**Issue by GlowMLG** [WhatsApp/stickers#254]
I have a really popular app and half of my 1 star ratings are because people won't understand that it doesnt work with GBWhatsapp and the other half that the stickers aren't added to WhatsApp correctly. I have pretty much the base template with a couple tweaks. I have 2 main isses I'm unable to replicate and fix:

- Stickers aren't added to WhatsApp with the add button (for some the '+' works)

- Stickers disappear after a while from WhatsApp

Does anyone else have these issues? I'm posting them together because they may be related

Thanks

**Comment by Zandor300** [comment]
Disappearing of stickers is caused by optimisation of non-Google device manufacturers. For a quick and dirty fix, see https://github.com/WhatsApp/stickers/issues/167#issuecomment-437684615

Also, I'm pretty sure GBWhatsApp isn't supported by the official WhatsApp team. With your first issue, do you mean they can't be added to the official WhatsApp app, or GBWhatsApp?

**Comment by GlowMLG** [comment]
Is there anything I can do with code instead of having to tell everyone to do disable battery optimization?

And yes, I'm already aware GBWhatsapp and Whatsapp Plus haven't implemented stickers yet, I just wanted to point it out. The issue is that many people say that the 'Add to Whatsapp' button or the '+' icon next to the pack do nothing at all. But the weird thing is that they're using the official WhatsApp app

Thanks

**Comment by Zandor300** [comment]
You can't do anything about the battery optimization as non-Google device manufacturers don't supply APIs for this.

As for your other issue, someone else might be able to help you as I personally haven't really played around with the Android app and I am going of things I learned from moderating this forum.

**Comment by simonzhexu** [comment]
> Is there anything I can do with code instead of having to tell everyone to do disable battery optimization?
> 
> And yes, I'm already aware GBWhatsapp and Whatsapp Plus haven't implemented stickers yet, I just wanted to point it out. The issue is that many people say that the 'Add to Whatsapp' button or the '+' icon next to the pack do nothing at all. But the weird thing is that they're using the official WhatsApp app
> 
> Thanks

These users have an old WhatsApp build. Update your app to the latest master. It will remind these users to upgrade WhatsApp.

**Comment by jackdimon** [comment]
> > Is there anything I can do with code instead of having to tell everyone to do disable battery optimization?
> > And yes, I'm already aware GBWhatsapp and Whatsapp Plus haven't implemented stickers yet, I just wanted to point it out. The issue is that many people say that the 'Add to Whatsapp' button or the '+' icon next to the pack do nothing at all. But the weird thing is that they're using the official WhatsApp app
> > Thanks
> 
> These users have an old WhatsApp build. Update your app to the latest master. It will remind these users to upgrade WhatsApp.

Download the latest version of GBWhatsapp and also the GBetickers app..mine works like a charm
