### ISSUE TITLE
Error while Launching activity

### ISSUE THREAD

**Issue by developerpistachio** [WhatsApp/stickers#255]
11/16 23:51:55: Launching app
$ adb install-multiple -r -t C:\Users\Subham Saha\Downloads\stick\Android\app\build\intermediates\split-apk\debug\dep\dependencies.apk C:\Users\Subham Saha\Downloads\stick\Android\app\build\intermediates\split-apk\debug\slices\slice_1.apk C:\Users\Subham Saha\Downloads\stick\Android\app\build\intermediates\split-apk\debug\slices\slice_0.apk C:\Users\Subham Saha\Downloads\stick\Android\app\build\intermediates\split-apk\debug\slices\slice_2.apk C:\Users\Subham Saha\Downloads\stick\Android\app\build\intermediates\split-apk\debug\slices\slice_4.apk C:\Users\Subham Saha\Downloads\stick\Android\app\build\intermediates\split-apk\debug\slices\slice_3.apk C:\Users\Subham Saha\Downloads\stick\Android\app\build\intermediates\split-apk\debug\slices\slice_5.apk C:\Users\Subham Saha\Downloads\stick\Android\app\build\intermediates\split-apk\debug\slices\slice_8.apk C:\Users\Subham Saha\Downloads\stick\Android\app\build\intermediates\split-apk\debug\slices\slice_7.apk C:\Users\Subham Saha\Downloads\stick\Android\app\build\intermediates\split-apk\debug\slices\slice_6.apk C:\Users\Subham Saha\Downloads\stick\Android\app\build\intermediates\split-apk\debug\slices\slice_9.apk C:\Users\Subham Saha\Downloads\stick\Android\app\build\intermediates\instant-run-apk\debug\app-debug.apk 
Split APKs installed
$ adb shell am start -n "com.example.samplestickerapp/com.example.samplestickerapp.EntryActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while executing: am start -n "com.example.samplestickerapp/com.example.samplestickerapp.EntryActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.example.samplestickerapp/.EntryActivity }
Error type 3
Error: Activity class {com.example.samplestickerapp/com.example.samplestickerapp.EntryActivity} does not exist.

Error while Launching activity

** I am getting this error....can't launch or install the app
** I only changed the ApplicationId in build.gradle......didn't change the package name or anything.....and tried to run the app

**Comment by Zandor300** [comment]
>Error: Activity class {com.example.samplestickerapp/com.example.samplestickerapp.EntryActivity} does not exist.
>

Try to see if anything is wrong with that class. Or start over and use this handy trick to rename your bundle id: https://github.com/WhatsApp/stickers/issues/236#issuecomment-439182445

**Comment by developerpistachio** [comment]
![4](https://user-images.githubusercontent.com/41967292/48725037-f4004f80-ec50-11e8-9b6c-a7d24996b949.JPG)
When I rename the package I can only edit the part after 'example'. How can I rename the 'example' part also ?

**Comment by pranshu1701** [comment]
[](url)
<img width="1146" alt="screen shot 2018-11-22 at 9 15 13 am" src="https://user-images.githubusercontent.com/5506707/48880578-2b305580-ee37-11e8-9f2e-3c2bb15ecbbf.png">

Uncheck Flatten Package then you can edit the whole name
