### ISSUE TITLE
[IOS] fatalError(error.localizedDescription) in Xcode

### ISSUE THREAD

**Issue by FabryDeveloper** [WhatsApp/stickers#256]
Each time I start the application, Xcode gives me this error:
fatalError(error.localizedDescription)
![schermata 2018-11-16 alle 19 38 35](https://user-images.githubusercontent.com/45106681/48640515-374f8980-e9d7-11e8-92f0-ced35a6095f1.png)

**Comment by FabryDeveloper** [comment]
Can you help me, please?

**Comment by amrit-1901** [comment]
Your JSON file doesn't have the correct structure. Check for missing commas, parentheses, etc

**Comment by Zandor300** [comment]
Run your JSON config through a service like https://jsoneditoronline.org. That will tell exactly where your error is.
