### ISSUE TITLE
[IOS] Error Write image data to saved photos in Xcode

### ISSUE THREAD

**Issue by JoelSalcedo** [WhatsApp/stickers#257]
Hi, I just started. I want to make my stikers request for (ios). You are following the instructions, but send me these errors. Could someone support me?
![img_0527](https://user-images.githubusercontent.com/45082753/48646306-20e10800-e9ae-11e8-98de-6dfb10580f2c.jpg)

**Comment by Zandor300** [comment]
Those are warnings. The app will work just fine with these warnings. For more info, check https://github.com/WhatsApp/stickers/issues/238
