### ISSUE TITLE
Add own photo as sticker

### ISSUE THREAD

**Issue by HareshSolankiibl** [WhatsApp/stickers#258]
Hello,
  how can i convert own pic/photo as sticker. can is possible to i convert png to webp programatically? or other way is possible?

**Comment by HareshSolankiibl** [comment]
> Use Photoshop and save it as png through android studio convert it to webp

thanks dear for replay,
 but what for when i take photo using camera?

**Comment by simonzhexu** [comment]
You can reference the photos you took, see https://github.com/WhatsApp/stickers/blob/master/Android/README.md#expose-files-that-are-stored-internally-as-stickers-through-contentprovider on how to access those files. If you still have questions on how to get the image from camera, Stackoverflow would be more proper place to get answers.
