### ISSUE TITLE
Unable to add in stickers in second space

### ISSUE THREAD

**Issue by Vengat121** [WhatsApp/stickers#259]
when i use whatsapp in second space unable to use it

**Comment by Zandor300** [comment]
If you mean you want to make a second sticker pack, please read through this issue: https://github.com/WhatsApp/stickers/issues/252

**Comment by Vengat121** [comment]
no, i have two whatsapp in my mobile like two user accounts in window. i need to install third party for whatsapp in my second account(dual space)

**Comment by Zandor300** [comment]
Third-party WhatsApp apps are not supported here. You could however modify your stickers app to select which app you want to add your stickers to. To get support on how to do this, you are better of making a question on StackOverflow.

**Comment by Vengat121** [comment]
sorry i mean thirdy party sticker app

**Comment by Vengat121** [comment]
https://drive.google.com/file/d/127com9V9uJzaLS8qBNpcBwQqFYvTixwu/view?usp=drivesdk

**Comment by Syzygianinfern0** [comment]
> sorry i mean third party sticker app

Did you get to find out how to do this?
