### ISSUE TITLE
Potential leak: extendedImage

### ISSUE THREAD

**Issue by luiscraik** [WhatsApp/stickers#262]
Hi there, 
has someone encountered this alarming message on Xcode: 

> Object leaked: object allocated and stored into 'extendedImage' is not referenced later in this execution path and has a retain count of +1

 

I get it while running the Product > Analyze. Is there a fix for that? 
Thank you!

**Comment by Zandor300** [comment]
This is actually a memory leak in YYImage, which means that this isn't actually related to this project. Additionally, it is in a function that will never be called in the sample Stickers project so you don't actually have to worry about it. Though, feel free to make an issue and/or pull request over at https://github.com/ibireme/YYImage

https://github.com/WhatsApp/stickers/blob/0557409f9dc3b082cebe96e954890f450e9a8587/iOS/WAStickersThirdParty/YYImageCoder.m#L2564

**Comment by luiscraik** [comment]
Got it. Thank you @Zandor300
