### ISSUE TITLE
Create sticker from firebase

### ISSUE THREAD

**Issue by 3rsin3rgul** [WhatsApp/stickers#263]
Hey there,
I created models on firestore and im fetchig them. 
Is there any way to create sticker from those data or is there any sample app (iOS)

Thanks in advance 👍

**Comment by diepox** [comment]
Hi
Can you please provide how do you did that?
Are your stickers now fetch from firebase?

**Comment by amrit-1901** [comment]
This issue is off topic. Better discuss this elsewhere.
