### ISSUE TITLE
Android App Crashes in Developer Console

### ISSUE THREAD

**Issue by rishabhdugar** [WhatsApp/stickers#265]
I am finding crashes in my developer console, not able to locate the line, can someone please throw some light.
<img width="1038" alt="screenshot 2018-11-18 at 9 11 12 am" src="https://user-images.githubusercontent.com/7722125/48668390-0e7fdf00-eb12-11e8-9f8e-6bf1b0885e21.png">
<img width="1038" alt="screenshot 2018-11-18 at 9 11 18 am" src="https://user-images.githubusercontent.com/7722125/48668391-0f187580-eb12-11e8-970a-695747824588.png">

**Comment by rishabhdugar** [comment]
thanks for you comment, i just uploaded the file, lets see what i get, but i am little surprised as to why there are crashes in the first place, i have done no customization but changing json file and adding webp files.

**Comment by simonzhexu** [comment]
I have merged the fix. Thanks!

**Comment by rishabhdugar** [comment]
@simonzhexu , can you confirm the fix for all below crashes?? let me know if you need more logs
<img width="1000" alt="screenshot 2018-11-20 at 10 37 57 pm" src="https://user-images.githubusercontent.com/7722125/48790266-f926d280-ed14-11e8-9e24-ef9e9e304f80.png">
<img width="990" alt="screenshot 2018-11-20 at 10 37 51 pm" src="https://user-images.githubusercontent.com/7722125/48790264-f88e3c00-ed14-11e8-9921-61a57d0bb036.png">
