### ISSUE TITLE
Has anyone created apps that let you create your own Whatsapp stickers yet?

### ISSUE THREAD

**Issue by GoDzM4TT3O** [WhatsApp/stickers#267]
I am on iOS, so I wanted to know if I can create custom Whatsapp stickers with apps on the AppStore. This is already possible on Android.

**Comment by shamilp7** [comment]
Can you please guide me how do it in android?

**Comment by louislam** [comment]
@shamilp7 My platform could do this

https://whatsticker.online/create-pack

**Comment by shamilp7** [comment]
No mate..I mean that can I make an android app,that allows user to make their own WhatsApp sticker?.

**Comment by simonzhexu** [comment]
Sorry, please file real issues.
