### ISSUE TITLE
Can't make it run

### ISSUE THREAD

**Issue by Chosho-chan** [WhatsApp/stickers#268]
So I followed the instructions we're given very carefully and probably did it right.
As I am in general new to creating applications and using Android Studio I'm wondering why my Run button is greyed out?
I already looked around for solutions, e.g. where you select the module in the run configs, however there is no module to be seen.

I don't know if I overlooked something but I hope someone can help me. Right now I only have a bunch of code and some pics but no possibility to try out the app.

**Comment by MarvinJWendt** [comment]
Hey, if you still have that problem:
Can you please look if you followed those steps: https://developer.android.com/training/basics/firstapp/running-app

**Comment by sama940** [comment]
while importing project, provide path till "Android"  folder, you could be providing path till parent directory of "Android" directory.

**Comment by simonzhexu** [comment]
Question is not clear. Follow suggestion from @MarvinJWendt and familiarize yourself with Android Studio.
