### ISSUE TITLE
Enable webp animated

### ISSUE THREAD

**Issue by metalex10** [WhatsApp/stickers#271]
Enable an option to insert animated webp
I see that they use the cool library that supports animated webp because they do not implement it and do not leave it there

**Comment by sharadvermasv** [comment]
that will be cool

**Comment by Alex193a** [comment]
As written in ReadMe, animated webp will be supported in the future.

**Comment by lukzinho** [comment]
that would be very good !! I do not understand why it does not support at least for developers since everything today and for everyone :)
