### ISSUE TITLE
Info page/About page Title problem

### ISSUE THREAD

**Issue by sahqazhar** [WhatsApp/stickers#274]
![screenshot_20181119-160245](https://user-images.githubusercontent.com/43394618/48701531-bed60c00-ec14-11e8-961b-cce667e2eba4.png)
I want to change the name in the About/Info page but it is always displaying Tray icon
How to fix?
Someone please help me out with this.

**Comment by Zandor300** [comment]
Use the strings xml file.

**Comment by sahqazhar** [comment]
I have used ....but no output
I have 2 sticker pack so I think it's creating a problem

**Comment by Zandor300** [comment]
Having 2 stickerpacks shouldn’t matter

**Comment by sahqazhar** [comment]
In every sticker pack I am getting the same name Tray icon

**Comment by Zandor300** [comment]
So you’ve editted the following file on your local copy? https://github.com/WhatsApp/stickers/blob/master/Android/app/src/main/res/values/strings.xml

**Comment by sahqazhar** [comment]
@Zandor300
It's the exact same thing I am having

**Comment by Zandor300** [comment]
Please post source of that file here so we can look at it

**Comment by sahqazhar** [comment]
@Zandor300 

here is my code
<resources>
    <string name="app_name">WhatsApp Stickers</string>
    <string name="tray_image_content_description">Sticker Pack Tray Image</string>
    <string name="more_info_button">More info about sticker pack</string>
    <string name="add_to_whatsapp">Add to WhatsApp</string>
    <string name="add_button_content_description">Add sticker pack to WhatsApp</string>
    <string name="title_activity_sticker_packs_list">Sticker Packs</string>
    <string name="dot">•</string>
    <string name="title_activity_sticker_pack_details_single_pack">Sticker Pack</string>
    <string name="title_activity_sticker_pack_details_multiple_pack">Sticker details</string>
    <string name="title_activity_sticker_pack_info">Info</string>
    <string name="view_webpage">Instagram</string>
    <string name="send_email">Send email</string>
    <string name="privacy_policy">Privacy policy</string>
    <string name="error_adding_sticker_pack">Could not add this sticker pack. Please install the latest version of WhatsApp before adding sticker pack</string>
    <string name="error_message">Error: %s \nSee logcat for stack trace.</string>
    <string name="title_validation_error">Error with the pack</string>
    <string name="info_screen_tray_icon">Tray icon</string>
    <string name="details_pack_already_added">Sticker pack added to WhatsApp</string>
    <string name="info_send_email_to_prompt">Send email with</string>
    <string name="add_pack_fail_prompt_update_whatsapp">Sticker pack not added. If you\'d like to add it, make sure you update to the latest version of WhatsApp.</string>
    <string name="add_pack_fail_prompt_update_play_link">Update</string>
    <string name="cannot_find_play_store">Google Play is not installed on the device.</string>
    <string name="desc_text">All Stickers in this pack created by SAHQ  All rights reserved.\n\n<b>Version 1.0</b></string>
    
</resources>

**Comment by sahqazhar** [comment]
@Zandor300 
<resources>
    <string name="app_name">WhatsApp Stickers</string>
    <string name="tray_image_content_description">Sticker Pack Tray Image</string>
    <string name="more_info_button">More info about sticker pack</string>
    <string name="add_to_whatsapp">Add to WhatsApp</string>
    <string name="add_button_content_description">Add sticker pack to WhatsApp</string>
    <string name="title_activity_sticker_packs_list">Sticker Packs</string>
    <string name="dot">•</string>
    <string name="title_activity_sticker_pack_details_single_pack">Sticker Pack</string>
    <string name="title_activity_sticker_pack_details_multiple_pack">Sticker details</string>
    <string name="title_activity_sticker_pack_info">Info</string>
    <string name="view_webpage">Instagram</string>
    <string name="send_email">Send email</string>
    <string name="privacy_policy">Privacy policy</string>
    <string name="error_adding_sticker_pack">Could not add this sticker pack. Please install the latest version of WhatsApp before adding sticker pack</string>
    <string name="error_message">Error: %s \nSee logcat for stack trace.</string>
    <string name="title_validation_error">Error with the pack</string>
    <string name="info_screen_tray_icon">Tray icon</string>
    <string name="details_pack_already_added">Sticker pack added to WhatsApp</string>
    <string name="info_send_email_to_prompt">Send email with</string>
    <string name="add_pack_fail_prompt_update_whatsapp">Sticker pack not added. If you\'d like to add it, make sure you update to the latest version of WhatsApp.</string>
    <string name="add_pack_fail_prompt_update_play_link">Update</string>
    <string name="cannot_find_play_store">Google Play is not installed on the device.</string>
    <string name="desc_text">All Stickers in this pack created by SAHQ. All rights reserved.\n\n<b>Version 1.0</b></string>
    
</resources>

**Comment by sahqazhar** [comment]
@Zandor300 `
<resources>
    <string name="app_name">WhatsApp Stickers</string>
    <string name="tray_image_content_description">Sticker Pack Tray Image</string>
    <string name="more_info_button">More info about sticker pack</string>
    <string name="add_to_whatsapp">Add to WhatsApp</string>
    <string name="add_button_content_description">Add sticker pack to WhatsApp</string>
    <string name="title_activity_sticker_packs_list">Sticker Packs</string>
    <string name="dot">•</string>
    <string name="title_activity_sticker_pack_details_single_pack">Sticker Pack</string>
    <string name="title_activity_sticker_pack_details_multiple_pack">Sticker details</string>
    <string name="title_activity_sticker_pack_info">Info</string>
    <string name="view_webpage">Instagram</string>
    <string name="send_email">Send email</string>
    <string name="privacy_policy">Privacy policy</string>
    <string name="error_adding_sticker_pack">Could not add this sticker pack. Please install the latest version of WhatsApp before adding sticker pack</string>
    <string name="error_message">Error: %s \nSee logcat for stack trace.</string>
    <string name="title_validation_error">Error with the pack</string>
    <string name="info_screen_tray_icon">Tray icon</string>
    <string name="details_pack_already_added">Sticker pack added to WhatsApp</string>
    <string name="info_send_email_to_prompt">Send email with</string>
    <string name="add_pack_fail_prompt_update_whatsapp">Sticker pack not added. If you\'d like to add it, make sure you update to the latest version of WhatsApp.</string>
    <string name="add_pack_fail_prompt_update_play_link">Update</string>
    <string name="cannot_find_play_store">Google Play is not installed on the device.</string>
    <string name="desc_text">All Stickers in this pack created by SAHQ .All rights reserved.\n\n<b>Version 1.0</b></string>
    
</resources>`

**Comment by sahqazhar** [comment]
@Zandor300 
here is my code  

`<resources>
    <string name="app_name">WhatsApp Stickers</string>
    <string name="tray_image_content_description">Sticker Pack Tray Image</string>
    <string name="more_info_button">More info about sticker pack</string>
    <string name="add_to_whatsapp">Add to WhatsApp</string>
    <string name="add_button_content_description">Add sticker pack to WhatsApp</string>
    <string name="title_activity_sticker_packs_list">Sticker Packs</string>
    <string name="dot">•</string>
    <string name="title_activity_sticker_pack_details_single_pack">Sticker Pack</string>
    <string name="title_activity_sticker_pack_details_multiple_pack">Sticker details</string>
    <string name="title_activity_sticker_pack_info">Info</string>
    <string name="view_webpage">Instagram</string>
    <string name="send_email">Send email</string>
    <string name="privacy_policy">Privacy policy</string>
    <string name="error_adding_sticker_pack">Could not add this sticker pack. Please install the latest version of WhatsApp before adding sticker pack</string>
    <string name="error_message">Error: %s \nSee logcat for stack trace.</string>
    <string name="title_validation_error">Error with the pack</string>
    <string name="info_screen_tray_icon">Tray icon</string>
    <string name="details_pack_already_added">Sticker pack added to WhatsApp</string>
    <string name="info_send_email_to_prompt">Send email with</string>
    <string name="add_pack_fail_prompt_update_whatsapp">Sticker pack not added. If you\'d like to add it, make sure you update to the latest version of WhatsApp.</string>
    <string name="add_pack_fail_prompt_update_play_link">Update</string>
    <string name="cannot_find_play_store">Google Play is not installed on the device.</string>
    <string name="desc_text">All Stickers in this pack created by SAHQ. All rights reserved.\n\n<b>Version 1.0</b></string>
    
</resources>`

**Comment by sahqazhar** [comment]
![screenshot 167](https://user-images.githubusercontent.com/43394618/48710716-3e70d480-ec2f-11e8-8361-3ba9d2f9633c.png)
@Zandor300 here is my code

**Comment by Zandor300** [comment]
It still says Tray icon on line 18...

**Comment by sahqazhar** [comment]
So what it should be?
I think it's the same in the original file

**Comment by Zandor300** [comment]
Whatever you want it to be, you wanted to change Tray icon into something different. That is atleast what I got from your initial question.

**Comment by sahqazhar** [comment]
@Zandor300
It's not working for different sticker pack ...
I said I have 2 packs so I can't have the same sticker pack name in the info section

**Comment by suriya27** [comment]
@sahqazhar what do you need in the info section about you app info or about your corresponding sticker pack info?

**Comment by sahqazhar** [comment]
@suriya27
I want the corresponding sticker pack info

**Comment by suriya27** [comment]
ok then you need to edit the strings.xml file.
Example:
<string name="pack_info1"> Here Put Your Sticker Pack 1 Info<\string>
<string name="pack_info2"> Here Put Your Sticker Pack 2 Info<\string>
similarly enter infos of stickers you need to show.

Then edit the java file to match with pack info 1 if sticker pack one is clicked and put the settext to match with xml string resource.

**Comment by sahqazhar** [comment]
@suriya27
Thank you so much for your reply
But can you please specify which Java file I need to make changes?

**Comment by suriya27** [comment]
The Java File Which Invokes The Info Screen

**Comment by simonzhexu** [comment]
Tray icon is not the title of the page. you want to change Info, then edit "title_activity_sticker_pack_info" string in https://github.com/WhatsApp/stickers/blob/master/Android/app/src/main/res/values/strings.xml
