### ISSUE TITLE
I want to add a button for the preview

### ISSUE THREAD

**Issue by AnasCode** [WhatsApp/stickers#275]
I want to add a button for previewing the pack , currently to see what each pack has you can just click on the pack , but i want to add a button for that , i looked through the code to find the lines that are responsible of this action but i couldn't

**Comment by suriya27** [comment]
Check Line Number 44-60 In EntryActivity.java. 
Follow Whatever Classes are Called From There It Will Help You.
For Example, the if . . else Statement in Line Number 46 on EntryActivity is Used for Checking Total Counts Of Sticker Pack.
If there is only One Sticker Pack ,No need to Call StickerPackListActivity. So else part Is Executed Which is Displaying the Preview of The Only Sticker Available .

For Your Requirement, You Need To Edit The Layout for StickerPackListActivity to Show Button In It.

**Comment by AnasCode** [comment]
@suriya27 thanks i'm going to check the class you told me about
