### ISSUE TITLE
[iOS] Rejected External Testers

### ISSUE THREAD

**Issue by luiscraik** [WhatsApp/stickers#276]
FYI, I uploaded my Sticker app (based on the stickers repository) to the App Store **Connect** page for some testing. I decided to just do an external test (still not ready for submit) with a couple of friends and surprise, I got a Binary Rejected alert for **4. 3 Design: Spam**.

I am still waiting for some good news from talks between Apple and WhatsApp. Meanwhile, I am illustrating and tunning my stickers. I hope all of my work, as well as all the hard work people around the sticker app, have done can see light. 

Thanks!

**Comment by Zandor300** [comment]
This comes down to the same reason as just releasing to the App Store. See issue: https://github.com/WhatsApp/stickers/issues/230
