### ISSUE TITLE
Android | iOs - How to get a license from WhatsApp?

### ISSUE THREAD

**Issue by sdergachev** [WhatsApp/stickers#279]
How to get a license to use the name WhatsApp, necessary for the application to work with stickers?

Hi.

Like many others, цe received a letter from Google which is said that our application «WhatsApp Stickers – Wachanga» has been removed from Google Play – «REASON FOR SUSPENSION: Alleged trademark infringement». Google also said that the reason for this decision was a complaint:

From Alexis Meghrouni Rivas 
Director, Enforcement Strategies and Services, WhatsApp
enf.whatsapp.18186@enfappdetex.com
<…>
https://play.google.com/store/apps/details?id=com.wachanga.stickers
The app uses the trademarks, banners, badges and logos 
of WhatsApp without authorization.

We want to assure that we did not intend to violate the rights and interests of WhatsApp or other companies. On the contrary, our application is designed to increase the popularity of the messenger and separately a new function among its users. In developing our product, we were inspired by and used an official guide - https://faq.whatsapp.com/general/26000226.

We studied all documents, including everything at https://whatsappbrand.com/, sent many letters to all available addresses (including brand@whatsapp.com). But it took a long time, but did not receive an answer.

We ask you to give permission to use the trademarks, banners, badges and logos of WhatsApp in our Android and iOS Apps – in order to Google could restore our application, and to avoid any problems with Apple Store, when we release the same application on iOS. 

How to get it? What god to pray?

**Comment by Alex193a** [comment]
WhatsApp doesn't allow the use of their name and they won't give the permission to use it. 

Also, at the moment the Apple App Store has removed almost all of the stickers app for WhatsApp and it reject all the new apps because they are considered spam, so it's useless to release the app on iOS.

**Comment by sdergachev** [comment]
@simonzhexu

**Comment by simonzhexu** [comment]
For your Android app, please don't use WhatsApp in your app name. You are allowed to use WhatsApp in the description. And make sure you put WAStickerApps in your description. This will help your app show up in Play Search.

For iOS, it is a different story, we are working with Apple. Our current suggestion is for you to build a very different UI from the sample app. You may also include additional functionality. Otherwise, Apple would not allow your app to be published. Sorry about that. But we are figuring this out.

**Comment by lemiapps** [comment]
Hi, We have the same issue on Google Play with our WhatsApp Auto Reply, package name com.lemi.whatsappautoreply. Have you succeed to solve the issue?
Google wrote “You may contact WhatsApp at gp.enforcements.prod@gmail.com. If WhatsApp contacts us specifically authorizing your app to be re-published”

We tried a couple of time to contact Alexis at 
gp.enforcements.prod@gmail.com
and
enf.whatsapp.51081@enfappdetex.com

Unfortunately, we got no answer.

**Comment by nguyencongbinh** [comment]
> For your Android app, please don't use WhatsApp in your app name. You are allowed to use WhatsApp in the description. And make sure you put WAStickerApps in your description. This will help your app show up in Play Search.
> 
> For iOS, it is a different story, we are working with Apple. Our current suggestion is for you to build a very different UI from the sample app. You may also include additional functionality. Otherwise, Apple would not allow your app to be published. Sorry about that. But we are figuring this out.

Hello Simon,
Can I use WA on my app title name like "Auto Reply for WA"? Thank you.

**Comment by lemiapps** [comment]
> For your Android app, please don't use WhatsApp in your app name. You are allowed to use WhatsApp in the description. And make sure you put WAStickerApps in your description. This will help your app show up in Play Search.
> 
> For iOS, it is a different story, we are working with Apple. Our current suggestion is for you to build a very different UI from the sample app. You may also include additional functionality. Otherwise, Apple would not allow your app to be published. Sorry about that. But we are figuring this out.
=======
@simonzhexu
on Google Play
AutoResponder for WhatsApp
https://play.google.com/store/apps/details?id=tkstudio.autoresponderforwa&hl=en
Auto Reply for WA was removed

**Comment by nguyencongbinh** [comment]
How the app "AutoResponder for WhatsApp" is allowed but your app "Auto Reply for WA" was removed?
How long your app was removed since received email from Google?

**Comment by lemiapps** [comment]
Same moment 
reply from WhatsApp:
While we appreciate that you wish to, or may have modified your app, we don’t review or consent to republication of apps.
Please carefully review and comply with the policies and guidelines published by WhatsApp and Google Play
Below is a partial list of examples from our guidelines that illustrate a few common issues with developers' apps. As noted above, please review the complete WhatsApp guidelines and terms of service and ensure your app complies with all of them as well as the app store’s guidelines.

- The title of your app cannot include the name WhatsApp or any variation, phonetic equivalent, foreign language equivalent, takeoff, **or abbreviation** of a WhatsApp trademark, (or any portion of it), for any purpose. Here are a few examples of text that can’t be included in a app title: WhatsAp, Watsapp, WutsApp, wazapp, watapp, wutzap, watzapp, ZapZap, etc.

- References to WhatsApp should be restricted to the description of your app (not the description included in the title).

- Don’t combine the WhatsApp name or logos, or any portion of them, with any other logo, company name, mark or generic terms.

- Don’t use an image confusingly similar to the WhatsApp telephone logo or any other WhatsApp Brand Resource or other variation of any WhatsApp Brand Resource for any purpose.

- Don’t edit, modify, distort, rotate or recolor the WhatsApp logo.

**Comment by nguyencongbinh** [comment]
@lemiapps , thank you for your info. 
As I read above, It looks like you named the app is "WhatsApp Auto Reply", not "Auto Reply for WA", isn't it?

How many times they/Google alerted your before your app was get removed? Did they give you a chance to update your app to comply the trademark policy?

**Comment by lemiapps** [comment]
no We tried  2 names
Auto Reply for WA
Whats  Auto Reply
Both removed
The title of your app cannot include the name WhatsApp or any variation, phonetic equivalent, foreign language equivalent, takeoff, or abbreviation
No alerts - Just removed - no chance to update
Your app has been suspended and removed due to alleged trademark infringement.

**Comment by nguyencongbinh** [comment]
@lemiapps 
Thank you for your answer and info provided. I also don't understand why some app still using "WhatsApp" or "WA" in app title without violating trademark policy. 
To not take the risk, I decide to removed the "WA" text in my app title.

**Comment by moodeezz** [comment]
> > بالنسبة لتطبيق Android الخاص بك، يرجى عدم استخدام WhatsApp في اسم التطبيق الخاص بك. يُسمح لك باستخدام WhatsApp في الوصف. وتأكد من وضع WAStickerApps في الوصف الخاص بك. سيساعد هذا في ظهور تطبيقك في بحث Play.
> > أما بالنسبة لنظام التشغيل iOS، فالأمر مختلف، فنحن نعمل مع شركة Apple. اقتراحنا الحالي هو أن تقوم بإنشاء واجهة مستخدم مختلفة تمامًا عن نموذج التطبيق. يمكنك أيضًا تضمين وظائف إضافية. وإلا فلن تسمح Apple بنشر تطبيقك. اسف بشأن ذلك. لكننا نكتشف ذلك. 
> > =======
> > @simonzhexu
> > على Google Play 
> > AutoResponder لـ WhatsApp 
> > https://play.google.com/store/apps/details?id=tkstudio.autoresponderforwa&hl=en 
> > تمت إزالة الرد التلقائي لـ WA

I see that you have restored your application. Can you help me or tell me how to restore it?
