### ISSUE TITLE
[Android] Validation authority error

### ISSUE THREAD

**Issue by bap94** [WhatsApp/stickers#280]
**Specifications**  
OS Level: [6 , 7 , 8.1]
Device Manifacture: [VIVO , SAMSUNG , MOTO]
And more devices..

**Stickers**
My stickers do comply with the sticker requirements (512x512 and < 100 KB): [YES]
My tray icon does comply with the requirements (96x96 and < 50 KB): [YES]
I am using [WebP] images for stickers.

**The problem**  
When try to add in whatsapp I get below error : 

**Validation** : Third party pack cannot be found， **authority**: app.sticker.mystickers.stickercontentprovider,
**identifier**: apack1542691882

**manifest**

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="app.sticker.mystickers">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
        android:appComponentFactory="android.support.v4.app.CoreComponentFactory"
        android:hardwareAccelerated="false"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
       

        <activity android:name="app.sticker.mystickers.Activities.MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <provider
            android:name=".StickerContentProvider"
            android:authorities="${contentProviderAuthority}"
            android:enabled="true"
            android:exported="true"
            android:readPermission="com.whatsapp.sticker.READ" />
    </application>

</manifest>`

My build.gradle file :
[build.txt](https://github.com/WhatsApp/stickers/files/2598368/build.txt)

**Comment by suriya27** [comment]
post your manifest.xml.file

**Comment by bap94** [comment]
@suriya27  Updated

**Comment by suriya27** [comment]
@bap94 change this and try
provider android:name=".StickerContentProvider"

**Comment by bap94** [comment]
@suriya27 But StickerContentProvider is in WhatsApp folder.

**Comment by suriya27** [comment]
is it in another folder?

**Comment by bap94** [comment]
@suriya27 Yes

**Comment by suriya27** [comment]
try placing the package name.contentProviderAuthority in android:authorities

**Comment by bap94** [comment]
@suriya27  like this `android:authorities="${app.sticker.mystickers.contentProviderAuthority}"` ?

**Comment by bap94** [comment]
I replace as `android:authorities="app.sticker.mystickers.stickercontentprovider"` but still same error

**Comment by bap94** [comment]
@simonzhexu any help sir

**Comment by bap94** [comment]
@ oh that's not an problem.. in content provider it can't read any file from folder that's why I'm getting error. By the way thanks u r the only one who's replying me  Thanks a lot. It's take 6 hour to find that issue.😅

**Comment by VineshChauhan24** [comment]
@bap94 i am also getting this error. can you explain why i am getting this error?

**Comment by bap94** [comment]
There is several reasons in my case i tried to fetch stickers from storage and that array is empty that's y I am getting there error.

**Comment by bap94** [comment]
@VineshChauhan24 There is several reasons in my case i tried to fetch stickers from storage and that array is empty that's y I am getting there error

**Comment by PriyankPainter** [comment]
> @VineshChauhan24 There is several reasons in my case i tried to fetch stickers from storage and that array is empty that's y I am getting there error

In my case, Storage contains all the packs containing stickers and contents.json file write dynamically while download stickers pack and then after when i am trying to add stickers by clicking plus button, it will gives error "Third Party pack cannot be found authority : <ContentProviderAuthority of your app>"

but 1st 2 packs are successfully working and from 3rd pack it wil give above mentioned error.

if you have some knowledge about this please contact me on : priyank@jksol.com

**Comment by PriyankPainter** [comment]
Solved...

**Comment by vrsrohit** [comment]
@PriyankPainter  can you please share your code here

**Comment by PriyankPainter** [comment]
Sorry for late reply, I just missed mail.
For your response, I mentioned the answer below my question

If .json file have some issue then it will generate this error.

**Comment by sunil-singh-chaudhary** [comment]
any body have answer or not

**Comment by Prathamv007** [comment]
I too had same error .I solved it by changing the name of the stickers .For ex:-  name_1 is the syntax for the name of sticker. Changing this solved my error.

**Comment by mananjain001** [comment]
Can anyone tell me how to solve this issue 
Didn't got any answer in thread
@PriyankPainter you said you solved issue can you tell me how
