### ISSUE TITLE
[Android]Description in about/info page

### ISSUE THREAD

**Issue by sahqazhar** [WhatsApp/stickers#284]
Have different description for different sticker pack?

**Comment by simonzhexu** [comment]
Change Content.json file, add description and implement the ContentProvider to parse the description, then add those to your UI.

**Comment by Zandor300** [comment]
Please provide more information which part you're struggling with. "Not working out..." isn't very informative.

**Comment by sahqazhar** [comment]
@Zandor300
As said earlier I want to add description in the info section of the sticker pack 
I can't have a constant description
I want different based on the identifier

**Comment by Zandor300** [comment]
Yes, just follow @simonzhexu’s instructions and then tell us where you’re struggling along the process. Just add another key-value entry in the json config inside the stickerpack map. Modify the loading method to also load that new entry. And in the view where you want that description displayed, modify it so that it also does exactly that.

**Comment by sahqazhar** [comment]
I have added description in json file..

"description"= "this is check of description",


Then in contentFileParser.java



And when I use that in my activity..in the Java file it is showing error"cannot resolve symbol 'Description'"

**Comment by Zandor300** [comment]
Thats because json works like this:
“description”: “blabla”,

Use something like http://jsoneditoronline.org to see where the config has syntax errors.

**Comment by sahqazhar** [comment]
My mistake...I wrote it like this in my program
“description”: “this is check of description",

I made a mistake here...
But is my approach correct..

I am extremely sorry for disturbing you..
Thank you so much sir.

**Comment by Zandor300** [comment]
Can you run your entire config through http://jsoneditoronline.org and see if there are anymore syntax errors?

Also, does the variable “Description” actually exist in your file parser?

**Comment by sahqazhar** [comment]
Yes I did include it in the file parser

**Comment by Zandor300** [comment]
And does the variable exist in the stickerpack class?

**Comment by sahqazhar** [comment]
I don't think so..
What should I include... please tell me
Thank you so much

**Comment by sahqazhar** [comment]
I have done everything..
No errors
But when I'm launching the app..
It's telling  WhatsApp sticker app has stopped...

**Comment by sahqazhar** [comment]
@Zandor300
Please help me out with this.

**Comment by Zandor300** [comment]
@sahqazhar First off, you should stop pinging me. I also have a life and I am helping here in my free time.

Second, please submit your project to GitHub because this isn’t working.

**Comment by sahqazhar** [comment]
Ok
