### ISSUE TITLE
[Android] Sticker Pack can't be added to WhatsApp

### ISSUE THREAD

**Issue by Edydaoud** [WhatsApp/stickers#285]
**Specifications**  
OS Level: Android Oreo 8.1.0
Device Manufacturer: BlackBerry

**Stickers**
My stickers do comply with the sticker requirements (512x512 and < 100 KB): YES
My tray icon does comply with the requirements (96x96 and < 50 KB): YES
I am using WebP images for stickers.

**The problem**  
After calling the addStickerPackToWhatsApp() method in AddStickerPackActivity I got a dialog with this message "There's a problem with this sticker pack and can't be added to WhatsApp" with result code 0 and "validation_error" with an error message "Play link: not valid"

@simonzhexu.

**Comment by nandosilvajr** [comment]
I have a same problem.

**Comment by simonzhexu** [comment]
What is your play link?

**Comment by nandosilvajr** [comment]
The app nota add, but doesn't show me a notice. I didnt insert a play link.

**Comment by pranshu1701** [comment]
Can you share your content.json file? Maybe I can help you with that

**Comment by re-LIFE** [comment]
How to add more sticker in json?

**Comment by pranshu1701** [comment]
@re-LIFE you need to change content.json file and create a respective package with webp images. You can refer Readme doc shared in repo

**Comment by re-LIFE** [comment]
@pranshu1701  i mean like this ,
![image](https://user-images.githubusercontent.com/27994247/48888990-f6d48d80-ee66-11e8-948c-7c990d6828c6.png)

**Comment by Edydaoud** [comment]
> What is your play link?

It seems that the problem is the user is using a modified version of WhatsApp which is fixes by using the official version.
Thank you @simonzhexu

**Comment by RojPro** [comment]
hello 
every think is work and folder 1 add to whatsapp but folder 2,3,4,5 is cant add and show me this Message(There's a problem with this sticker pack and it  can't be added to whatsapp)
how ican fix that ??
![screenshot_20181208-150820_whatsapp](https://user-images.githubusercontent.com/37383703/49691809-397ab300-fb53-11e8-9861-56227720eaba.jpg)
![screenshot_20181208-150912_dissticker](https://user-images.githubusercontent.com/37383703/49691810-397ab300-fb53-11e8-86ae-86fd3381eb2f.jpg)

**Comment by pansuriyasumit** [comment]
Replace sticker pack with Old one issue in android. How can I solve it? Any one have faced this issue, help me!

**Comment by Androidsignal** [comment]
im getting this error plzz help me:

exception fetching input stream uri:content://ne.stickers.whatsapp.com.whatsappstickers.WhatsAppLicensedCode.StickerContentProvider/stickers_asset/b7a29678-e7ae-4182-87d0-f1e9fa66e7e6/0, exception message: fd must not be null
