### ISSUE TITLE
pleas can somone add Admob ads to this andorid source code?

### ISSUE THREAD

**Issue by Essayad** [WhatsApp/stickers#286]
```
We ask you:
- Please add [Android] or [iOS] to your issue title to indicate which platform your issue is for.
- For Android, please assign the issue to @simonzhexu. For iOS, please assign the issue to @amrit-1901.
- Remove this notes section after reading before submitting issue.
```

**Specifications**  
OS Level: [FILL IN]
Device Manifacture: [FILL IN]

**Stickers**
My stickers do comply with the sticker requirements (512x512 and < 100 KB): [YES/NO]
My tray icon does comply with the requirements (96x96 and < 50 KB): [YES/NO]
I am using [WebP/PNG] images for stickers.

**The problem**  
[FILL IN WITH DETAILED DESCRIPTION OF THE PROBLEM]

**How anyone may be able to reproduce the problem**  
[FILL IN WITH DETAILED DESCRIPTION]

**Links**  
[FILL IN PLAY STORE / APP STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by pranshu1701** [comment]
I have added Admob in my app for Android. Can you try my app and let me know if you want like that only https://play.google.com/store/apps/details?id=com.tatoo.cannabissticker. Then I can help you with that.

**Comment by Alex193a** [comment]
Admob will not be added to this project, if you want to do it, you can do it in your forked code 😄

**Comment by Essayad** [comment]
@pranshu1701
I've seen your app.
it is working well .
Ads appear in sequence. I have the same application format. But without ads.
Can you give me the source code you used?
Thank you
This is my e-mail contact@fitsshop.com

**Comment by pranshu1701** [comment]
@Essayad First of all thanks for checking out my app. I will share some sample code on this email id by EOD. And will tell you which all places you need to add. Assuming you have Admob account and some knowledge of Admob

**Comment by pingcasa** [comment]
@pranshu1701 can u send me too the source code my e-mail / pirlooo2019@gmail.com

**Comment by Zandor300** [comment]
Implementing ads is not supported here. If any of you want help implementing ads, you a free to ask that on StackOverflow.

**Comment by pranshu1701** [comment]
@pingcasa Please check my app first and let me know if you guys have similar requirement or else there is no point in having discussion. I am also planning to ad native ad apart from banner and interstitial ads (https://play.google.com/store/apps/details?id=com.tatoo.cannabissticker)

**Comment by Jithiin** [comment]
@pranshu1701 can you please share the code with me too? 
My email 
jithinashok174 @ gmail . com

**Comment by bap94** [comment]
@pranshu1701 nice strategy for marketing:joy:

**Comment by sahqazhar** [comment]
@pranshu1701
I too need the code...
Ur app is working quite fine..
Mail me at azharhussain7a@gmail.com
