### ISSUE TITLE
Constraint breaking  in iOS

### ISSUE THREAD

**Issue by DGP13** [WhatsApp/stickers#287]
**Specifications**  
OS Level: iOS 12
Device Manifacture: iPhone XR

**The problem**  
![iPhone XR in not proper showing "Add to whatsapp" button. Check below link in.](https://user-images.githubusercontent.com/42146205/48883941-3fc91980-ee48-11e8-9312-71682c81ee5f.png)

**Comment by Zandor300** [comment]
I don't think this is an issue with the sample app. When I get a clean copy and run it in an iPhone Xr simulator, I don't get this problem:

![image](https://user-images.githubusercontent.com/6069593/48898210-7bfe7900-ee4c-11e8-9514-d4bf2ca6dd4b.png)

(On iPhone Xs Max it's also fine)

I think this is a problem with your own project. Is it on GitHub? Maybe we could look at it.

**Comment by JobMoll** [comment]
I got the same problem. But if you restart Xcode or clean your build it shows up normal again.

**Comment by DGP13** [comment]
Ok thanks, it's work for me.
