### ISSUE TITLE
How create List Pack

### ISSUE THREAD

**Issue by re-LIFE** [WhatsApp/stickers#288]
https://user-images.githubusercontent.com/13077343/48121084-46fefd80-e274-11e8-902b-8316a3290638.jpg
Can samone teach me tho code ? And step?

**Comment by pranshu1701** [comment]
@re-LIFE I think if you go through readme doc it pretty well explained there. If you still face some difficulty I can help you with that. I have created one are you looking for something like this https://play.google.com/store/apps/details?id=com.tatoo.cannabissticker

**Comment by re-LIFE** [comment]
@pranshu1701  im still new android, i was try to add more sticker in json but fail

**Comment by pranshu1701** [comment]
@re-LIFE Share your email id I will send my content.json over there. You can refer that

**Comment by re-LIFE** [comment]
@ pranshu1701 

Akiakane290@gmail.com

Thanks
