### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by MehulBhundiya** [WhatsApp/stickers#294]
Hi ,

How to delete pack from application it self without removing from whatsapp sticker can you please elaborate.

Thanks & Regards

**Comment by Zandor300** [comment]
Do you want to remove a sticker pack from your application without it being removed from your WhatsApp sticker board?

**Comment by MehulBhundiya** [comment]
No i want to remove from whasapp also can you give some idea about that

**Comment by Zandor300** [comment]
You can do that within WhatsApp. When in the sticker board within WhatsApp, hit the `+` button, then go to "Your Stickers" and select your sticker pack. Then hit delete. Done

**Comment by MehulBhundiya** [comment]
i am developing an application in which i want to give one option for remove pack from whatsapp.

when user tap on this option then pack will removed from application and also removes from whatsapp packs

how to do this

**Comment by Zandor300** [comment]
Thats not possible.
