### ISSUE TITLE
Error when testing on phone

### ISSUE THREAD

**Issue by Mixtery** [WhatsApp/stickers#3]
![img_4522](https://user-images.githubusercontent.com/8360478/47594521-fcc87300-d97b-11e8-91d0-788d697d43e1.PNG)

Translation: "There is a problem with this stickerpack and it cannot be added to whatsapp". 

There are no other errors in the debug window... please advice...

**Comment by cioMR** [comment]
How do I put my own stikers in WhatsApp

في سبت، ٢٧ أكتوبر، ٢٠١٨ في ١:٠٦ ص، كتب Mixtery <notifications@github.com>:

**Comment by Mixtery** [comment]
Please open your own thread. Your reply has nothing to do with my issue.

**Comment by cioMR** [comment]
I'm sorry but I'm a beginner

Can you explain to me how to add a special Stickers in whtsapp and thank you
في سبت، ٢٧ أكتوبر، ٢٠١٨ في ١:٢٧ ص، كتب Mixtery <notifications@github.com>:

**Comment by amrit-1901** [comment]
@Mixtery Can you clarify what you mean by "changed everything"?

**Comment by Mixtery** [comment]
Sure. I followed this guide: 


In Xcode, you must also modify the 'sticker_packs.wasticker' file. Replace the values of the metadata with your own. A few notes:

name: the sticker pack's name (128 characters max)
identifier: The identifier should be unique and can be alphanumeric: a-z, A-Z, 0-9, and the following characters are also allowed "_", "-", "." and " ". The identifier should be less than 128 characters.
Replace the image_file value with the file name of your sticker image. It must have both the file name and extension. The ordering of the files in the JSON will dictate the ordering of your stickers in your pack.
ios_app_store_link and android_play_store_link (optional fields): here you can put the URL to your sticker app in the App Store as well as a URL to your sticker app in the Google Play Store (if you have an Android version of your sticker app). If you provide these URLs, users who receive a sticker from your app in WhatsApp can tap on it to view your sticker app in the respective App Stores. To get your App Store link before you publish your app, refer to the instructions here: https://stackoverflow.com/questions/4137426/get-itunes-link-for-app-before-submitting.
emoji (optional): add up to a maximum of three emoji for each sticker file. Select emoji that best describe or represent that sticker file. For example, if the sticker is portraying love, you may choose to add a heart emoji like 💕. If your sticker portrays pizza, you may want to add the pizza slice emoji 🍕. In the future, WhatsApp will support a search function for stickers and tagging your sticker files with emoji will enable that. The sticker picker/tray in WhatsApp today already categorizes stickers into emotion categories (love, happy, sad, and angry) and it does this based on the emoji you tag your stickers with.

**Comment by amrit-1901** [comment]
The README should tell you all you need to know to import stickers (please read all of the paragraphs before "Advanced development" if you use the sample app as is). Also make sure to not change any part of the code outside of the `.wasticker` file: they show you errors if the requirements are not met even before the stickers are imported into WhatsApp.

**Comment by Mixtery** [comment]
i did everything correct.. or so it seems... no errors on the simulator. 
But error when clicking add to whatsapp on a real phone.

**Comment by amrit-1901** [comment]
OK, if this is the case, then it's a WhatsApp issue and needs to reported to WhatsApp support (WhatsApp->Settings->Help->Contact Us). Please report it soon after you are able to reproduce this bug.

**Comment by Psycoguana** [comment]
I had this error and it was because some images were bigger than 100KB.
