### ISSUE TITLE
[Android] Question about STICKER_SIZE_MAX

### ISSUE THREAD

**Issue by xopez** [WhatsApp/stickers#300]
Hello,

I have a quick question. 
Is it possible to make sticker packs bigger than 30 images or is this a limitation of whatsapp itself?
The line to change must be this i guess: https://github.com/WhatsApp/stickers/blob/master/Android/app/src/main/java/com/example/samplestickerapp/StickerPackValidator.java#L33

**Comment by suriya27** [comment]
It is Limitation in Whatsapp itself.
Because In Advanced Development there is no need if StickerPackValidator.java File .
May Be They Will Increase The Limit In Future Updates.
