### ISSUE TITLE
[Android] App stuck at Sending to Whatsapp

### ISSUE THREAD

**Issue by AjayDextrous** [WhatsApp/stickers#301]
**Specifications**  
OS Level: 8.1.0
Device Manifacture: Moto (Lenovo)

**Stickers**
My stickers do comply with the sticker requirements (512x512 and < 100 KB): [YES]
My tray icon does comply with the requirements (96x96 and < 50 KB): [YES]
I am using [WebP/PNG] images for stickers.

**The problem**  
App stuck at "Sending TO Whatsapp" and yes, my whatsapp is at latest version

**How anyone may be able to reproduce the problem**  
I dont know, just added 3 files with photos of my friends for our presonal use, so I cant share those publicly

**Comment by nandosilvajr** [comment]
I have a same problem. My specifications be like yours and the rest exactly equals.

**Comment by nandosilvajr** [comment]
Hi! I solved my problem. It happend because I used for convert to WEBP the GIMP, when I converted the .png file on Android Studio the problem has resolve.

**Comment by AjayDextrous** [comment]
@nandosilvajr Exactly, I figured out that the webp files made by gimp were the problem. Thanks for the Input
cc @shashankchandak
