### ISSUE TITLE
Please i need Help 

### ISSUE THREAD

**Issue by jamali10** [WhatsApp/stickers#302]
Hi I really appreciate the project, its really Awesome.
If you can just Help me to resolve some issues,
How can i add stickers ?
Will i need to have a host?
I appreciate so much your assistance,
i am waiting you answer 
Have a great day

**Comment by viztushar** [comment]
1. You can read the **README** for that.
2. You don't need any type of host.

**Comment by jamali10** [comment]
@viztushar 
I try to read for many times 
But i can't understand how it works 
Please if you can just give me a little Help

**Comment by jamali10** [comment]
@viztushar 
Sorry bro i was trying to open the wrong **README** I will try and let you know 
I appreciate your Help 
Respect Bro

**Comment by rebelholic** [comment]
@jamali10 if you have a paypal I can help you to make a sticker pack.

**Comment by jamali10** [comment]
Bro give me your Email 
I need your Help

**Comment by rebelholic** [comment]
@jamali10 I already replied your email
