### ISSUE TITLE
[Android] Error running app :Default activity not found 

### ISSUE THREAD

**Issue by PrakharAwasthi0** [WhatsApp/stickers#304]
App not launching and giving message over run button "Error running app:Default Activity not Found"

**Here is my manifest file**
`<?xml version="1.0" encoding="utf-8"?>`
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.yeft.whatsappsticker">`

    <application
        android:allowBackup="true"
        android:fullBackupContent="false"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:name="com.yeft.whatsappsticker.StickerApplication"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        tools:ignore="GoogleAppIndexingWarning">

        <activity android:name="com.yeft.whatsappsticker.EntryActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name="com.yeft.whatsappsticker.StickerPackListActivity"
            android:label="@string/title_activity_sticker_packs_list" />
        <activity
            android:name="com.yeft.whatsappsticker.StickerPackDetailsActivity"
            android:parentActivityName="com.yeft.whatsappsticker.StickerPackListActivity"
            tools:ignore="UnusedAttribute">
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value="com.yeft.whatsappsticker.StickerPackListActivity" />
        </activity>
        <activity
            android:name="com.yeft.whatsappsticker.StickerPackInfoActivity"
            android:label="@string/title_activity_sticker_pack_info"
            android:parentActivityName="com.yeft.whatsappsticker.StickerPackDetailsActivity"
            tools:ignore="UnusedAttribute">
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value="com.yeft.whatsappsticker.StickerPackDetailsActivity" />
        </activity>

        <provider
            android:name="com.yeft.whatsappsticker.StickerContentProvider"
            android:authorities="${contentProviderAuthority}"
            android:enabled="true"
            android:exported="true"
            android:readPermission="com.whatsapp.sticker.READ" />
    </application>
</manifest>

**I have changed the application ID in build.gradle and also the package name**

**Comment by suriya27** [comment]
The Error Shows that the BottomFadingRecyclerActivity.java Class not found Check that file is Existing in your app.

**Comment by godixyz** [comment]
**Error inflating class com.example.samplestickerapp.BottomFadingRecyclerView**  The message is clear

**Comment by soyabali44** [comment]
i am not got it this problem, please  exaplain
