### ISSUE TITLE
[Android]Stickers stuck at sending 

### ISSUE THREAD

**Issue by shashankchandak** [WhatsApp/stickers#305]
![screenshot_20181125-233801 2](https://user-images.githubusercontent.com/24842289/48982749-9b2b2e00-f10c-11e8-82d3-76623ab7e541.png)
I have added stickers according to all the specifications mentioned in the readme but when sending stickers in whatsapp for some of the stickers not all , they get stuck as in the image attached above.Have I done something wrong or is this issue from whatsapp itself.

**Comment by aditya-jangid** [comment]
I am also facing the same issue. Can you please look into this. @simonzhexu 
Regards,
Aditya

**Comment by simonzhexu** [comment]
I am not able to help you here because the information provided here is very limited. Please go on to WhatsApp, use Settings -> Help -> Contact Us to send us issues there. The email will contain logs, which we can use to diagnose the issue.
