### ISSUE TITLE
[ANDROID] ERROR WHEN ADDING TO WHATSAPP

### ISSUE THREAD

**Issue by Zerlingg** [WhatsApp/stickers#306]
**Specifications**  
OS Level: Android 7.0
Device Manifacture: Samsung J7 2016

**Stickers**
My stickers do comply with the sticker requirements (512x512 and < 100 KB): YES
My tray icon does comply with the requirements (96x96 and < 50 KB): YES
I am using WebP  images for stickers.

**The problem**  
when you try to add a pack to whatsapp it give this error:
https://cdn.discordapp.com/attachments/468437303023370260/516355342737866772/Screenshot_20181125-215202.png

@simonzhexu

**Comment by Zerlingg** [comment]
the screenshot says:
"theres a problem with this sticker pack and it cant be added to whatsapp"

**Comment by Zerlingg** [comment]
@simonzhexu

**Comment by rebelholic** [comment]
I guess you should reconvert these images to webp format again.

**Comment by Zerlingg** [comment]
> I guess you should reconvert these images to webp format again.

they already are webp

**Comment by Zerlingg** [comment]
i used the debugg app now and it says: play link is invalid

**Comment by Zerlingg** [comment]
i fixed it bjt now i have other error.

**Comment by suriya27** [comment]
what does the debug app says about the error?

**Comment by Zerlingg** [comment]
okay, i fixed the error myself nwn
