### ISSUE TITLE
[Android] app crashes after adding " implementation 'com.google.android.gms:play-services-ads:17.1.1' " to gradle

### ISSUE THREAD

**Issue by JavidAbbas** [WhatsApp/stickers#307]
I want to integrate Admob ads to my app. After adding dependency "implementation 'com.google.android.gms:play-services-ads:17.1.1' " to gradle, app crashes. Could you please help me  for this issue?

@simonzhexu

**Comment by JavidAbbas** [comment]
Solution was found

**Comment by systemRockstar** [comment]
@JavidAbbas what's the solution?
