### ISSUE TITLE
[iOS] How to add ios_app_store_link to programmatically generated sticker pack?

### ISSUE THREAD

**Issue by jordibruin** [WhatsApp/stickers#310]
**Specifications**  
OS Level: iOS 10 +
Device Manifacture: Apple

**Stickers**
My stickers do comply with the sticker requirements (512x512 and < 100 KB): YES
My tray icon does comply with the requirements (96x96 and < 50 KB): YES
I am using PNG images for stickers.

**The problem**  
I'm creating StickerPacks programmatically by using the init :

init(identifier: String, name: String, publisher: String, trayImageFileName: String, publisherWebsite: String?, privacyPolicyWebsite: String?, licenseAgreementWebsite: String?)

How can I add a ios_app_store_link and a android_play_store_link to these sticker packs? In the readme there is only information about modifying the wasticker file,  which I believe is similar to the StickerPack.swift class. However, when I search through the files I've added to the project I can only find references to ios_app_store_link in "Interoperability" and in the fetchStickerPacks function in StickerPaackManager. 

Am I overlooking something?

**How anyone may be able to reproduce the problem**  
Create a StickerPack instance, and try to add ios_app_store_link to it in code.

**Comment by jordibruin** [comment]
@amrit-1901

**Comment by 3rsin3rgul** [comment]
You have to create three different Sticker model and then you can combine together all of them.

**Comment by Zandor300** [comment]
Set the following variable to your App Store URL:
https://github.com/WhatsApp/stickers/blob/4725aab8b7ca66474b6e6ca3301544b319e737ff/iOS/WAStickersThirdParty/Interoperability.swift#L17

When the `Interoperability.send(json: [String: Any])` function will be called, it will be set in the JSON that it sends over to WhatsApp:
https://github.com/WhatsApp/stickers/blob/4725aab8b7ca66474b6e6ca3301544b319e737ff/iOS/WAStickersThirdParty/Interoperability.swift#L34

**Comment by Zandor300** [comment]
It gets sent to WhatsApp Messenger.
