### ISSUE TITLE
[Android] Adding Stickers from Local Storage Final Error...

### ISSUE THREAD

**Issue by mahirozdin** [WhatsApp/stickers#312]
Hi , I'm building app that stickers downloading from server. Everything is fine . I can download. And downloaded pack shown in packs list. But When i try to add pack to the whatsapp there is an error.. 

Error Code:  
`Validation failed:exception fetching input stream uri:content://com.mizanapps.stickers.stickercontentprovider/stickers_asset/59/59_0.webp`

This URI tries to find 59_0.webp file in my local assets but its in local storage.. How can i implement this. 

@simonzhexu

**Comment by viztushar** [comment]
check this [#183](https://github.com/WhatsApp/stickers/issues/183#issuecomment-441017139)

**Comment by mahirozdin** [comment]
Thanks that solved.
