### ISSUE TITLE
Debugger is not stopping at breakpoint in EntryActivity.java

### ISSUE THREAD

**Issue by sama940** [WhatsApp/stickers#314]
@simonzhexu  I want to do some changes in EntryActivity but debugger does not stop at EntryActivity.java breakpoints, breakpoint in StickerContentProvider.java works fine. any idea what could be the issue?
Android studio version 3.2.1, build 9th Oct.

**Comment by simonzhexu** [comment]
rather than "Run app" and attach debugger
You gotta try "Debug app" as EntryActivity is the first activity that gets launched.

**Comment by simonzhexu** [comment]
Close the issue if you have solved it.
