### ISSUE TITLE
[Android] App cant be installed in this phone:

### ISSUE THREAD

**Issue by Zerlingg** [WhatsApp/stickers#315]
**Specifications**  
https://imgur.com/a/df6xvpB

**Stickers**
My stickers do comply with the sticker requirements (512x512 and < 100 KB): YES
My tray icon does comply with the requirements (96x96 and < 50 KB): YES
I am using WebP images for stickers.

**The problem**  
The app cant be installed in that phone.

**Links**  
https://ufile.io/a8y23

**Comment by KuroiNekoWitch** [comment]
With some friends we tried and only works from Android 7 to newest versions

**Comment by TechPakka** [comment]
@KuroiNekoWitch While signing the apk select both v1 and v2 signatures.which gives compatibility way back to jelly bean
