### ISSUE TITLE
[Android] Problem to add sticker in Whatsapp

### ISSUE THREAD

**Issue by xXIschyrosXx** [WhatsApp/stickers#316]
**Sorry my english, i speak spanish**

**Specifications**
OS Level: 8.1.0
Device Manifacture: J7 Neo

**Stickers**
My stickers do comply with the sticker requirements (512x512 and < 100 KB): [YES]
My tray icon does comply with the requirements (96x96 and < 50 KB): [YES]
I am using [WebP] images for stickers.

**The problem**
In my device when i press for add a sticker a message appears that says: "Sticker pack not added. If you´d like add it, make sure you update to the latest version of Whattsapp (Already update)"

**Comment by Zerlingg** [comment]
try the debug version and then it will tell you more about the error, or maybe you are using a modified version of whatsapp

**Comment by TheBotBox** [comment]
show me the code, so that I can help you in resolving the issue.
