### ISSUE TITLE
[Android] How I add support for Android 5/6?

### ISSUE THREAD

**Issue by KuroiNekoWitch** [WhatsApp/stickers#317]
**Specifications**  
OS Level: 5 & 6
Device Manifacture: Huawei, Samsung & LG

**Stickers**
My stickers do comply with the sticker requirements (512x512 and < 100 KB): Yes
My tray icon does comply with the requirements (96x96 and < 50 KB): Yes
I am using WebP images for stickers.

**The problem** 
We tried theAPK in 7 devices (4 Huawei, 2 Samsung & 1 LG), 3 with Android 5, 4 with Android 6... And in all of them appears "this app can't be installed" (but works fine in Android 7 & 8)

How can we add support for 5 & 6?
(sorry, I don't speak english)

**Comment by Zerlingg** [comment]
i wanna know too, @simonzhexu

**Comment by Alex193a** [comment]
It happens because you have selected only v2 signature during the APK generation process. 
Re-generate the APK and select both (v1 and v2) signatures and it will work on Android 4.0.3+ 😉

**Comment by Zerlingg** [comment]
Thx!!! @alex193a
