### ISSUE TITLE
[Android] I need to change play link with Mediashare link. But when i replaced the link in the json file, it encounter an error: There's a problem with this sticker pack and it can't be added to WhatsApp. How to fix it?

### ISSUE THREAD

**Issue by DevAmal** [WhatsApp/stickers#319]
**Specifications**  
OS Level: [NAUGUT]
Device Manifacture: [XIAOMI REDMI NOTE 4]

**Stickers**
My stickers do comply with the sticker requirements (512x512 and < 100 KB): [YES]
My tray icon does comply with the requirements (96x96 and < 50 KB): [YES]
I am using [WebP/PNG] images for stickers.

**The problem**  
 I need to change play link with Mediashare link. But when i replaced the link in the json file, it encounter an error: There's a problem with this sticker pack and it can't be added to WhatsApp. How to fix it?
**How anyone may be able to reproduce the problem**  
Here is the snapshot of json:
![capture](https://user-images.githubusercontent.com/30649789/49083185-e9a60d00-f271-11e8-90e5-c69638a5ba4b.PNG)

**Comment by suriya27** [comment]
You Cannot Add Link Other Than PlayLink In android_play_link Field.
If You Need To Add Mediashare Link You Can Add Somewhere Else In The App Such As "App Download Link" .

**Comment by simonzhexu** [comment]
@suriya27  is correct. Play link is only for play store. We don't allow any other website in there to avoid spam.
