### ISSUE TITLE
Is it still risky to add Whatsapp to the name of the app ? [Android]

### ISSUE THREAD

**Issue by AnasCode** [WhatsApp/stickers#321]
Why a lot of apps are using WhatsApp name and having no problem ? does that means it's fine to use it ?

**Comment by GabrielBB** [comment]
My app was removed yesterday because of Trademark infringement but i see tons of apps with "WhatsApp" as part of their names :(

**Comment by Zandor300** [comment]
Don't use WhatsApp in the name. 

See https://github.com/WhatsApp/stickers/issues/253 and LICENSE:

> * Neither the name WhatsApp nor the names of its contributors may be used to
   endorse or promote products derived from this software without specific
   prior written permission.
>
https://github.com/WhatsApp/stickers/blob/master/LICENSE

**Comment by GabrielBB** [comment]
@Zandor300 How do i get a "specific prior written permission"? Who should i write to?

**Comment by simonzhexu** [comment]
Guys, follow the instruction. Do not use WhatsApp in your app name. Some other apps using it doesn't mean they are legit. As long as you have the WAStickerApps tag, your app would be found. And as long as you have a quality sticker, your downloads will come.
