### ISSUE TITLE
[Android] Same dependency repeated two times

### ISSUE THREAD

**Issue by Vengat121** [WhatsApp/stickers#322]
@simonzhexu I am new to android.  Is necessary to add a dependency again
![sticker_same_dependency_repeated](https://user-images.githubusercontent.com/39154924/49202665-5a147180-f3cb-11e8-9b9f-4a816221ee2d.png)

**Comment by simonzhexu** [comment]
Thanks. This has been fixed in commit: https://github.com/WhatsApp/stickers/commit/4f6224e38c5b0dca53ac6084113d5256c6cec835
