### ISSUE TITLE
[Android] - Whatsapp Sticker Blank When Receive

### ISSUE THREAD

**Issue by savemydinar** [WhatsApp/stickers#323]
@simonzhexu 

**Specifications**  
OS Level: [Android V7]
Device Manifacture: [Samsung]

**Stickers**
My stickers do comply with the sticker requirements (512x512 and < 100 KB): [YES]
My tray icon does comply with the requirements (96x96 and < 50 KB): [YES]
I am using [WebP/PNG] images for stickers.

**The problem**  
Stickers are blank when receive

**How anyone may be able to reproduce the problem**  
 i have successfully generated the apk everything is fine but when send/receive some stickers are showing blank like below image

![image](https://user-images.githubusercontent.com/30769922/49205930-7f03e700-f3c1-11e8-9e61-bc698e238226.png)

This is my JSon file

```
{
  "android_play_store_link": "",
  "ios_app_store_link": "",
  "sticker_packs": [

    {
      "identifier": "test",
      "name": "test",
      "publisher": "",
      "tray_image_file": "53.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",
      "stickers": [
        {
          "image_file": "1.webp",
          "emojis": ["âک•","ًں™‚"]
        },
        {
          "image_file": "2.webp",
          "emojis": ["ًںک„","ًںک€"]
        },
        {
          "image_file": "3.webp",
          "emojis": ["ًںک†","ًںک‚"]
        },
        {
          "image_file": "4.webp",
          "emojis": ["ًںک©","ًںک°"]
        }
      ]
    },

    {
      "identifier": "test2",
      "name": "test2",
      "publisher": "",
      "tray_image_file": "53.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",
      "stickers": [
        {
          "image_file": "1.webp",
          "emojis": ["âک•","ًں™‚"]
        },
        {
          "image_file": "2.webp",
          "emojis": ["ًںک„","ًںک€"]
        },
        {
          "image_file": "3.webp",
          "emojis": ["ًںک†","ًںک‚"]
        },
        {
          "image_file": "4.webp",
          "emojis": ["ًںک©","ًںک°"]
        }
      ]
    },








  ]
}
```
@simonzhexu

**Comment by Zandor300** [comment]
You have a syntax error in your JSON. Below is a fixed version. Please try again with that one.

```
{
  "android_play_store_link": "",
  "ios_app_store_link": "",
  "sticker_packs": [
    {
      "identifier": "test",
      "name": "test",
      "publisher": "",
      "tray_image_file": "53.png",
      "publisher_email": "",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",
      "stickers": [
        {
          "image_file": "1.webp",
          "emojis": [
            "âک•",
            "ًں™‚"
          ]
        },
        {
          "image_file": "2.webp",
          "emojis": [
            "ًںک„",
            "ًںک€"
          ]
        },
        {
          "image_file": "3.webp",
          "emojis": [
            "ًںک†",
            "ًںک‚"
          ]
        },
        {
          "image_file": "4.webp",
          "emojis": [
            "ًںک©",
            "ًںک°"
          ]
        }
      ]
    },
    {
      "identifier": "test2",
      "name": "test2",
      "publisher": "",
      "tray_image_file": "53.png",
      "publisher_email": "",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",
      "stickers": [
        {
          "image_file": "1.webp",
          "emojis": [
            "âک•",
            "ًں™‚"
          ]
        },
        {
          "image_file": "2.webp",
          "emojis": [
            "ًںک„",
            "ًںک€"
          ]
        },
        {
          "image_file": "3.webp",
          "emojis": [
            "ًںک†",
            "ًںک‚"
          ]
        },
        {
          "image_file": "4.webp",
          "emojis": [
            "ًںک©",
            "ًںک°"
          ]
        }
      ]
    }
  ]
}
```

**Comment by eduardoalthaus** [comment]
> @simonzhexu
> 
> **Specifications**
> OS Level: [Android V7]
> Device Manifacture: [Samsung]
> 
> **Stickers**
> My stickers do comply with the sticker requirements (512x512 and < 100 KB): [YES]
> My tray icon does comply with the requirements (96x96 and < 50 KB): [YES]
> I am using [WebP/PNG] images for stickers.
> 
> **The problem**
> Stickers are blank when receive
> 
> **How anyone may be able to reproduce the problem**
> i have successfully generated the apk everything is fine but when send/receive some stickers are showing blank like below image
> 
> ![image](https://user-images.githubusercontent.com/30769922/49205930-7f03e700-f3c1-11e8-9e61-bc698e238226.png)
> 
> This is my JSon file
> 
> ```
> {
>   "android_play_store_link": "",
>   "ios_app_store_link": "",
>   "sticker_packs": [
> 
>     {
>       "identifier": "test",
>       "name": "test",
>       "publisher": "",
>       "tray_image_file": "53.png",
>       "publisher_email":"",
>       "publisher_website": "",
>       "privacy_policy_website": "",
>       "license_agreement_website": "",
>       "stickers": [
>         {
>           "image_file": "1.webp",
>           "emojis": ["âک•","ًں™‚"]
>         },
>         {
>           "image_file": "2.webp",
>           "emojis": ["ًںک„","ًںک€"]
>         },
>         {
>           "image_file": "3.webp",
>           "emojis": ["ًںک†","ًںک‚"]
>         },
>         {
>           "image_file": "4.webp",
>           "emojis": ["ًںک©","ًںک°"]
>         }
>       ]
>     },
> 
>     {
>       "identifier": "test2",
>       "name": "test2",
>       "publisher": "",
>       "tray_image_file": "53.png",
>       "publisher_email":"",
>       "publisher_website": "",
>       "privacy_policy_website": "",
>       "license_agreement_website": "",
>       "stickers": [
>         {
>           "image_file": "1.webp",
>           "emojis": ["âک•","ًں™‚"]
>         },
>         {
>           "image_file": "2.webp",
>           "emojis": ["ًںک„","ًںک€"]
>         },
>         {
>           "image_file": "3.webp",
>           "emojis": ["ًںک†","ًںک‚"]
>         },
>         {
>           "image_file": "4.webp",
>           "emojis": ["ًںک©","ًںک°"]
>         }
>       ]
>     },
> 
> 
> 
> 
> 
> 
> 
> 
>   ]
> }
> ```
> @simonzhexu

Same problem here...
It works?

**Comment by eduardoalthaus** [comment]
When editing the image in webp by photoshop, it gives this problem.
I solved by **converting PNG through Android Studio** itself.
