### ISSUE TITLE
Gpdr Updaate

### ISSUE THREAD

**Issue by mourad-dev** [WhatsApp/stickers#326]
Please anyone can help me to add the GPDR option in this code.. 
I dont have any coding skills

**Comment by Zandor300** [comment]
Please provide more information. Writing a privacy policy doesn't require programming.

**Comment by simonzhexu** [comment]
This seems like a stackoverflow problem. While I really think this is something legitimate, I don't have the capacity to help you. Please ask over there at stackoverflow.com.
