### ISSUE TITLE
Stickers limit (30)

### ISSUE THREAD

**Issue by ptkdev** [WhatsApp/stickers#33]
Can I exceed the limit of 30 stickers? Whatsapp don't support more than 30 stickers/pack? Why exist if-statement <= 30?

**Comment by BoArZa** [comment]
hi

**Comment by joelfischerr** [comment]
yes, WhatsApp will not import sticker packs with more than 30 stickers.

**Comment by nasseralbakr** [comment]
good

**Comment by ptkdev** [comment]
I publish on android, work with whatsapp beta:
[io.ptkdev.wastickers](https://play.google.com/store/apps/details?id=io.ptkdev.wastickers)

**Comment by nasseralbakr** [comment]
Good and continue
