### ISSUE TITLE
How to add sticker pack into whatsapp from local storage, if possible please provide Content provider class[Android]

### ISSUE THREAD

**Issue by nishi312** [WhatsApp/stickers#332]

**Comment by TheBotBox** [comment]
have you found any way to do it !?

**Comment by Zandor300** [comment]
https://github.com/WhatsApp/stickers/issues/204

**Comment by godixyz** [comment]
I think it's answered there https://github.com/WhatsApp/stickers/issues/204#issuecomment-438046873

**Comment by TheBotBox** [comment]
I have resolved it. You you want, I can upload the repo.

**Comment by PriyankPainter** [comment]
can you send me repo link please

can we use PNG images to add on whatsApp or not .webp?
please reply as earlier as possible

**Comment by simonzhexu** [comment]
https://github.com/WhatsApp/stickers/blob/master/Android/README.md#expose-files-that-are-stored-internally-as-stickers-through-contentprovider
