### ISSUE TITLE
Export Sticker Pack using Ionic

### ISSUE THREAD

**Issue by gigiosilva** [WhatsApp/stickers#336]
Is there a way to export the Sticker Packs to WhatsApp using Ionic or any other mobile app SDK based on JS?

When I call "whatsapp://stickerPack" url, the WhatsApp opens and tries to import the pack, but I get an JSON error.

Anyone knows how can I pass the JSON to WhatsApp? 
I have already imported the JSON to the Clipboard but no luck.

**Comment by design365** [comment]
how to import the pack in android?

**Comment by kesepara** [comment]
@gigiosilva did you manage to solve this problem? I am also trying with react native.

**Comment by gigiosilva** [comment]
@kesepara not yet :/

**Comment by kesepara** [comment]
@gigiosilva :( please let me know if you can solve this..

**Comment by rebelholic** [comment]
@kesepara please use android studio for best experinces.

**Comment by senstadi** [comment]
I soo waiting for solition

**Comment by prabhashibuddhima** [comment]
@gigiosilva can you tell how do you solved the issue?
