### ISSUE TITLE
how to remove sticker pack which was added from my app?

### ISSUE THREAD

**Issue by design365** [WhatsApp/stickers#337]
i add some sticker pack to whatsapp,  but when i reinstall my app some times, whatsapp has the old sticker packs, but no stickers in it , so ,i think if some intent action to remove my sticker pack ?

**Comment by EvgeniyNesterchuk** [comment]
I have the same problem. I am creating an app for WhatsApp stickers and I am fetching data from the server. When a user adds a sticker to WhatsApp, it will download the sticker file into the folder. My problem is that when I delete pack folder WhatsApp contains empy category for a random time. Is anybody can help me?

**Comment by simonzhexu** [comment]
there is no intent action to remove sticker pack. The control is on WhatsApp side to remove packs.

**Comment by TenmaMune** [comment]
I'm almost four years late, but I've recently found why Sticker Packs they don't remove from whatsapp properly, once you try to remove it from the contents.json file of our custom sticker app.

Debugging the **StickerContentProvider.java** class, looks like that whatsapp triggers this class for each new Sticker Pack you added from your custom stickers app. That's how whatsapp knows if your sticker pack is still there or not.

But there is an issue, most of the apps are Battery Optimized by default, and this must be disabled in order to delete it safely without any errors. The Sticker App must check at start,  and if is Battery Optimized enabled, let the user disable it like a permission stuff. Otherwhise, whatsapp will not delete the sticker pack correctly, leaving an empty sticker pack that says it had some error. 

To solve this in Native Android, follow this steps :

1. Check if the user has the Battery Optimized enabled for you app by default using the next code.
May it sounds stupid, but watch out with the term "battery optimization ignored" , that means that the battery optimization it's no enabled, so must return true to allow the user to use the app.

```
private boolean isBatteryOptimizationIgnored()
{
    if ( Build.VERSION.SDK_INT >= Build.VERSION_CODES.M )
    {
        String packageName = getPackageName();
        PowerManager powerManager = ( PowerManager ) getSystemService( Context.POWER_SERVICE );
        return powerManager.isIgnoringBatteryOptimizations( packageName );
    }
    else
    {
        return true;
    }
}
```
2. Then launch some alert dialog to warn the user that the app would not work properly without disabling the battery optimization.

3. Launch this intent to let the user disable the optimization battery by him self.

```
Intent intent = new Intent() ;
intent.setAction( Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS ) ;
startActivityForResult( intent , SOME_REQUEST_CODE ) ;
```

4. Finally, check in the onActivityResult if the user disabled the Battery Optimization correctly.

```
@Override
protected void onActivityResult( int requestCode , int resultCode , @Nullable Intent data )
{
    super.onActivityResult( requestCode , resultCode , data ) ;
    if ( requestCode == SOME_REQUEST_CODE )
    {
        if ( isBatteryOptimizationIgnored() )
        {
                // Some method to let the user start using your app.
        }
    }
}
```

Also, I've checked that in the recent whatsapp versions, if you've added, removed or changed any sticker, whatsapp will be noticed only by changing the param "image_data_version"  from each sticker pack in the contents.json that the **StickerContentProvider.java** will read later.


Take in mind that in the following method is where **StickerContentProvider.java** actually checks StickerPack metadata like "image_data_version" param.

```
@NonNull
private Cursor getStickerPackInfo( @NonNull Uri uri , @NonNull List<StickerPack> stickerPackList )
{
    MatrixCursor cursor = new MatrixCursor(
            new String[]{
                    STICKER_PACK_IDENTIFIER_IN_QUERY ,
                    STICKER_PACK_NAME_IN_QUERY ,
                    STICKER_PACK_PUBLISHER_IN_QUERY ,
                    STICKER_PACK_ICON_IN_QUERY ,
                    ANDROID_APP_DOWNLOAD_LINK_IN_QUERY ,
                    IOS_APP_DOWNLOAD_LINK_IN_QUERY ,
                    PUBLISHER_EMAIL ,
                    PUBLISHER_WEBSITE ,
                    PRIVACY_POLICY_WEBSITE ,
                    LICENSE_AGREENMENT_WEBSITE ,
                    IMAGE_DATA_VERSION , // THIS IS THE TARGET PARAM !!!
                    AVOID_CACHE ,
                    ANIMATED_STICKER_PACK ,
            } );

     // THE STICKER PACK LIST THAT CAN BE FETCHED FROM ANOTHER SOURCE
    for ( StickerPack stickerPack : stickerPackList )
    {
        MatrixCursor.RowBuilder builder = cursor.newRow();
        builder.add( stickerPack.identifier );
        builder.add( stickerPack.name );
        builder.add( stickerPack.publisher );
        builder.add( stickerPack.trayImageFile );
        builder.add( stickerPack.androidPlayStoreLink );
        builder.add( stickerPack.iosAppStoreLink );
        builder.add( stickerPack.publisherEmail );
        builder.add( stickerPack.publisherWebsite );
        builder.add( stickerPack.privacyPolicyWebsite );
        builder.add( stickerPack.licenseAgreementWebsite );
        builder.add( stickerPack.imageDataVersion ); // THIS IS THE TARGET PARAM !!!
        builder.add( stickerPack.avoidCache ? 1 : 0 );
        builder.add( stickerPack.animatedStickerPack ? 1 : 0 );
    }
    cursor.setNotificationUri( Objects.requireNonNull( getContext() ).getContentResolver() , uri );
    return cursor;
}
```

In the whatsappStickers Base code, the stickerPackList is fetched from assets folder combined with contents.json file by default, but this list can be provided by your custom sticker app, without using this system too with some changes.

Hope this safes time to some one, because I've barely found any information about this and I felt very frustated.

**Comment by CrackerKSR** [comment]
> I'm almost four years late, but I've recently found why Sticker Packs they don't remove from whatsapp properly, once you try to remove it from the contents.json file of our custom sticker app.
> 
> Debugging the **StickerContentProvider.java** class, looks like that whatsapp triggers this class for each new Sticker Pack you added from your custom stickers app. That's how whatsapp knows if your sticker pack is still there or not.
> 
> But there is an issue, most of the apps are Battery Optimized by default, and this must be disabled in order to delete it safely without any errors. The Sticker App must check at start, and if is Battery Optimized enabled, let the user disable it like a permission stuff. Otherwhise, whatsapp will not delete the sticker pack correctly, leaving an empty sticker pack that says it had some error.
> 
> To solve this in Native Android, follow this steps :
> 
> 1. Check if the user has the Battery Optimized enabled for you app by default using the next code.
>    May it sounds stupid, but watch out with the term "battery optimization ignored" , that means that the battery optimization it's no enabled, so must return true to allow the user to use the app.
> 
> ```
> private boolean isBatteryOptimizationIgnored()
> {
>     if ( Build.VERSION.SDK_INT >= Build.VERSION_CODES.M )
>     {
>         String packageName = getPackageName();
>         PowerManager powerManager = ( PowerManager ) getSystemService( Context.POWER_SERVICE );
>         return powerManager.isIgnoringBatteryOptimizations( packageName );
>     }
>     else
>     {
>         return true;
>     }
> }
> ```
> 
> 2. Then launch some alert dialog to warn the user that the app would not work properly without disabling the battery optimization.
> 3. Launch this intent to let the user disable the optimization battery by him self.
> 
> ```
> Intent intent = new Intent() ;
> intent.setAction( Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS ) ;
> startActivityForResult( intent , SOME_REQUEST_CODE ) ;
> ```
> 
> 4. Finally, check in the onActivityResult if the user disabled the Battery Optimization correctly.
> 
> ```
> @Override
> protected void onActivityResult( int requestCode , int resultCode , @Nullable Intent data )
> {
>     super.onActivityResult( requestCode , resultCode , data ) ;
>     if ( requestCode == SOME_REQUEST_CODE )
>     {
>         if ( isBatteryOptimizationIgnored() )
>         {
>                 // Some method to let the user start using your app.
>         }
>     }
> }
> ```
> 
> Also, I've checked that in the recent whatsapp versions, if you've added, removed or changed any sticker, whatsapp will be noticed only by changing the param "image_data_version" from each sticker pack in the contents.json that the **StickerContentProvider.java** will read later.
> 
> Take in mind that in the following method is where **StickerContentProvider.java** actually checks StickerPack metadata like "image_data_version" param.
> 
> ```
> @NonNull
> private Cursor getStickerPackInfo( @NonNull Uri uri , @NonNull List<StickerPack> stickerPackList )
> {
>     MatrixCursor cursor = new MatrixCursor(
>             new String[]{
>                     STICKER_PACK_IDENTIFIER_IN_QUERY ,
>                     STICKER_PACK_NAME_IN_QUERY ,
>                     STICKER_PACK_PUBLISHER_IN_QUERY ,
>                     STICKER_PACK_ICON_IN_QUERY ,
>                     ANDROID_APP_DOWNLOAD_LINK_IN_QUERY ,
>                     IOS_APP_DOWNLOAD_LINK_IN_QUERY ,
>                     PUBLISHER_EMAIL ,
>                     PUBLISHER_WEBSITE ,
>                     PRIVACY_POLICY_WEBSITE ,
>                     LICENSE_AGREENMENT_WEBSITE ,
>                     IMAGE_DATA_VERSION , // THIS IS THE TARGET PARAM !!!
>                     AVOID_CACHE ,
>                     ANIMATED_STICKER_PACK ,
>             } );
> 
>      // THE STICKER PACK LIST THAT CAN BE FETCHED FROM ANOTHER SOURCE
>     for ( StickerPack stickerPack : stickerPackList )
>     {
>         MatrixCursor.RowBuilder builder = cursor.newRow();
>         builder.add( stickerPack.identifier );
>         builder.add( stickerPack.name );
>         builder.add( stickerPack.publisher );
>         builder.add( stickerPack.trayImageFile );
>         builder.add( stickerPack.androidPlayStoreLink );
>         builder.add( stickerPack.iosAppStoreLink );
>         builder.add( stickerPack.publisherEmail );
>         builder.add( stickerPack.publisherWebsite );
>         builder.add( stickerPack.privacyPolicyWebsite );
>         builder.add( stickerPack.licenseAgreementWebsite );
>         builder.add( stickerPack.imageDataVersion ); // THIS IS THE TARGET PARAM !!!
>         builder.add( stickerPack.avoidCache ? 1 : 0 );
>         builder.add( stickerPack.animatedStickerPack ? 1 : 0 );
>     }
>     cursor.setNotificationUri( Objects.requireNonNull( getContext() ).getContentResolver() , uri );
>     return cursor;
> }
> ```
> 
> In the whatsappStickers Base code, the stickerPackList is fetched from assets folder combined with contents.json file by default, but this list can be provided by your custom sticker app, without using this system too with some changes.
> 
> Hope this safes time to some one, because I've barely found any information about this and I felt very frustated.

Can you suggest how to access image data version. Should I query the whatsapp's content provider or my app's content provider

**Comment by CryptoNeunet** [comment]
> > I'm almost four years late, but I've recently found why Sticker Packs they don't remove from whatsapp properly, once you try to remove it from the contents.json file of our custom sticker app.
> > Debugging the **StickerContentProvider.java** class, looks like that whatsapp triggers this class for each new Sticker Pack you added from your custom stickers app. That's how whatsapp knows if your sticker pack is still there or not.
> > But there is an issue, most of the apps are Battery Optimized by default, and this must be disabled in order to delete it safely without any errors. The Sticker App must check at start, and if is Battery Optimized enabled, let the user disable it like a permission stuff. Otherwhise, whatsapp will not delete the sticker pack correctly, leaving an empty sticker pack that says it had some error.
> > To solve this in Native Android, follow this steps :
> > 
> > 1. Check if the user has the Battery Optimized enabled for you app by default using the next code.
> >    May it sounds stupid, but watch out with the term "battery optimization ignored" , that means that the battery optimization it's no enabled, so must return true to allow the user to use the app.
> > 
> > ```
> > private boolean isBatteryOptimizationIgnored()
> > {
> >     if ( Build.VERSION.SDK_INT >= Build.VERSION_CODES.M )
> >     {
> >         String packageName = getPackageName();
> >         PowerManager powerManager = ( PowerManager ) getSystemService( Context.POWER_SERVICE );
> >         return powerManager.isIgnoringBatteryOptimizations( packageName );
> >     }
> >     else
> >     {
> >         return true;
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Then launch some alert dialog to warn the user that the app would not work properly without disabling the battery optimization.
> > 3. Launch this intent to let the user disable the optimization battery by him self.
> > 
> > ```
> > Intent intent = new Intent() ;
> > intent.setAction( Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS ) ;
> > startActivityForResult( intent , SOME_REQUEST_CODE ) ;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 4. Finally, check in the onActivityResult if the user disabled the Battery Optimization correctly.
> > 
> > ```
> > @Override
> > protected void onActivityResult( int requestCode , int resultCode , @Nullable Intent data )
> > {
> >     super.onActivityResult( requestCode , resultCode , data ) ;
> >     if ( requestCode == SOME_REQUEST_CODE )
> >     {
> >         if ( isBatteryOptimizationIgnored() )
> >         {
> >                 // Some method to let the user start using your app.
> >         }
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, I've checked that in the recent whatsapp versions, if you've added, removed or changed any sticker, whatsapp will be noticed only by changing the param "image_data_version" from each sticker pack in the contents.json that the **StickerContentProvider.java** will read later.
> > Take in mind that in the following method is where **StickerContentProvider.java** actually checks StickerPack metadata like "image_data_version" param.
> > ```
> > @NonNull
> > private Cursor getStickerPackInfo( @NonNull Uri uri , @NonNull List<StickerPack> stickerPackList )
> > {
> >     MatrixCursor cursor = new MatrixCursor(
> >             new String[]{
> >                     STICKER_PACK_IDENTIFIER_IN_QUERY ,
> >                     STICKER_PACK_NAME_IN_QUERY ,
> >                     STICKER_PACK_PUBLISHER_IN_QUERY ,
> >                     STICKER_PACK_ICON_IN_QUERY ,
> >                     ANDROID_APP_DOWNLOAD_LINK_IN_QUERY ,
> >                     IOS_APP_DOWNLOAD_LINK_IN_QUERY ,
> >                     PUBLISHER_EMAIL ,
> >                     PUBLISHER_WEBSITE ,
> >                     PRIVACY_POLICY_WEBSITE ,
> >                     LICENSE_AGREENMENT_WEBSITE ,
> >                     IMAGE_DATA_VERSION , // THIS IS THE TARGET PARAM !!!
> >                     AVOID_CACHE ,
> >                     ANIMATED_STICKER_PACK ,
> >             } );
> > 
> >      // THE STICKER PACK LIST THAT CAN BE FETCHED FROM ANOTHER SOURCE
> >     for ( StickerPack stickerPack : stickerPackList )
> >     {
> >         MatrixCursor.RowBuilder builder = cursor.newRow();
> >         builder.add( stickerPack.identifier );
> >         builder.add( stickerPack.name );
> >         builder.add( stickerPack.publisher );
> >         builder.add( stickerPack.trayImageFile );
> >         builder.add( stickerPack.androidPlayStoreLink );
> >         builder.add( stickerPack.iosAppStoreLink );
> >         builder.add( stickerPack.publisherEmail );
> >         builder.add( stickerPack.publisherWebsite );
> >         builder.add( stickerPack.privacyPolicyWebsite );
> >         builder.add( stickerPack.licenseAgreementWebsite );
> >         builder.add( stickerPack.imageDataVersion ); // THIS IS THE TARGET PARAM !!!
> >         builder.add( stickerPack.avoidCache ? 1 : 0 );
> >         builder.add( stickerPack.animatedStickerPack ? 1 : 0 );
> >     }
> >     cursor.setNotificationUri( Objects.requireNonNull( getContext() ).getContentResolver() , uri );
> >     return cursor;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the whatsappStickers Base code, the stickerPackList is fetched from assets folder combined with contents.json file by default, but this list can be provided by your custom sticker app, without using this system too with some changes.
> > Hope this safes time to some one, because I've barely found any information about this and I felt very frustated.
> 
> Can you suggest how to access image data version. Should I query the whatsapp's content provider or my app's content provider

If you mean to actually read what whatsapp stored in their own app, I guess that we don't have access to query that. Only whatsapp query each of the current packages that you've sent from your app.

But, if you mean to read the data version that you set yourself, I think it depends on how you're loading your stickers.

In case you want to query any data from your dynamically created custom packages, you only just need to load from internal memory, som key value data that represents each sticker pack object, and get the data version attribute.

But, in case your're making an App that your stickers are loaded from assets ( like default sample from Github ) , then you're using your App content provider to read the JSON located in assets  folder, in order to get the data version from each sticker.
That means that even if you query that value, you will have to change it manually, and run the app again.

Hope that answers your question!

**Comment by TenmaMune** [comment]
> > I'm almost four years late, but I've recently found why Sticker Packs they don't remove from whatsapp properly, once you try to remove it from the contents.json file of our custom sticker app.
> > Debugging the **StickerContentProvider.java** class, looks like that whatsapp triggers this class for each new Sticker Pack you added from your custom stickers app. That's how whatsapp knows if your sticker pack is still there or not.
> > But there is an issue, most of the apps are Battery Optimized by default, and this must be disabled in order to delete it safely without any errors. The Sticker App must check at start, and if is Battery Optimized enabled, let the user disable it like a permission stuff. Otherwhise, whatsapp will not delete the sticker pack correctly, leaving an empty sticker pack that says it had some error.
> > To solve this in Native Android, follow this steps :
> > 
> > 1. Check if the user has the Battery Optimized enabled for you app by default using the next code.
> >    May it sounds stupid, but watch out with the term "battery optimization ignored" , that means that the battery optimization it's no enabled, so must return true to allow the user to use the app.
> > 
> > ```
> > private boolean isBatteryOptimizationIgnored()
> > {
> >     if ( Build.VERSION.SDK_INT >= Build.VERSION_CODES.M )
> >     {
> >         String packageName = getPackageName();
> >         PowerManager powerManager = ( PowerManager ) getSystemService( Context.POWER_SERVICE );
> >         return powerManager.isIgnoringBatteryOptimizations( packageName );
> >     }
> >     else
> >     {
> >         return true;
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Then launch some alert dialog to warn the user that the app would not work properly without disabling the battery optimization.
> > 3. Launch this intent to let the user disable the optimization battery by him self.
> > 
> > ```
> > Intent intent = new Intent() ;
> > intent.setAction( Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS ) ;
> > startActivityForResult( intent , SOME_REQUEST_CODE ) ;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 4. Finally, check in the onActivityResult if the user disabled the Battery Optimization correctly.
> > 
> > ```
> > @Override
> > protected void onActivityResult( int requestCode , int resultCode , @Nullable Intent data )
> > {
> >     super.onActivityResult( requestCode , resultCode , data ) ;
> >     if ( requestCode == SOME_REQUEST_CODE )
> >     {
> >         if ( isBatteryOptimizationIgnored() )
> >         {
> >                 // Some method to let the user start using your app.
> >         }
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, I've checked that in the recent whatsapp versions, if you've added, removed or changed any sticker, whatsapp will be noticed only by changing the param "image_data_version" from each sticker pack in the contents.json that the **StickerContentProvider.java** will read later.
> > Take in mind that in the following method is where **StickerContentProvider.java** actually checks StickerPack metadata like "image_data_version" param.
> > ```
> > @NonNull
> > private Cursor getStickerPackInfo( @NonNull Uri uri , @NonNull List<StickerPack> stickerPackList )
> > {
> >     MatrixCursor cursor = new MatrixCursor(
> >             new String[]{
> >                     STICKER_PACK_IDENTIFIER_IN_QUERY ,
> >                     STICKER_PACK_NAME_IN_QUERY ,
> >                     STICKER_PACK_PUBLISHER_IN_QUERY ,
> >                     STICKER_PACK_ICON_IN_QUERY ,
> >                     ANDROID_APP_DOWNLOAD_LINK_IN_QUERY ,
> >                     IOS_APP_DOWNLOAD_LINK_IN_QUERY ,
> >                     PUBLISHER_EMAIL ,
> >                     PUBLISHER_WEBSITE ,
> >                     PRIVACY_POLICY_WEBSITE ,
> >                     LICENSE_AGREENMENT_WEBSITE ,
> >                     IMAGE_DATA_VERSION , // THIS IS THE TARGET PARAM !!!
> >                     AVOID_CACHE ,
> >                     ANIMATED_STICKER_PACK ,
> >             } );
> > 
> >      // THE STICKER PACK LIST THAT CAN BE FETCHED FROM ANOTHER SOURCE
> >     for ( StickerPack stickerPack : stickerPackList )
> >     {
> >         MatrixCursor.RowBuilder builder = cursor.newRow();
> >         builder.add( stickerPack.identifier );
> >         builder.add( stickerPack.name );
> >         builder.add( stickerPack.publisher );
> >         builder.add( stickerPack.trayImageFile );
> >         builder.add( stickerPack.androidPlayStoreLink );
> >         builder.add( stickerPack.iosAppStoreLink );
> >         builder.add( stickerPack.publisherEmail );
> >         builder.add( stickerPack.publisherWebsite );
> >         builder.add( stickerPack.privacyPolicyWebsite );
> >         builder.add( stickerPack.licenseAgreementWebsite );
> >         builder.add( stickerPack.imageDataVersion ); // THIS IS THE TARGET PARAM !!!
> >         builder.add( stickerPack.avoidCache ? 1 : 0 );
> >         builder.add( stickerPack.animatedStickerPack ? 1 : 0 );
> >     }
> >     cursor.setNotificationUri( Objects.requireNonNull( getContext() ).getContentResolver() , uri );
> >     return cursor;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the whatsappStickers Base code, the stickerPackList is fetched from assets folder combined with contents.json file by default, but this list can be provided by your custom sticker app, without using this system too with some changes.
> > Hope this safes time to some one, because I've barely found any information about this and I felt very frustated.
> 
> Can you suggest how to access image data version. Should I query the whatsapp's content provider or my app's content provider

If you mean to actually read what whatsapp stored in their own app, I guess that we don't have access to query that. Only whatsapp query each of the current packages that you've sent from your app.

But, if you mean to read the data version that you set yourself, I think it depends on how you're loading your stickers.

In case you want to query any data from your dynamically created custom packages, you only just need to load from internal memory, som key value data that represents each sticker pack object, and get the data version attribute.

But, in case your're making an App that your stickers are loaded from assets ( like default sample from Github ) , then you're using your App content provider to read the JSON located in assets  folder, in order to get the data version from each sticker.
That means that even if you query that value, you will have to change it manually, and run the app again.

Hope that answers your question!

**Comment by CrackerKSR** [comment]
> > > I'm almost four years late, but I've recently found why Sticker Packs they don't remove from whatsapp properly, once you try to remove it from the contents.json file of our custom sticker app.
> > > Debugging the **StickerContentProvider.java** class, looks like that whatsapp triggers this class for each new Sticker Pack you added from your custom stickers app. That's how whatsapp knows if your sticker pack is still there or not.
> > > But there is an issue, most of the apps are Battery Optimized by default, and this must be disabled in order to delete it safely without any errors. The Sticker App must check at start, and if is Battery Optimized enabled, let the user disable it like a permission stuff. Otherwhise, whatsapp will not delete the sticker pack correctly, leaving an empty sticker pack that says it had some error.
> > > To solve this in Native Android, follow this steps :
> > > 
> > > 1. Check if the user has the Battery Optimized enabled for you app by default using the next code.
> > >    May it sounds stupid, but watch out with the term "battery optimization ignored" , that means that the battery optimization it's no enabled, so must return true to allow the user to use the app.
> > > 
> > > ```
> > > private boolean isBatteryOptimizationIgnored()
> > > {
> > >     if ( Build.VERSION.SDK_INT >= Build.VERSION_CODES.M )
> > >     {
> > >         String packageName = getPackageName();
> > >         PowerManager powerManager = ( PowerManager ) getSystemService( Context.POWER_SERVICE );
> > >         return powerManager.isIgnoringBatteryOptimizations( packageName );
> > >     }
> > >     else
> > >     {
> > >         return true;
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 2. Then launch some alert dialog to warn the user that the app would not work properly without disabling the battery optimization.
> > > 3. Launch this intent to let the user disable the optimization battery by him self.
> > > 
> > > ```
> > > Intent intent = new Intent() ;
> > > intent.setAction( Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS ) ;
> > > startActivityForResult( intent , SOME_REQUEST_CODE ) ;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 4. Finally, check in the onActivityResult if the user disabled the Battery Optimization correctly.
> > > 
> > > ```
> > > @Override
> > > protected void onActivityResult( int requestCode , int resultCode , @Nullable Intent data )
> > > {
> > >     super.onActivityResult( requestCode , resultCode , data ) ;
> > >     if ( requestCode == SOME_REQUEST_CODE )
> > >     {
> > >         if ( isBatteryOptimizationIgnored() )
> > >         {
> > >                 // Some method to let the user start using your app.
> > >         }
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also, I've checked that in the recent whatsapp versions, if you've added, removed or changed any sticker, whatsapp will be noticed only by changing the param "image_data_version" from each sticker pack in the contents.json that the **StickerContentProvider.java** will read later.
> > > Take in mind that in the following method is where **StickerContentProvider.java** actually checks StickerPack metadata like "image_data_version" param.
> > > ```
> > > @NonNull
> > > private Cursor getStickerPackInfo( @NonNull Uri uri , @NonNull List<StickerPack> stickerPackList )
> > > {
> > >     MatrixCursor cursor = new MatrixCursor(
> > >             new String[]{
> > >                     STICKER_PACK_IDENTIFIER_IN_QUERY ,
> > >                     STICKER_PACK_NAME_IN_QUERY ,
> > >                     STICKER_PACK_PUBLISHER_IN_QUERY ,
> > >                     STICKER_PACK_ICON_IN_QUERY ,
> > >                     ANDROID_APP_DOWNLOAD_LINK_IN_QUERY ,
> > >                     IOS_APP_DOWNLOAD_LINK_IN_QUERY ,
> > >                     PUBLISHER_EMAIL ,
> > >                     PUBLISHER_WEBSITE ,
> > >                     PRIVACY_POLICY_WEBSITE ,
> > >                     LICENSE_AGREENMENT_WEBSITE ,
> > >                     IMAGE_DATA_VERSION , // THIS IS THE TARGET PARAM !!!
> > >                     AVOID_CACHE ,
> > >                     ANIMATED_STICKER_PACK ,
> > >             } );
> > > 
> > >      // THE STICKER PACK LIST THAT CAN BE FETCHED FROM ANOTHER SOURCE
> > >     for ( StickerPack stickerPack : stickerPackList )
> > >     {
> > >         MatrixCursor.RowBuilder builder = cursor.newRow();
> > >         builder.add( stickerPack.identifier );
> > >         builder.add( stickerPack.name );
> > >         builder.add( stickerPack.publisher );
> > >         builder.add( stickerPack.trayImageFile );
> > >         builder.add( stickerPack.androidPlayStoreLink );
> > >         builder.add( stickerPack.iosAppStoreLink );
> > >         builder.add( stickerPack.publisherEmail );
> > >         builder.add( stickerPack.publisherWebsite );
> > >         builder.add( stickerPack.privacyPolicyWebsite );
> > >         builder.add( stickerPack.licenseAgreementWebsite );
> > >         builder.add( stickerPack.imageDataVersion ); // THIS IS THE TARGET PARAM !!!
> > >         builder.add( stickerPack.avoidCache ? 1 : 0 );
> > >         builder.add( stickerPack.animatedStickerPack ? 1 : 0 );
> > >     }
> > >     cursor.setNotificationUri( Objects.requireNonNull( getContext() ).getContentResolver() , uri );
> > >     return cursor;
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > In the whatsappStickers Base code, the stickerPackList is fetched from assets folder combined with contents.json file by default, but this list can be provided by your custom sticker app, without using this system too with some changes.
> > > Hope this safes time to some one, because I've barely found any information about this and I felt very frustated.
> > 
> > 
> > Can you suggest how to access image data version. Should I query the whatsapp's content provider or my app's content provider
> 
> If you mean to actually read what whatsapp stored in their own app, I guess that we don't have access to query that. Only whatsapp query each of the current packages that you've sent from your app.
> 
> But, if you mean to read the data version that you set yourself, I think it depends on how you're loading your stickers.
> 
> In case you want to query any data from your dynamically created custom packages, you only just need to load from internal memory, som key value data that represents each sticker pack object, and get the data version attribute.
> 
> But, in case your're making an App that your stickers are loaded from assets ( like default sample from Github ) , then you're using your App content provider to read the JSON located in assets folder, in order to get the data version from each sticker. That means that even if you query that value, you will have to change it manually, and run the app again.
> 
> Hope that answers your question!

Hi, Yeah I can access the Image_data_version as well as other info from both contentProvider and the storage system (a key-value storage system alternate fro Sqlite db called Hawk). 
But increasing the image_data_version does not add new stickers to existing pack.
While without increasing stickers get added.

I listed out data using ContentProvider's cursor and also the stored objects in Hawk storage
ContentProvider holds new uri for new pack with same name if version is increased and those new stickers does not get added in whatsapp.

I also tried to add stickers to list using StickerPack class method 'setStickers()' that simply goes wrong as sticker pack gives error 'There is problem with this pack....' plus whatsapp  does not load those stickers. I think I am doing something wrong here else it would have solve the issue.


I just want to add and remove stickers from stickerpack.

**Comment by vipulbuoyancy** [comment]
Hi Guys,

do you have any update on this? I am facing the same issue.

Thank you.
