### ISSUE TITLE
[iOS] How can I design a new UI? Apple Store keeps rejecting my app

### ISSUE THREAD

**Issue by sanestani** [WhatsApp/stickers#338]
@amrit-1901.

**Stickers**
My stickers do comply with the sticker requirements (512x512 and < 100 KB): [YES]
My tray icon does comply with the requirements (96x96 and < 50 KB): [YES]
I am using [PNG] images for stickers.

**The problem**  
I want to change the UI, adding a splash screen at start, and anything that help me to not get rejected by Apple Store "Spam"
Also, my English is very bad, sorry for that

**Comment by gbougakov** [comment]
See #230
