### ISSUE TITLE
Stickers App must include "DMCA Policy" to avoid suspension

### ISSUE THREAD

**Issue by diepox** [WhatsApp/stickers#339]
Hi guys
Google Play Suspended my 3 Sticker Apps in the same day, they said the reason is "Impesonation", Additionally there an app called "Stickify" it was in Play Store but it is also suspended & removed from the store!
When i had a little reasearch, I relized that i need to add DMCA policy to my App & Website, since i'm using Copyrighted Content which is those stickers in my app, Telegram permission isn't enough too.

So what you think guys? and how i would write that DMCA policy, i'm working as individual, is it fine if you just take a copy from some one and change the informations to mine, like this one: 
https://stickify.app/dmca/

This app too is using DMCA pop-up in first launch and full DMCA Policy in a webview:
- https://play.google.com/store/apps/details?id=com.stickostore.wastickerapps.stickerforwhatsapp

If you have any additional idea/informations, Please help me guys!

Thank you!

**Comment by leonardo748** [comment]
@diepox can share the source code of your APP?

**Comment by Blast06** [comment]
Subscribed, to see what someone would say.

Btw, i ask, is it ok to have ads on this kind of app?

**Comment by Zandor300** [comment]
@Blast06 No one is stopping you but it will not be supported here.

**Comment by MarvinJWendt** [comment]
It seems like all questions are answered. There hasn't been any recent activity here, so I would say the Issue is resolved. If you have any further questions on this Issue don't hesitate to drop a comment and I will reopen the Issue if necessary. 
Have a nice day 😄
