### ISSUE TITLE
[Android] In runtime changing contents.json but not refreshing because of content provider already worked.

### ISSUE THREAD

**Issue by mahirozdin** [WhatsApp/stickers#340]
Hi, I'm changing and adding sticker_packs on runtime to contents.json but when contents.json changed nothing is happened becase contents.json is already readed  at the beginning . I want to reload content provider because when I restart the app new pack is coming. How can I solve this issue without restarting app.

**Comment by suriya27** [comment]
one way is to add sticker pack manually again.
other way is to maintain the sticker pack name ,sticker pack id and sticker name same before and after modification.

**Comment by Zandor300** [comment]
Please try https://github.com/WhatsApp/stickers/issues/204#issuecomment-438046873

**Comment by mahirozdin** [comment]
@suriya27  I cant do it i need to reload content provider. @Zandor300 its not about stroing in extarnal storage.

**Comment by simonzhexu** [comment]
If you want to build sticker pack list dynamically, you don't have to think about Contents.JSON anymore. You can modify the stickerPackList in StickerContentProvider directly.

**Comment by mahirozdin** [comment]
@simonzhexu That's an great idea Thanks.

**Comment by adityaspt** [comment]
@mahirozdin Did you manage to do it ? Im trying the same thing. Would love to get some more insight on this issue.

**Comment by mwolffalonso** [comment]
Hello 

I am trying to update the StickerPackList inside the StickerContentProvider as mentioned by @simonzhexu before.
I am trying to get the StickerContentProvider this way so i can add the new sticker at the end of the list, just before calling the "addNewPack" code.
I am getting and empty list, i was expecting to get all sticker packs i have installed to whatsapp from the app which are in the configfile that was read before this new sticker is added.

```
        ContentResolver resolver = context.getContentResolver();
        ContentProviderClient client = 
        resolver.acquireContentProviderClient("com.mtheorysoft.memes.stickercontentprovider");
        StickerContentProvider provider = (StickerContentProvider) client.getLocalContentProvider();
        List<StickerPack> spl = provider.getStickerPackList();
        for(StickerPack sp: spl){
            System.out.println("Sticker Pack "+sp.name);
        }
```
I have changed to public accesor the getStickerPackList in StickerContentProvider...

I am not getting the dynamics of the example code quite well, appreciate any insight and help.
Thanks
