### ISSUE TITLE
Hey guys I am trying to create a webapp for whatsapp stickers. If someone has some tips how to do this please share.

### ISSUE THREAD

**Issue by sage7978** [WhatsApp/stickers#342]
I am trying to create a web app to add stickers to WhatsApp. By this, I think it will be common for both ios and android at the same time. In the same way, I  think uploading the stickers from time to time will be easy. If someone knows or someone has worked on it before, please share your technique how to do this. I am a beginner. If there are some mistakes in this idea, rectifications are appreciated.

**Comment by mauriciabad** [comment]
You may get some info from here: #278
