### ISSUE TITLE
There's a problem with this sticker pack and it can't be added to whatsapp

### ISSUE THREAD

**Issue by RojPro** [WhatsApp/stickers#344]
hello
every think is work and folder 1 add to whatsapp but folder 2,3,4,5 is cant add and show me this Message(There's a problem with this sticker pack and it can't be added to whatsapp)
how can fix that ??  i using android 8.0.0
![screenshot_20181208-150912_dissticker](https://user-images.githubusercontent.com/37383703/49692061-1fdc6a00-fb59-11e8-8cab-43f7899f28ab.jpg)
![screenshot_20181208-150820_whatsapp](https://user-images.githubusercontent.com/37383703/49692062-27037800-fb59-11e8-9ec7-a8af778629f9.jpg)

**Comment by suriya27** [comment]
check the resoulution of stickers and tray icon.
also check the contents.json.
size of the stickers and tray icon.

**Comment by RojPro** [comment]
that all stickers are 512x512px and the tray icon is 96x96px?
 and they are all below 50 kB to 79kB even though the requirement is under 100 kb and converted icon to webP withe android studio 

> check the resoulution of stickers and tray icon.
> also check the contents.json.
> size of the stickers and tray icon.

**Comment by suriya27** [comment]
tray icon less than 50kb

**Comment by RojPro** [comment]
yes all tray icon 6kB and less

**Comment by suriya27** [comment]
does any one of the sticker pack can be added or all of them saying like cannot be added?

**Comment by RojPro** [comment]
Can I explain more or give me an example

**Comment by suriya27** [comment]
post your contents.json file 
and if possible 2nd sticker pack folder

**Comment by RojPro** [comment]
bro i folder 1 its ok add but folder 2,3,4,5,6 in project can't add

**Comment by suriya27** [comment]
i understand that .
the issue may be in the names of stickers in contents.json of remaining packs and have you checked the count of stickers in each pack?

**Comment by RojPro** [comment]
this my contents.json file
and if possible folder 6 sticker pack 

![layda 0](https://user-images.githubusercontent.com/37383703/49695717-f3037380-fba7-11e8-877c-bf14fe2b6974.png)

**Comment by RojPro** [comment]
how i send to your  contents.json file

**Comment by RojPro** [comment]
{   
  "android_play_store_link": "https://play.google.com/store/apps/details?id=",
  "ios_app_store_link": "",
  "sticker_packs": [
    {
      "identifier": "1",
      "name": "Dis",
      "publisher": "Jaan M",
      "tray_image_file": "dis0.png",
      "publisher_email":"munirna6891@gmail.com",
      "publisher_website": "https://dispackage.blogspot.com",
      "privacy_policy_website": "https://github.com/RojPro",
      "license_agreement_website": "https://github.com/RojPro",
      "stickers": [
        {
          "image_file": "dis1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "dis2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "dis3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "dis4.webp",
          "emojis": ["😩","😰"]
        },
        {
          "image_file": "dis5.webp",
          "emojis": ["😭","💧"]
        },
        {
          "image_file": "dis6.webp",
          "emojis": ["😍","♥"]
        },
        {
          "image_file": "dis7.webp",
          "emojis": ["💔","👎"]
        },
        {
          "image_file": "dis8.webp",
          "emojis": ["😍","💑"]
        },
        {
          "image_file": "dis9.webp",
          "emojis": ["😘","🍪"]
        },
        {
          "image_file": "dis10.webp",
          "emojis": ["🤔","😐"]
        },
        {
          "image_file": "dis11.webp",
          "emojis": ["😱","😵"]
        },
        {
          "image_file": "dis12.webp",
          "emojis": ["🔋","😦"]
        },
        {
          "image_file": "dis13.webp",
          "emojis": ["🔋","😌"]
        },
        {
          "image_file": "dis14.webp",
          "emojis": ["🔋","👋"]
        },
        {
          "image_file": "dis15.webp",
          "emojis": ["🔋","🙋"]
        },
        {
          "image_file": "dis16.webp",
          "emojis": ["🔋","👎"]
        },
        {
          "image_file": "dis17.webp",
          "emojis": ["🔋","✨"]
        },
        {
          "image_file": "dis18.webp",
          "emojis": ["🔋","🌃"]
        },
        {
          "image_file": "dis19.webp",
          "emojis": ["🔋","😨"]
        },
        {
          "image_file": "dis20.webp",
          "emojis": ["🔋","😤"]
        },
        {
          "image_file": "dis21.webp",
          "emojis": ["🔋","😩"]
        },
        {
          "image_file": "dis22.webp",
          "emojis": ["🔋","😜"]
        },
        {
          "image_file": "dis23.webp",
          "emojis": ["🔋","🤔"]
        },
        {
          "image_file": "dis24.webp",
          "emojis": ["🔋","😠"]
        },
        {
          "image_file": "dis25.webp",
          "emojis": ["🔋","😵"]
        },
        {
          "image_file": "dis26.webp",
          "emojis": ["🔋","😐"]
        },
        {
          "image_file": "dis27.webp",
          "emojis": ["🔋","🍪"]
        },
        {
          "image_file": "dis28.webp",
          "emojis": ["🔋","💑"]
        },
        {
          "image_file": "dis29.webp",
          "emojis": ["🔋","👎"]
        },
        {
          "image_file": "dis30.webp",
          "emojis": ["🔋","♥"]
        }
      ]
    },{
      "identifier": "2",
      "name": "PBoy",
      "publisher": "Jaan M",
      "tray_image_file": "hoboy (0).png",
      "publisher_email":"munirna6891@gmail.com",
      "publisher_website": "https://dispackage.blogspot.com",
      "privacy_policy_website": "https://github.com/RojPro",
      "license_agreement_website": "https://github.com/RojPro",
      "stickers": [
        {
          "image_file": "hoboy (1).webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "hoboy (2).webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "hoboy (3).webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "hoboy (4).webp",
          "emojis": ["😩","😰"]
        },
        {
          "image_file": "hoboy (5).webp",
          "emojis": ["😭","💧"]
        },
        {
          "image_file": "hoboy (6).webp",
          "emojis": ["😍","♥"]
        },
        {
          "image_file": "hoboy (7).webp",
          "emojis": ["💔","👎"]
        },
        {
          "image_file": "hoboy (8).webp",
          "emojis": ["😍","💑"]
        },
        {
          "image_file": "hoboy (9).webp",
          "emojis": ["😘","🍪"]
        },
        {
          "image_file": "hoboy (10).webp",
          "emojis": ["🤔","😐"]
        },
        {
          "image_file": "hoboy (11).webp",
          "emojis": ["😱","😵"]
        },
        {
          "image_file": "hoboy (12).webp",
          "emojis": ["🔋","😦"]
        },
        {
          "image_file": "hoboy (13).webp",
          "emojis": ["🔋","😌"]
        },
        {
          "image_file": "hoboy (14).webp",
          "emojis": ["🔋","👋"]
        },
        {
          "image_file": "hoboy (15).webp",
          "emojis": ["🔋","🙋"]
        },
        {
          "image_file": "pepe1.webp",
          "emojis": ["🔋","🙋"]
        },
        {
          "image_file": "pepe2.webp",
          "emojis": ["🔋","🙋"]
        },
        {
          "image_file": "pepe3.webp",
          "emojis": ["🔋","🙋"]
        }
      ]
    },{
      "identifier": "3",
      "name": "HotGirl ",
      "publisher": "Jaan M",
      "tray_image_file": "backEnd (0).png",
      "publisher_email":"munirna6891@gmail.com",
      "publisher_website": "https://dispackage.blogspot.com",
      "privacy_policy_website": "https://github.com/RojPro",
      "license_agreement_website": "https://github.com/RojPro",
      "stickers": [
        {
          "image_file": "backEnd (1).webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "backEnd (2).webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "backEnd (3).webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "backEnd (4).webp",
          "emojis": ["😩","😰"]
        },
        {
          "image_file": "backEnd (5).webp",
          "emojis": ["😭","💧"]
        },
        {
          "image_file": "backEnd (6).webp",
          "emojis": ["😍","♥"]
        },
        {
          "image_file": "backEnd (7).webp",
          "emojis": ["💔","👎"]
        },
        {
          "image_file": "backEnd (8).webp",
          "emojis": ["😍","💑"]
        },
        {
          "image_file": "backEnd (9).webp",
          "emojis": ["😘","🍪"]
        },
        {
          "image_file": "backEnd (10).webp",
          "emojis": ["🤔","😐"]
        },
        {
          "image_file": "backEnd (11).webp",
          "emojis": ["😱","😵"]
        },
        {
          "image_file": "backEnd (12).webp",
          "emojis": ["🔋","😦"]
        },
        {
          "image_file": "backEnd (13).webp",
          "emojis": ["🔋","😌"]
        },
        {
          "image_file": "backEnd (14).webp",
          "emojis": ["🔋","👋"]
        }
      ]
    },{
      "identifier": "4",
      "name": "Christmas",
      "publisher": "Jaan M",
      "tray_image_file": "cristmas (1).png",
      "publisher_email":"munirna6891@gmail.com",
      "publisher_website": "https://dispackage.blogspot.com",
      "privacy_policy_website": "https://github.com/RojPro",
      "license_agreement_website": "https://github.com/RojPro",
      "stickers": [
        {
          "image_file": "cristmas1 (1).webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "cristmas1 (3).webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "cristmas1 (6).webp",
          "emojis": ["😍","♥"]
        },
        {
          "image_file": "cristmas1 (7).webp",
          "emojis": ["💔","👎"]
        },
        {
          "image_file": "cristmas1 (8).webp",
          "emojis": ["😍","💑"]
        },
        {
          "image_file": "cristmas1 (9).webp",
          "emojis": ["😘","🍪"]
        },
        {
          "image_file": "cristmas1 (10).webp",
          "emojis": ["🤔","😐"]
        }
      ]
    },{
      "identifier": "5",
      "name": "HotLips",
      "publisher": "Jaan M",
      "tray_image_file": "lipsHo (1).png",
      "publisher_email":"munirna6891@gmail.com",
      "publisher_website": "https://dispackage.blogspot.com",
      "privacy_policy_website": "https://github.com/RojPro",
      "license_agreement_website": "https://github.com/RojPro",
      "stickers": [
        {
          "image_file": "lipsHo (2).webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "lipsHo (3).webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "lipsHo (4).webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "lipsHo (5).webp",
          "emojis": ["😩","😰"]
        },
        {
          "image_file": "lipsHo (6).webp",
          "emojis": ["😭","💧"]
        },
        {
          "image_file": "lipsHo (7).webp",
          "emojis": ["😍","♥"]
        },
        {
          "image_file": "lipsHo (8).webp",
          "emojis": ["💔","👎"]
        },
        {
          "image_file": "lipsHo (9).webp",
          "emojis": ["😍","💑"]
        },
        {
          "image_file": "lipsHo (10).webp",
          "emojis": ["😘","🍪"]
        }
      ]
    },{
      "identifier": "6",
      "name": "XLLady",
      "publisher": "Jaan M",
      "tray_image_file": "layda (0).png",
      "publisher_email":"munirna6891@gmail.com",
      "publisher_website": "https://dispackage.blogspot.com",
      "privacy_policy_website": "https://github.com/RojPro",
      "license_agreement_website": "https://github.com/RojPro",
      "stickers": [
        {
          "image_file": "layda (1).webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "layda (2).webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "layda (3).webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "layda (4).webp",
          "emojis": ["😩","😰"]
        },
        {
          "image_file": "layda (5).webp",
          "emojis": ["😭","💧"]
        },
        {
          "image_file": "layda (6).webp",
          "emojis": ["😍","♥"]
        }
      ]
    }

  ]
}

**Comment by suriya27** [comment]
@RojPro send it as attachment
the image you send is the tray icon right?

**Comment by RojPro** [comment]
this is for folder 5 and 6
[5.zip](https://github.com/WhatsApp/stickers/files/2660402/5.zip)
[6.zip](https://github.com/WhatsApp/stickers/files/2660403/6.zip)

**Comment by suriya27** [comment]
remove the spaces in the names of stickers and tray icon name.
this is the issue.
use like this hoboy_0.png or hoboy(0).png and dont use spacesin names.

**Comment by RojPro** [comment]
Try and tell you the result

**Comment by suriya27** [comment]
ok
