### ISSUE TITLE
[Android]how to send sticker pack zip to whatsapp from android app?

### ISSUE THREAD

**Issue by design365** [WhatsApp/stickers#345]
@simonzhexu
i make a sticker pack android app, i want to share the sticker pack zip to whatsapp's friends,
can i do this in my android app?

**Comment by simonzhexu** [comment]
It is not supported natively. We would not be able to help you with that.

**Comment by design365** [comment]
@simonzhexu thanks for your reply, i find some app can do this, share the sticker pack to friends
