### ISSUE TITLE
Android Stickers not added to whatsapp

### ISSUE THREAD

**Issue by SumiGhosh** [WhatsApp/stickers#348]
Am trying custom stickers app, when i add the sticker pack to whatsapp i am getting below dialog and error message on activity result.

![whatsapp image 2018-12-10 at 10 54 23 pm](https://user-images.githubusercontent.com/1071036/49749720-fe04f380-fcce-11e8-862c-f033f3ad10f4.jpeg)

Below is the onActivityResult message;
Validation failed:sticker file name: /data/user/0/MyPackageName/files/1544459914371/img15444599143711.webp is invalid, authority: MyPackageNameWithAuthority,identifier: 1544459914371

I have verified size and length of each file, all seems ok. 

44 Kb 
img15444599143711.webp 
16 Kb 
img1544459914371trayicon.png
33 Kb 
img15444599143712.webp
18 Kb
img15444599143713.webp

@simonzhexu

**Comment by Zandor300** [comment]
Does it properly import the images from files using your ContentProvider?

**Comment by StoreHD18** [comment]
I have the same error, my contents.json:


{
  "android_play_store_link": "",
  "ios_app_store_link": "",
  "sticker_packs": [


    {
      "identifier": "1",
      "name": "Project Name 1",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "2",
      "name": "Project Name 2",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "3",
      "name": "Project Name 3",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "4",
      "name": "Project Name 4",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "5",
      "name": "Project Name 5",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "6",
      "name": "Project Name 6",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "7",
      "name": "Project Name 7",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "8",
      "name": "Project Name 8",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "9",
      "name": "Project Name 9",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "10",
      "name": "Project Name 10",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "11",
      "name": "Project Name 11",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    }

  ]
}

{
  "android_play_store_link": "",
  "ios_app_store_link": "",
  "sticker_packs": [


    {
      "identifier": "1",
      "name": "Project Name 1",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "2",
      "name": "Project Name 2",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "3",
      "name": "Project Name 3",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "4",
      "name": "Project Name 4",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "5",
      "name": "Project Name 5",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "6",
      "name": "Project Name 6",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "7",
      "name": "Project Name 7",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "8",
      "name": "Project Name 8",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "9",
      "name": "Project Name 9",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "10",
      "name": "Project Name 10",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "11",
      "name": "Project Name 11",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    }

  ]
}
{
  "android_play_store_link": "",
  "ios_app_store_link": "",
  "sticker_packs": [


    {
      "identifier": "1",
      "name": "Project Name 1",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "2",
      "name": "Project Name 2",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "3",
      "name": "Project Name 3",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "4",
      "name": "Project Name 4",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "5",
      "name": "Project Name 5",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "6",
      "name": "Project Name 6",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "7",
      "name": "Project Name 7",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "8",
      "name": "Project Name 8",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "9",
      "name": "Project Name 9",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "10",
      "name": "Project Name 10",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    },

    {
      "identifier": "11",
      "name": "Project Name 11",
      "publisher": "Publisher Name",
      "tray_image_file": "pic.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",

      "stickers": [
        {
          "image_file": "pic1.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "pic2.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "pic3.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "pic4.webp",
          "emojis": ["😩","😰"]
        }
      ]
    }

  ]
}

**Comment by StoreHD18** [comment]
I can not add project 11, this project I took and copied and pasted and it worked, but when I went to put my own figures it is not possible to add to whatsapp

**Comment by suriya27** [comment]
@StoreHD18 currently 10 sticker packs are allowed for one app i think this is the issue.

**Comment by StoreHD18** [comment]
> @ StoreHD18 atualmente 10 pacotes de adesivos são permitidos para um aplicativo eu acho que este é o problema.

I think the problem is different, because I removed all packages from 1 to 10 and made a new package with 5 figures, and even then gave that error above. What do I do? The images are already in correct format and correct sizes, what is wrong?

**Comment by suriya27** [comment]
@StoreHD18 remove spaces in names and try it may be an issue

**Comment by simonzhexu** [comment]
Are you trying to send us a file in your internal storage? The sticker file name you passed to WhatsApp is "/data/user/0/MyPackageName/files/1544459914371/img15444599143711.webp", given your contents.json file, it should be something like "pic1.webp"

**Comment by samyakjain** [comment]
@simonzhexu How to fix this? I am downloading files and storing it on internalStorage and then want to expose it to whatsapp? It says Invalid file name because my filename is of similar to pattern "data/user/0/MyPackageName/files/1544459914371/img15444599143711.webp"

**Comment by StoreHD18** [comment]
I discovered the problem, is that the package icon was being bigger than it should, the pro icone size of the package is 96x96
