### ISSUE TITLE
SoLoader.init() not yet called  error in StickerPackValidation.java

### ISSUE THREAD

**Issue by prasanthvel** [WhatsApp/stickers#351]
@simonzhexu 
I have tried running the exact code for Android, but I got an error in 
`StickerPackValidation.java` at line `final WebPImage webPImage = WebPImage.create(bytes);`
Error message : SoLoader.init() not yet called.

Is there any fix?
Android Studio 3.2.1
Android 7.0

**Comment by simonzhexu** [comment]
did you have the latest code?

**Comment by prasanthvel** [comment]
Yes, I have downloaded the master code

**Comment by salmankhalid876** [comment]
How did you solved it?

**Comment by salmankhalid876** [comment]
I solved this issue by writing android:name=".StickerApplication" in manifest file in application attribute.

**Comment by a2zZuhaib** [comment]
Initialize the Fresco in Application or main Base Activity or before going to do work on stickers.

    @Override
    public void onCreate() {
        super.onCreate();
        Fresco.initialize(this);
    }
