### ISSUE TITLE
[iOS] reducing the file size of your stickers 

### ISSUE THREAD

**Issue by devorblackbeard** [WhatsApp/stickers#353]
Hi how can I reduce the file size of the sticker with transparent background programmatically in swift

I have a transparent background PNG image which is picked from photos, how can I convert to a size less than 100KB without losing a transparent background and maintain 512 X 512 pixels.

**Comment by Yarregr** [comment]
use https://nukesaq88.github.io/Pngyu/

**Comment by devorblackbeard** [comment]
Is there any way to do this programmatically in iPhone itself, as I'm picking from phone gallery, and create a sticker

**Comment by amrit-1901** [comment]
This is more of a generic iOS SDK question, so this is not the right place to ask.
