### ISSUE TITLE
[Android] How to load the pack from internet?

### ISSUE THREAD

**Issue by mbouix** [WhatsApp/stickers#354]
I'm trying to get the stickers from the internet to make the app lighter. 
e.g get the JSON from a link .. www.google.com/content.json and the images too.

Can someone help me? I'm trying for a couple days :/

**Comment by simonzhexu** [comment]
You probably can do some async operation in EntryActivity to load the url to get the contents.json, then have the json point images to other images, then download those images to internal storage, see README for how to serve images from internal storage to ContentProvider

**Comment by sahqazhar** [comment]
I too have the same doubt 
how to load the entire sticker pack from the internet?

**Comment by Rezakarimi66** [comment]
A sample code would be nice

**Comment by Zandor300** [comment]
See https://github.com/WhatsApp/stickers/pull/311

**Comment by sahqazhar** [comment]
I think that is for iOS.
I need that thing in Android

**Comment by some28** [comment]
https://github.com/viztushar/stickers-internet
