### ISSUE TITLE
Sticker Void

### ISSUE THREAD

**Issue by kinorth** [WhatsApp/stickers#358]
Several stickers are going like this:  https://i.imgur.com/EOByRKF.jpg

They are in 512x512, weighing less than 50kb.
How to solve?

@simonzhexu

**Comment by MarvinJWendt** [comment]
Hey @kinorth,
You didn't gave us a lot of information, but I am trying my best.
The issue could be that:
- As simple as it seems, it looks like you didn't download the sticker in WhatsApp, maybe a bad internet connection?
- Your stickers aren't in a correct WebP format?

Please tell me if this is the case.
If you still have this issue, feel free to ask me here :)

**Comment by waleedammari** [comment]
Hello, I have the same issue on iOS, when I check the package on my app you can see all the stickers without any problem, but when you press "add to Whatsapp" some of them are missing on Whatsapp. Even though I collected these webp from whatsapp (stickers were used before). I made sure they are 512x512 and less than 100kb

**Comment by waleedammari** [comment]
Hmmm so I tried to make them as PNG files, it worked! but the problem is that PNGs takes more space, I tried to upload the webp files that didn't work but the .webp extension isn't allowed here.

**Comment by MarvinJWendt** [comment]
Hey,
This Issue seems to be inactive. To keep things organized I will close this for now. If this Issue is still relevant, don't hesitate to drop a comment and I will reopen it if necessary.

Sincerely,
Marvin Wendt
