### ISSUE TITLE
[Android] Please App Bundle Support For More Reduce Size

### ISSUE THREAD

**Issue by rebelholic** [WhatsApp/stickers#360]
Dear  @simonzhexu 

Please read [this article](https://medium.com/google-developer-experts/exploring-the-android-app-bundle-ca16846fa3d7), could  you add dynamic delivery support for every sticker pack and it will help us to reduce more size per package before upload to play store?

**Comment by rebelholic** [comment]
ok I will consider it

**Comment by simonzhexu** [comment]
closing this for now, when you do get to it, please send a pull request.
