### ISSUE TITLE
[Inquiry][Android] Searching stickers in WhatsApp @simonzhexu

### ISSUE THREAD

**Issue by some28** [WhatsApp/stickers#361]
Hi
I have noticed that WhatsApp has introduced search feature for stickers. (Though it's buggy, only displays for the first time after we remove app from background )
![screen shot 2018-12-21 at 13 26 43](https://user-images.githubusercontent.com/45552691/50325054-e971f800-0525-11e9-8de6-ebb4ea36cca7.png)
Can we input some keywords (ex: thrones, disney.. etc) instead of emoji's in "emoji's array" and search with those keywords in WhatsApp sticker search?
Could you let us know how "search for stickers" filters the stickers? 
Thank you!

**Comment by Alex193a** [comment]
It is not allowed to talk about features not yet officially released

**Comment by simonzhexu** [comment]
> It is not allowed to talk about features not yet officially released

that!

**Comment by some28** [comment]
Actually it's already released in Stable version but may be not intentional ?
I could search with strings like sad, happy, hungry and with emoji's

**Comment by Alex193a** [comment]
It's not intentional, the search button becomes visible in some circumstances due to a bug.

**Comment by some28** [comment]
Thank you! Closing the ticket.
