### ISSUE TITLE
[Android] Sticker pack disappearing inside WhatsApp after closing Sticker Pack

### ISSUE THREAD

**Issue by carstenhag** [WhatsApp/stickers#363]
**Specifications**  
OS Level: 7.0
Device Manufacturer: Huawei - P9 lite

**Stickers**
My stickers do comply with the sticker requirements (512x512 and < 100 KB): Yes
My tray icon does comply with the requirements (96x96 and < 50 KB): Yes
I am using WebP images for stickers.

**The problem & Repro steps**  
1. Add sticker pack to WhatsApp.
2. See sticker pack in WhatsApp, send them, everything's fine. Close the chat, reopen chat, sticker pack ist still there. [Screenshot](https://i.imgur.com/zXF8QVj.jpg)

3. Close Sticker Pack App.
4. The sticker pack isn't visible anymore in WhatsApp, see this screenshot:

![Screenshot 2](https://i.imgur.com/nKkRvlB.jpg)

**Head of commit**
fb5c7c79801a015d4e48e5dd2d26b30bc171bf66

Might try to update to master later, but I don't think this is the issue.

**Links**  
https://play.google.com/store/apps/details?id=de.chagemann.thinkingstickers
https://gitlab.com/carstenhag/thinking-stickers

**Comment by carstenhag** [comment]
Possibly related to #221 or #205.

This isn't a OnePlus device though, it's an Huawei.

**Comment by carstenhag** [comment]
Fixed this issue (thanks to #167) by disabling 2 battery optimizations targeted at my sticker app:
* Ignore battery optimizations
* Removed it from the list of "Apps to clean/remove when locking the phone

With just the first one it still kept disappearing.

**Comment by simonzhexu** [comment]
We are going to add some dialog suggesting users to disable battery optimizations when this case appear.
