### ISSUE TITLE
[Android] Doubt on the local storage stickers

### ISSUE THREAD

**Issue by Adarshkl** [WhatsApp/stickers#365]
@simonzhexu.
Is it possible to create a sticker pack out of the received stickers in WhatsApp? Let's say the recently received 10 stickers in the pack.
I am trying to build an app around this use case.
I am aware of the documentation available at (https://github.com/WhatsApp/stickers/blob/master/Android/README.md#expose-files-that-are-stored-internally-as-stickers-through-contentprovider)
But I am not sure how exactly should I modify the code to fit this. Is it possible to completely bypass the CONTENTS.json since my sticker list is going to be dynamic? How can I modify the content provider to read the stickers from the whatsapp stickers folder?
Any help from the assignee or the community would be of great help. Thank a lot in advance.

**Comment by en-Vishal** [comment]
yes! it possible to create sticker pack out of the received stickers in WhatsApp.

**Comment by CrackerKSR** [comment]
Did you get the solution?
