### ISSUE TITLE
sticker packs

### ISSUE THREAD

**Issue by Vivek2kumar1** [WhatsApp/stickers#366]
Where can I download copyright free sticker packs for the app or do I have to buy them?

**Comment by MarvinJWendt** [comment]
Hey @Vivek2kumar1,
It's your choice what stickers you want to publish, they just have to comply with the ToS of WhatsApp.
You can make them yourself in Illustrator/Photoshop or any other program. Stickers are mostly intended to be self-made. If you want to use others work make sure you have the permission from the original creator to do so. And obviously these images also have to comply with the ToS of WhatsApp.

If you want commercially usable images I would recommend you looking for "stock photos".
These can be free or paid, depends on the provider.

Stock image providers for example:

- https://www.shutterstock.com/
- https://www.istockphoto.com
- https://pixabay.com/
- https://www.pexels.com/
- https://unsplash.com/

I don't think there is a place for actual **free stickers**.
I hope this could help you :)

**Comment by MarvinJWendt** [comment]
It seems like all questions are answered. There hasn't been any recent activity here, so I would say the Issue is resolved. If you have any further questions on this Issue don't hesitate to drop a comment and I will reopen the Issue if necessary. 
Have a nice day 😄
