### ISSUE TITLE
how can i use webp image from document folder in ios ?

### ISSUE THREAD

**Issue by beladiya** [WhatsApp/stickers#368]

**Comment by simonzhexu** [comment]
question not clear.

**Comment by beladiya** [comment]
i mean i download one folder from server.It is save on document.Inside that so many .webp images.Now on code side, if i want to share webp image on whastup then how i can i use this folder images.
Now i get crash on fileNotFound . How can i use this images and share it on whatsUp

**Comment by beladiya** [comment]
i mean i download one folder from server.It is save on document.Inside that so many .webp images.Now on code side, if i want to share webp image on whastup then how i can i use this folder images.
Now i get crash on fileNotFound . How can i use this images and share it on whatsUp
