### ISSUE TITLE
[Android][Inquiry] Google play account termination reminder

### ISSUE THREAD

**Issue by some28** [WhatsApp/stickers#374]
Hi
I got an email as below.
![email](https://user-images.githubusercontent.com/45552691/50561741-00e48880-0d51-11e9-93b7-7ac4767c36dd.png)
This mail was to sent to my public email listed in play store but not to the email associated with play store account.
Could someone please let me know whether it is fake or real? Thank you!

**Comment by MarvinJWendt** [comment]
I can confirm that this is not an official email by Google. Google would not use `..@gmail.com` emails. Please report the sender to Google directly.
Google would not ask you to unpublish your app. They would suspend it. After 3 suspensions they would terminate your Google account eventually.
And they normally speak to you with your full name.

**Comment by some28** [comment]
Thanks for your comments @DanielK1511 and @MarvinJWendt 
Let me close the issue.
