### ISSUE TITLE
[Android] Sticker categories disappear from WhatsApp occasionally

### ISSUE THREAD

**Issue by tetyanab** [WhatsApp/stickers#378]
**Specifications**  
OS Version: 8.0, 6.0
Device Manufacturer: HUAWEI Y9 2018 (HWFLA-H), MEIZU_M5, Meizu U10

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.

**Problem Description**  
Some of my users complain that sticker categories that they add into WhatsApp sometimes disappear. So they have to open my app again to re-add them. This happens to a small percentage of users only based on users' comments. 

**Reproduction Steps**  
So far I couldn't reproduce this on my devices with more than 20 sticker categories imported into WhatsApp. Raising it here in case other reports surface with the same issue.

**Comment by MarvinJWendt** [comment]
Hey @tetyanab,
**I am not sure but for anyone who wants to investigate into this:**

Android optimizes apps in the background for better battery usage. If the app, which is providing the stickers, gets optimized (closed), WhatsApp can't get the stickers.

This could be a solution to the problem (client side): https://github.com/WhatsApp/stickers/issues/167#issuecomment-437684615 

*I cannot verify that this is the actual problem, but it seems to have been in the past.*

**Comment by tetyanab** [comment]
Thanks @MarvinJWendt , I will recommend the linked fix to users.
