### ISSUE TITLE
[Android] Adding Sticker Pack on Runtime to Sticker Pack List

### ISSUE THREAD

**Issue by mahirozdin** [WhatsApp/stickers#382]
Question is simple , I'm creating sticker packs on runtime and want to add this pack to list on runtime. I'm adding it to contents.json but contents.json only triggers on launch. How to add sticker pack to available list on runtime.

Thanks, Best Regards.

**Comment by MarvinJWendt** [comment]
Hey @mahirozdin,
If you want to create a custom stickers app this should help you: [Advanced Development](https://github.com/WhatsApp/stickers/tree/master/Android#advanced-development)

**Comment by mahirozdin** [comment]
> Hey @mahirozdin,
> If you want to create a custom stickers app this should help you: [Advanced Development](https://github.com/WhatsApp/stickers/tree/master/Android#advanced-development)

Did you read what I ask for? @MarvinJWendt

**Comment by MarvinJWendt** [comment]
@mahirozdin Yes of cource I did. If you want to add a sticker pack on runtime, you do not have to care about the `contents.json`. 
The sticker pack list is stored here:
https://github.com/WhatsApp/stickers/blob/86d38d3da0e1d1204269bb5c9078d6bc277f78cb/Android/app/src/main/java/com/example/samplestickerapp/StickerContentProvider.java#L72

You can modify it on runtime.

You can also take a look here:
- #340 
- And specially this comment: https://github.com/WhatsApp/stickers/issues/340#issuecomment-445425552


This is the information in the `README` explains how the sticker app is "sending" the stickers to WhatsApp. If you modify parts in there, you can add packs on runtime 😉 
![image](https://user-images.githubusercontent.com/31022056/50864634-f35b7e00-13a2-11e9-8908-8ae62318878f.png)

I hope this can help you more now 😄

**Comment by simonzhexu** [comment]
Thank you @MarvinJWendt  for your help. Great information. @mahirozdin please close the issue if your issue is solved.

**Comment by mahirozdin** [comment]
@MarvinJWendt  Yes ı understood the logic but if you have a time could you please make an example to adding this `private List<StickerPack> stickerPackList; ` i have main image and other images alsaa pack name and other thing how to add on this list.

**Comment by MarvinJWendt** [comment]
I am sorry, but I don't have time to code that at the moment.
I will leave this open so others can take a look at it. If you get it to work you can close this issue, and probably post the solution so others can use it too :)

**Comment by Blast06** [comment]
I think you want something like this https://github.com/idoideas/StickerMaker-for-Whatsapp
That app adds stickers at runtime i guess, you just have to look at the code.
Let me know if you have achieved

**Comment by Blast06** [comment]
@mahirozdin read [Read this](https://medium.com/bobble-engineering/dynamic-whatsapp-stickers-part-1-android-2ac00dc57111)
