### ISSUE TITLE
[Android] How do I properly set the applicationId?

### ISSUE THREAD

**Issue by rajkumarbhaiya** [WhatsApp/stickers#383]
hello 
i am a graphic designer . i want to make whatsapp sticker app . but i don't know how to make app . but i try with android studio. but i am facing many issue .

during running emulator where it show me that - you application com.raj. samplestickerapp , please change your application id to a diffrent string in a app/gradle in line 16

how to solve this prob ......
please i request all of you to make youtube video on it. how to make whatsapp sticker....

**Comment by EBDitore** [comment]
Você precisa mudar o nome do pacote do seu aplicativo

**Comment by MarvinJWendt** [comment]
Hey @rajkumarbhaiya,
Please follow the instructions in the Android [`README`](https://github.com/WhatsApp/stickers/blob/master/Android/README.md)



> during running emulator where it show me that - you application com.raj. samplestickerapp , please change your application id to a diffrent string in a app/gradle in line 16

For this specific problem you have to change this line: https://github.com/WhatsApp/stickers/blob/86d38d3da0e1d1204269bb5c9078d6bc277f78cb/Android/app/build.gradle#L10
to a unique name for your app.

**Comment by rajkumarbhaiya** [comment]
Bro give example - what i write instead of that line . Please 🙏

**Comment by simonzhexu** [comment]
Hi @rajkumarbhaiya , is your issue resolved? If so, please close the issue.

**Comment by rajkumarbhaiya** [comment]
Yes  .solved
