### ISSUE TITLE
[Android] WhatsApp keeps stopping

### ISSUE THREAD

**Issue by jaydeeees** [WhatsApp/stickers#384]
**Specifications**  
OS Version: Android 8.1.0
Device Manufacturer: Razer Phone

**Stickers**
- [ X ] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ X ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ X ] I am using **WebP** images for stickers.
- [ X ] I am using **PNG** images for stickers.

**Problem Description**  
Have already published my app, there was no problem in installing and adding the packs to Whatsapp. However, while browsing through the stickers in my newly added pack in Whatsapp, it always crashes Whatsapp and prompts "WhatsApp keeps stopping" options given were, restart, wait or close the app. 

Please kindly advise what is making my sticker app to caused Whatsapp to crash? As there were no other issues adding in my stickers.

**Reproduction Steps**  
1) Installed app from Play Store
2) Open
3) Add to Whatsapp
4) Successfully added to Whatsapp
5) Open Whatsapp
6) While browsing the newly added stickers, Whatsapp stops working.

Playstore link:
https://play.google.com/store/apps/details?id=com.bbnevertell.stickerapp

**Comment by MarvinJWendt** [comment]
Hey @jaydeeees,
Sticker apps *should* not be able to crash WhatsApp.
If you are able to get any error logs you can post them here, to help to analyze this behavior.
In the case that this is an internal WhatsApp problem, @simonzhexu should take a look at it :)

**Comment by jaydeeees** [comment]
@MarvinJWendt Yes that's the strange thing, there is no error log when i build and run my app on emulator or my phone. However whenever i'm trying to select a sticker from my sticker pack in Whatsapp, it always crashes and my Whatsapp just stop working.There is just no problem with my sticker app at all as functions such as opening, and adding sticker pack to whatsapp has no problem at all.

**Comment by MarvinJWendt** [comment]
Hey @jaydeeees,
```
    Process: com.whatsapp, PID: 22929
    java.lang.IllegalStateException: Failed to decode frame
        at com.facebook.animated.webp.WebPFrame.nativeRenderFrame(Native Method)
        at com.whatsapp.stickers.bo.a(:123124)
        at com.whatsapp.stickers.w$a.run(:123364)
```
Are you using **animated** `WebP` images?

This seems like it could be related to: https://github.com/facebook/fresco/issues/1954

**Comment by jaydeeees** [comment]
Have re-converted all my stickers from png to Webp again, updated and rebuild my project. Having no more issues that crashes Whatsapp anymore!

Greatly appreciate your help @MarvinJWendt Thanks again!
