### ISSUE TITLE
[Android] Gradle settings for this project are not configured yet

### ISSUE THREAD

**Issue by EBDitore** [WhatsApp/stickers#386]
Gradle settings for this project are not configured yet.

Would you like the project to use the Gradle wrapper?
(The wrapper will automatically download the latest supported Gradle version).

Click 'OK' to use the Gradle wrapper, or 'Cancel' to manually set the path of a local Gradle distribution.

What this is? How resolve, please?

**Comment by DanielK1511** [comment]
If im not wrong, you can click on OK

**Comment by EBDitore** [comment]
How resolve, please?

**Comment by Zandor300** [comment]
Try to click OK like @DanielK1511 suggested.

**Comment by EBDitore** [comment]
And after?

**Comment by DanielK1511** [comment]
What exactly asks Android Studio after clicking OK?

**Comment by Zandor300** [comment]
Well, what do you get to see after you clicked OK? Maybe post a screenshot or at least tell us.

**Comment by EBDitore** [comment]
Do not ask anything else, before it was wrong, now it seems ok!, thanks!

**Comment by EBDitore** [comment]
I have another question, my stickers are not appearing

**Comment by Zandor300** [comment]
Are your stickers exactly 512x512 and is the size < 100 KB? Are they PNG or WebP?

**Comment by EBDitore** [comment]
yes

**Comment by Zandor300** [comment]
Have you made any changes to the sample app apart from the JSON file?

Please post your JSON config.

**Comment by EBDitore** [comment]
yes

**Comment by EBDitore** [comment]
{
  "android_play_store_link": "",
  "ios_app_store_link": "",
  "sticker_packs": [
    {
      "identifier": "1",
      "name": "Brasil",
      "publisher": "Abstract Studio",
      "tray_image_file": "tray_Cuppy.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",
      "stickers": [
        {
          "image_file": "b3.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "02_Cuppy_lol.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "03_Cuppy_rofl.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "04_Cuppy_sad.webp",
          "emojis": ["😩","😰"]
        },
        {
          "image_file": "05_Cuppy_cry.webp",
          "emojis": ["😭","💧"]
        },
        {
          "image_file": "06_Cuppy_love.webp",
          "emojis": ["😍","♥"]
        },
        {
          "image_file": "07_Cuppy_hate.webp",
          "emojis": ["💔","👎"]
        },
        {
          "image_file": "08_Cuppy_lovewithmug.webp",
          "emojis": ["😍","💑"]
        },
        {
          "image_file": "09_Cuppy_lovewithcookie.webp",
          "emojis": ["😘","🍪"]
        },
        {
          "image_file": "10_Cuppy_hmm.webp",
          "emojis": ["🤔","😐"]
        },
        {
          "image_file": "11_Cuppy_upset.webp",
          "emojis": ["😱","😵"]
        },
        {
          "image_file": "12_Cuppy_angry.webp",
          "emojis": ["😡","😠"]
        },
        {
          "image_file": "13_Cuppy_curious.webp",
          "emojis": ["❓","🤔"]
        },
        {
          "image_file": "14_Cuppy_weird.webp",
          "emojis": ["🌈","😜"]
        },
        {
          "image_file": "15_Cuppy_bluescreen.webp",
          "emojis": ["💻","😩"]
        },
        {
          "image_file": "16_Cuppy_angry.webp",
          "emojis": ["😡","😤"]
        },
        {
          "image_file": "17_Cuppy_tired.webp",
          "emojis": ["😩","😨"]
        },
        {
          "image_file": "18_Cuppy_workhard.webp",
          "emojis": ["💻","🌃"]
        },
        {
          "image_file": "19_Cuppy_shine.webp",
          "emojis": ["🎉","✨"]
        },
        {
          "image_file": "20_Cuppy_disgusting.webp",
          "emojis": ["🤮","👎"]
        },
        {
          "image_file": "21_Cuppy_hi.webp",
          "emojis": ["🖐","🙋"]
        },
        {
          "image_file": "22_Cuppy_bye.webp",
          "emojis": ["🖐","👋"]
        },
        {
          "image_file": "23_Cuppy_greentea.webp",
          "emojis": ["🍵","😌"]
        },
        {
          "image_file": "24_Cuppy_phone.webp",
          "emojis": ["📱","😦"]
        },
        {
          "image_file": "25_Cuppy_battery.webp",
          "emojis": ["🔋","😵"]
        },
        {
          "image_file": "b1.webp",
          "emojis": ["🔋","😵"]
        },
        {
          "image_file": "25_Cuppy_battery.webp",
          "emojis": ["🔋","😵"]
        },
        {
          "image_file": "25_Cuppy_battery.webp",
          "emojis": ["🔋","😵"]
        },
        {
          "image_file": "25_Cuppy_battery.webp",
          "emojis": ["🔋","😵"]
        },
        {
          "image_file": "25_Cuppy_battery.webp",
          "emojis": ["🔋","😵"]
        }
      ]
    }
  ]
}

**Comment by EBDitore** [comment]
My first sticker is the "b3.webp"

**Comment by EBDitore** [comment]
I only changed this one for now.

**Comment by DanielK1511** [comment]
In my experience, the app crashes if somethings wrong with the 
```
content.json
```
Does the app says something? (in red text?)
greets

**Comment by Zandor300** [comment]
How did you generate the WebP file? Using Photoshop or Android Studio? If you used Photoshop, please try doing it using Android Studio or with just a PNG file.

Also please try to avoid spam. You can edit comments.

**Comment by EBDitore** [comment]
Android Studio

**Comment by EBDitore** [comment]
How do I insert a picture into the question, please?

**Comment by EBDitore** [comment]
Many thanks for the support, I had not rebuild my project after renaming it, now yes, I did the rebuild, and changed the name in all classes that was wrong, now it worked, my stickers appear without error, thank you same!!!
