### ISSUE TITLE
[Android] Manifest merger failed with multiple errors 

### ISSUE THREAD

**Issue by DevenRathod2** [WhatsApp/stickers#387]
I'm trying to implement Onesignal push notifications on app but after all implementation
[Manifest merger failed with multiple errors] This error coming please help me to fix this error

**Comment by MarvinJWendt** [comment]
Hey @DevenRathod2,
Please use the Issue templates for Android or iOS,

Your problem seems to be resolved on StackOverflow:
https://stackoverflow.com/questions/35842955/manifest-merger-failed-with-multiple-errors-in-android-studio/35844350

**Comment by DevenRathod2** [comment]
This is error log :-Manifest merger failed with multiple errors. and i'm using whatsapp sticker source code that whatsapp provide on github and when i'm going to add onesignal push notifications on my app then this error is showing sync successful but build not

**Comment by simonzhexu** [comment]
It means, when the app tries to build, it merges all the manifest from all the modules together. And when it fails to merge the manifest, it displays this error. Please look closely into the actual errors, and figure out the problem. We don't see your code, so we cannot figure this out with the information you have provided.

**Comment by DevenRathod2** [comment]
I already fix that issue with lots of struggle i be post code soon for other users
