### ISSUE TITLE
After adding multiple sticker packs Whatsapp sticker panel takes too much time to display stickers[Android]

### ISSUE THREAD

**Issue by nishi312** [WhatsApp/stickers#392]
I am loading stickers from internet and storing it into local directory and all thing working fine , but only problem which i face that it continuously displaying loading message in Whatsapp sticker panel and after some time it displays stickers,
Please help me out from this problem

**Comment by some28** [comment]
I'm also facing the same problem when loading stickers from android internal storage. 
Time taken to load stickers is directly proportional to the number of sticker packs added.

private AssetFileDescriptor fetchFile(@NonNull Uri uri, @NonNull AssetManager am, @NonNull String fileName, @NonNull String identifier) {
        try {
            File file;
            if(fileName.endsWith(".png")){
                file = new File(getContext().getFilesDir()+  "/" + "stickers_asset" + "/" + identifier + "/try/", fileName);
            } else {
                file = new File(getContext().getFilesDir()+  "/" + "stickers_asset" + "/" + identifier + "/", fileName);
            }
            if (!file.exists()) {
                Log.d("fetFile", "StickerPack dir not found");
            }
            Log.d("fetchFile", "StickerPack " + file.getPath());
            return new AssetFileDescriptor(ParcelFileDescriptor.open(file, ParcelFileDescriptor.MODE_READ_ONLY), 0L, -1L);
        } catch (IOException e) {
            Log.e(Objects.requireNonNull(getContext()).getPackageName(), "IOException when getting asset file, uri:" + uri, e);
            return null;
        }
    }

**Comment by some28** [comment]
@muhammadn Loading is slow in WhatsApp and not in 3rd party sticker app.

**Comment by simonzhexu** [comment]
Your app should provide a memory cache inside the provider. Reading the file everytime we load the sticker packs will certainly be slow.

**Comment by nishi312** [comment]
do you have any demo related to

> Your app should provide a memory cache inside the provider. Reading the file everytime we load the sticker packs will certainly be slow.

do you have any demo or reference for providing a memory cache in provider ?

**Comment by MarvinJWendt** [comment]
Hey,
This Issue seems to be inactive. To keep things organized I will close this for now. If this Issue is still relevant, don't hesitate to drop a comment and I will reopen it if necessary.

**Comment by SubhanshuMG** [comment]
@MarvinJWendt please open this issue as now I'm facing this same problem too.

**Comment by MarvinJWendt** [comment]
Hey @SubhanshuMG, this issue is nearly 2 years old now. Please open a new one with a detailed description. The fix for this issue will most likely not apply to you :)
