### ISSUE TITLE
Hassan AlMohannadi

### ISSUE THREAD

**Issue by 5H8** [WhatsApp/stickers#393]
**Specifications**  
OS Version: [12.1.1]
Device Manufacturer: [Apple]

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for stickers.

**Problem Description**  
[FILL IN WITH DETAILED DESCRIPTION OF THE PROBLEM]

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN APP STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by MarvinJWendt** [comment]
Hey @5H8,
You haven't filled out any information, nor described a problem.
If you have an Issue please open a new Issue and fill out the template :)
