### ISSUE TITLE
i want to add more then 30 sticker in one pack how can i do it.

### ISSUE THREAD

**Issue by khushal96** [WhatsApp/stickers#394]
how can i increase sticker in one pack > 30

**Comment by muhammadn** [comment]
For iOS. you can change it here:

https://github.com/WhatsApp/stickers/blob/master/iOS/WAStickersThirdParty/Limits.swift#L19

**Comment by MarvinJWendt** [comment]
Hey @khushal96,
The limitation is on WhatsApp´s side. I am sorry but, you cannot change that.
If you want to create more stickers than a single app can hold, you would need to create a second app.
See #107 and https://github.com/WhatsApp/stickers/issues/359#issuecomment-448845493
