### ISSUE TITLE
Help unbanning me from Google Play

### ISSUE THREAD

**Issue by 0566055455** [WhatsApp/stickers#397]
Hi,

I was one of the first to create stickers apps for WhatsApp, Things wasnt clear back then on what to name the app.
I used the form "App name - WhatsApp"
Instead of "App name for WhatsApp".

I didnt care that much but recently my brother who lives with me in the same house got terminated because of google thinking its me. I really need a help from you to contact AppDetex or whoever is responsible of banning me and ask them to send an email to Google so they unban me and then my brother will get unbanned. 

I was one of the first to get banned just because I named the app in the wrong form, I am pretty sure there was nothing written in the readme file about naming the app and it has been added after me and few other developers got banned.

Edit: I mean what to name the app has been added after me and others got banned.

**Comment by MarvinJWendt** [comment]
Hey @0566055455,
Well this is difficult. First of all your brother could try to contact Google, as he didn't violate any rules at Google AFAIK. But the thing is different for you. My first app was suspended by Google too, but if you think about it, it's not that unfair. 
Using `WhatsApp` in the way you (and I) did, violates against the ToS of Google (and trademark law).
I know that others do it too, and some don't get any suspension. They don't have extra rights, they're just lucky. 

> I mean what to name the app has been added after me and others got banned.

And to be fair, there was **always** a notice in the License file:
https://github.com/WhatsApp/stickers/blob/bf5c52f7a5c025c5eabdf54b65c4d2ae8d875d4b/LICENSE#L17-L19

This file was never changed. If you had read the license, you would have known that you should not use `WhatsApp` in the apps name.
I know it's frustrating, I went through it too, and I am sorry that we cannot really help you here.

Sincerely,
Marvin Wendt

**Comment by zawawimanja** [comment]
rip..apps just suspend..

**Comment by MarvinJWendt** [comment]
It seems like all questions are answered. There hasn't been any recent activity here, so I would say the Issue is resolved. If you have any further questions on this Issue don't hesitate to drop a comment and I will reopen the Issue if necessary. 
Have a nice day 😄
