### ISSUE TITLE
[Android] You can make it work in GB Whatsapp

### ISSUE THREAD

**Issue by Mateuslapa** [WhatsApp/stickers#399]
I get many requests to make it work in GBWhatsapp, how?

**Comment by MarvinJWendt** [comment]
Hey @Mateuslapa,
GBWhatsApp is not an official WhatsApp application. It's strongly suggested to **not** use third party software to modify WhatsApp.

**Comment by simonzhexu** [comment]
Sorry, we will not provide support for working with a hacked client.
