### ISSUE TITLE
Custom Sticker doesn't finish loading for others

### ISSUE THREAD

**Issue by falassiry** [WhatsApp/stickers#4]
Note: I haven't published the app yet. I've followed instructions on modifying the sample app and it seems to work "correctly" by adding my new stickers.

However, when I send any of my newly added stickers, they never finish loading on the other side, and it doesn't even show the first tick if it's sent in a direct PM.

Is publishing the app on the store a prerequisite for stickers to work? Or is there another problem causing this.

**Comment by amrit-1901** [comment]
Can you report this issue using the standard WhatsApp support route? This issue is not related to the sample app.
