### ISSUE TITLE
JSON structure generate

### ISSUE THREAD

**Issue by developerpistachio** [WhatsApp/stickers#406]
is there any way to generate the json structure from the images automatically ?

**Comment by simonzhexu** [comment]
I am not sure what is the question. Please elaborate.

**Comment by MarvinJWendt** [comment]
Hey @developerpistachio,
Currently there is no way to generate the JSON structure AFAIK. I don't think that anyone is working on such a tool. If you find a tool or create one, feel free to post the link here - maybe that could be added to the docs then.
I also thought about such a tool, but sadly I don't have time for that at the moment.

**Comment by Windows10User2k19** [comment]
Not that I'm aware of... The JSON file in the sticker-master is quite user friendly though a bit time consuming.

You can use either Android Studio or [this](https://jsonformatter.curiousconcept.com/) to help debug your JSON file once you modify it.

**Comment by pratikbutani** [comment]
> Hey @developerpistachio,
> Currently there is no way to generate the JSON structure AFAIK. I don't think that anyone is working on such a tool. If you find a tool or create one, feel free to post the link here - maybe that could be added to the docs then.
> I also thought about such a tool, but sadly I don't have time for that at the moment.

I have created one file that I used to create JSON (for one pack) from files. I will post online soon so it will be helpful to all developers.

**Comment by pratikbutani** [comment]
@developerpistachio @MarvinJWendt 

I have created script that will give you JSON of selected files.

[Convert Image names to JSON Array (WAStickerApp)](http://pratikbutani.com/wastickerapp/)

That will allows you to:
- Select 30 Images (Must be **webp**)
- JSON Array of Name of Selected Files 

**Format:**
```
[
    {
        "image_file":"1.webp",
        "emojis":[
            "☕",
            "🙂"
        ]
    },
    {
        "image_file":"2.webp",
        "emojis":[
            "😄",
            "😀"
        ]
    },
    {
        "image_file":"3.webp",
        "emojis":[
            "☕",
            "🙂"
        ]
    }
]
```

I will try to add more functionality like developer can input publisher name, email, Android/iOS link etc...

Created Repository [WAStickerApp-JSON-Generator](https://github.com/pratikbutani/WAStickerApp-JSON-Generator) on GitHub if anyone wants to contribute <3

Hope it will helps. Thank you.

**Comment by pratikbutani** [comment]
@developerpistachio  @MarvinJWendt 

I have added more functionality. Please check and do let me know If any suggestions.

[Convert Image names to JSON Array (WAStickerApp)](http://pratikbutani.com/wastickerapp/)

Thanks.

**Comment by pratikbutani** [comment]
@MarvinJWendt  If you think that my link is helpful to other developers, you can put it in docs. 

Thanks.

**Comment by MarvinJWendt** [comment]
Hey, @pratikbutani,
I already considered that, but I don't have much time at the moment. If you want, I can take a closer look over the weekend 😄 
But your tool looks good as far as I can tell now 👍
I have some Ideas to improve it, I'll send them to you as soon as I have time again :)

**Comment by MarvinJWendt** [comment]
Sadly we could not implement the tool from @pratikbutani due to a WhatsApp regulation. There aren't any updates anymore, so I guess this issue can be closed. If any further questions may come up, feel free to drop a comment and I will reopen the issue :)
