### ISSUE TITLE
[Android] package Name

### ISSUE THREAD

**Issue by umang56** [WhatsApp/stickers#421]
Hi, I am uploading a new app on play store as I went through README.MD I found that 

when naming your app, it is strongly advised you do not use "WhatsApp" anywhere in the name of your app or in the name field of your app listing on the Google Play Store. However, when preparing your app for submission in Google Play Store, you'll have the option to add description associated with your app and it's okay to mention WhatsApp in the description. WhatsApp can also launch the Google Play Store and perform a search for other sticker pack apps. To help your app appear in this list, also add the keyword WAStickerApps to app's description when setting up your app in the Google Play Store console. You can use additional keywords, but make sure you at least use this one.

This simply means I cannot use WhatsApp in my package name & app title but however whats app is suggesting us to use WAStickerApps  

here is my query

1. Can I use WAStickerApps in my package name for eg. com.domain.wastickerapps 
2. as I seen on play store app developer are using for whatsapp in the title of App for e.g Gujarati Stickers for Whatsapp - WAStickerApps
3. is it important to use 
IMPORTANT : The "WhatsApp" name is copyright to WhatsApp, Inc. Sticker Pack for whatsapp is in no way affiliated with, sponsored or endorsed by WhatsApp, Inc.
If you notice that any content in our app violates any copyrights than please inform us so that we remove that content.
or 
DISCLAIMER - 
1. The app is not affiliated by WhatsApp
2. The app complies to WhatsApp TOS related to distribution of WhatsApp Stickers
3. App does not store any user's information
4. This is a part of WAStickerApps collection of WhatsApp

This kind of note in the bottom of the description?

**Comment by MarvinJWendt** [comment]
Hey @umang56,
The license just states that the name "WhatsApp" may not be used to advertise your app. So it's not recommended to put it in the title. However the name "WAStickerApps" isn't copyrighted AFAIK. I don't think you'll have a problem using it.

**Disclaimer:** Please wait for a response from @simonzhexu or @amrit-1901. My answer could be wrong as I am just guessing.

**Comment by simonzhexu** [comment]
Here is my suggestion from WhatsApp.

-Do not put WhatsApp in your app name or app title or package name.
-You can put WAStickerApps in your app description
- Do not use WAStickerApps in your package name.

One example that will pass this criteria:
Package name: com.umang56.stickerpacks
App name: Piggy sticker packs
App description:
cute piggy sticker packs that will make you happy
wastickerapps

**Comment by simonzhexu** [comment]
Using wastickerapps keyword will help play store find your sticker packs. That's all its purpose.

**Comment by umang56** [comment]
> Here is my suggestion from WhatsApp.
> 
> * Do not put WhatsApp in your app name or app title or package name.
> * You can put WAStickerApps in your app description
> * Do not use WAStickerApps in your package name.
> 
> One example that will pass these criteria:
> Package name: com.umang56.stickerpacks
> App name: Piggy sticker packs
> App description:
> cute piggy sticker packs that will make you happy
> wastickerapps

@simonzhexu  Thanks For the reply

But I have seen apps that rank on play store with  name whats app in title and description

For e.g stickers for whatsapp - wastickersapps  
Gujarati STICKERS FOR WHATSAPP - WAStickerApps 

These apps are having 10,00,000+ downloads 

Also, I have seen a package name that includes wastickerapps and that also has good numbers of download 

May I know why their app is not banned ??

And can you tell me is it important to use DISCLAIMER At the end of the description ???

**Comment by MarvinJWendt** [comment]
Hey @umang56,
> But I have seen apps that rank on play store with name whats app in title and WAStickerApps in the package name

This is right, there are app authors who do that.. That doesn't mean that they are allowed to do it. In fact the most (if not all) are not allowed to use WhatsApp in the title. They aren't banned because nobody cared, yet. But they have to live at the risk getting banned (and losing all revenue).

> Also, I have seen a package name that includes wastickerapps and that also has good numbers of download

This is right too, but still, they are not allowed to do that.

> And can you tell me is it important to use DISCLAIMER At the end of the description ???

AFAIK there is no guideline stating that you need to write a disclaimer. But it doesn't hurt and it clarifies that your app is not affiliated with WhatsApp. I would recommend writing it, but I think you don't need to.

**Comment by umang56** [comment]
> Hey @umang56,
> 
> > But I have seen apps that rank on play store with name whats app in title and WAStickerApps in the package name
> 
> This is right, there are app authors who do that.. That doesn't mean that they are allowed to do it. In fact the most (if not all) are not allowed to use WhatsApp in the title. They aren't banned because nobody cared, yet. But they have to live at the risk getting banned (and losing all revenue).
> 
> > Also, I have seen a package name that includes wastickerapps and that also has good numbers of download
> 
> This is right too, but still, they are not allowed to do that.
> 
> > And can you tell me is it important to use DISCLAIMER At the end of the description ???
> 
> AFAIK there is no guideline stating that you need to write a disclaimer. But it doesn't hurt and it clarifies that your app is not affiliated with WhatsApp. I would recommend writing it, but I think you don't need to.

@MarvinJWendt  Thanks for the reply 


Waiting for @simonzhexu  Comment

**Comment by simonzhexu** [comment]
@MarvinJWendt  said what I want to say. Those apps get away with it as Google didn't really push hard, and WhatsApp didn't have time to push hard either. But that doesn't mean they are doing the right thing. Disclaimer is optional.
