### ISSUE TITLE
[Android]Error at building on file activity_sticker_pack_list.xml

### ISSUE THREAD

**Issue by juan-vega-95** [WhatsApp/stickers#422]
**Specifications**  
OS Version: [Android SDK 28, gradle-4.10.1]
Device Manufacturer: [Non applicable]

**Stickers**
- [*] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [*] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [*] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

[Building on linux, after issuing the build command I get:

/home/juan/stickers/Android/app/src/main/res/layout/activity_sticker_pack_list.xml:9: Error: This view is not constrained. It only has designtime positions, so it will jump to (0,0) at runtime unless you add the constraints [MissingConstraints]
      <TextView
       ~~~~~~~~
  /home/juan/stickers/Android/app/src/main/res/layout/activity_sticker_pack_list.xml:16: Error: This view is not constrained vertically: at runtime it will jump to the top unless you add a vertical constraint [MissingConstraints]
      <android.support.v7.widget.RecyclerView



**Reproduction Steps**  
Inside strickers/Android:
./gradlew build

commit d517b4984e3e9b702d7a80301ae0269fa636f065 (HEAD -> master, origin/master, origin/HEAD)

**Comment by juan-vega-95** [comment]
Ok, i make it build modifying activity_sticker_pack_list.xml, adding 
to  <android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
**** xmlns:app="http://schemas.android.com/apk/res-auto"
and to <TextView
****android:text="textview"
****app:layout_constraintHorizontal_bias="0.0"
****app:layout_constraintVertical_bias="0.0"
and  to <android.support.v7.widget.RecyclerView
****app:layout_constraintHorizontal_bias="0.0"
****app:layout_constraintVertical_bias="0.0"

I don't know if it's the way to go, but it build.
I will test the app tomorrow, thanks for the app. :)

**Comment by simonzhexu** [comment]
Thanks. Fixed in https://github.com/WhatsApp/stickers/commit/e4c8f451b0a473a4d328d4daeae331953b69e8c8
