### ISSUE TITLE
[Android] problems in dependences and others packages technicians

### ISSUE THREAD

**Issue by darcknnes** [WhatsApp/stickers#427]
Good, my problem is this,
1st In app -> assets -> contents. json are defined the packages of stickers that will be displayed in the main view, the main view shows 5 stickers per package (5 images to show the package), with a "padding" or space  between each, when more than 5 packages are created from the sixth package onwards, the padding (space) inter stickers is lost and stick with each other
2nd Can I mount a banner on the bottom?
3rd Forgive this question if something bothers you, but I want to add a BANNER in the bottom part and I could not, when I added the dependency of admob in app: Module (implementation 'com.google.android.gms: play-services- ads) I create an error (I do not know if it is incompatible) with the other dependencies, specifically is the first dependency of the list that shows the error, in this case appcompat, a red line is created at the bottom of the first dependency that is deleted if I remove the dependence on gms: play-services-ads, I had tried in many ways and until now it was not erased, recently (today precisely) I did something and the error was deleted, but that BANNER still not show, so I do not know either if the end if it worked.
EntryActivity.java is the MainActivity according the AndroidManifest.xml, i put the BANNER in activity_entry.xml, but it is not displayed, there are other views that are running.
I do not want to go too far I want to put a BANNER. Can I put it and where can I put it so it can be seen? preferably in the bottom part of the main view and already.
Thanyou for your time and i'm sorry i don't speak english, i speack spanish, my english is very bad, but I did what I could, sorry and very thanks.

**Comment by MarvinJWendt** [comment]
Hey @darcknnes,
Please write your Issue in English :)
Thanks.

**Comment by simonzhexu** [comment]
for 1st question, contents.json should list all the stickers you want to add. And the app will show the first few up to 5 stickers in the main view. I don't see cases where the padding is lost, please attach a screenshot where you see that.
For 2nd question, please ask on StackOverflow
3nd, EntryActivity is only shown for a split second, after that it decides to take the user to go to StickerPackListActivity or StickerPackDetailsActivity

You would want to put your banner in there.

**Comment by darcknnes** [comment]
![image](https://user-images.githubusercontent.com/31108336/53291730-00330600-3786-11e9-9562-cfa0ee8ec5e6.png)
The PADDING is lost.
The main activity is EntryActivity, from here other views are loaded (pages), the first view that is loaded is StickerPackListActivity if there is more than one package, if there is only one package, the view than loaded is StickerPackDetailsActivity, the problem it's in the RecyclerView of the StickerPackListActivity that only show 5 packages all right and the others show them wrong

**Comment by onyet** [comment]
That's right.
not only for rows after line 5. but random. try to enter the sticker details, then come back again to list activity. see what happens. I think it's a problem when loading stickers from the json file.
thanks.

sorry because my english is bad :v:

**Comment by simonzhexu** [comment]
Thanks guys. I will take a look!

**Comment by simonzhexu** [comment]
This is now fixed. Thank you for reporting.
