### ISSUE TITLE
[Android] Error in StickerPackValidator.java

### ISSUE THREAD

**Issue by PXNX** [WhatsApp/stickers#429]
**Specifications**  
OS Version: [Android 7.0.1, 8.0.1, 9.0.1]
Device Manufacturer: [Samsung]

**Stickers**
- [ ] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [X] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
by trying to run the app i get the following error:
> error: cannot access AnimatedImage
> class file for com.facebook.imagepipeline.animated.base.AnimatedImage not found

**Reproduction Steps**  
just open up the project (freshly downloaded from here) and try to sync, run or make a new project.
I'm using the newest (canary) version of android studio and retried it with other versions of android studio already, getting the same result.

**Links**  
i asked it on stackoverflow, too.
https://stackoverflow.com/questions/54834307/error-in-offical-whatsapp-stickers-example-app

and another one did it aswell.
https://stackoverflow.com/questions/54427681/error-cannot-access-animatedimage-class-file-for-com-facebook-imagepipeline-ani

Thanks in advance - hoping for a quick response.

**Comment by MarvinJWendt** [comment]
Hey @PXNX,
Have you seen this answer on StackOverflow?
![image](https://user-images.githubusercontent.com/31022056/53446012-2c62b700-3a12-11e9-9a07-8427247b01ae.png)
If not please verify that this is not your issue :)

**Comment by PXNX** [comment]
It doesn't have to do anything with that.
I simply can't create a project, nor sync/run it.

**Comment by pratikbutani** [comment]
@PXNX Which version do you use of fresco?

**Comment by PXNX** [comment]
1.12.0, but i also tried it with a few other versions.

**Comment by pratikbutani** [comment]
Try out 1.12.1 for fb library.

**Comment by PXNX** [comment]
still same error.

**Comment by onyet** [comment]
Just update your Android API, Build tools, Kotlin, and grandle. I fixed just like that. Thanks.

**Comment by lohigno** [comment]
Hi.
Similaro problem whit me also , giving this 2 errors when try to Build Project

error: package com.facebook.animated.webp does not exist
error: cannot find symbol variable WebPImage

**Comment by PXNX** [comment]
Its all up-to-date, but still the same error.

**Comment by simonzhexu** [comment]
Hi, @PXNX , could you share the android studio version you have? It appears you have some issues downloading fresco library from JCenter.

**Comment by PXNX** [comment]
Android Studio 3.5 Canary 6
Build #AI-183.5429.30.35.5326993, built on February 21, 2019
JRE: 1.8.0_152-release-1343-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by dawud-tan** [comment]
@simonzhexu I'm experiencing same error, with fresco 1.13.0

```
error: cannot access AnimatedImage
error: cannot access AnimatedImageDecoder
````

following is my dependency
```java
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.facebook.fresco:fresco:1.13.0'
    implementation 'com.facebook.fresco:animated-webp:1.13.0'
    implementation 'com.facebook.fresco:webpsupport:1.13.0'
    implementation 'androidx.legacy:legacy-support-core-utils:1.0.0'
    implementation 'com.google.android.gms:play-services-ads-lite:17.2.0'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'com.squareup.picasso:picasso:2.71828'
```

here my  android studio version 
```
Android Studio 3.3.2
Build #AI-182.5107.16.33.5314842, built on February 16, 2019
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by dawud-tan** [comment]
@simonzhexu I'm just manually download all fresco deps, and import it using `implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs')`, then it works just fine:

`animated-base-1.13.0,  animated-drawable-1.13.0, animated-webp-1.13.0, bolts-tasks-1.4.0, drawee-1.13.0, fbcore-1.13.0, fresco-1.13.0, imagepipeline-1.13.0, imagepipeline-base-1.13.0, nativeimagefilters-1.13.0, nativeimagetranscoder-1.13.0, soloader-0.6.0, webpsupport-1.13.0`

**Comment by tanwarsachin** [comment]
just add one more dependency
implementation 'com.facebook.fresco:animated-base:1.13.0', then it works just fine

**Comment by dawud-tan** [comment]
@tanwarsachin `'com.facebook.fresco:animated-base:1.13.0'` is already transitive dependency of `'com.facebook.fresco:animated-webp:1.13.0'`, it will just make it explicit, but I think it would not solve both error: `cannot access AnimatedImage` and `cannot access AnimatedImageDecoder`. Though I'm still curious what could have caused it in the first place?

**Comment by PXNX** [comment]
Somehow it seems to work as for now <3
@tanwarsachin

**Comment by MarvinJWendt** [comment]
@PXNX please close this issue if you do not need further advice :)

**Comment by vimalcvs** [comment]
@PXNX @MarvinJWendt @pratikbutani @onyet @lohigno 

   just add one more dependency
```
    implementation 'com.facebook.fresco:fresco:1.13.0'
    implementation 'com.facebook.fresco:animated-webp:1.13.0'
    implementation 'com.facebook.fresco:webpsupport:1.13.0'

    implementation 'com.facebook.fresco:animated-base:1.13.0'
```

**Comment by simonzhexu** [comment]
should be fixed.

**Comment by Blast06** [comment]
> Somehow it seems to work as for now <3
> @tanwarsachin

Lol, also for me! thanks
