### ISSUE TITLE
Сууйуута

### ISSUE THREAD

**Issue by maximivanov71** [WhatsApp/stickers#435]
**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [ ] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ ] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
[FILL IN WITH DETAILED DESCRIPTION OF THE PROBLEM]

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN APP STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]
![021a9da4-942d-43db-a781-864fa3162f20](https://user-images.githubusercontent.com/48170532/53691324-cb930000-3dbe-11e9-8bc0-602a7defab68.png)
![021a9da4-942d-43db-a781-864fa3162f20](https://user-images.githubusercontent.com/48170532/53691325-e4031a80-3dbe-11e9-8be9-62b56d330ec8.png)

**Comment by maximivanov71** [comment]
Сууйуута!!!

**Comment by MarvinJWendt** [comment]
Hey, you are in the support section of the WhatsApp Sticker App template. Posting your stickers here won't make them available in WhatsApp.
Have a nice day :)
