### ISSUE TITLE
Current whatsapp sticker packs are not compatible or usable in Whatsapp Business?

### ISSUE THREAD

**Issue by jaydeeees** [WhatsApp/stickers#439]
Specifications
OS Version: [Android]

Stickers

 My stickers do comply with the sticker requirements (512x512 and < 100 KB)
 My tray icon does comply with the requirements (96x96 and < 50 KB)
 I am using WebP images for stickers.
 
Problem Description
Have no problem/error with running the app as it is published for a few months already. However im getting reviews that my customers are not able to use it in Whatsapp Business. 

Please advise if this is common that stickers are not usable in Whatsapp Business yet? Or the souce code here provided is not designed to implement stickers or be compatible with Whatsapp Business?

 Please kindly advise. Thank you.

**Comment by simonzhexu** [comment]
The app is designed to work with both WhatsApp and WhatsApp Business. I have made some improvements in this area after the original code was published. So I suggest you and all other developers to get the latest from master and merge into your app. 

If your user doesn't get a way to add to WhatsApp Business, there could be a few reasons:
1. When they tried to add the app initially, the Android System asks them whether they want to add it to WhatsApp or WhatsApp Business. And then there is a button to choose "Just Once" or "Always", if they choose "Always", the system will not prompt WhatsApp Business again. This is what is called "Default Apps". The way to fix it is: go to the settings of WhatsApp, and do "Clear Defaults". More info: https://www.makeuseof.com/tag/remove-change-set-default-apps-android/
If you get the latest source code, we will ask the user to choose WhatsApp or WhatsApp Business even if they have set a default.
2. They have a really old WhatsApp Business that doesn't support stickers
