### ISSUE TITLE
[iOS] why ios code doesn't have something to check whether sticker pack is deleted from whatsapp or not ? Something like Whitelistcheck in android code

### ISSUE THREAD

**Issue by ib7sandbox** [WhatsApp/stickers#440]
**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
[FILL IN WITH DETAILED DESCRIPTION OF THE PROBLEM]

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN APP STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by simonzhexu** [comment]
iOS doesn't have ability to allow communication between apps. Thus, no things like ContentProvider in Android. The only workaround was to use Paste board which was used when exporting sticker packs from sticker app to WhatsApp. There is no way available for communication from WhatsApp back to the Sticker app.
