### ISSUE TITLE
[iOS]Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: SYEmojies.StickerPackError.fileNotFound

### ISSUE THREAD

**Issue by Ruman1234** [WhatsApp/stickers#441]
Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: 
Emojies.StickerPackError.fileNotFound

i am having this error

let stickerPack = try! StickerPack(identifier: "emojies",
                                           name: "emojies1",
                                           publisher: "emojies1",
                                           trayImageFileName: "emojies.png",
                                           publisherWebsite: "https://emojies.com",
                                           privacyPolicyWebsite: nil,
                                           licenseAgreementWebsite: nil)

**Comment by simonzhexu** [comment]
what is your wasticker file, it seem to indicate that you don't have the tray or sticker image added.

**Comment by Zandor300** [comment]
@simonzhexu I think he isn't using the wasticker file and just hardcoding stickerpacks.

@Ruman1234 Does the `emojies.png` file exist and is it added to your app's target inside of Xcode?

**Comment by Ruman1234** [comment]
i fix this issue thanks
