### ISSUE TITLE
when added to whatsapp the number of sticker in this pack isn't between 3 and 30[iOS]

### ISSUE THREAD

**Issue by Ruman1234** [WhatsApp/stickers#445]
the number of sticker in this pack isn't between 3 and 30

```
Skipping bad sticker data
[-[YYImageEncoder initWithType:]: 2332] WebP is not available, check the documentation to see how to install WebP component: https://github.com/ibireme/YYImage#installation
```

i have webp images but its not adding i also added YYImage

<img width="441" alt="Screenshot 2019-03-18 at 3 34 49 PM" src="https://user-images.githubusercontent.com/37799754/54524402-ae9c2680-4993-11e9-9f1f-ba98e9bd56c0.png">

**Comment by Ruman1234** [comment]
<img width="663" alt="Screenshot 2019-03-18 at 3 38 22 PM" src="https://user-images.githubusercontent.com/37799754/54524484-e6a36980-4993-11e9-84e1-bc99b68327a6.png">

**Comment by Ruman1234** [comment]
<img width="1183" alt="Screenshot 2019-03-18 at 3 40 35 PM" src="https://user-images.githubusercontent.com/37799754/54524608-341fd680-4994-11e9-8a44-6432b069534a.png">


this is my code

**Comment by Zandor300** [comment]
Do you have the `WebP.framework` included in your project?

### Cocoapods

If you are adding YYImage to your project through Cocoapods, you have to make sure to add their WebP subspec too:

```ruby
pod 'YYImage'
pod 'YYImage/WebP'
```

> Notice: it doesn't include WebP subspec by default, if you want to support WebP format, you may add pod 'YYImage/WebP' to your Podfile.

(See https://github.com/ibireme/YYImage#cocoapods)

### Manual

In case you aren't using Cocoapods; you should copy the WebP.framework to your project directory and include it as a static library on your project settings page in Xcode. You can get the WebP.framework from this repo in the following directory: https://github.com/WhatsApp/stickers/tree/master/iOS

**Comment by Ruman1234** [comment]
yes i added webP.framework

**Comment by Ruman1234** [comment]
<img width="1440" alt="Screenshot 2019-03-18 at 4 32 02 PM" src="https://user-images.githubusercontent.com/37799754/54527330-62ed7b00-499b-11e9-8e2f-2ba422035550.png">

**Comment by Zandor300** [comment]
> yes i added webP.framework

If that's the case and it still doesn't work; I think your WebP file is incorrectly created. WebP files generated from certain programs don't work well. Did you use one of the methods described here? https://github.com/WhatsApp/stickers/tree/master/iOS#converting-to-webp, if you didn't, please try one of those methods instead and try again.

**Comment by Zandor300** [comment]
Specific to your code:

```swift
StickerPack.addSticker(contentsOfFile: String, emojis: String)
```

* Afaik, `contentsOfFile` needs to contain the extension of the file.
* I also believe the file `stickers` doesn't exist in your project.
* Also, make sure your WebP and PNG files are included in your app's target. Select it in the filelist on the left en make sure, under **Target Membership** on the right, your app's target, in this case `SYEmojies`, is checked and that under **Identity and Type**, your Type is set to `Data`.

**Comment by Ruman1234** [comment]
i deleted the project and now i want to add webP.framework but it isn't shown

**Comment by Ruman1234** [comment]
<img width="1400" alt="Screenshot 2019-03-18 at 5 00 30 PM" src="https://user-images.githubusercontent.com/37799754/54528643-5bc86c00-499f-11e9-9052-eb720ac6f4a5.png">

**Comment by Zandor300** [comment]
Click **Add Other** and select it in your project directory.

**Comment by Ruman1234** [comment]
i cannot see webP.framework there also

**Comment by Zandor300** [comment]
Then you should download it from this repository and copy it into your project directory.

**Comment by Ruman1234** [comment]
can you send me this wastickersthiredparty
my xcode is not opening the which i downloaded

**Comment by Ruman1234** [comment]
which repository

**Comment by Zandor300** [comment]
I’ve given you this link before: https://github.com/WhatsApp/stickers/tree/master/iOS

**Comment by Ruman1234** [comment]
i download it

**Comment by Zandor300** [comment]
Now add it like I’ve told you earlier.

**Comment by Ruman1234** [comment]
<img width="1398" alt="Screenshot 2019-03-18 at 5 36 56 PM" src="https://user-images.githubusercontent.com/37799754/54530402-7b15c800-49a4-11e9-9af7-c230b8f79595.png">

**Comment by Ruman1234** [comment]
> the number of sticker in this pack isn't between 3 and 30
> 
> ```
> Skipping bad sticker data
> [-[YYImageEncoder initWithType:]: 2332] WebP is not available, check the documentation to see how to install WebP component: https://github.com/ibireme/YYImage#installation
> ```
> i have webp images but its not adding i also added YYImage
> 
> <img alt="Screenshot 2019-03-18 at 3 34 49 PM" width="441" src="https://user-images.githubusercontent.com/37799754/54524402-ae9c2680-4993-11e9-9f1f-ba98e9bd56c0.png">

now whatsapp is showing still this

**Comment by Zandor300** [comment]
Rename it to WebP.framework. This won’t work.

**Comment by Ruman1234** [comment]
![rn](https://user-images.githubusercontent.com/37799754/54530883-d300fe80-49a5-11e9-9923-157ce31031e4.jpeg)

**Comment by Ruman1234** [comment]
Skipping bad sticker data
2019-03-18 17:42:38.432226+0500 SYEmojies[3493:234557] [-[YYImageEncoder initWithType:]: 2332] WebP is not available, check the documentation to see how to install WebP component: https://github.com/ibireme/YYImage#installation

**Comment by Ruman1234** [comment]
why it is giving this

Skipping bad sticker data
2019-03-18 17:42:38.432226+0500 SYEmojies[3493:234557] [-[YYImageEncoder initWithType:]: 2332] WebP is not available, check the documentation to see how to install WebP component: https://github.com/ibireme/YYImage#installation

**Comment by Zandor300** [comment]
Please provide us with your project on GitHub so we can inspect it because you are obviously doing something wrong. All my instructions should've solved this problem afaik.

**Comment by Ruman1234** [comment]
[SYEmojies.zip](https://github.com/WhatsApp/stickers/files/2978415/SYEmojies.zip)

**Comment by Ruman1234** [comment]
![newerror](https://user-images.githubusercontent.com/37799754/54535791-1a40bc80-49b1-11e9-8c57-bf4f96f271af.jpeg)

**Comment by Ruman1234** [comment]
<img width="1395" alt="Screenshot 2019-03-18 at 7 08 37 PM" src="https://user-images.githubusercontent.com/37799754/54535857-46f4d400-49b1-11e9-9aeb-4d2c63a8750c.png">

**Comment by Ruman1234** [comment]
> [SYEmojies.zip](https://github.com/WhatsApp/stickers/files/2978415/SYEmojies.zip)

i send you the zip file of my project kindly check it

**Comment by Ruman1234** [comment]
@Zandor300 Please have a look on that

**Comment by Ruman1234** [comment]
@amrit-1901 @ericnakagawa @eakret 
Please have a look on that

> > [SYEmojies.zip](https://github.com/WhatsApp/stickers/files/2978415/SYEmojies.zip)
> 
> i send you the zip file of my project kindly check it

**Comment by Ruman1234** [comment]
@Zandor300 @amrit-1901 @ericnakagawa @eakret 

now whatsapp is show me this error 
![newerror](https://user-images.githubusercontent.com/37799754/54591926-182c3b80-4a4d-11e9-8a29-863ad8c5908b.jpeg)

**Comment by Ruman1234** [comment]
can any one send me code how to make stickerpack array and where to put png images

**Comment by Ruman1234** [comment]
why it takes too long to solve this error

**Comment by Ruman1234** [comment]
can you please solve this issue i have to deliver this app 
kindly
