### ISSUE TITLE
can anyone send me WAStickersThiredParty [iOS]

### ISSUE THREAD

**Issue by Ruman1234** [WhatsApp/stickers#446]
i want this project can anyone send me
this project is not working which i download

**Comment by Zandor300** [comment]
`WAStickersThirdParty` is the sample app for iOS contained in this repository.

Click to download zip of this repository: 
https://github.com/WhatsApp/stickers/archive/master.zip

---

or clone the repository directly onto your desktop by executing in Terminal:

```bash
git clone https://github.com/WhatsApp/stickers.git ~/Desktop/WhatsAppStickers
```

Now look on your desktop and go into the `WhatsAppStickers` folder that was just created. Now open the `WAStickersThirdParty.xcproj` and the project will open.
