### ISSUE TITLE
[Android] How to Load Stickers Packs from firebase?

### ISSUE THREAD

**Issue by darshanpatidar1** [WhatsApp/stickers#449]
**Problem Description**  
How to Load Stickers Packs from firebase?

**Links**
Already I've been through -
https://github.com/idoideas/StickerMaker-for-Whatsapp
https://github.com/viztushar/stickers-internet
#204
#312
#183
#311 
#402

**Comment by simonzhexu** [comment]
Please ask in stackoverflow. We don't support firebase so I cannot help you on that.

**Comment by darshanpatidar1** [comment]
If anyone can help on stackoverflow just follow https://stackoverflow.com/questions/55253064/how-to-load-whatsapp-sticker-from-firebase 
Let it be open if others can help..!

**Comment by Blast06** [comment]
@darshanpatidar1 i have written you an answer to your question on StackOverflow, which was extracted from this post on medium: [Link](https://medium.com/bobble-engineering/dynamic-whatsapp-stickers-part-1-android-2ac00dc57111)

As you can see, there's also a  part two: [Link](https://medium.com/bobble-engineering/how-to-create-dynamic-whatsapp-stickers-part-2-android-b0e3d433984b)

**Comment by simonzhexu** [comment]
Great explanation by @Blast06 . Hope it helps @darshanpatidar1 
.
