### ISSUE TITLE
where to query the sticker using statistic?

### ISSUE THREAD

**Issue by gongzyes** [WhatsApp/stickers#454]
**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
[I want to know where to query each sticker's using statistic? like how many times does stickers send, which sticker pack is popular? ]

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN PLAY STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by simonzhexu** [comment]
We don't support counting how many times a sticker is sent. As to which sticker pack is popular I guess you could add some stats when user click "add sticker pack to WhatsApp" button and record count there. I understand where you are coming from. But we don't have such support at the moment.
