### ISSUE TITLE
[Android] App got removed, dev account closed

### ISSUE THREAD

**Issue by darcknnes** [WhatsApp/stickers#461]
For reasons I do not understand and due to these applications, Google canceled my developer account, I can not say that it was explicitly because of the code, but for something I do not know (regarding applications) Google closed my account, they even threatened me with re-closing it if I create it again, I use ADMOB to put advertising, so I do not know if it was because of the advertising or the applications as such.
Do they have any idea why, if they know why I appreciate the information?
Postscript: I know this is for technical problems, but I have no idea if it was due to technical problems or that, likewise, I do not have anyone else to turn to.
I do'nt speak english, i speak spanish, i used google translate

**Comment by MarvinJWendt** [comment]
Hey @darcknnes,
You probably had "WhatsApp" in the name of your application. This is a common problem, and Google will terminate accounts because of that. It's a copyright infringement.
If you had WhatsApp in the name please take a look here: #150

**Comment by darcknnes** [comment]
I did not make a reference to whatsapp at any time I did so I wrote to them asking for an explanation and the truth is that when it comes to the truth I am a mosco in the soup for Google, the name of my applications were always Stickers (name of) only that, I have no choice but to cry on my own because they do not answer anything, I want to open another but if Google closed it once it does it again for no apparent reason.
Do you have any other ideas? I would appreciate it with pleasure to not make the same mistake in the new account, shit that they close my admob account

**Comment by MarvinJWendt** [comment]
I am sorry @darcknnes, but I don't think that I am able to help you. You can still contact Google. To assist you we would need to know why your account was terminated.

**Comment by darcknnes** [comment]
Of course, obviously, the reason is more important, I'm not asking them to open it again, I think it's more feasible for Google to tell me the reason for the sanction in that way I can help others and prevent others from pass same, but they don't response nothing at all, they closed the account and now, they do not respond to my messages, I do not even know who I should send a message to
![image](https://user-images.githubusercontent.com/31108336/56088445-990d0600-5e46-11e9-95bb-fbe20a7c633b.png)
This is the reason according to them:
![image](https://user-images.githubusercontent.com/31108336/56088466-1cc6f280-5e47-11e9-9ad3-f3a47f4d7017.png)
Associated account?
Sincerely, I remained the same.

**Comment by MarvinJWendt** [comment]
@darcknnes Your app seems to have violated the Google ToS. Please read through that. Every Android developer should make sure that their app is compliant to these rules.

**Comment by darcknnes** [comment]
Can you please help me with a link that shows the correct way to publish this application?
I do not have any privacy policy document and taking into account that the app is from a third party, I do not know either, I understand that it is a lot to ask, but to read all this to just say you must put privacy policies . I wish there was a summary without so much text.
![image](https://user-images.githubusercontent.com/31108336/56157906-4470a480-5f86-11e9-9b00-8d5b75099067.png)
The application is not mine and many already have it published, I think that those people who already have it already know what they add and what not, I am a programmer and although I program in native Android, publishing it is another story, I was guided myself with tutorials, so at in this point I do not know.
Can you provide me with a legality document?
thank you very much and sorry for the inconvenience. u.u

**Comment by MarvinJWendt** [comment]
I am sorry, but I cannot provide you with documents, as it would be my fault then if there is something wrong with them. Although you can google for `Android App Privacy Policy generator`. There should be some good tools. I hope this will help you :)

**Comment by darcknnes** [comment]
Google took it against me, as if it was not enough with the suspension account dev now suspended Google adsense and along with that google Admob, the money I had collected was also lost
What are the bastards of google doing with my account?
You can practically say that I no longer have an account now.
![image](https://user-images.githubusercontent.com/31108336/56386266-ed1d3f00-61e6-11e9-9761-be38a64e7c58.png)
![image](https://user-images.githubusercontent.com/31108336/56386424-52713000-61e7-11e9-8321-a9fff6744831.png)
damn google bitches >:v

**Comment by simonzhexu** [comment]
Sorry, this is happening to you. Please contact Google for resolution.
