### ISSUE TITLE
[Android] The applicationId isn't the line 16 anymore

### ISSUE THREAD

**Issue by juandelacruz23** [WhatsApp/stickers#464]
https://github.com/WhatsApp/stickers/blob/86d38d3da0e1d1204269bb5c9078d6bc277f78cb/Android/app/build.gradle#L57
According to build.gradle, you have to change the applicationId in line 16. I don't know if at any point in time it was at that line, but seems that right now it's at line 10.
Line 10:
https://github.com/WhatsApp/stickers/blob/86d38d3da0e1d1204269bb5c9078d6bc277f78cb/Android/app/build.gradle#L10
Line 16:
https://github.com/WhatsApp/stickers/blob/86d38d3da0e1d1204269bb5c9078d6bc277f78cb/Android/app/build.gradle#L16

**Comment by MarvinJWendt** [comment]
Hi @juandelacruz23,
Yes you're right. If you want, you can change the string to `line 10` and create a pull request.
If you do not want to do it yourself, I am sure that @simonzhexu will update this 👍 

Thanks for your report, have a nice day :)

**Comment by juandelacruz23** [comment]
Already made the pull request @MarvinJWendt, hope it helps :)) nice day for you too!
