### ISSUE TITLE
[Android] How to remove the divider

### ISSUE THREAD

**Issue by danieldhop** [WhatsApp/stickers#467]
I wanted to remove the line that divides the sections how can I do this?

**Comment by Zandor300** [comment]
I suggest you look this up on [StackOverflow](https://stackoverflow.com). There, you're the most likely to receive help with this.

**Comment by viztushar** [comment]
@danieldhop 

```
RecyclerView recycle =(RecyclerView) findViewById(R.id.recyclerView);
recycle.addItemDecoration(new DividerItemDecoration(context, 0));

```
