### ISSUE TITLE
[Android] Stopped Work After Publish

### ISSUE THREAD

**Issue by Darsh23** [WhatsApp/stickers#471]
I was finished my app and it work and tested on mass of devie , but after publish it on google play
and someone download it , it didn't open and som devices get error

**Comment by Zandor300** [comment]
Please provide us with the error your users are getting. Without more details, we can't help you. Do you have error messages, logs, etc. available?

**Comment by Darsh23** [comment]
just when they try to open app that's close again

**Comment by Zandor300** [comment]
Does it spit out error messages when that happens?

**Comment by Darsh23** [comment]
no losed only , but when try with the same apk without google paly it work good on any device

**Comment by Darsh23** [comment]
closed *

**Comment by simonzhexu** [comment]
what is your google play app link, and what device has problem?

**Comment by simonzhexu** [comment]
did you enable app bundle?
