### ISSUE TITLE
1

### ISSUE THREAD

**Issue by firaataydin** [WhatsApp/stickers#472]
**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ ] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
[FILL IN WITH DETAILED DESCRIPTION OF THE PROBLEM]

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN APP STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by firaataydin** [comment]
![48BAE4ED-86DC-4D6F-89D4-694F90F71020](https://user-images.githubusercontent.com/49923930/56613964-818d0480-6620-11e9-86ef-933093b74d85.png)

**Comment by firaataydin** [comment]
![288549FD-958B-4DE3-A39B-E54FFDF7E60D](https://user-images.githubusercontent.com/49923930/56614013-9a95b580-6620-11e9-945c-51b0b3e00088.jpeg)

**Comment by Zandor300** [comment]
Closing since there is no question. If you really did have a question, please open a new issue with proper content.
