### ISSUE TITLE
i cant  open the repo

### ISSUE THREAD

**Issue by kinggorillla** [WhatsApp/stickers#473]
**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
[FILL IN WITH DETAILED DESCRIPTION OF THE PROBLEM]

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN PLAY STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by MarvinJWendt** [comment]
Please describe your problem. From where are you trying to access the repo, etc..?

**Comment by kinggorillla** [comment]
Im sorry, i am new to programing
I managed to open it and everything but i cant open the app on a test run,
ill send theerror messege in the log

בתאריך יום ה׳, 25 באפר׳ 2019, 02:16, מאת MarvinJWendt ‏<
notifications@github.com>:

**Comment by Zandor300** [comment]
Because of the inactivity, I presume you fixed your issue? I'll close for now to clean up, but if the issue isn't fixed feel free to reopen the issue.
