### ISSUE TITLE
How to remove the stickers that already added to whatsapp?

### ISSUE THREAD

**Issue by risaputra** [WhatsApp/stickers#475]
If I have a lot of sticker in my apps that I've made, users will be confuse because there are a lot of stickers.. so If users want to remove specific stickers that already added to whatsapp, how to do it? like there's an option to choose whether to add to whatsapp or remove from whatsapp if the stickers already added
please help..

**Comment by Zandor300** [comment]
This is currently not possible.

**Comment by simonzhexu** [comment]
The only way to remove sticker packs is to go to WhatsApp, and remove stickers from My Stickers. You can tell the user to do so in the app. There is no other way currently.
