### ISSUE TITLE
[Android] When i try to upload apk to play console. it's saying "You Uploaded an APK with Invalid Signature"

### ISSUE THREAD

**Issue by mmmfarhan** [WhatsApp/stickers#476]
**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
[FILL IN WITH DETAILED DESCRIPTION OF THE PROBLEM]

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN PLAY STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by simonzhexu** [comment]
I think you gotta sign the app with v1 and v2 signatures, please try it out.

**Comment by MarvinJWendt** [comment]
It seems like all questions are answered. There hasn't been any recent activity here, so I would say the issue is resolved. If you have any further questions on this Issue don't hesitate to drop a comment and I will reopen the Issue if necessary. 
Have a nice day 😄
