### ISSUE TITLE
[Android] App crashes on Oppo

### ISSUE THREAD

**Issue by jochebedtjq** [WhatsApp/stickers#477]
**Specifications**  
OS Version: Android 5.1
Device Manufacturer: Oppo

**Stickers**
- [X] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [X] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [X] I am using **WebP** images for stickers.

**Problem Description**  
The app works perfectly well with other devices but crashes when opened on Oppo Android 5.1.

The crash reports from Google Console are:

1) Oppo R7sfg (R7sf), Android 5.1
java.lang.UnsatisfiedLinkErrorin
com.facebook.soloader.SoLoader.b

2) Oppo F1f  (Android 5.1)
java.util.concurrent.TimeoutExceptionin
org.codeaurora.Performance.native_deinit

**Links**  
Here's the link to the app:
https://play.google.com/store/apps/details?id=com.akkg.stickerapp

**Comment by MarvinJWendt** [comment]
Hey,
This Issue seems to be inactive. To keep things organized I will close this for now. If this Issue is still relevant, don't hesitate to drop a comment and I will reopen it if necessary.

Sincerely,
Marvin Wendt
