### ISSUE TITLE
[Android] Application closing alone on android 9.0

### ISSUE THREAD

**Issue by luizflb** [WhatsApp/stickers#478]
**Specifications**  
OS Version: 9.0
Device Manufacturer: moto g(6) play 

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
Recently several people have reported that the application is closing, including I put the version of the cell phone that most report it!
I do not know for sure if it is the application that is having problems or the ads that may be causing this, I have Android phone with 9.0 and it works normally, it is a zenfone 5, in android studio also opens normally!

**Links**  
https://play.google.com/store/apps/details?id=com.sticker.pacotaodememes

**Comment by simonzhexu** [comment]
Hi, Could you share additional information? I have a 9.0 and it works. I cannot fix it if I cannot repro it. Stack trace, logs, would be helpful. If you can get hold a user to send you a video and logs, that would be most helpful.

Also, what application is closing? the sticker app or WhatsApp?
