### ISSUE TITLE
[iOS] Webp Framework not usable

### ISSUE THREAD

**Issue by undeaDD** [WhatsApp/stickers#480]
**Specifications**  
OS Version: 12.2
Device Manufacturer: Apple, iPhone XS
Xcode Version: 10.2.1
Swift Version: 4.0 / 4.2 / 5

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ ] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for stickers.

**Problem Description**  
Can not use (correctly linked) WebP Framework ...
Won't work with: **iOS Demo Project** / _own Project with cocoapods installation_ / own _Project with manual installation_

**Error Console Output everytime:**
[-[YYImageEncoder initWithType:]: 2332] WebP is not available, check the documentation to see how to install WebP component: https://github.com/ibireme/YYImage#installation
Skipping bad sticker data

**UIAlert from Whatsapp App:**
"Die Anzahl der Sticker in diesem Set liegt nicht zwischen 3 und 30"

**Reproduction Steps**  
1. Download iOS Demo Project
2. Change Team and bundleID
3. Build and Run on Device
4. Add the Stickerpack to Whatsapp

**Head of Commit**
Latest version from "master" branch
commit hash: "9ec2fb4d4ca41d3970883358759c90df67bb0493"

**Links**  
own Project ( hacked together to test stickers for apps ^^ ):
https://github.com/undeaDD/AlienStickers/tree/master/AlienSticker

iOS Demo App:
no link needed ... its right here ^^

**Comment by Zandor300** [comment]
Have you added the WebP.framework to your project?

**Comment by undeaDD** [comment]
yes obviously (as i mentioned in the first sentence of the problem description )

here is a screenshot of it in my private project:
![Screenshot 2019-05-04 at 20 34 26](https://user-images.githubusercontent.com/8116188/57183355-122ed480-6eac-11e9-84ae-70521ca2d90a.png)

and it was already added / linked in the iOS demo project ;)
which also did not work (same error) ...

**Comment by undeaDD** [comment]
also using other / newer builds does not seem to work:
https://storage.googleapis.com/downloads.webmproject.org/releases/webp/index.html

**Comment by undeaDD** [comment]
nevermind. I solved it myself ...
This issue can be closed ;)

**Comment by maxschneidercodes** [comment]
> nevermind. I solved it myself ...
> This issue can be closed ;)

May i ask you how you solved this issue, i have the same problem here.

**Comment by undeaDD** [comment]
i’ll post a link later when im back home ;)
