### ISSUE TITLE
[Android] Stickers are not displayed on Samsung devices

### ISSUE THREAD

**Issue by Ferdari** [WhatsApp/stickers#485]
**Specifications**  
OS Version: Android 8, 8.1
Device Manufacturer: Samsung

**Stickers**
- [+ ] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [+ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [+ ] I am using **WebP** images for stickers.
- [x ] I am using **PNG** images for stickers.

**Problem Description**  
My app has 2 months published in PlayStore, im getting too much people complaining stickers are not displayed only on samsung devices (few LG K and Q),
i tracked this phone models on my reviews:
Samsung Galaxy S7, S9, S9+, J3, J4, J4+, J5, J6, J8, A4, Grand Prime, Android 8.0 and 8.1, some 6.0, but few.

**Reproduction Steps**  
Push add Stickers to Whatsapp, result was ok, but on Whatsapp nothing happens. no tabs, no stickers.

**Head of Commit**
No commit hash, im not using Android Studio. PLUS i use lastest Android SDK 28

**Links**  
https://play.google.com/store/apps/details?id=stickers.memetflix

**Comment by simonzhexu** [comment]
Samsung has a battery saving mode that prevents the ContentProvider, your user might have that problem. Turning off battery saving mode will get the app back on track.

**Comment by simonzhexu** [comment]
If you can confirm they are not in battery saving mode, please attach some logs.

**Comment by Ferdari** [comment]
Thanks for your response, I will ask them to disable Power Saving Mode and reply back with the results.

________________________________
De: Simon Xu <notifications@github.com>
Enviado: Wednesday, May 15, 2019 7:24:44 PM
Para: WhatsApp/stickers
CC: Ferdari; Author
Asunto: Re: [WhatsApp/stickers] [Android] Stickers are not displayed on Samsung devices (#485)


Samsung has a battery saving mode that prevents the ContentProvider, your user might have that problem. Turning off battery saving mode will get the app back on track.
