### ISSUE TITLE
redsocial1

### ISSUE THREAD

**Issue by xdr1xnx** [WhatsApp/stickers#486]
![stikerRS](https://user-images.githubusercontent.com/50602077/57662090-565c5c00-75b3-11e9-8e64-3d34ab39f99b.png)

**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ ] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for stickers.

**Problem Description**  
[FILL IN WITH DETAILED DESCRIPTION OF THE PROBLEM]

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN APP STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by MarvinJWendt** [comment]
Hey @xdr1xnx, you cannot submit stickers here. This is a bug tracker, where problems with the provided code get reported.
Have a nice day 😄
