### ISSUE TITLE
[Android] Can't load Stickers on WhatsApp once I close the sticker App

### ISSUE THREAD

**Issue by AnuPramod** [WhatsApp/stickers#487]
**Specifications**  
OS Version: [Every OS]
Device Manufacturer: [All the devices]

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
I am loading stickers from web urls and downloading it on my local storage(by creating a folder inside the sticker app). After downloading I take the uris and create the sticker pack then I add it to WhatsApp. Everything went fine, I could send the stickers through WhatsApp. But when I close sticker app from the background, the stickers are disappeared from WhatsApp and I have no idea why this happened. 
Please help...

**Comment by MarvinJWendt** [comment]
Hey @AnuPramod, please make sure that your sticker app is excluded from any energy saving options your phone may have and try it again.
Please leave a quick comment when you tried it with the result :)
