### ISSUE TITLE
Unable to build the whatsapp sticker app

### ISSUE THREAD

**Issue by satyavja** [WhatsApp/stickers#489]
Merging Errors: Error: Attribute provider#com.example.stickerapplication.StickerContentProvider@authorities at AndroidManifest.xml:44:13-62 requires a placeholder substitution but no value for <contentProviderAuthority> is provided. app main manifest (this file), line 43 Error: Validation failed, exiting app main manifest (this file)

**Comment by viztushar** [comment]
@satyavja if you change 'com.example.stickerapplication' to your package then make sure you change everywhere.
