### ISSUE TITLE
Many users are reporting about app crashing,all of them were android 9 users

### ISSUE THREAD

**Issue by hariiprasad** [WhatsApp/stickers#498]

**Comment by hariiprasad** [comment]
total 407 crashes in 3 months. All of them were ClassNotFoundException
at gn.b(com.google.android.gms.dynamite_adsdynamite@17455081@17.4.55
something like this i got in my report. Thank you

**Comment by MarvinJWendt** [comment]
Hey @hariiprasad,
I am sure that someone will look into this soon.
Please be patient :)

**Comment by simonzhexu** [comment]
Sorry, I was on vacation for 2 weeks. I will look into it.

**Comment by hariiprasad** [comment]
@simonzhexu will be waiting Brother!

**Comment by simonzhexu** [comment]
Hi @hariiprasad , I suspect it is the ad component you inserted into your app that is causing the crash. Our sample app doesn't have anything around dynamite or ads.

**Comment by simonzhexu** [comment]
likely ad mob. Please check.

**Comment by hariiprasad** [comment]
hey @simonhexu  thanks for responding . I found this one .

 <uses-library android:name="org.apache.http.legacy" android:required="false" />

I placed this in android manifest file (in application tag) . Seems to be working fine. from last 10 hours no app crashing reports.

**Comment by hariiprasad** [comment]
`` <uses-library android:name="org.apache.http.legacy" android:required="false" />

**Comment by hariiprasad** [comment]
` <uses-library android:name="org.apache.http.legacy" android:required="false" /> `
