### ISSUE TITLE
Sticker are not added in What's App

### ISSUE THREAD

**Issue by RahulPrajapati97** [WhatsApp/stickers#501]
When I was add stickers in what's up, sticker are added but if I remove my sticker app from recent apps stickers are automatically disappear

**Comment by MarvinJWendt** [comment]
Hi @RahulPrajapati97, sorry for the late response.
Please make sure that your sticker app has an exception in your energy-saving options.
Your phone tries to save as much energy, that results in your phone closing the sticker app - WhatsApp cannot communicate with your sticker app then.

**Comment by RahulPrajapati97** [comment]
@MarvinJWendt  Bur I have already turn off battery optimization option from app setting.Still sticker are not appear.

**Comment by MarvinJWendt** [comment]
@RahulPrajapati97 did you follow those steps? https://github.com/WhatsApp/stickers/issues/167#issuecomment-437684615

**Comment by RahulPrajapati97** [comment]
@MarvinJWendt  Yes Sir I have already come out from this steps

**Comment by MarvinJWendt** [comment]
Okay that's strange, I don't know any other case where the energy-options weren't the reason.
Can you please give us more information (Device, Android Version, etc..)

**Comment by RahulPrajapati97** [comment]
I have face this in all android device from 6 to 9 all device I have taken code of sticker from https://github.com/idoideas/StickerMaker-for-Whatsapp this link

**Comment by bhavesh-srashtasoft** [comment]
Yes i am getting same issue

**Comment by simonzhexu** [comment]
what phone do you have?

**Comment by RahulPrajapati97** [comment]
@simonzhexu I have Samsung Galaxy J7 prime But I have check in all the devices it give me same O/P

**Comment by simonzhexu** [comment]
I downloaded your app and was able to see stickers in WhatsApp after adding a pack. I removed your sticker app from recents, and the stickers are still in WhatsApp. I do have plans to cache the stickers in WhatsApp after they are added. If your problem is not happening very often, my suggestion is to wait for my ultimate fix:)

**Comment by RahulPrajapati97** [comment]
@simonzhexu  No you have misunderstanding that's not his app. He gave you example that thus app work properly but our not.

**Comment by simonzhexu** [comment]
I see. well, I have some plans to get cache the stickers, so this problem will be happening way less. Hang on there.

**Comment by MarvinJWendt** [comment]
Sticker caching is now a thing, read more here: https://github.com/WhatsApp/stickers/wiki/Sticker-Updates:-September-30,-2019

Closing this because it is solved now :)
