### ISSUE TITLE
How to read another JSON file for another set of sticker pack list

### ISSUE THREAD

**Issue by ArcherEmiya05** [WhatsApp/stickers#503]
How can I possibly provide more than one JSON asset in `StickerContentProvider.class` `CONTENT_FILE_NAME` so that I could provide more than one set list of sticker pack ?

**Comment by ArcherEmiya05** [comment]
When do `StickerContentProvider` exactly being called? I tried to trace method call starting from `EntryActivity` -> `StickerPackLoader.fetchStickerPacks(context)` and inside I lost to cursors. How can I dynamically change `CONTENT_FILE_NAME ` value so that I could categorize and show a list of sticker pack with my 3 fragments.

**Comment by ArcherEmiya05** [comment]
Done I already get it after a day, I created a new `StickerContentProvider.class`  with different `CONTENT_FILE_NAME` value and register it on Manifest and build app level build.gradle. I went through a lot of modification specially in parameters like in `StickerPackLoader.fetchStickerPacks(Context context, int requestCode)` where my request code value could be from EntryActivity `LoadListAsyncTask` or each fragment also. Thanks this is a very good sample project I do learn a lot of things specially what is a  `ContentProvider` and how to modify `BuildConfig` through gradle.

**Comment by g4-studios** [comment]
Hey ArcherEmiya05, how can I contact you? I need help with this same issue, want to also categorize sticker packs and would really appreciate if you made a tutorial or something like that to do it, or explain it step by step how you did it, please. Best regards.
