### ISSUE TITLE
Sticker Not Appearing

### ISSUE THREAD

**Issue by DevenRathod2** [WhatsApp/stickers#507]
Hello

I just update my Whatsapp Sticker app into new version and after adding sticker on app
Sticker not showing on app not on Emulator or not on my mobile phone i check every thing all perfect also app build without any error so please help me to fix this issue
![screenshot](https://user-images.githubusercontent.com/44080100/59549916-3937f600-8f82-11e9-8a06-e034f191550a.png)

**Comment by MarvinJWendt** [comment]
Hi @DevenRathod2,

Could you please provide the code from your app? And if you debug your app on your phone, do you get any errors in logcat?

**Comment by DevenRathod2** [comment]
Their is no error and also app is not force stoping all working well and can you please tell me which kind of code do you neen i mean mainActivity or other code then i provide you

this is the link of app please check out : http://bit.ly/2Ij5TWs

**Comment by MarvinJWendt** [comment]
The best would be if you could share your project, if you want you can create a repository here on GitHub.
If you do not want to do that you can make a screenshot from your file structure and attach it. The code that you modified and your `contents.json`  (../app/src/main/assets/contents.json) would also be very helpful.

**Comment by DevenRathod2** [comment]
Sure here is the link of my drive where i upload my app source code please check and help me.. 

Link : http://bit.ly/2KFbLfd 

if you need more info i can provide you

Thankyou

**Comment by DevenRathod2** [comment]
Hello Can You Please help me

**Comment by MarvinJWendt** [comment]
Hi @DevenRathod2, your sticker folders do not contain any images. Just the tray icons.

![image](https://user-images.githubusercontent.com/31022056/60759609-477cad80-a028-11e9-8f78-9cec1e998404.png)

(https://drive.google.com/drive/folders/1wmYVI9iE9YgkjYcA34AHgxPwgpic5giI)

**Comment by DevenRathod2** [comment]
Opps sorry for that check this file i properfly upload with sticker : https://drive.google.com/open?id=1P0J4ru6wagfLJwXyh_nod8iFqvkKpKVY

please help fast

Thankyou

**Comment by MarvinJWendt** [comment]
Hey @DevenRathod2, I currently don't have the time to check all of your code. Also, I do not know which files are modified by you. The fastest way to solve this would probably be to set up a new project with the current `master` branch and then copy your `contents.json` and your stickers to that new project. 

You most likely forgot to update something while you were migrating your project.
