### ISSUE TITLE
my app "WAStickerApps" Suspended

### ISSUE THREAD

**Issue by iyad2** [WhatsApp/stickers#508]
i use this code

but I have received an email from Google " your app is Suspended" because

The app uses the trademarks, banners, badges and logos of WhatsApp without authorization.

What do I do to solve this problem ?! 
I sad

**Comment by MarvinJWendt** [comment]
Hey @iyad2,

Did you use the name "WhatsApp" in your apps title? If so: "WhatsApp" is a copyrighted name and you are  not allowed to write it into your apps name/title.

**Comment by iyad2** [comment]
title my app : ملصقات واتساب رومانسية WAStickerApps 

email gogole : trademark_explain: The app uses the trademarks, banners, badges and logos 
of WhatsApp without authorization.

how need authorization for open source code?!

**Comment by MarvinJWendt** [comment]
@iyad2 This is a problem already known here. Sadly it will take it's time to get a solution.
Have you used the name "WhatsApp" anywhere else (for example in the description or tags)?

**Comment by simonzhexu** [comment]
could you get rid of WAStickerApps from the title? Just provide it in the description?

**Comment by darshanpatidar1** [comment]
Hey, @iyad2 
I think the issue is in **Play Store Icon** of your app submitted. You just **keep** **WAStickerApps** in your title but **don't copy whatsapp logo** or you can copy Vector but don't copy as it is.

Just take a look at my app logo and you will get it.
Reference link :- https://play.google.com/store/apps/details?id=com.darshan.sahi60&hl=en_IN

**Comment by 0566055455** [comment]
@simonzhexu Do you know if I could contact someone that could unban my account, I got two app suspensions due to using WhatsApp on my app title.

**Comment by darshanpatidar1** [comment]
> @simonzhexu Do you know if I could contact someone that could unban my account, I got two app suspensions due to using WhatsApp on my app title.

You just need to change stuff in your **Google Play Console** and suspension will be removed after app review by Google

**Comment by simonzhexu** [comment]
Unfortunately, our reach to Google is limited. So I cannot. Sorry.

**Comment by thecodingcaravan** [comment]
Hello All,
i have the same issue, any help please
