### ISSUE TITLE
Problem while upload app to Google play

### ISSUE THREAD

**Issue by juanignacioquev** [WhatsApp/stickers#514]
It show me this
What i have to do to the file?
You have uploaded an APK or Android App Bundle that can be debugged. For security reasons, you must disable debugging in order to publish them on Google Play. See more information about the APK or Android App Bundles debuggable.

You have uploaded an APK or Android App Bundle signed in debug mode, but you must sign them in publication mode. See more information on how to sign files.

**Comment by ar-arvind** [comment]
I think you uploaded the **debug** version of your app, you need to build a **release** version for submission to the Google Play Store. In Android Studio, Click **Build > Generate Signed Bundle/APK**. 

For more information, visit https://developer.android.com/studio/publish/app-signing#sign-apk.

**Comment by juanignacioquev** [comment]
thanks!
