### ISSUE TITLE
App is showing just the coffee cup stickers.

### ISSUE THREAD

**Issue by SArsalanK** [WhatsApp/stickers#517]
App is showing only the "Coffee Cup" stickers. Are there more?

**Comment by ar-arvind** [comment]
Hey @SArsalanK , this is sample app, it has only one sticker pack. You can also add more stickers, for more info refer the below link.

https://github.com/WhatsApp/stickers/blob/master/Android/README.md

**Comment by Zandor300** [comment]
@SArsalanK This is a sample app for developers to distribute their stickers through the App Store and the Play Store. If you aren't a developer, you should go the App Store or Play Store and search for WAStickerApps to download sticker apps with stickers.
