### ISSUE TITLE
[Android] How to solve this crash !

### ISSUE THREAD

**Issue by Rishandudz** [WhatsApp/stickers#522]
![Capture](https://user-images.githubusercontent.com/52799367/61151081-b2cfef00-a502-11e9-80a3-8cdd52ff8764.JPG)

**The crash occurs when someone install the app through the playstore and opening for first time it unfortunately closing. After that there are no crash at all . i tested on various android version and the result was same. please someone give solution**

**Comment by ar-arvind** [comment]
Hi @Rishandudz, If you're using AdMob version `18.0.0`, add these dependencies in your `build.gradle` file to avoid crash on app first launch.

```
com.google.android.gms:play-services-measurement:17.0.0
com.google.android.gms:play-services-measurement-sdk:17.0.0
```

Refer this link
https://developers.google.com/admob/android/rel-notes

**Comment by Rishandudz** [comment]
@ar-arvind  **After adding these some other errors popup. here is the logcaat**

![Capture](https://user-images.githubusercontent.com/52799367/61166136-7625e700-a546-11e9-83bd-b0f52b10273f.JPG)

**Comment by Rishandudz** [comment]
![Capture](https://user-images.githubusercontent.com/52799367/61166716-12a0b700-a550-11e9-8d0b-d663595dc193.JPG)
 
@ar-arvind  Thankyou Added that. but Some other errors

**Comment by ar-arvind** [comment]
@Rishandudz I think these errors occurred due to `AdMob library`, there is no problem with your code. It will not create any issues in the app, you can ignore this.

**Comment by Rishandudz** [comment]
@ar-arvind Thanks
