### ISSUE TITLE
[Android]Error: There's a problem with this sticker pack and it can't be added to WhatsApp

### ISSUE THREAD

**Issue by fionawen96** [WhatsApp/stickers#524]
Hi all,
Sorry to bother, I've published a Wasticker app on Google Play for several months. Most of the users can download the stickers successfully so I think the sticker pack itself is OK. 
However, some devices show the error: "There's a problem with this sticker pack and it can't be added to WhatsApp". This error almost happens on the Samsung devices and users claim that they are using the official version Whatsapp. (Galaxy Grand Prime, J4. From Android 5.1 to Android 9, as far as I know.) 
I've checked the previous issues and it seems there is no solution yet. 
Can anyone help?
Thanks a lot! 

OS Version: Android

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for tray image.

**Comment by DevSensei-ZA** [comment]
I'm also facing the same issue on my upcoming project. Sticker Packs can be added successfully but on some devices they gave error " There's a problem with this sticker pack and it can't be added to WhatsApp" and mostly this issue is happening to devices on OS 5.0 to 7.0

**Comment by DevSensei-ZA** [comment]
#509

**Comment by simonzhexu** [comment]
Thanks guys. I have not been able to track down the problem given it is hard to reproduce. If you guys can help me, by providing exact phone model, app apk, reproducing steps, and WhatsApp version, that will be helpful for me to resolve this issue.

**Comment by DevSensei-ZA** [comment]
@simonzhexu  Thanks for replying the problem is occuring on one of the device listed below

Model: Huawei P9 Lite
OS: 6.0
WhatsApp version: 2.19.159
APK: https://drive.google.com/file/d/1J_B-Mc16FviZFGKCi-m4oJPASjoL1sZa/view?usp=sharing
Reproducing Steps:
Open app and try to add few of the sticker packs some of them will be added successfully while others give error but all of the sticker packs can be added without issue on other devices (OS 8.0 and later) means the issue isn't with sticker packs.

**Comment by DevSensei-ZA** [comment]
List of devices which are giving errors:
1. Huawei p9 lite
2. Huawei Mate S
3. LG X5

List of devices which on which sticker packs can be added successfully:
1. Samsung Galaxy C9 Pro
2. Huawei Nexus 6P

**Comment by fionawen96** [comment]
Hi @simonzhexu,
Thanks for your reply. 
Below is the device list in my case: 
1. Samsung Galaxy J4+ (j4primelte) (Android 9)
2. Samsung Galaxy Grand Prime (Android 5.1)

APK: https://drive.google.com/file/d/15Al7GMkqXHnWNvmZGc-5SIrNQ4eIRU5v/view?usp=sharing

Sorry I am not able to get the Whatsapp version since I can't reach the users.
Thanks again for your great help

**Comment by DevSensei-ZA** [comment]
@simonzhexu any news?

**Comment by DevSensei-ZA** [comment]
@simonzhexu  Though you didn't replied but now I figured out the actual problem and it's now solved, Anyway thank you.

**Comment by fionawen96** [comment]
@DevSensei-ZA
Could you share the solution with me? 
Thank you

**Comment by DevSensei-ZA** [comment]
@fionawen96  In my case the problem was with Tray Icon and Sticker images names, there was space ( ) in names of tray icon and sticker images (For example: "tray_icon sticker1.png" or "love sticker1.webp"). It'll be best practice if you also don't use special characters in images names. I hope this'll also solves your problem.

**Comment by fionawen96** [comment]
@DevSensei-ZA
Hi, thanks for your reply.
I named all the tray icon as : tray.png
So I think my problem is different with yours.
Even the same stickers pack, most users can download it but some are not...😢
Thanks for your reply again!

**Comment by DevSensei-ZA** [comment]
@fionawen96 Let me check,  I requested file access please grant it.

**Comment by fionawen96** [comment]
@DevSensei-ZA
Thank you, 
It is allowed, please let me know if there is any questions 😊

**Comment by iLyxa3D** [comment]
How to debug this problem? 
I do not see any error messages in android console (from com.whatsapp and my app logs) or react-native console ("success" log only).

**Comment by prabhashibuddhima** [comment]
hi, have you guys solved this issue? can you please help me with it?

**Comment by mr94valerio** [comment]
Still having issue news?

**Comment by krunalOrigin** [comment]
> @fionawen96 In my case the problem was with Tray Icon and Sticker images names, there was space ( ) in names of tray icon and sticker images (For example: "tray_icon sticker1.png" or "love sticker1.webp"). It'll be best practice if you also don't use special characters in images names. I hope this'll also solves your problem.


I have to create my custom sticker pack. this is my custom sticker pack data but when i have to add it in whatapp then 
getting "There's a problem with this sticker pack and it can't be added to WhatsApp" error can you solve it?
{
  "android_play_store_link": "",
  "ios_app_store_link": "",
  "sticker_packs": [
    {
      "avoid_cache": false,
      "identifier": "temp",
      "image_data_version": "100",
      "license_agreement_website": "",
      "name": "Temp",
      "privacy_policy_website": "",
      "publisher": "Origin",
      "publisher_email": "",
      "publisher_website": "",
      "stickers": [
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_0.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_1.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_2.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_3.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_4.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_5.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_6.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_7.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_8.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_9.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_10.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_11.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_12.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_13.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "temp_14.webp"
        }
      ],
      "tray_image_file": "temp.webp"
    },
    {
      "avoid_cache": false,
      "identifier": "emoji",
      "image_data_version": "101",
      "license_agreement_website": "",
      "name": "Emoji",
      "privacy_policy_website": "",
      "publisher": "Origin",
      "publisher_email": "",
      "publisher_website": "",
      "stickers": [
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "emoji_0.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "emoji_1.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "emoji_2.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "emoji_3.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "emoji_4.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "emoji_5.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "emoji_6.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "emoji_7.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "emoji_8.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "emoji_9.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "emoji_10.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "emoji_11.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "emoji_12.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "emoji_13.webp"
        },
        {
          "emojis": [
            "☕",
            "🙂"
          ],
          "image_file": "emoji_14.webp"
        }
      ],
      "tray_image_file": "emoji.webp"
    }
  ]
}

**Comment by mkarcher98** [comment]
add android:readPermission="com.whatsapp.sticker.READ" to your provider at manifest and add :
aaptOptions { noCompress "webp" } under `android` tag
to your build.gradle file then rebuild

**Comment by jonex41** [comment]
i am having same issues, i could add static stickers, but could not add animated stickers, please help
