### ISSUE TITLE
[iOS] The numebr of sticker in this pack isn't between 3 and 30.

### ISSUE THREAD

**Issue by surbhivarma90** [WhatsApp/stickers#532]
I Can't access the sticker in my app i am always facing one alert message which is **(The numebr of sticker in this pack isn't . between 3 and 30)**
please help me out

**Comment by Zandor300** [comment]
As the message states, you have to have at least 3 stickers in each pack and no more than 30. Can you post your sticker app config so we can help you debug your issue?

**Comment by surbhivarma90** [comment]
> As the message states, you have to have at least 3 stickers in each pack and no more than 30. Can you post your sticker app config so we can help you debug your issue?

"stickers": [
            {
                "image_file": "hello.png",
                "emojis": ["👍","😁"]
            },
            {
                "image_file": "good-morning.png",
                "emojis": ["😎","😁"]
            },
            {
                "image_file": "waah.png",
                "emojis": ["👍","😁"]
            },
        ]
i set this type of sticker

**Comment by Zandor300** [comment]
Below the waah.png you have an extra comma. Your config should be:
```json
        "stickers": [
            {
                "image_file": "hello.png",
                "emojis": ["👍","😁"]
            },
            {
                "image_file": "good-morning.png",
                "emojis": ["😎","😁"]
            },
            {
                "image_file": "waah.png",
                "emojis": ["👍","😁"]
            }
        ]
```
