### ISSUE TITLE
[Android] Stickers not loading in latest WhatsApp version

### ISSUE THREAD

**Issue by ar1808** [WhatsApp/stickers#534]
Stickers not loading in latest WhatsApp Beta version (2.19.213). It works in previous release 2.19.211. default WhatsApp stickers itself not loading.

**Comment by MarvinJWendt** [comment]
Hey @ar1808, I cannot replicate your issue (as I have `2.19.215`) installed. Which device are you using? And which Android version? 

Is the update to `2.19.215` available for you?

**Comment by ar1808** [comment]
@MarvinJWendt I have updated the app 2.19.215 just now and this issue is resolved. 

Thanks.
