### ISSUE TITLE
In Whatsapp stickers doesnt have image and details

### ISSUE THREAD

**Issue by suleymankoparir** [WhatsApp/stickers#535]
Specifications
OS Version: Android 8
Device Manufacturer: Huawei P9 lite and Asus Zenfone 3
Whatsapp Version: 2.19.203

I have fulfilled all requirements for stickers but stickers doesnt show up in whatsapp. Some stickers doesnt have images in whatsapp but all stickers doesnt have details. Only Cuppy work fine.
link: https://github.com/suleymankoparir/MassivePack
Screenshots:
https://drive.google.com/file/d/1wkzflPn-fU5ubpqDxBMwZ8cOhph0jSky/view?usp=sharing
https://drive.google.com/open?id=1zXTt5D6X3Sj6mguEoeGfYcNqKEZ1LiIo

**Comment by Zandor300** [comment]
Can you provide us with your sticker config?

**Comment by suleymankoparir** [comment]
{
  "android_play_store_link": "",
  "ios_app_store_link": "",
  "sticker_packs": [
    {
      "identifier": "1",
      "name": "Cuppy",
      "publisher": "Jane Doe",
      "tray_image_file": "tray_Cuppy.png",
      "publisher_email":"",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",
      "stickers": [
        {
          "image_file": "01_Cuppy_smile.webp",
          "emojis": ["☕","🙂"]
        },
        {
          "image_file": "02_Cuppy_lol.webp",
          "emojis": ["😄","😀"]
        },
        {
          "image_file": "03_Cuppy_rofl.webp",
          "emojis": ["😆","😂"]
        },
        {
          "image_file": "04_Cuppy_sad.webp",
          "emojis": ["😩","😰"]
        },
        {
          "image_file": "05_Cuppy_cry.webp",
          "emojis": ["😭","💧"]
        },
        {
          "image_file": "06_Cuppy_love.webp",
          "emojis": ["😍","♥"]
        },
        {
          "image_file": "07_Cuppy_hate.webp",
          "emojis": ["💔","👎"]
        },
        {
          "image_file": "08_Cuppy_lovewithmug.webp",
          "emojis": ["😍","💑"]
        },
        {
          "image_file": "09_Cuppy_lovewithcookie.webp",
          "emojis": ["😘","🍪"]
        },
        {
          "image_file": "10_Cuppy_hmm.webp",
          "emojis": ["🤔","😐"]
        },
        {
          "image_file": "11_Cuppy_upset.webp",
          "emojis": ["😱","😵"]
        },
        {
          "image_file": "12_Cuppy_angry.webp",
          "emojis": ["😡","😠"]
        },
        {
          "image_file": "13_Cuppy_curious.webp",
          "emojis": ["❓","🤔"]
        },
        {
          "image_file": "14_Cuppy_weird.webp",
          "emojis": ["🌈","😜"]
        },
        {
          "image_file": "15_Cuppy_bluescreen.webp",
          "emojis": ["💻","😩"]
        },
        {
          "image_file": "16_Cuppy_angry.webp",
          "emojis": ["😡","😤"]
        },
        {
          "image_file": "17_Cuppy_tired.webp",
          "emojis": ["😩","😨"]
        },
        {
          "image_file": "18_Cuppy_workhard.webp",
          "emojis": ["💻","🌃"]
        },
        {
          "image_file": "19_Cuppy_shine.webp",
          "emojis": ["🎉","✨"]
        },
        {
          "image_file": "20_Cuppy_disgusting.webp",
          "emojis": ["🤮","👎"]
        },
        {
          "image_file": "21_Cuppy_hi.webp",
          "emojis": ["🖐","🙋"]
        },
        {
          "image_file": "22_Cuppy_bye.webp",
          "emojis": ["🖐","👋"]
        },
        {
          "image_file": "23_Cuppy_greentea.webp",
          "emojis": ["🍵","😌"]
        },
        {
          "image_file": "24_Cuppy_phone.webp",
          "emojis": ["📱","😦"]
        },
        {
          "image_file": "25_Cuppy_battery.webp",
          "emojis": ["🔋","😵"]
        }
      ]
    },
    {
      "identifier": "2",
      "name": "Lord Pepe",
      "publisher": "Massive Pack",
      "tray_image_file": "tray_pepe.png",
      "publisher_email":"contact@suleymankoparir.com",
      "publisher_website": "http://www.suleymankoparir.com",
      "privacy_policy_website": "",
      "license_agreement_website": "",
      "stickers": [
        {
          "image_file": "01_Pepe_one.webp"
        },
        {
          "image_file": "02_Pepe_two.webp"
        },
        {
          "image_file": "03_Pepe_three.webp"
        },
        {
          "image_file": "04_Pepe_four.webp"
        },
        {
          "image_file": "05_Pepe_five.webp"
        },
        {
          "image_file": "06_Pepe_six.webp"
        },
        {
          "image_file": "07_Pepe_seven.webp"
        },
        {
          "image_file": "08_Pepe_eight.webp"
        },
        {
          "image_file": "09_Pepe_nine.webp"
        },
        {
          "image_file": "10_Pepe_ten.webp"
        }
      ]
    }
  ]
}

**Comment by suleymankoparir** [comment]
I solved the problem. I think the pictures were wrongly converted. Problem solved when converting images again.
