### ISSUE TITLE
Stickers not working with WhatsApp Business [iOS]

### ISSUE THREAD

**Issue by c42sx** [WhatsApp/stickers#539]
**Specifications**  
OS Version: [12]
Device Manufacturer: [apple]

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.

**Problem Description**  
Recently I started receiving emails from my users complaining that the app is not working with WhatsApp business, is there a specific URL to whatsapp business? Some users have both Whatsapp and Whatsapp business installed and some users only have the Whatsapp business installed.

**Reproduction Steps**  
Tap the send sticker button and the iOS takes the user directly to the normal Whatsapp.

**Head of Commit**
ec019e19a0e11f2c1a4e68eac74989c18d04ea63

**Links**  
AppStore link: https://apps.apple.com/us/app/top-stickers-maker-memes-funny/id938243056

**Comment by Zandor300** [comment]
On my iPhone, I have WhatsApp aswell as WA Business installed. When I click the button to add to WhatsApp, it opens WA Business first, but within WA Business, I have the option to forward it to WhatsApp. The sticker app I tried this with is a private fork of this repo and hasn't been modified except for the sticker config.

WA Business should use the same `whatsapp://stickerPack` URL I believe. Maybe @amrit-1901 can confirm this?

**Comment by amrit-1901** [comment]
Yes what @Zandor300 says is correct: both the consumer and business versions of WhatsApp share the same URL. However, we don't get to decide which one to open as that is decided by iOS is a random fashion. There should also be an option to switch between the two apps.

**Comment by Zandor300** [comment]
Closing this for now. If the issue still exists, feel free to reopen the issue.
