### ISSUE TITLE
No animated sticker support at the moment

### ISSUE THREAD

**Issue by maplexmovie** [WhatsApp/stickers#542]
Hey guys,
When are you planning to support animated WebP (your competitors already did that and are way ahead.. why are you sleeping over there in WhatsApp?)
Also nothing has changed with stickers and it seem like this feature was created in 2012 instead of 2019..

Thanks.

**Comment by MarvinJWendt** [comment]
As far as I know, WhatsApp employees are not allowed to talk about future features.
![image](https://user-images.githubusercontent.com/31022056/63696211-7fc78d80-c81a-11e9-97c2-ec0bd0975e4e.png)

**Comment by simonzhexu** [comment]
Thanks for the nudge. We added stickers into doodles, published new sticker packs. So we are moving. In regards to animated stickers, I cannot talk about it, sorry:)
