### ISSUE TITLE
[Android] There's a problem with this sticker pack and it can't be added to WhatsApp

### ISSUE THREAD

**Issue by angkukuehgirlsg** [WhatsApp/stickers#551]
I've published a WhatsApp sticker app with several sticker packs. However, only the latest sticker pack gives the error of "**There's a problem with this sticker pack and it can't be added to WhatsApp**" for some users. Other users are able to download the same sticker pack with no problem.

So far, the error showed on Samsung 7.

Have tried updating and also deleting+reinstalling the sticker app but the error still exists.

Appreciate any help please! Thank you!

Here's the sticker app:
https://play.google.com/store/apps/details?id=com.akkg.stickerapp

- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [X] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [X] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

![screenshot](https://user-images.githubusercontent.com/55232960/64769581-1e275300-d57e-11e9-8e6f-65669c562fb3.jpeg)

**Comment by angkukuehgirlsg** [comment]
I’m using .webp for stickers and .png for tray icon.

**Comment by simonzhexu** [comment]
Are you able to reproduce the problem yourself?

**Comment by simonzhexu** [comment]
@angkukuehgirlsg

**Comment by angkukuehgirlsg** [comment]
Hi @simonzhexu, I'm unable to reproduce the error myself. I'm able to add the sticker pack on my phone but my customers have been coming back with the same error message.

**Comment by simonzhexu** [comment]
@angkukuehgirlsg, have your customer send logs to WhatsApp team via the Contact us in settings, and mention Simon Xu.

**Comment by simonzhexu** [comment]
The information currently provided is not sufficient to debug.

**Comment by rehanullahgithub** [comment]
I have the same error but i am fetching custom stickers from internal storage

**Comment by prakash1307** [comment]
> I have the same error but i am fetching custom stickers from internal storage

@rehanullahgithub Did you solve the issue?. If yes, please help me to fix.

**Comment by rehanullahgithub** [comment]
> > I have the same error but i am fetching custom stickers from internal storage
> 
> @rehanullahgithub Did you solve the issue?. If yes, please help me to fix.

Yes, I fixed this issue.
Send me your email I will send you

**Comment by Dwite** [comment]
> > > I have the same error but i am fetching custom stickers from internal storage
> > 
> > 
> > @rehanullahgithub Did you solve the issue?. If yes, please help me to fix.
> 
> Yes, I fixed this issue.
> Send me your email I will send you

I'm also curious in it, could you please share the details as a gist or to email dwite.lol@gmail.com

**Comment by prakash1307** [comment]
> > > I have the same error but i am fetching custom stickers from internal storage
> > 
> > 
> > @rehanullahgithub Did you solve the issue?. If yes, please help me to fix.
> 
> Yes, I fixed this issue.
> Send me your email I will send you

@rehanullahgithub Please share the details to email prakashsai179@gmail.com

Thanks in advance

**Comment by bryantee84** [comment]
@rehanullahgithub would you be able to send the the solutions? I am facing the same issues as well. 

bryantee@omni-machinery.com

**Comment by abkoradiya** [comment]
Hey @rehanullahgithub share solution.

**Comment by pratik-tech4** [comment]
@rehanullahgithub  hi, i am also facing same issue. In my case getting stickers from server. And these are animated stickers. So this issue "There's a problem with this sticker pack and it can't be added to WhatsApp" I'm facing only for animated stickers, normal stickers are working.

if you have any solution, please share it here or at pratik@ngendevtech.com

Thanks!

**Comment by jonex41** [comment]
> > > I have the same error but i am fetching custom stickers from internal storage
> > 
> > 
> > @rehanullahgithub Did you solve the issue?. If yes, please help me to fix.
> 
> Yes, I fixed this issue.
> Send me your email I will send you

please i will appreciate also agudajohn4@gmail.com

**Comment by TrinhBX** [comment]
> 

@rehanullahgithub hi, i am also facing same issue.
Please share the details to email [trinhbx196@gmail.com](mailto:trinhbx196@gmail.com)

Thanks in advance

**Comment by Danjo420** [comment]
> > > Ich habe den gleichen Fehler, aber ich hole benutzerdefinierte Aufkleber aus dem internen Speicher
> > 
> > 
> > @rehanullahgithubHaben Sie das Problem gelöst?. Wenn ja, helfen Sie mir bitte zu beheben.
> 
> Ja, ich habe dieses Problem behoben. Senden Sie mir Ihre E-Mail, die ich Ihnen senden werde

Please send solution
schalkerdanny@gmail.com
