### ISSUE TITLE
simonzhexu need urgent help

### ISSUE THREAD

**Issue by homyo9** [WhatsApp/stickers#554]
Hey @simonzhexu ,

I've an urgent work with you regarding WhatsApp trademark, how can I contact you privately? drop your personal email or any other contact information, thanks.

**Comment by MarvinJWendt** [comment]
As the readme states: 
> For support, please contact developer@support.whatsapp.com

Maybe try it there first? :)

**Comment by simonzhexu** [comment]
Hi @homyo9 , please reach out to developer@support.whatsapp.com. or list your issues here. I normally do not share my email to public. Thanks.
