### ISSUE TITLE
iOS Build - A Ton of Error Messages

### ISSUE THREAD

**Issue by pagegracie** [WhatsApp/stickers#56]
I have used the sample app for iOS to build my WhatsApp sticker pack in XCode. I followed the steps located in [this tutorial](https://github.com/WhatsApp/stickers/tree/master/iOS).

Once I completed all steps in the tutorial, I attempted to build and run on a simulator iPhone 7 Plus.

I have been met with a plethora of error messages, few (none...) of which pertain to the images I uploaded or any of the data I changed myself.

![screen shot 2018-10-29 at 13 58 16 1](https://user-images.githubusercontent.com/44575975/47655416-e5100b00-db84-11e8-853c-4cd52d5a2648.png)

As an example of a bundle of errors. This was rectified by re-writing the string. Easy enough.

However, having fixed an initial 7 bugs, I am now faced with 21 new error messages on my attempted build-and-run that pertain to all sorts in the Swift code and UI code that goes way beyond my competencies. See below for a screen grab of the 21 errors I am currently looking at:

![screen shot 2018-10-29 at 14 15 42](https://user-images.githubusercontent.com/44575975/47655573-2b656a00-db85-11e8-91d7-17dae2d21057.png)

As you can see, it's things like UINavigationItems not having the members that are defined in the code.

Plus:

![screen shot 2018-10-29 at 14 18 16](https://user-images.githubusercontent.com/44575975/47655702-8008e500-db85-11e8-942b-d1ec85e66819.png)

Binary operators can not be applied to certain operands as per the above screenshot.

How do I fix all this? Can anyone help?

Thank you.

**Comment by firstangel999** [comment]
you use xcode 10?

**Comment by pagegracie** [comment]
No, XCode 8.3.3

**Comment by firstangel999** [comment]
Update Xcode to version 10 :)

**Comment by pagegracie** [comment]
If it's as simple as this I will be the biggest, and most grateful, fool. Will report back!

**Comment by firstangel999** [comment]
When you update xcode, re-download the project from github (for a clean version). Xcode will give only two yellow warning...don't worry for them now. ;)

**Comment by amrit-1901** [comment]
@pagegracie Please close this issue if it has been solved
