### ISSUE TITLE
BigPig&SmallPig

### ISSUE THREAD

**Issue by small10pig** [WhatsApp/stickers#561]
**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ ] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for stickers.

**Problem Description**  
[FILL IN WITH DETAILED DESCRIPTION OF THE PROBLEM]

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN PLAY STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by small10pig** [comment]
![p01](https://user-images.githubusercontent.com/56989438/67551881-77b59c80-f73c-11e9-9926-fd38d7052257.png)
![p02](https://user-images.githubusercontent.com/56989438/67551882-77b59c80-f73c-11e9-83d6-f474b320272e.png)
![b01](https://user-images.githubusercontent.com/56989438/67551862-74baac00-f73c-11e9-9c02-8eafd9944a83.png)
![b02](https://user-images.githubusercontent.com/56989438/67551863-74baac00-f73c-11e9-9e84-90dca855fddd.png)
![b03](https://user-images.githubusercontent.com/56989438/67551865-75534280-f73c-11e9-9fca-f8bb7d055947.png)
![b04](https://user-images.githubusercontent.com/56989438/67551867-75534280-f73c-11e9-9eda-57ae006f7c34.png)
![b05](https://user-images.githubusercontent.com/56989438/67551869-75534280-f73c-11e9-9b5b-32357b7e21e9.png)
![b06](https://user-images.githubusercontent.com/56989438/67551870-75534280-f73c-11e9-9e09-acc612945c63.png)
![b07](https://user-images.githubusercontent.com/56989438/67551871-75ebd900-f73c-11e9-8b0f-9a49febca90f.png)
![b08](https://user-images.githubusercontent.com/56989438/67551873-75ebd900-f73c-11e9-9a4c-f9eadc740cd8.png)
![b09](https://user-images.githubusercontent.com/56989438/67551874-75ebd900-f73c-11e9-9701-9974048c76c4.png)
![b10](https://user-images.githubusercontent.com/56989438/67551875-76846f80-f73c-11e9-8aaf-e4fef7d431a5.png)
![b11](https://user-images.githubusercontent.com/56989438/67551876-76846f80-f73c-11e9-8dba-08c55ea07a2f.png)
![b12](https://user-images.githubusercontent.com/56989438/67551877-76846f80-f73c-11e9-95fc-1a212f53000b.png)
![b13](https://user-images.githubusercontent.com/56989438/67551878-771d0600-f73c-11e9-85ee-85f12bef0d96.png)
![s01](https://user-images.githubusercontent.com/56989438/67551883-77b59c80-f73c-11e9-94f8-e396b36ec8c6.png)
![s02](https://user-images.githubusercontent.com/56989438/67551885-784e3300-f73c-11e9-8a39-1acf6294263e.png)
![s03](https://user-images.githubusercontent.com/56989438/67551887-784e3300-f73c-11e9-9198-b0400b703c3a.png)
![s04](https://user-images.githubusercontent.com/56989438/67551888-784e3300-f73c-11e9-9611-6618f6be8822.png)
![s05](https://user-images.githubusercontent.com/56989438/67551889-78e6c980-f73c-11e9-9926-1f1c8306b83c.png)
![s06](https://user-images.githubusercontent.com/56989438/67551890-78e6c980-f73c-11e9-9f1a-f1d90eed3859.png)
![s07](https://user-images.githubusercontent.com/56989438/67551892-78e6c980-f73c-11e9-97a4-bc926986dc8a.png)
![s08](https://user-images.githubusercontent.com/56989438/67551893-78e6c980-f73c-11e9-813f-a66979c0324b.png)
![s09](https://user-images.githubusercontent.com/56989438/67551894-797f6000-f73c-11e9-94d5-7b33fc81870b.png)
![s10](https://user-images.githubusercontent.com/56989438/67551895-797f6000-f73c-11e9-8cd9-eddec2df62cd.png)
![s11](https://user-images.githubusercontent.com/56989438/67551896-797f6000-f73c-11e9-995a-655022f9389d.png)
![s12](https://user-images.githubusercontent.com/56989438/67551897-7a17f680-f73c-11e9-802a-91b2946d2531.png)
![s13](https://user-images.githubusercontent.com/56989438/67551898-7a17f680-f73c-11e9-9179-08788a59a1a6.png)
![h01](https://user-images.githubusercontent.com/56989438/67551879-771d0600-f73c-11e9-9c5d-20caea4744cc.png)
![h02](https://user-images.githubusercontent.com/56989438/67551880-771d0600-f73c-11e9-9a74-5c2172d19504.png)

**Comment by MarvinJWendt** [comment]
Hi, you have created an empty issue<sup>1</sup> in the bug-tracker of this repository<sup>2</sup>. 

The `Issue` tab of repositories on [GitHub](https://github.com) is meant to report problems with the repository or to discuss features of the project. If you have an actual issue with the repository, please [open a new issue](../issues/new) with a decent description.

Have fun exploring this repository 🎉 

<sub>If you want to know more about how to write good issues, look here: https://guides.github.com/features/issues/</sub>

---

<sup>1: Issue ⇾ Bug Report / Feature Request / etc..</sup>
<sup>2: Repository ⇾ Project</sup>
