### ISSUE TITLE
[Android] When I installed both type(Business / Original) of Whats apps, Exported Sticker is not working on chat box

### ISSUE THREAD

**Issue by kiyoung-Lee** [WhatsApp/stickers#565]
**My condition**
**Step1:** Only Whats App(Original) installed, download sample app & export cuppy sticker working well on my chatbox.

**Step2:** I was Installed new Whats App(Business) and log in with my same phone number(Whats app original is automatically log out), export cuppy sticker by sample app in the same way(Export Sticker is success & add on my sticker list also success). 
But When I using on my chatbox cuppy sticker is not working on Whats app(Business) with "Finding media file is failed" Error message.

**Step3:** So I come back Whats App(Original), I log in again the same number, Suddenly cuppy sticker is also not working at Whats App(Original).

**Step4:** I uninstalled both of Whats App(Original / Business) and reinstall only Whats App(Original) and login again. But the problem is not fixed. I can't use cuppy sticker forever on this phone.
But I installed only Whats App(Original) on other device, Login same phone number(before I said) cuppy sticker is working. After that I Installed Whats App(Business) this phone. This phone is also get a same problem.

**Additional:** I develope making sticker app for Whats app, Custom Sticker by my app is same. When only What's app(Original) installed, working well. But When I installed Whats App(Business), 
Custom Sticker is not working also same as likes sample app.

How do I solve the problem?

**Comment by MarvinJWendt** [comment]
Could you please give us the following information:
- Mobile Phone Model
- Android Version
- WhatsApp (Original) Version
- WhatsApp (Business) Version

> I uninstalled both of Whats App(Original / Business) and reinstall only Whats App(Original) and login again. But the problem is not fixed.

To get a *fresh* WhatsApp you should also clear the Cache of your phone after you have uninstalled WhatsApp.

Thank you for reporting!

**Comment by kiyoung-Lee** [comment]
I found the problem!

The Problem is getting permission with access storage. 
If I installed the first Whats App, showing question popup to backup latest data,
I use the custom sticker after I clicked 'later' button on that popup window.
The problem is occurring in every device.
So I check the settings at Whats app, access storage permission is off.
Then I turn on the permission by my self, It's working!

So I think you should check storage access permission. Before customers using the custom sticker.

Thank you.

**Comment by MarvinJWendt** [comment]
Hi @kiyoung-Lee, were you ever asked for storage permissions?

/cc @simonzhexu maybe there really should be a check if the storage permission is given, if the user want's to use a sticker? Otherwise, the Error message `Finding media file is failed` would display.

Thanks again for reporting 😄

**Comment by kiyoung-Lee** [comment]
Hi. @MarvinJWendt 

Yes, but only if I click the "OK" button on the 'latest data back up pop up window', Whats app asked me storage permission.

If I click the "Later" button Whats app doesn't ask me permission. 

Thanks!

**Comment by simonzhexu** [comment]
Yes, I will fix it. Thank you! Good bug!

**Comment by simonzhexu** [comment]
Issue has been fixed in WhatsApp. It will prompt user to give storage permission if WhatsApp doesn't have that permission. The fix will ship according to our normal release process.
