### ISSUE TITLE
[Android] User can't insert sticker. Sorry this mediafile doesn't exist on your internal storage

### ISSUE THREAD

**Issue by peterdk** [WhatsApp/stickers#568]
**Specifications**  
OS Version: 9
Device Manufacturer: Samsung S8

**Stickers**
- [X] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [X] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [X] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
User can succesfully add stickers to Whatsapp. They show up there, but when inserting one in chat, they get a empty sticker with a 'retry' button for downloading. If clicking on it, the user gets error: Sorry this mediafile doesn't exist on your internal storage. 
The user does not use a SD card. 
This only happens with a single user, I have 1500+ users who have no issues.

**Reproduction Steps**  
Can't reproduce locally

**Head of Commit**
013d921b049e3260e9c1fbb1adfc57c0a033d5eb

**Comment by ar-arvind** [comment]
Hi @peterdk, is your app allows users to convert the photos from their gallery to stickers? Could you please share your app link here?

**Comment by peterdk** [comment]
@ar-arvind sure. http://play.google.com/store/apps/details?id=com.fowllanguagecomics.stickers.android 

The app contains 2 sticker packs, no dynamic generation or whatsoever. WhatsApp part of the app is based on this repo's example. (not the UI).

**Comment by peterdk** [comment]
User reported back that it somehow magically works now. So I think this can be closed.

**Comment by MarvinJWendt** [comment]
Good to hear @peterdk 😄
