### ISSUE TITLE
[Android] Tray icon doesn't get updated to new version

### ISSUE THREAD

**Issue by BattleShipPark** [WhatsApp/stickers#572]
I exported a pack to WA, and updated only tray icon, and exported it again to WA, but the tray icon in WA is not changed.
Is it a bug or specification?

Thanks.

**Comment by simonzhexu** [comment]
Please see: https://github.com/WhatsApp/stickers/issues/560

**Comment by simonzhexu** [comment]
WhatsApp was recently updated to cache tray icons, if your tray icon doesn't update, it means you need to update your app to support image_data_version and upgrade it when any sticker or tray icon changes in your pack.

**Comment by BattleShipPark** [comment]
understood. thanks.
