### ISSUE TITLE
[Android] Add detailed error message

### ISSUE THREAD

**Issue by BattleShipPark** [WhatsApp/stickers#573]
Hi,
If I have a error when adding a pack to WA, I don't have enough information to debug. You just show dialog without any hint.
Especially here is onActivityResult():
```java
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);
    if (requestCode == ADD_PACK) {
        if (resultCode == Activity.RESULT_CANCELED) {
            if (data != null) {
                final String validationError = data.getStringExtra("validation_error");
                if (validationError != null) {
                    if (BuildConfig.DEBUG) {
                        //validation error should be shown to developer only, not users.
                        MessageDialogFragment.newInstance(R.string.title_validation_error, validationError).show(getSupportFragmentManager(), "validation error");
                    }
                    Log.e(TAG, "Validation failed:" + validationError);
                }
            } else {
                new StickerPackNotAddedMessageFragment().show(getSupportFragmentManager(), "sticker_pack_not_added");
            }
        }
    }
}
```
If Intent data is null, that's all. I can't do anything.
Please tell me what the problem is with onActivityResult(), not returning null data.

Thanks.

**Comment by simonzhexu** [comment]
Two things to try:
1. make sure you use debug version of your sticker app
2. make sure that your WhatsApp is the latest version.

The error should be returned if you have the above two requirement met.

**Comment by BattleShipPark** [comment]
I realized that data is null when user cancelled to add a pack to whatsapp. It is a natural action in startActivityForResult/onActivityResult.
thanks.
