### ISSUE TITLE
TAMO DEPORTISTA - COLEGIOS EL VALLE

### ISSUE THREAD

**Issue by MuchoKras** [WhatsApp/stickers#578]
![Mesa de trabajo 1-8](https://user-images.githubusercontent.com/57755629/69899381-80197c80-1365-11ea-804c-89bcaa2e33e4.png)
![2Mesa de trabajo 1-8](https://user-images.githubusercontent.com/57755629/69899382-80197c80-1365-11ea-8faa-6184dddb03a5.png)
![3Mesa de trabajo 1-8](https://user-images.githubusercontent.com/57755629/69899383-80b21300-1365-11ea-9e4e-9d754d2c831a.png)
![4Mesa de trabajo 1-8](https://user-images.githubusercontent.com/57755629/69899384-80b21300-1365-11ea-8eee-e43ce0058f7a.png)
![5Mesa de trabajo 1-8](https://user-images.githubusercontent.com/57755629/69899385-80b21300-1365-11ea-8683-7924791eddea.png)
![6Mesa de trabajo 1-8](https://user-images.githubusercontent.com/57755629/69899386-814aa980-1365-11ea-8816-dd3de72df21f.png)
![7Mesa de trabajo 1-8](https://user-images.githubusercontent.com/57755629/69899387-814aa980-1365-11ea-8b72-6f8285f946a1.png)
![8Mesa de trabajo 1-8](https://user-images.githubusercontent.com/57755629/69899388-814aa980-1365-11ea-9b89-37fead4b09d4.png)
![9Mesa de trabajo 1-8](https://user-images.githubusercontent.com/57755629/69899389-814aa980-1365-11ea-8c88-faee0f618757.png)

**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ ] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for stickers.

**Problem Description**  
[FILL IN WITH DETAILED DESCRIPTION OF THE PROBLEM]

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN PLAY STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by stalinesatola** [comment]
use WebP

**Comment by MarvinJWendt** [comment]
Hi, you have created an empty issue<sup>1</sup> in the bug-tracker of this repository<sup>2</sup>. 

The `Issue` tab of repositories on [GitHub](https://github.com) is meant to report problems with the repository or to discuss features of the project. If you have an actual issue with the repository, please [open a new issue](../issues/new) with a decent description.

Have fun exploring this repository 🎉 

<sub>If you want to know more about how to write good issues, look here: https://guides.github.com/features/issues/</sub>

---

<sup>1: Issue ⇾ Bug Report / Feature Request / etc..</sup>
<sup>2: Repository ⇾ Project</sup>
