### ISSUE TITLE
[Android] New stickers not showing in added stickerpack

### ISSUE THREAD

**Issue by svenvdz** [WhatsApp/stickers#579]
**Specifications**  
OS Version: 9
Device Manufacturer: OnePlus 5 and samsung a3

**Stickers**
- [X ] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [X ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ X] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for stickers.

**Problem Description**  
New stickers are not showing in already added stickerpacks even after updating the version. This is what the json file looks like:
`{"android_play_store_link":"https:\/\/play.google.com\/store\/apps\/details?id=stickermaker.android.stickermaker","sticker_packs":[{"identifier":"gMdcfnS0JmR66Oa0pC3gvjYrWl4xyLH47N1dGSfgWZG4T4mdRs","name":"lolol","publisher":"Sticker Studio for WhatsApp","tray_image_file":"tray_lolol.png","image_data_version":"9","avoid_cache":true,"stickers":[{"image_file":"sticker1575407681534.webp"},{"image_file":"sticker1575407688986.webp"},{"image_file":"sticker1575407695693.webp"},{"image_file":"sticker1575407715908.webp"},{"image_file":"sticker1575407931853.webp"},{"image_file":"sticker1575408212380.webp"},{"image_file":"sticker1575408320921.webp"},{"image_file":"sticker1575408371488.webp"},{"image_file":"sticker1575408401718.webp"},{"image_file":"sticker1575408429151.webp"},{"image_file":"sticker1575408900519.webp"},{"image_file":"sticker1575409194544.webp"}]}]}`

**Reproduction Steps**  
Add a stickerpack to whatsapp, update the contents.json of the stickerpack.

**Links**  
https://play.google.com/store/apps/details?id=stickermaker.android.stickermaker

**Comment by svenvdz** [comment]
Removing the stickerpack from whatsapp and adding it again from the app works, but it does not update itself.

**Comment by svenvdz** [comment]
Battery optimization turned off

**Comment by svenvdz** [comment]
I forgot to update the contentprovider

**Comment by hamza-ahmed** [comment]
@svenvdz How you are solve the problem ?

**Comment by nabeel-terafort** [comment]
how to update the content provider any help?

**Comment by nabeel-terafort** [comment]
i have a same problem..

**Comment by CrackerKSR** [comment]
> I forgot to update the contentprovider

How do you update the content provider?

By the way adding new stickers requires next version of in json. But It ask to add again. After adding it replaces the existing sticker pack having same name.

But updating content provider would be better way It seems.
Please can share that code snippet?
