### ISSUE TITLE
Is it possible to load stickers from storage?

### ISSUE THREAD

**Issue by Alexmartinez3** [WhatsApp/stickers#58]
I need to create and load stickers from external or internal storage. Only works if the stickers are in the assets folder?

Im trying to export the file content of my internal storage but whatsapp not load the sticker pack.

Any help will be welcome. Thanks in advance

**Comment by amrit-1901** [comment]
Please take a look at the "Advanced development" section for how to do this.

**Comment by priyeshmarvi** [comment]
i have same issue it's working for you @Alexmartinez3?
Thanks in advance

**Comment by Testify-hub** [comment]
I have same issue. Please help. How should I be able to add stickers from pack that is present in internal storage of phone??
