### ISSUE TITLE
Whatsapp Stikers

### ISSUE THREAD

**Issue by ibnusf20** [WhatsApp/stickers#581]

**Comment by MarvinJWendt** [comment]
Hi, you have created an empty issue<sup>1</sup> in the bug-tracker of this repository<sup>2</sup>. 

The `Issue` tab of repositories on [GitHub](https://github.com) is meant to report problems with the repository or to discuss features of the project. If you have an actual issue with the repository, please [open a new issue](../issues/new) with a decent description.

Have fun exploring this repository 🎉 

<sub>If you want to know more about how to write good issues, look here: https://guides.github.com/features/issues/</sub>

---

<sup>1: Issue ⇾ Bug Report / Feature Request / etc..</sup>
<sup>2: Repository ⇾ Project</sup>
