### ISSUE TITLE
Third party pack cannot be found likely because the corresponding app is restricted

### ISSUE THREAD

**Issue by vincekruger** [WhatsApp/stickers#584]
I'm reporting a new issue here because I think this is a new problem.

```Third-party pack cannot be found likely because the corresponding app is restricted```

I've managed to consistently replicate the issue.  I will add the first sticker pack to WhatsApp successfully, however, when adding the second pack it fails with the above error, however, when I kill the app and re-open it and try to add the second pack again it passes.  If I then try to add a third sticker pack it fails again with the same error.  Kill the app, works and so forth.  Is this a problem with WhatsApp trying to restrict the number of sticker packs being added in a certain time frame or is this something else?

My issue has nothing to do with the power-saving mode.  I've tried these steps too. https://github.com/WhatsApp/stickers/issues/468

Please see my implementation for WhatsApp Stickers: https://pub.dev/packages/flutter_whatsapp_stickers

It's driving me crazy and I cannot figure out what the problem is.

**Comment by MarvinJWendt** [comment]
Hi @vincekruger, 
thank you for reporting this! 

Could you please tell us:
- The WhatsApp version you are using
- Your Android version
- Your mobile phone vendor and model

Thanks 👍

**Comment by marwanzak** [comment]
Same here I have the same problem. When I add a new pack I need to remove the application from the background threads and reopen it to add a new pack.
WhatsApp version: 2.19.360
Android Version: 7.1.1
Mobile phone vendor and model: Samsung A7 2016
I don't have multiple versions of WhatsApp.

Please give me a solution.

**Comment by ubutt9dtech** [comment]
Hi @MarvinJWendt ,
I have the same problem.Can you please tell me the cause of this issue.
Thanks you

**Comment by MarvinJWendt** [comment]
Hi @marwanzak and @ubutt9dtech,

If you have the same problem please open a new Issue and provide every information that is asked for. Also, please include if you have **multiple or modified** versions of WhatsApp installed. Thanks :)

**Comment by sidoruvigo** [comment]
This also happens to me with this [flutter sticker implementation](https://github.com/viztushar/flutter_whatsapp_stickers_internet)

**Comment by Zeeshan0201** [comment]
@sidoruvigo yes I am also facing same issue :disappointed:

**Comment by vincekruger** [comment]
@MarvinJWendt 

Super delayed response to my original post. Sorry about that.

WhatsApp version: Latest
Android version: 8.0.0
Mobile phone vendor and model: Huawei PRA-LX1
Do you have multiple or modified versions of WhatsApp installed on your phone? Single Version. Consumer (Beta)

**Comment by adenilson-santos** [comment]
I have this problem too. =(
WhatsApp version: Latest
Android version 8.1.0
Mobile phone vendor and model: Moto G5S Plus
I don't have any another whatsapp version in my cellphone

**Comment by MarvinJWendt** [comment]
I will mark this as a bug, as it seems to occur often.

/cc @simonzhexu

**Comment by vincekruger** [comment]
Thanks, @MarvinJWendt.

Do we have a general timeline on bugs like this?

**Comment by MarvinJWendt** [comment]
@vincekruger I am sorry, I cannot tell you how long this will take. Simon has to look into it and as it seems he's busy at the moment. 
If there's an update I'll post it here :)

**Comment by simonzhexu** [comment]
Hey Guys, sorry, have been busy with internal development stuff, I will take a look and let you know.

**Comment by vincekruger** [comment]
@simonzhexu Thank! Appreciate it.

**Comment by Purus** [comment]
Same issue.

WhatsApp version: Latest
Android version: 8.0.0
Mobile phone vendor and model: Redmi Note 7 Pro
Do you have multiple or modified versions of WhatsApp installed on your phone? Single Version.

**Comment by prabhashibuddhima** [comment]
@Purus any luck? I'm using the same phone model as you and facing the same issue

**Comment by vincekruger** [comment]
@simonzhexu I've narrowed this issue down a little.

I load sticker packs remotely and store these in internal storage.  I then update the main contents.json file.

It seems that this new file update is cached somewhere along the line.
If I query this using adb shell I can see the updated version.

**Comment by adityaspt** [comment]
Guys any progress at solving this? Im having the same issue.

**Comment by vincekruger** [comment]
So I've managed to resolve this for my issue.  I was getting this error because I was adding stickers packs to my config file dynamically after the content provider was created and not refreshing the content provider.  There is a check in the content provider to serve was is already loaded, I simply removed that.

**Comment by adityaspt** [comment]
> So I've managed to resolve this for my issue. I was getting this error because I was adding stickers packs to my config file dynamically after the content provider was created and not refreshing the content provider. There is a check in the content provider to serve was is already loaded, I simply removed that.

where is the check happening exactly? Can you point me at the line in StickerContentProvider class

**Comment by vincekruger** [comment]
@adityaspt https://github.com/WhatsApp/stickers/blob/bb12c5b1fc95506a199acb5903d224702be8a901/Android/app/src/main/java/com/example/samplestickerapp/StickerContentProvider.java#L157

**Comment by adityaspt** [comment]
E/AddStickerPackActivity: Validation failed:Third party pack cannot be found likely because the corresponding app is restricted, sdk: 29 ,power saving mode: false
Im still getting this in my log cat

What changes i have made in the original project is I have changed all the layout, I have just added a Button in my main activity and on the clicking the button

` @Override
    public void onClick(View v) {
        addStickerPackToWhatsApp("1", "Adi");
    }
                                         });
    }`

I just call the function to add my sticker pack giving the identifier and pack name. I have done this for testing purpose only. Actually I want to call this function from my unity project later, as I will be passing this native project as a plugin there. My current project was working two days before. But after then I have been constantly getting "There's a problem with this sticker pack and it cant be added to Whatsapp". Im very new to working on Android. Thanks for any help!

**Comment by krunalpandav** [comment]
> E/AddStickerPackActivity: Validation failed:Third party pack cannot be found likely because the corresponding app is restricted, sdk: 29 ,power saving mode: false
> Im still getting this in my log cat
> 
> What changes i have made in the original project is I have changed all the layout, I have just added a Button in my main activity and on the clicking the button
> 
> ` @Override public void onClick(View v) { addStickerPackToWhatsApp("1", "Adi"); } }); }`
> 
> I just call the function to add my sticker pack giving the identifier and pack name. I have done this for testing purpose only. Actually I want to call this function from my unity project later, as I will be passing this native project as a plugin there. My current project was working two days before. But after then I have been constantly getting "There's a problem with this sticker pack and it cant be added to Whatsapp". Im very new to working on Android. Thanks for any help!

I have to used same method as you say it working when i add sticker from assets it was working but when i have to create my custome  stickerpack and add to it whatsapp then getting same issue "Third party pack cannot be found likely because the corresponding app is restricted, sdk: 29 ,power saving mode: false"

**Comment by adityaspt** [comment]
That seems to be a constant issue. No solutions found yet.

**Comment by jiao08** [comment]
> So I've managed to resolve this for my issue. I was getting this error because I was adding stickers packs to my config file dynamically after the content provider was created and not refreshing the content provider. There is a check in the content provider to serve was is already loaded, I simply removed that.

This is  the correct answer! I've managed to resolve it for my issue too.(And the reason is same)
Thanks a lot!

**Comment by JeremyR34** [comment]
More explicit error message could be nice.

**Comment by viyyan** [comment]
I got the same issue on my project, please make sure your contents.json has the same structure (key naming) as this one -> [contents.json](https://github.com/WhatsApp/stickers/blob/master/Android/app/src/main/assets/contents.json).

**Comment by rebelholic** [comment]
> I got the same issue on my project, please make sure your contents.json has the same structure (key naming) as this one -> [contents.json](https://github.com/WhatsApp/stickers/blob/master/Android/app/src/main/assets/contents.json).

whats your email? I need your help to fix this bug

**Comment by rebelholic** [comment]
I already fixed this bug on build.gradle (app) like below:

![build.gradle](https://user-images.githubusercontent.com/6254876/127594258-87835b34-fa22-49d5-8d85-ee4d476b4e66.jpg)

You can try [my app on playstore](https://play.google.com/store/apps/details?id=com.baysoft.wisdomtextstickers) if you don't believe

**Comment by khushbuvadi** [comment]
Any solution found? I also have same issue:

Validation failed:Third party pack cannot be found likely because the corresponding app is restricted, sdk: 30 ,power saving mode: false

**Comment by symphony701** [comment]
> @adityaspt
> 
> https://github.com/WhatsApp/stickers/blob/bb12c5b1fc95506a199acb5903d224702be8a901/Android/app/src/main/java/com/example/samplestickerapp/StickerContentProvider.java#L157

This works! Thanks

**Comment by parthpatel1029** [comment]
Third party pack cannot be found likely because the corresponding app is restricted, sdk: 33 ,power saving mode: false

Getting this error is there any solution for this?

**Comment by parthvirani-oceanmtech** [comment]
> So I've managed to resolve this for my issue. I was getting this error because I was adding stickers packs to my config file dynamically after the content provider was created and not refreshing the content provider. There is a check in the content provider to serve was is already loaded, I simply removed that.

you're absolutely right, so guys if you are adding sticker from remote and getting errors than you just have to remove this if condition in order to make it work.

![image](https://github.com/WhatsApp/stickers/assets/108506837/590357c6-614b-41a0-94a8-1a8f902bab04)

**Comment by Soorajaniyeri** [comment]
this issue solved iam stuck on this issue in flutter app
