### ISSUE TITLE
[Android] Unclear why I'm getting: "Validation failed:sticker file might be corrupted or invalid"

### ISSUE THREAD

**Issue by markkorput** [WhatsApp/stickers#606]
EDIT -- SOLVED; the issue was accidentally added garbage bytes at the end of my generated webp files which makes whatsapp reject them. Maybe WhatsApp's webp-corruption check can be added to the validator in the example app?

**Specifications**  
OS Version: Android 8.0.0
Device Manufacturer: Huawei (P10 lite), but also other android devices

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for stickers.

**Problem Description**  
On Android, when trying to add a sticker pack to whatsapp I keep getting the following rejection message (copied from log);

> AddStickerPackActivity: Validation failed:sticker file might be corrupted or invalid

**Reproduction Steps**  
I'm simply building and running the original Android Example app replacing single sticker images (giving it the same name as the original) to test the validity (in WhatsApp's opinion) of the file;
- Generate a .webp
- Place the generated .webp file in the assets/1/ folder of the Android example app
- remove the 01_Cuppy_smile.webp file
- Give the generated .webp file the name 01_Cuppy_smile.webp (replacing the existing .webp file)
- Build and run the application on Android phone with whatsapp installed
- In the app press the big green "ADD TO WHATSAPP" button

Result; sometimes the pack gets  accepted (see below), sometimes the pack gets rejected with an alert:
> There's a problem with this sticker pack and it can't be added to WhatApp
Followed by: 
> Error with the Pack -- sticker file might be corrupted or invalid

- If the pack got accepted, go into whatsapp to manually remove the pack again.

**Head of Commit**
d238f2b (master at the time of writing)

**Links**  
Not yet

**Further Info**
Apparently WhatsApp is doing more validations than the StickerPackValidator, or anything in the Android example app, because the images look fine in the Android Example App (which is just the Android example app, with only a sticker image replaced).

It would be very useful to know what kind of other validation the sticker images must pass, and if possible to have this validation added to the StickerPackValidator in the example app, because this way the only way to figure out what requirements WhatsApp sets is just by throwing stuff against the wall and see what sticks…

What I’ve notice so far;

Below are a couple of [webpinfo](https://developers.google.com/speed/webp/docs/webpinfo) outputs from both sticker images that I DO manage to get accepted by whatsapp and sticker images that are getting rejected. First I thought I had something to do with missing alpha channel, but eventually I found a file without alpha that got accepted.

Note that I need to dynamically generate my stickers as I export them from my application, so I’m looking for a valid way to do this. The only self-produced images I’ve been able to get accepted so far, are the images that I manually generated using [weaponise](http://webponize.org/) or [cwebp](https://developers.google.com/speed/webp/docs/cwebp) which are not workflows that can be incorporate into an app… (ironically, most of the images produced by webponize are completely messed up, but DO get accepted by whatsapp).

Any help or information would be appreciated!

***webpinfo outputs***
```
File:accepted_and_generated_using_webponize.webp
RIFF HEADER:
  File size:  49686
Chunk VP8  at offset     12, length  49674
  Width: 512
  Height: 512
  Alpha: 0
  Animation: 0
  Format: Lossy (1)
No error detected.
```

```
File: 17_Cuppy_tired_from_example_app.webp
RIFF HEADER:
  File size:  11738
Chunk VP8L at offset     12, length  11726
  Width: 512
  Height: 512
  Alpha: 1
  Animation: 0
  Format: Lossless (2)
No error detected.
```

```
File: rejected_with_alpha01.webp
RIFF HEADER:
  File size:  15850
Chunk VP8L at offset     12, length  15838
  Width: 512
  Height: 512
  Alpha: 1
  Animation: 0
  Format: Lossless (2)
No error detected.
```

```
File: rejected_with_alpha02.webp
RIFF HEADER:
  File size:  25718
Chunk VP8X at offset     12, length     18
  ICCP: 0
  Alpha: 1
  EXIF: 0
  XMP: 0
  Animation: 0
  Canvas size 512 x 512
Chunk ALPH at offset     30, length   2996
Chunk VP8  at offset   3026, length  22692
  Width: 512
  Height: 512
  Alpha: 0
  Animation: 0
  Format: Lossy (1)
No error detected.
```

```
File: rejected_without_alpha.webp
RIFF HEADER:
  File size:  18298
Chunk VP8  at offset     12, length  18286
  Width: 512
  Height: 512
  Alpha: 0
  Animation: 0
  Format: Lossy (1)
No error detected.
```

**Comment by markkorput** [comment]
Ok I found the issue, now all my images actually get accepted.

It turns out that a bug in my webp generator was adding useless bytes to the end of the file. For some reason most webp implementations weren't picking this up, dwebp and webpinfo (as seen from the "No error detected." results above) and most android views, were not having any problems with my webp files (with added garbage bytes at the end), but whatsapp ís picking up on it.

It would still be useful to have this validation step in the example app's validator as well!

**Comment by Zandor300** [comment]
@simonzhexu Can the same validation from WhatsApp be added to the example app?

**Comment by simonzhexu** [comment]
We have a custom code written by one of our engineers to check webp validation. The goal is to avoid our users receive invalid webp files or even malicious webp files. Due to the security of our users, we cannot bundle that library in this open source library, since that will reveal the code to potential hackers and they may try to find loop holes in the code. 

I am sorry for the frustration that this inconsistency creates for our developers. If you have other ideas on how to resolve this issue, I am happy to explore.

**Comment by markkorput** [comment]
@simonzhexu thanks for clarifying

**Comment by ploth** [comment]
@markkorput I think have the same problem.

> It turns out that a bug in my webp generator was adding useless bytes to the end of the file.

How much data do I need to cut at the end? I already had a look into the hexdumps and compared image sizes with the bytes 5-8 of my webp (indicating the image size) but couldn't find the useless bytes :/

**Comment by markkorput** [comment]
@ploth In my case I believe it was my own code that was adding the useless bytes, so it depends on what mechanism you're using to produce the webp files. If it's your own code; have a good hard look at your code. If it's an existing library, then the problem is probably something else. I'd suggest to first isolate the problem; start from the (working) demo app, just replace one webp file with one of yours and see if it still works. If so, the problem is something else, otherwise; improve/change the way you create webp files.

**Comment by sudheernaidu53** [comment]
Hi

I found another reason for which the error "AddStickerPackActivity: Validation failed:sticker file might be corrupted or invalid"
The files shouldn't contain special characters. my sticker had "~". renaming it solved the issue.

**Comment by slg407** [comment]
> We have a custom code written by one of our engineers to check webp validation. The goal is to avoid our users receive invalid webp files or even malicious webp files. Due to the security of our users, we cannot bundle that library in this open source library, since that will reveal the code to potential hackers and they may try to find loop holes in the code.
> 
> I am sorry for the frustration that this inconsistency creates for our developers. If you have other ideas on how to resolve this issue, I am happy to explore.

it would be nice if there was a clientside feature to clean up stickers with errors (i.e. if the sticker is rejected it sends a code to the client and makes the client remake the sticker using the stored image file, maybe something that looks at each pixel and recreates it in a new image, same for animated stickers (where in animated stickers it does it for each frame, following whatsapps normal compression algorithm is the end file is too big), afterwards it shows the user a screen with both stickers side by side and gives the user 3 options, one to reject the remade sticker (in cases the sticker turns out bad), one to replace the old sticker, and one to make a new sticker, i might open this up in a new issue
