### ISSUE TITLE
iOS - webp crashed app

### ISSUE THREAD

**Issue by alkharaz** [WhatsApp/stickers#61]
I have tried to include webp instead of png but the app didn't recognize it and crashed

error : 

Thread 4: Fatal error: test.webp not found.

ps. I have export the webp from Pixelmator

**Comment by amrit-1901** [comment]
Make sure that the webp file has been added to the `WAStickersThirdParty` target.

**Comment by alkharaz** [comment]
Yes i have added it

**Comment by amrit-1901** [comment]
Where did you save the "test.webp" file? Did you create any additional folders in your Xcode project to save the image in?

**Comment by alkharaz** [comment]
Inside folder SampleStickers

**Comment by alkharaz** [comment]
Xcode debug throw the error here 

`catch StickerPackError.fileNotFound {
                        fatalError("\(filename) not found.")`

also I have tried to change the extinction from .webp to .Webp but no lock

**Comment by alkharaz** [comment]
<img width="233" alt="screen shot 2018-10-30 at 6 39 00 am" src="https://user-images.githubusercontent.com/17476415/47694380-81cabb00-dc0e-11e8-9f64-9fed772b1488.png">
<img width="421" alt="screen shot 2018-10-30 at 6 38 51 am" src="https://user-images.githubusercontent.com/17476415/47694389-8a22f600-dc0e-11e8-8437-02ea26b4e526.png">

**Comment by michaelluk** [comment]
![image](https://user-images.githubusercontent.com/1543408/47703146-43f38400-dc5a-11e8-8c23-8d454a63c367.png)

Make sure you've checked the box in `Target Membership`

**Comment by alkharaz** [comment]
> ![image](https://user-images.githubusercontent.com/1543408/47703146-43f38400-dc5a-11e8-8c23-8d454a63c367.png)
> 
> Make sure you've checked the box in `Target Membership`

Yes It solve the problem
