### ISSUE TITLE
[WhatsApp Web] No Favorite Stickers and each pack takes long to load

### ISSUE THREAD

**Issue by ars4l4n** [WhatsApp/stickers#611]
Not Adding the favorite Stickers function to the whatsapp web client wasn't a good idea
Now I have to search each single sticker out of about 15 packs. Each pack takes way longer to load than on my phone where it's almost instant

People who only use their own stickers could circumvent this by adding all their stickers into a single stickerpack but I can't do that with stickers inside other peoples' stickerpacks.

What's the point of leaving out the favorites function?

**Comment by simonzhexu** [comment]
We will look into resolving this issue. Unfortunately, we cannot disclose our development plans.
