### ISSUE TITLE
[Android] After update stickers don't immediately refresh, force update possible?

### ISSUE THREAD

**Issue by markkorput** [WhatsApp/stickers#612]
**Specifications**  
OS Version: Android 8.0.0
Device Manufacturer: Huawei (P10 lite)

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for stickers.

**Problem Description**  
The stickers in whatsapp don't immediately refresh after updating a previously added stickerpack, which as far as I know doesn't involve any signal to whatsapp but will automatically be picked up when the _image_data_version_ field has increased. Whatsapp still shows the old stickers, until I manually press the '+' button on the right of the stickerpacks bar to open the stickerpack-management-screen, where the updated stickers are shown correctly. After closing the stickerpack-management-screen the updated stickers show correctly in the sticker tray as well.

**Reproduction Steps**  
- Add you custom sticker pack to whatsapp
- Open whatsapp, verify the sticker pack is added
- Change the stickers and increase the image_data_version field
- Make sure your ContentProvider supplies to updated data/images
- Open your stickerpack in whatsapp
- Expected: to see the updated stickers.
- Actual: I see the old stickers

- Click on the '+' button and go to the "MY STICKERS" tab
- Here it should correctly show the updated stickers
- Press the back button
- Now it correctly shows the updated stickers

**Head of Commit**
d238f2b

**Links**  
not yet

**Desired behaviour**
It seems like whatsapp polls for new data at certain moments (like when opening the stickerpack-management-screen?) and/or maybe at a fixed interval. Is it possible to force a sticker data update programmatically? 

Currently the UX for an external app when updating stickers is;
 user presses save [in external app] -> gets notification that stickers are saved [in external app] -> opens whatsapp -> sees old stickers.

This is obviously confusing. The best solution at this point is to notify the user in advance in the external app about the manual steps that have to be taken force a sticker refresh, but this would obviously preferably be avoided.

**Comment by markkorput** [comment]
Anything on this? Anybody able to reproduce?

**Comment by Zandor300** [comment]
@simonzhexu

**Comment by simonzhexu** [comment]
Thanks @markkorput. Sticker packs should refresh when user open sticker picker or sticker management screen.I will see what we can do.

**Comment by thewayur** [comment]
can u please send a proper code flow , how u able to update stickers?
