### ISSUE TITLE
INFRINGEMENT NOTICE FROM APPDETEX ON BEHALF OF WHATSAPP (SUSPENSION OF APP)

### ISSUE THREAD

**Issue by jayateertha043** [WhatsApp/stickers#614]
Hello WhatsApp team,
Got a infringement notice from AppDetex on your behalf for my app removal.

ALSO MENTIONED IN EMAIL - "You may contact Alexis Meghrouni Rivas at enf.whatsapp.75532@enfappdetex.com. If Alexis Meghrouni Rivas contacts us specifically authorizing your app to be re-published, and your app does not otherwise violate the Developer Distribution Agreement and Developer Program Policies, we will reinstate the app."

![notice](https://user-images.githubusercontent.com/26671870/77817065-06fd1c80-70ee-11ea-9e2e-33a8512009b5.jpg)

APP URL:https://play.google.com/store/apps/details?id=com.japps.wastatusdownloader
NAME OF APP:Status Saver - Download,Share Whatsapp Status
I also attach my logo in the ISSUE.
![logo](https://user-images.githubusercontent.com/26671870/77817025-c00f2700-70ed-11ea-9014-a08a401d9ca1.png)

I don't think my logo,banner or anything inside my app contains WhatsApp trademarks.
If I have unknowingly violated any trademarks kindly let me know ,I will correct them .
Moreover I have clearly stated in APP description that,This app is solely a individual APP and is not affilated with any 3rd party including WhatsApp or FaceBook,So that Users Won't get misleaded at any cost.

Kindly re-instate the app so that I can make required changes and republish them again.

Moreover I have paid money from my pocket savings for opening PLAY DEVELOPER  ACCOUNT for uploading APPS,If APPS are suspended ,they might also suspend my Whole PlayStore Account which might be a severe loss to me.

Here are links to similar apps by other developers which has 1M+ Downloads:https://play.google.com/store/apps/details?id=statussaver.statusdownloader.savestatus.downloadstatus

Kindly let me know why my app is suspended and what I can do to reinstate my app back to playstore.

I understand that title of my word contains Whatsapp not WhatsApp,kindly re-instate my app so that I can make those changes ,I hadn't known those earlier.
Just read :https://whatsappbrand.com/

I am a solo Student Developer and have devoted a lot of time and efforts for this project ,I hope WhatsApp understands this and reinstates my App

Thank You 
Jayateertha G

**Comment by jayateertha043** [comment]
As Mentioned in the E-Mail from Google - "You may contact Alexis Meghrouni Rivas at enf.whatsapp.75532@enfappdetex.com. If Alexis Meghrouni Rivas contacts us specifically authorizing your app to be re-published, and your app does not otherwise violate the Developer Distribution Agreement and Developer Program Policies, we will reinstate the app."

Only If APPDETEX authorizes  Google again to re-publish my app,It will be published again and I can make the required changes.

Kindly tell APPDETEX to re-instate my APP,I promise that ,I will immediately change everything as per policies and guidelines you provide.

As more important than this App is that My Google Play Developer  Account  might be suspended due to this  ,for which I had paid $25(Huge Amount for a student like me in India).

Kindly reinstate my APP so that I will make required changes.

I hope WhatsApp team helps me in this.

Thank You

Jayateertha G

**Comment by jayateertha043** [comment]
As Mentioned in the E-Mail from Google - "You may contact Alexis Meghrouni Rivas at enf.whatsapp.75532@enfappdetex.com. If Alexis Meghrouni Rivas contacts us specifically authorizing your app to be re-published, and your app does not otherwise violate the Developer Distribution Agreement and Developer Program Policies, we will reinstate the app."

Only If APPDETEX authorizes  Google again to re-publish my app,It will be published again and I can make the required changes.

Kindly tell APPDETEX to re-instate my APP,I promise that ,I will immediately change everything as per policies and guidelines you provide.

As more important than this App is that My Google Play Developer  Account  might be suspended due to this  ,for which I had paid $25(Huge Amount for a student like me in India).

Kindly reinstate my APP so that I will make required changes.

I hope WhatsApp team helps me in this.

Thank You

Jayateertha G

**Comment by jayateertha043** [comment]
Sorry I have clicked close unknowingly,just re-opened the issue again.
Please help me resolve this issue soon

**Comment by jayateertha043** [comment]
Hi,
Just got a mail from appdetex person,
![Screenshot_2020-03-30 App Infringement Notice - jayateertha043 gmail com - Gmail](https://user-images.githubusercontent.com/26671870/77934562-e25f9b00-72cd-11ea-9b4d-951ed8719572.png)

It says -"While we appreciate that you wish to, or may have modified your app, we don’t review or consent to republication of apps."

Is this fair ? Just suspending apps without any notice directly and not even giving a chance to correct myself.
I hadn't known abot the naming rules earlier(Just a Young Student Devloper!!!),I have seen many apps like https://play.google.com/store/apps/details?id=in.mohalla.sharechat in Google Play with more than 20M+ downloads,There are even much more apps like these.

Moreover I have clearly mentioned in description that "This app is solely individual and doesn't belong to Whatsapp or Facebook or any 3rd Party" ,so that users do not get confused. 

Now my Google Play Developer account is on verge of getting closed due to this single mistake.

Kindly give a small chance to correct it,I will remove the whole APP itself from Google Play,I don't want a small APP to affectmy whole Google Play Account.

I have paid $25 for developer account (I am a young student so it's huge amount for me) .

By reinstating the app ,I can learn from my mistakes and publish more apps which follow all the branding rules.
I am young developer just learning to develop ,if my account itself is banned ,I will be very much discouraged about developing mobile apps.

I have seen for many people you have given 2nd chance and helped them reinstate the app.
Kindly give me one more chance and I promise this won't happen again.

Kindly reinstate the APP,I can even remove the APP from PlayStore ,I dont want my account itself to be closed.
Kindly show some mercy on small develeper like me.

I hope you understand this and help a growing student developer's career.

Thank You 

Jayateertha G

**Comment by jayateertha043** [comment]
I am just a Student Developer ,After developing app I looked for app names with similar functionality of my APP,
I saw https://play.google.com/store/apps/details?id=in.mohalla.sharechat and https://play.google.com/store/apps/details?id=statussaver.statusdownloader.savestatus.downloadstatus
They too had Whatsapp at the end of title ,But these were not suspended.SO I thought MY APP name :Status Saver - Download,Share Whatsapp Status is also good and named my app.

> I have clearly mentioned in the description:"This app is solely individual and doesn't belong to Whatsapp or Facebook or any 3rd Party" ,so that users do not get confused.

Just give me one chance so that I can correct myself ,I can also remove the app,If you insist once My App is reinstated.

**Comment by jayateertha043** [comment]
Just a small mail from Whatsapp or Appdetex could bring back my Play Dveleoper account and my app to life,after which I will either remove all whatsapp from title ,description wherever it's present or even totally remove whole app from playstore if you insist.
Kindly help a small developer

**Comment by MarvinJWendt** [comment]
Hi @jayateertha043,

it is stated in the README that you may not include the word `WhatsApp` in the title. 

> When naming your app, it is strongly advised you do not use "WhatsApp" anywhere in the name of your app or in the name field of your app listing.
https://github.com/WhatsApp/stickers#brand-guideline

This Issue has happened to many other, and to my knowledge, nobody got their suspension revoked. 

You can also look here: #150 

Sadly nobody here is able to lift those suspensions.

**Comment by jayateertha043** [comment]
Thanks for reply , I am building new app , I need to know can I use WhatsApp in description or any other place than title ?
As the utility of my app is WhatsApp status saving ,users search for WhatsApp status saver,
So let me know if I can use in description and short description for playstore.

I don't want my app to get suspended again which may lead to closure of Google play developer account

**Comment by MarvinJWendt** [comment]
> However, when preparing your app for submission in Google Play Store/App Store, you'll have the option to add description associated with your app and it's okay to mention WhatsApp in the description. Make sure you use "WhatsApp" as brand name, with "W" and "A" capitalized with no space between letters.
https://github.com/WhatsApp/stickers#brand-guidelines

**I cannot guarantee for that tho.**

**Comment by Lurzapps** [comment]
got suspended as well. This is my third app being banned from the PlayStore now. The first one was a mistake I made when I was 14, the other one was a CoronaTracker. I have been banned probably as well because I used the brand's name in my title. What a shit. I have to upload it completely again, they did not even send me any kind of information why it had been banned. This is absolutely not great for small developers, they just get crushed by such things. Well, I guess I'll upload it again without the brand's name in the title.

**Comment by tajjacob** [comment]
My app just got suspended (4/11/2020) due to same issue. what a life.

**Comment by Maxwellcyk83** [comment]
> 
> 
> My app just got suspended (4/11/2020) due to same issue. what a life.

Just don't put the word 'WhatsApp' in anywhere , no matter in the title or in the short description or in the long description. That's the safest way in long term.

**Comment by shasan5144** [comment]
Same situation for me and I got same email as well 
My case is Instagram instead of WhatsApp and my app just published 2 weeks ago I don’t know what to do 
I’ve just update my store listing and I removed the word Instagram from app name, short description and full description
Which is not making sense for me. tens if not hundreds of apps available containing the Instagram name even the icon looks almost same as Instagram 
Anyways I’ll wait for the response and I’ll let you know

**Comment by agarwalrohit2503** [comment]
Will the disturbed app get reinstated again with the same downloads and reviews
Will my developer account also get banned , can i publish apps using the same developer account.

**Comment by BatelBB** [comment]
My extension also got taken down because of them.

**Comment by MarvinJWendt** [comment]
Hi @BatelBB, please make sure to fulfill the brand guidelines, as stated in the readme: https://github.com/WhatsApp/stickers#brand-guidelines

**Comment by NomanBaigA** [comment]
there are lots of people on the play store using the name WhatsApp and even creating the exact same icon as WhatsApp but why did only a few apps got suspended because of this

**Comment by santi-petersen** [comment]
> there are lots of people on the play store using the name WhatsApp and even creating the exact same icon as WhatsApp but why did only a few apps got suspended because of this

It probably depends on the quality of your app. They decide whether the direct relationship between your app and WhatsApp is beneficial or harmful to them. To avoid problems, use WAStickersApps instead of WhatsApp -in name and short description- and don't use the WhatsApp icon.

**Comment by NomanBaigA** [comment]
play store becomes very unsafe for developers because you don't even know which day is last for your app. I don't know why they have a review process if they can reject or suspend your app anytime they want

**Comment by Wandering-Consciousness** [comment]
Same issue happened to me. Guess I'll have to publish it as a new app with "WhatsApp" removed from the title.
