### ISSUE TITLE
[Android] Tap to preview

### ISSUE THREAD

**Issue by maplexmovie** [WhatsApp/stickers#616]
Hey guys, I have seen inside WhatsApp in the "built-in" stickers section that when entering a sticker pack a single sticker can be previewed by tapping the sticker (A magnified version appears) can you please add this section of code onto the sample app code? That will be very helpful.

Thanks and stay safe.

**Comment by simonzhexu** [comment]
Hi @maplexmovie , great suggestion. I am currently busy with other stuff. This is an open source repo, you are welcome to contribute. If you are willing to add that functionality, I can merge that into the repo. Please do the best work you can, follow all Java and Android best practices. 

You can send a pull request, I will review and test. If things look good. I will merge it in.

**Comment by maplexmovie** [comment]
I'm sorry, I asked for this feature because I'm incapable of writing this code ... I'll wait for now :)

**Comment by simonzhexu** [comment]
this is added now.
