### ISSUE TITLE
[Android] Deleted 1 sticker after I exported 3 stickers

### ISSUE THREAD

**Issue by BattleShipPark** [WhatsApp/stickers#625]
Hi,
I exported 3 stickers from my app to WA and deleted 1 sticker in my app.
Then WA shows "Something went wrong"
![Screenshot_20200422-145805_WhatsApp](https://user-images.githubusercontent.com/10345980/79945955-f3a15f00-84a9-11ea-88f8-9f12b74dc6fe.jpg)

Is this your expected result? Then I want to avoid this as a service provider because it is not a good experience to user.
Can I have any solutions?

Thanks.

**Comment by simonzhexu** [comment]
There is a limit of at least 3 stickers for each pack.

**Comment by simonzhexu** [comment]
Each sticker pack must have a minimum of 3 stickers and a maximum of 30 stickers

in https://github.com/WhatsApp/stickers/blob/master/Android/README.md
