### ISSUE TITLE
[Android]

### ISSUE THREAD

**Issue by edmarrag** [WhatsApp/stickers#627]
Stickers keeps stopping.
help me pls.
![Screenshot_20200427-233649 1](https://user-images.githubusercontent.com/64452541/80444815-0c19db00-88e9-11ea-8f2b-6703adea2342.png)

**Comment by dstukalov** [comment]
Dear edmarrag,
Your app crashes. In order to stop seeing this "keeps stopping" screen you need to fix your app. The logcat with call stack of the crash would help you a lot

**Comment by edmarrag** [comment]
thanks

**Comment by Zandor300** [comment]
I don't think this is an issue related to the example code itself. Closing this for now to keep the issue thread clean. If you think this is still an issue related with the example code, feel free to reopen this.
