### ISSUE TITLE
Whatsapp Group Invite not working on Firefox and Chrome (Ubuntu)

### ISSUE THREAD

**Issue by edmoreta** [WhatsApp/stickers#634]
I received a link to join a group on WhatsApp but it is not working, I do not know where to post it. I googled the error but got no solution.
![Screenshot from 2020-05-07 10-16-20](https://user-images.githubusercontent.com/42651939/81312090-d349d680-904b-11ea-91d3-586c8d352679.png)

**Comment by Zandor300** [comment]
The link you are trying to open on your machine is a deep link. Deep links only work on Android and iOS, not on desktop.
