### ISSUE TITLE
When I click add do whatsapp nothing happens

### ISSUE THREAD

**Issue by williamokano** [WhatsApp/stickers#64]
Hi, I was trying the vanilla version, no modifications. When I build, everything seens to occur correctly, except that when I click on the button to add the sticker, the Intent is not opened so I can try to add the sticker pack.

I put a break point te debug hoping that some exception was being throw but... nothing.

It don't throw any exception, looks like the intent was called correctly, but nothing happened.

Anyone had this same problem?

**Comment by simonzhexu** [comment]
We currently don't support adding sticker packs if you don't have sticker sending capabilities yet. You can get onto the Android beta(https://play.google.com/apps/testing/com.whatsapp) to get sticker sending capabilities, or you can download website build (visit https://whatsapp.com/dl on your android phone). Note, if you download website build, you will not be able to get autoupdate. But you can go back to play build by redownloading the play build again to get auto update.

**Comment by williamokano** [comment]
Sorry about that, although I had the last version of whatsapp I didn't realized that I needed a newer version.

Updated the version through beta opt-in and now everything works perfectly.
