### ISSUE TITLE
[Android] - Push Notification after Update

### ISSUE THREAD

**Issue by SvenBudak** [WhatsApp/stickers#640]
Alot users told me that they dont realize when i update a pack with new stickers, that they need to reexport the new pack... I never wrote native Java. Can someone add a pushnotification logic and in config a setting for firebase as provider? because firebase is for small projects like this free and they handle all well i think.

**Comment by MarvinJWendt** [comment]
This repository only exists to provide the logic of the sticker apps. I don't think everybody needs push notifications. 
Of course, you are welcome to implement this logic yourself 😄 
Tip: Users of your app can enable the auto-update feature for your app in the Google PlayStore :)

**Comment by SvenBudak** [comment]
Yes, but even if the app updates itself, no new stickers are automatically exported to whatsapp ;)

I would be very happy if someone could help me to implement this.

**Comment by MarvinJWendt** [comment]
Okay I see what you mean now. I thought the notification should tell the user to update the app on the PlayStore.

Some help to get you started:
 - [Send push notifications with firebase.](https://firebasetutorials.com/send-push-notification-using-firebase-in-android/) You can use this to send notifications by yourself using the firebase website.
 - [You can use this to get the build version of your app (client side).](https://stackoverflow.com/questions/4616095/how-to-get-the-build-version-number-of-your-android-application) Useful when you want the app to detect that it has been updated.
   - [You could also try to detect app updates using a BroadcastReceiver](https://stackoverflow.com/a/30131340/10588376)

When your app detects an update, it could [trigger the notification by itself](https://www.androidauthority.com/how-to-create-android-notifications-707254/). You don't need the Firebase logic then.

I hope this helps :)

**Comment by SvenBudak** [comment]
Thank you very much for your detailed answer. But I quickly realized that I am massively overstrained with it. I think I just have to accept that the users don't get anything from new stickers. ^^"

**Comment by Ferdari** [comment]
Try using the sticker pack **version**, increase version and automagically you should see new stickers in pack in WA.
