### ISSUE TITLE
Generate Signed APK [Android]

### ISSUE THREAD

**Issue by syntaxsl** [WhatsApp/stickers#641]
I am developing WhatsApp Sticker app using your GitHub repository. I build app and its working smoothly.Signed Bundle aab file generated.But i getting try to Generate Signed APK file of this app. every attempt show this error 
`Execution failed for task ':app:checkRelease'.
> applicationId in defaultConfig cannot start with com.yansl, please change your applicationId in app/build.gradle`

I Google it and i find one of your solution from github issue 356 same like to my issue. soure: 
[https://github.com/WhatsApp/stickers/issues/356](url) 
this is my GradleExceptions part.i didnt change original one.
`        if (android.defaultConfig.applicationId.startsWith("com.whatsapp")) {
            throw new GradleException("applicationId in defaultConfig cannot start with com.whatsapp, please change your applicationId in app/build.gradle");
        }`
`        if (android.defaultConfig.applicationId.startsWith("com.yansl")) {
            throw new GradleException("applicationId in defaultConfig cannot start with com.yansl, please change your applicationId in app/build.gradle")
        }`
How i get the signed apk file solving this issue? Thank you.

**Comment by sahq-azhar** [comment]
what is your package name?

if its com.whatsapp.somthing...
change it to com.yourname (or)something .something
