### ISSUE TITLE
[Android]

### ISSUE THREAD

**Issue by gireeshks-design** [WhatsApp/stickers#647]
**Specifications**  
OS Version: [Windows 32]
Device Manufacturer: Intel]

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for stickers.

**Problem Description**  
After updating Android studio, There is no preview seen in sticker details while opening the app, only shown an add button.
![Screenshot_2020-06-19-11-12-05](https://user-images.githubusercontent.com/67137743/85101367-e1c90780-b21f-11ea-9afc-41a1d013bb45.png)
 

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**No preview in sticker details **
A

**Links**  
https://play.google.com/store/apps/details?id=com.malayalammovie.actorssticker

**Comment by simonzhexu** [comment]
Please ask this question in stackoverflow, I have limited time and unfortunately cannot help every developer with particular questions.
