### ISSUE TITLE
Allow to use openFile in Android ContentProvider

### ISSUE THREAD

**Issue by asfdfdfd** [WhatsApp/stickers#65]
We are creating app that allows to generate stickers based on user face. Right now we could not add these stickers to WhatsApp because every user generate their own sticker pack from template with their own face and images could not be stored in "assets" folder.

Without "openFile" support it seems impossible to add such stickerpacks to WhatsApp on Android.

Do you have plans to add "openFile" support?

**Comment by simonzhexu** [comment]
This sample app is meant for a general purpose. If you are intending to build a more sophisticated app, you are welcome to extend that support to use "openFile", but we are not planning to work on that as we don't have a use case for that in sample app. As long as you provide the correct URI and have support openFile in your ContentProvider, WhatsApp will pick it up.

**Comment by asfdfdfd** [comment]
@simonzhexu 

Would you be so kind to mention Uri path that will trigger call of "openFile" on ContentProvider? 

"stickers_asset" is for "openAssetFile" and what is for "openFile"?

**Comment by asfdfdfd** [comment]
For anyone interested in sharing files from SD card i've found the way.

Get 'File' object, then call 'ParcelFileDescriptor.open' and get 'ParcelFileDescriptor' object, then pass descriptor to the 'AssetFileDescriptor' constructor.

**Comment by arindammitra06** [comment]
Hi, Thanks for letting us know.. Can you please share the code. Also is there a way we can load stickers from url? Please share the code if possible.

**Comment by leonardo748** [comment]
> For anyone interested in sharing files from SD card i've found the way.
> 
> Get 'File' object, then call 'ParcelFileDescriptor.open' and get 'ParcelFileDescriptor' object, then pass descriptor to the 'AssetFileDescriptor' constructor.

Can you share your code?

**Comment by leonardo748** [comment]
@asfdfdfd please

**Comment by asfdfdfd** [comment]
Well, it's nothing special. First, you have to get 'File' object somehow. You may download it with OkHttp, you may download it earlier by user request, you may use Kotlin Coroutines etc.

```Kotlin
override fun openAssetFile(uri: Uri, mode: String): AssetFileDescriptor? {
    val file: File = existing file with sticker image you received somehow
    val pfd = ParcelFileDescriptor.open(file, MODE_READ_ONLY)
    return AssetFileDescriptor(pfd, 0, file.length())
}
```

**Comment by leonardo748** [comment]
Thanks

**Comment by kilanko** [comment]
@asfdfdfd I tried but its not working. My code is below:

```
 override fun openAssetFile(uri: Uri, mode: String): AssetFileDescriptor? {
         val dir =  context.filesDir.absolutePath
            val file = File(dir, identifier + "/" + fileName)
            val pfd = ParcelFileDescriptor.open(file, MODE_READ_ONLY)
    return AssetFileDescriptor(pfd, 0, file.length())
}

```

My content.json  and sticker folders are stored in the internal storage device so that i can download new sticker packs and also modify the contents.json file programatically.

The problem i have is that i always get "Third party sticker pack cannot be found" error. I think the problem is with the  "STICKERS_ASSET" in the Uri.

i've been stuck on this for day :(

Please Help!!
