### ISSUE TITLE
Sticker Pack only shows 1 sticker in whatsapp

### ISSUE THREAD

**Issue by krishjha07** [WhatsApp/stickers#650]
I am adding 4 stickers in a sticker pack,the images are perfect but only one sticker is showing in whatsapp which is added at the last

**Comment by krishjha07** [comment]
I have noticed something strange
Out of the 4 image only 1 image works ,I copied that and re added and there was duplicate sticker
But I tried copying other Sticker which didn't worked and it didn't shown in what's
So the Matter is that only 1 sticker is working and itlf copied it then it also works

**Comment by krishjha07** [comment]
These are the 4 stickers
https://raw.githubusercontent.com/WhatsApp/stickers/master/Android/app/src/main/assets/1/04_Cuppy_sad.webp
https://raw.githubusercontent.com/WhatsApp/stickers/master/Android/app/src/main/assets/1/03_Cuppy_rofl.webp
https://raw.githubusercontent.com/WhatsApp/stickers/master/Android/app/src/main/assets/1/02_Cuppy_lol.webp
https://raw.githubusercontent.com/WhatsApp/stickers/master/Android/app/src/main/assets/1/01_Cuppy_smile.webp

in this only the last sticker "Cuppy Smile" work,if i copy it then also it works but other 3 stickers dont work

**Comment by adityaspt** [comment]
@krishjha07 Im also kindof facing the same issue, when i add a sticker pack with 3 stickers all three are added,
For pack with 7 stickers only 5 stickers are added
For pack with 10 stickers only 8 stickers are added
And for pack with 20 only 16 stickers are added
All the pickers are right and json is also alright.
Have you found any solution to this?

**Comment by krishjha07** [comment]
mine is a different issuse,only 1 type of image is showing that is https://raw.githubusercontent.com/WhatsApp/stickers/master/Android/app/src/main/assets/1/01_Cuppy_smile.webp
now i have stopped working on it as i suspected that same code is working for me in android studio but not on appinventor

**Comment by simonzhexu** [comment]
@krishjha07 so you were using appinventor to build the app and the app doesn't add enough stickers?

**Comment by krishjha07** [comment]
> @krishjha07 so you were using appinventor to build the app and the app doesn't add enough stickers?

@simonzhexu  I had built and exntension for appinventor

**Comment by krishjha07** [comment]
> @krishjha07 so you were using appinventor to build the app and the app doesn't add enough stickers?
@simonzhexu I had built an appinventor exntension (exntensions are made for adding external java code support in appinventor apps) so I noticed that no sticker is adding I tried many but no image is adding and only one image is adding that is https://raw.githubusercontent.com/WhatsApp/stickers/master/Android/app/src/main/assets/1/01_Cuppy_smile.webp
I still don't know the reason 😭
Appinventor apps don't support adding External provider so I am doing it with appinventor

**Comment by krishjha07** [comment]
If you want demo apk then I can give the demo apk

**Comment by simonzhexu** [comment]
Yes, if you don't mind, posting an apk here would be great.

**Comment by Ola4606** [comment]
can any one make a flutter plugin the ones there are not working fine. Please chat me  here if you can: olaoluwaadeyemo7@gmail.com
