### ISSUE TITLE
Manyaka

### ISSUE THREAD

**Issue by GreyOcel0t** [WhatsApp/stickers#651]
![isticker_1593399086575](https://user-images.githubusercontent.com/67589095/86009767-e4471080-ba1a-11ea-93f3-cf4e33bc137c.png)
![isticker_1593399154784](https://user-images.githubusercontent.com/67589095/86009771-e5783d80-ba1a-11ea-9151-5f8eceda9a0f.png)
![isticker_1593399412431](https://user-images.githubusercontent.com/67589095/86009778-e6a96a80-ba1a-11ea-99b1-0847f90c2692.png)
![isticker_1593399523533](https://user-images.githubusercontent.com/67589095/86009782-e7420100-ba1a-11ea-95a9-6a4a4cd72a59.png)
![isticker_1593399570494](https://user-images.githubusercontent.com/67589095/86009786-e8732e00-ba1a-11ea-809c-1ee3da6b2543.png)
![isticker_1593399670123](https://user-images.githubusercontent.com/67589095/86009788-e9a45b00-ba1a-11ea-9ee6-781abc022451.png)
![isticker_1593399786849](https://user-images.githubusercontent.com/67589095/86009794-ea3cf180-ba1a-11ea-9c17-999c9f01257b.png)
![isticker_1593399864153](https://user-images.githubusercontent.com/67589095/86009801-eb6e1e80-ba1a-11ea-8da4-763de6fe0dbc.png)
![isticker_1593399946108](https://user-images.githubusercontent.com/67589095/86009809-ed37e200-ba1a-11ea-9ab6-7452fbeadae0.png)
![isticker_1593400017025](https://user-images.githubusercontent.com/67589095/86009814-ee690f00-ba1a-11ea-8b69-701b2118414c.png)
![isticker_1593400093564](https://user-images.githubusercontent.com/67589095/86009817-ef9a3c00-ba1a-11ea-8dba-f28180f6a229.png)
![isticker_1593400181353](https://user-images.githubusercontent.com/67589095/86009819-f0cb6900-ba1a-11ea-8408-1f7067ed6319.png)
![isticker_1593400236282](https://user-images.githubusercontent.com/67589095/86009824-f1fc9600-ba1a-11ea-95a5-7172ffd3d3f9.png)
![isticker_1593400332481](https://user-images.githubusercontent.com/67589095/86009829-f32dc300-ba1a-11ea-84a0-279518e64379.png)
![isticker_1593400459915](https://user-images.githubusercontent.com/67589095/86009834-f4f78680-ba1a-11ea-932c-1ba27129547a.png)
![isticker_1593400536514](https://user-images.githubusercontent.com/67589095/86009843-f628b380-ba1a-11ea-980a-a75f982440ab.png)
![isticker_1593400623571](https://user-images.githubusercontent.com/67589095/86009848-f759e080-ba1a-11ea-8f60-41b2f4308b93.png)
![isticker_1593400811391](https://user-images.githubusercontent.com/67589095/86009852-f88b0d80-ba1a-11ea-8e01-5eca6c9e24ac.png)
![isticker_1593400947093](https://user-images.githubusercontent.com/67589095/86009859-fa54d100-ba1a-11ea-9be0-41e950417614.png)
![isticker_1593401094015](https://user-images.githubusercontent.com/67589095/86009866-faed6780-ba1a-11ea-855a-d0ed826f1d85.png)
![isticker_1593401159065](https://user-images.githubusercontent.com/67589095/86009873-fcb72b00-ba1a-11ea-9ddc-63317288d7bc.png)
![isticker_1593401214230](https://user-images.githubusercontent.com/67589095/86009878-fde85800-ba1a-11ea-9c3a-46517ec67d98.png)
![isticker_1593401274994](https://user-images.githubusercontent.com/67589095/86009883-ff198500-ba1a-11ea-93dc-bc8cb9d37dcf.png)
![isticker_1593401336753](https://user-images.githubusercontent.com/67589095/86009886-00e34880-ba1b-11ea-8f26-3c956103c5e8.png)
![isticker_1593401461986](https://user-images.githubusercontent.com/67589095/86009890-02ad0c00-ba1b-11ea-905b-929a2d7761c3.png)
![isticker_1593401669805](https://user-images.githubusercontent.com/67589095/86009894-0345a280-ba1b-11ea-9a27-111447a73a5a.png)
![isticker_1593401823453](https://user-images.githubusercontent.com/67589095/86009902-0476cf80-ba1b-11ea-9b47-358cffc6373c.png)
![isticker_1593401887093](https://user-images.githubusercontent.com/67589095/86009904-06409300-ba1b-11ea-82a2-a2182cf371e7.png)
![isticker_1593402018373](https://user-images.githubusercontent.com/67589095/86009911-0771c000-ba1b-11ea-9ba1-18d41f7059dd.png)
![isticker_1593402097423](https://user-images.githubusercontent.com/67589095/86009912-080a5680-ba1b-11ea-93c8-d651148a01aa.png)
![isticker_1593402188771](https://user-images.githubusercontent.com/67589095/86009918-093b8380-ba1b-11ea-973c-381229300f87.png)
![isticker_1593402282884](https://user-images.githubusercontent.com/67589095/86009921-0a6cb080-ba1b-11ea-866d-6c50547bac78.png)
![isticker_1593402409653](https://user-images.githubusercontent.com/67589095/86009924-0b054700-ba1b-11ea-88f2-5ff53e5737a9.png)
![isticker_1593402486893](https://user-images.githubusercontent.com/67589095/86009930-0c367400-ba1b-11ea-85c3-7c9087d75edb.png)
![isticker_1593402540210](https://user-images.githubusercontent.com/67589095/86009932-0d67a100-ba1b-11ea-8090-affd28ceb003.png)
![isticker_1593402726952](https://user-images.githubusercontent.com/67589095/86009934-0e98ce00-ba1b-11ea-9eb8-b6d151f4d326.png)
![isticker_1593402836210](https://user-images.githubusercontent.com/67589095/86009937-0fc9fb00-ba1b-11ea-9d3e-72f5a8be56d7.png)
![isticker_1593402974760](https://user-images.githubusercontent.com/67589095/86009939-10629180-ba1b-11ea-8e50-3e8d014c913d.png)
![isticker_1593403118511](https://user-images.githubusercontent.com/67589095/86009942-1193be80-ba1b-11ea-8844-a3ce9fd02b75.png)
![isticker_1593403191507](https://user-images.githubusercontent.com/67589095/86009945-122c5500-ba1b-11ea-8021-b9c78c87bcf2.png)
![isticker_1593403217243](https://user-images.githubusercontent.com/67589095/86009946-12c4eb80-ba1b-11ea-8c06-49b2e8021f0e.png)
![isticker_1593403266492](https://user-images.githubusercontent.com/67589095/86009948-13f61880-ba1b-11ea-8ddb-d3bf46c8b864.png)
![isticker_1593403353554](https://user-images.githubusercontent.com/67589095/86009954-148eaf00-ba1b-11ea-9070-a0c61543f8dd.png)
![isticker_1593403467532](https://user-images.githubusercontent.com/67589095/86009959-15bfdc00-ba1b-11ea-8d7c-ab0a8bbfeea0.png)
![isticker_1593403593492](https://user-images.githubusercontent.com/67589095/86009963-16f10900-ba1b-11ea-9506-e0c8d1f43978.png)
![isticker_1593403701410](https://user-images.githubusercontent.com/67589095/86009970-18223600-ba1b-11ea-8032-d8cc7fec82ed.png)
![isticker_1593403814590](https://user-images.githubusercontent.com/67589095/86009972-19ebf980-ba1b-11ea-965b-268c9ac7b573.png)
![isticker_1593403983568](https://user-images.githubusercontent.com/67589095/86009981-1b1d2680-ba1b-11ea-8f9f-4b4863ad3138.png)
![isticker_1593404111171](https://user-images.githubusercontent.com/67589095/86009986-1c4e5380-ba1b-11ea-890e-31c7641c847e.png)
![isticker_1593404139884](https://user-images.githubusercontent.com/67589095/86009989-1ce6ea00-ba1b-11ea-81c7-44497ce56063.png)
![isticker_1593404267919](https://user-images.githubusercontent.com/67589095/86009990-1d7f8080-ba1b-11ea-8003-73d1b154b859.png)
![isticker_1593404424948](https://user-images.githubusercontent.com/67589095/86009991-1e181700-ba1b-11ea-983b-a8708452c4ba.png)
![isticker_1593404460326](https://user-images.githubusercontent.com/67589095/86009992-1f494400-ba1b-11ea-9e6e-e3e5c12e9ed1.png)
![isticker_1593404639274](https://user-images.githubusercontent.com/67589095/86009995-1fe1da80-ba1b-11ea-92b3-9ef0d90cbf5a.png)
![isticker_1593404681972](https://user-images.githubusercontent.com/67589095/86009998-21130780-ba1b-11ea-94c8-e4ade941601f.png)
![isticker_1593404804705](https://user-images.githubusercontent.com/67589095/86009999-21ab9e00-ba1b-11ea-908d-059df6cc81bd.png)
![isticker_1593404901793](https://user-images.githubusercontent.com/67589095/86010002-23756180-ba1b-11ea-9dd9-aaafe94a6142.png)
![isticker_1593404996473](https://user-images.githubusercontent.com/67589095/86010005-24a68e80-ba1b-11ea-9f1d-d84eaa58f16b.png)
![isticker_1593405056827](https://user-images.githubusercontent.com/67589095/86010008-253f2500-ba1b-11ea-88be-84bab095db95.png)
![isticker_1593405533482](https://user-images.githubusercontent.com/67589095/86010011-25d7bb80-ba1b-11ea-864e-d816cca5cd2e.png)
![isticker_1593405643114](https://user-images.githubusercontent.com/67589095/86010012-26705200-ba1b-11ea-8a52-e08002c600a9.png)
![isticker_1593405842803](https://user-images.githubusercontent.com/67589095/86010014-27a17f00-ba1b-11ea-95a2-553be6ad0cfb.png)
![isticker_1593405942056](https://user-images.githubusercontent.com/67589095/86010017-283a1580-ba1b-11ea-8c67-675fb05bb44a.png)
![isticker_1593406082131](https://user-images.githubusercontent.com/67589095/86010018-296b4280-ba1b-11ea-8330-f12ec568a95b.png)
![isticker_1593406407374](https://user-images.githubusercontent.com/67589095/86010022-2a9c6f80-ba1b-11ea-9d60-5789c67d8607.png)
![isticker_1593406466174](https://user-images.githubusercontent.com/67589095/86010031-2bcd9c80-ba1b-11ea-849a-7c1abdbc0834.png)
![isticker_1593406619974](https://user-images.githubusercontent.com/67589095/86010034-2c663300-ba1b-11ea-86b1-474bec461993.png)
![isticker_1593406666586](https://user-images.githubusercontent.com/67589095/86010038-2d976000-ba1b-11ea-8ac2-5b8ec8170520.png)
![isticker_1593406795932](https://user-images.githubusercontent.com/67589095/86010040-2e2ff680-ba1b-11ea-820f-16bf0d606f26.png)
![isticker_1593406874705](https://user-images.githubusercontent.com/67589095/86010043-2ec88d00-ba1b-11ea-96b8-95285a943b3d.png)
![isticker_1593406946469](https://user-images.githubusercontent.com/67589095/86010044-2ff9ba00-ba1b-11ea-993b-b13aed220d02.png)
![isticker_1593407060627](https://user-images.githubusercontent.com/67589095/86010047-30925080-ba1b-11ea-906c-29d69861d4ed.png)
![isticker_1593407111244](https://user-images.githubusercontent.com/67589095/86010051-31c37d80-ba1b-11ea-8f32-028da5c9b8af.png)
![isticker_1593407304950](https://user-images.githubusercontent.com/67589095/86010057-338d4100-ba1b-11ea-9f25-5005707fe42a.png)
![isticker_1593407505634](https://user-images.githubusercontent.com/67589095/86010061-3425d780-ba1b-11ea-84b7-600dcf93ec6e.png)
![isticker_1593407593505](https://user-images.githubusercontent.com/67589095/86010066-35570480-ba1b-11ea-9ae0-d6ba836e38c9.png)
![isticker_1593407684201](https://user-images.githubusercontent.com/67589095/86010073-36883180-ba1b-11ea-848b-3a9693190966.png)
![isticker_1593407736067](https://user-images.githubusercontent.com/67589095/86010078-3851f500-ba1b-11ea-80ee-58ced5f0d69f.png)
![isticker_1593407798844](https://user-images.githubusercontent.com/67589095/86010085-38ea8b80-ba1b-11ea-818a-cb2903a6c7da.png)
![isticker_1593407857924](https://user-images.githubusercontent.com/67589095/86010088-3a1bb880-ba1b-11ea-9f6e-a5f312fd9607.png)
![isticker_1593407938425](https://user-images.githubusercontent.com/67589095/86010091-3b4ce580-ba1b-11ea-9114-b310ad901149.png)
![isticker_1593408058147](https://user-images.githubusercontent.com/67589095/86010096-3be57c00-ba1b-11ea-9bc0-251d4c813f66.png)
![isticker_1593408161027](https://user-images.githubusercontent.com/67589095/86010103-3d16a900-ba1b-11ea-976b-7435bea4c826.png)
![isticker_1593408376554](https://user-images.githubusercontent.com/67589095/86010109-3e47d600-ba1b-11ea-93d3-25c8b3a1a050.png)
![isticker_1593408452427](https://user-images.githubusercontent.com/67589095/86010112-3f790300-ba1b-11ea-92fd-aab888daad05.png)
![isticker_1593408506582](https://user-images.githubusercontent.com/67589095/86010116-40aa3000-ba1b-11ea-8320-d17dbe67d830.png)
![isticker_1593408679053](https://user-images.githubusercontent.com/67589095/86010121-41db5d00-ba1b-11ea-8361-5c7e593b6913.png)
![isticker_1593408742111](https://user-images.githubusercontent.com/67589095/86010128-430c8a00-ba1b-11ea-96e5-dffcac1ade69.png)
![isticker_1593433881800](https://user-images.githubusercontent.com/67589095/86010131-443db700-ba1b-11ea-886a-3b11f8d232c7.png)

**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [ ] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ ] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
[FILL 

> `
![isticker_1593392488697](https://user-images.githubusercontent.com/67589095/86009725-d72a2180-ba1a-11ea-8148-eafbaa35367f.png)
![isticker_1593392679648](https://user-images.githubusercontent.com/67589095/86009730-d8f3e500-ba1a-11ea-9ba6-f1f35baf36cf.png)
![isticker_1593397886830](https://user-images.githubusercontent.com/67589095/86009732-d98c7b80-ba1a-11ea-88f1-57a25449e2f6.png)
![isticker_1593397962055](https://user-images.githubusercontent.com/67589095/86009733-db563f00-ba1a-11ea-885d-7aa02418b0b8.png)
![isticker_1593398044782](https://user-images.githubusercontent.com/67589095/86009737-dc876c00-ba1a-11ea-9aca-545bfd4ce9ce.png)
![isticker_1593398096248](https://user-images.githubusercontent.com/67589095/86009742-ddb89900-ba1a-11ea-8d4c-056237e795e3.png)
![isticker_1593398173352](https://user-images.githubusercontent.com/67589095/86009745-dee9c600-ba1a-11ea-84e5-4d514d6f54fc.png)
![isticker_1593398355085](https://user-images.githubusercontent.com/67589095/86009754-e01af300-ba1a-11ea-9f07-073217000fe2.png)
![isticker_1593398519272](https://user-images.githubusercontent.com/67589095/86009761-e14c2000-ba1a-11ea-9fb8-35d4cc52a60a.png)
![isticker_1593398988590](https://user-images.githubusercontent.com/67589095/86009763-e27d4d00-ba1a-11ea-8cda-45be3676d57d.png)

` THE PROBLEM]

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN PLAY STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by GreyOcel0t** [comment]
Oo

**Comment by MarvinJWendt** [comment]
Hi, you have created an empty issue<sup>1</sup> in the bug-tracker of this repository<sup>2</sup>. 

The `Issue` tab of repositories on [GitHub](https://github.com) is meant to report problems with the repository or to discuss features of the project. If you have an actual issue with the repository, please [open a new issue](../issues/new) with a decent description.

Have fun exploring this repository 🎉 

<sub>If you want to know more about how to write good issues, look here: https://guides.github.com/features/issues/</sub>

---

<sup>1: Issue ⇾ Bug Report / Feature Request / etc..</sup>
<sup>2: Repository ⇾ Project</sup>
