### ISSUE TITLE
Support share sheet shortcut sharing

### ISSUE THREAD

**Issue by Idomo** [WhatsApp/stickers#652]
Hi, I know it doesn’t the right place to write about it, but the people (or should I say robots) from WhatsApp contact doesn’t really care about it.

As you all may or may not know, iOS 13 brought us an easy way to share things with specific contacts, via iMessage, AirDrop and even Telegram supports this.
A few months ago, WhatsApp finally added support to this very helpful feature (version 2.20.40) but unexpectedly, dropped it after to versions (version 2.20.42) when claiming in that version description that it “Fixed bugs.” and since than it doesn’t work anymore.

I’ve tried contacting WhatsApp and explain the issue, it took me about 20 messages that includes the explanation in a few different ways and robotic answers that asked for my phone number to check this (how it would help them? Really?) to understand I don’t have someone to talk to,
So I’m posting it here and hope that some WhatsApp developer will see it and move it on so it’ll finally work and everyone will be able to use and enjoy this feature.

Thanks,
Ido.

![image](https://user-images.githubusercontent.com/26777129/86092191-d8f4f300-bab5-11ea-8a58-ef92ead19275.jpeg)

**Comment by simonzhexu** [comment]
Hi,

Thanks for letting us know. Sorry for your experience. Could you explain what that share feature do in more detail.

Simon

**Comment by Idomo** [comment]
Hi @simonzhexu,
As you can see in the attached image, It adds the most recent peoples that you've chatted with to this line, when you touch one of them, it'll send the item you wanna share directly to this person.
Right now you have to choose WhatsApp in the line under it and search for the people you want to share with in the list that includes all of your contacts, so this feature really makes it easy to share things with the people that you most chat with.

Here there's a documentation to implement this (that is very easy to do):
https://developer.apple.com/documentation/foundation/app_extension_support/supporting_suggestions_in_your_app_s_share_extension

Please let me know if you misunderstood anything,
Ido.

**Comment by amrit-1901** [comment]
I know what feature you are talking about and we unfortunately don't have any information to release regarding this.

**Comment by Idomo** [comment]
@amrit-1901 What I’m saying is that you’ve already released it, but for some reason, 2 versions after that, you’ve removed this support by indicating the version contains “bugs fix”, what probably created another bug that made it stop working.
