### ISSUE TITLE
[Android] Animated Stickers doesn't work

### ISSUE THREAD

**Issue by PeterMX** [WhatsApp/stickers#653]
**Specifications**  
OS Version: Android 10
Device Manufacturer: LG

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
The app thrown an exception telling me Animated Stickers are not supported
but they are, https://blog.whatsapp.com/introducing-animated-stickers-qr-codes-and-more

**Reproduction Steps**  
add animated webp files as your stickers

**Head of Commit**
https://github.com/WhatsApp/stickers/commit/bb12c5b1fc95506a199acb5903d224702be8a901

**Comment by darshanpatidar1** [comment]
@PeterMX Yup I think because animated feature came like few days ago but last change in stickers github code was 2 months ago when only static stickers were supported.
Please @simonzhexu help !

**Comment by viztushar** [comment]
@darshanip is right GitHub code is only for supported for animated stickers.i guess they will release the code in few days as soon as they start rolling out the WhatsApp update.

**Comment by aihmgmal** [comment]
We're waiting for Source code application code

**Comment by Dwite** [comment]
But are there any info what format they will use? Gif or Lottie json ?

**Comment by priccis** [comment]
> But are there any info what format they will use? Gif or Lottie json ?

I received an animated sticker today. Working. It is a webp, same as before.

Here it is, zipped:

[animatedSticker.zip](https://github.com/WhatsApp/stickers/files/4900208/animatedSticker.zip)

**Comment by Nyaatech** [comment]
> @Dwite
> 
> > But are there any info what format they will use? Gif or Lottie json ?
> 
> I received an animated sticker today. Working. It is a webp, same as before.
> 
> Here it is, zipped:
> 
> [animatedSticker.zip](https://github.com/WhatsApp/stickers/files/4900208/animatedSticker.zip)

I've downloaded it but there is just a file without a format, do I need to rename it to the .webp format, or convert, or something?

**Comment by priccis** [comment]
> > @Dwite
> > > But are there any info what format they will use? Gif or Lottie json ?
> > 
> > 
> > I received an animated sticker today. Working. It is a webp, same as before.
> > Here it is, zipped:
> > [animatedSticker.zip](https://github.com/WhatsApp/stickers/files/4900208/animatedSticker.zip)
> 
> I've downloaded it but there is just a file without a format, do I need to rename it to the .webp format, or convert, or something?

Sorry for that, deleted the extension by mistake aparently. You can add it or just download this new zip.
[STK-XXXXXXX-WA0001.webp.zip](https://github.com/WhatsApp/stickers/files/4900434/STK-XXXXXXX-WA0001.webp.zip)

**Comment by Nyaatech** [comment]
> > > @Dwite
> > > > But are there any info what format they will use? Gif or Lottie json ?
> > > 
> > > 
> > > I received an animated sticker today. Working. It is a webp, same as before.
> > > Here it is, zipped:
> > > [animatedSticker.zip](https://github.com/WhatsApp/stickers/files/4900208/animatedSticker.zip)
> > 
> > 
> > I've downloaded it but there is just a file without a format, do I need to rename it to the .webp format, or convert, or something?
> 
> Sorry for that, deleted the extension by mistake aparently. You can add it or just download this new zip.
> [STK-XXXXXXX-WA0001.webp.zip](https://github.com/WhatsApp/stickers/files/4900434/STK-XXXXXXX-WA0001.webp.zip)

Still get the same result "Sticker should be a static image, no animated at the moment..." Which source code you use? the latest one?

**Comment by priccis** [comment]
> Still get the same result "Sticker should be a static image, no animated at the moment..." Which source code you use? the latest one?

I just received that sticker. I created another animated sticker and imported it into WhatsApp using an app called "Personal sticker for whatsapp" but it is static No movement. 

Then tried importing the one I received (attached) with the same app and it is static also. In conclusion, is not about file format but the way it is imported into whatsapp. Maybe a parameter is passed.

**Comment by al3bsi** [comment]
the only way to creat animated sticker via getstickerpack.com

how can did it that ?

**Comment by Khalufa** [comment]
i'm make more stickers I don't even need anyone to make stickers for me or save someone all I want to do myself

--

**Comment by edenserr** [comment]
Waiting for the source code, approximate time?

**Comment by sebasgps94** [comment]
> ¿Esperando el código fuente, tiempo aproximado?

Esperando lo mismo

**Comment by pratikbutani** [comment]
Following

**Comment by UdeeshaInduwara** [comment]
need source code too

**Comment by simonzhexu** [comment]
Hi Folks, we are figuring out the details on how to support animated stickers. Please stay tuned.

**Comment by Yaosile** [comment]
any idea how to do it even with a rooted android?

**Comment by Ola4606** [comment]
can any one make a flutter plugin the ones there are not working fine. Please chat me  here if you can: olaoluwaadeyemo7@gmail.com

**Comment by leonardo7489** [comment]
Does anyone know any way to convert a sequence of images to animated webp? or convert gif to animated webp? (Android Java/Kotlin)

**Comment by PeterMX** [comment]
With ffmpeg you can do both7:34 p. m., 16 de julio de 2020, leonardo7489 <notifications@github.com>:
Does anyone know any way to convert a sequence of images to animated webp? or convert gif to animated webp? (Android Java/Kotlin)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
Sent from Yandex.Mail for mobile: http://m.ya.ru/ymail

**Comment by kichappa** [comment]
> Does anyone know any way to convert a sequence of images to animated webp? or convert gif to animated webp? (Android Java/Kotlin)

Yeah, use photoshop and add those as frames. Save as a GIF, and convert it to webp [online].

**Comment by Ruchintha** [comment]
> @darshanip is right GitHub code is not supported for animated stickers.i guess they will release the code in few days as soon as they start rolling out the WhatsApp update.

Will we able to use the old source code or we will need edit from the beginning when the new source code is released?

**Comment by Ifah1977** [comment]
Hi All... I am sorry i am new here.. read the rules but some I dont quite understand.

I reached this page via a search to find out the issue with my animated sticker. So.. shall I ask here or I shall create a new thread on this?

Basically my issue is.. downloaded the stickerpack, converted into webp format, problem is
1. How to enable this to appear in sticker pack in whatsapp
2. Found and downloaded 1 apps from googleapps.. created new pack successfully but then it said "Animated Sticker are not Supported - Your whatsapp (2.20.200.22) does not support Animated Stickers yet. You may need to install Whatsapp Plus or Whatsapp with stickers to try Animated Stickers".

Im confused because i've checked my whatsapp version do support animated sticker. In fact I have received and resend animated sticker using my whatsapp.

Appreciate everyone help on this. If there is any other way i can get the animated sticker to be in the sticker pack in whatsapp, please do let me know. Thanks a lot in advance.

**Comment by santi-petersen** [comment]
> Hi All... I am sorry i am new here.. read the rules but some I dont quite understand.

Hi @Ifah1977 , I assume you are not a developer. This platform is more suitable for developers.
We as developers, like you as a user, are waiting for a WhatsApp update that supports **third-party** animated stickers. It's supposed to come soon.


> 2\. Found and downloaded 1 apps from googleapps.. created new pack successfully but then it said "Animated Sticker are not Supported - Your whatsapp (2.20.200.22) does not support Animated Stickers yet. You may need to install Whatsapp Plus or Whatsapp with stickers to try Animated Stickers".

I recommend that you don't use those unofficial versions of WA. Maybe a temporary solution for you could be this app: https://play.google.com/store/apps/details?id=alpha.sticker.maker

**Comment by Ifah1977** [comment]
> > Hi All... I am sorry i am new here.. read the rules but some I dont quite understand.
> 
> Hi @Ifah1977 , I assume you are not a developer. This platform is more suitable for developers.
> We as developers, like you as a user, are waiting for a WhatsApp update that supports **third-party** animated stickers. It's supposed to come soon.
> 
> > 2. Found and downloaded 1 apps from googleapps.. created new pack successfully but then it said "Animated Sticker are not Supported - Your whatsapp (2.20.200.22) does not support Animated Stickers yet. You may need to install Whatsapp Plus or Whatsapp with stickers to try Animated Stickers".
> 
> I recommend that you don't use those unofficial versions of WA. Maybe a temporary solution for you could be this app: https://play.google.com/store/apps/details?id=alpha.sticker.maker

Hi Santi,

You are correct.. i am not a developer. I am only user with very minimal knowledge on IT related thing because of my interest in IT. Thanks for the suggestion. I've tried but it does not allow to add from source other than those available in it's option. Namely.. Import from GIF, Import from GIPHY, Import video (beta), Take from camera (beta). The file I converted to webp does not appear in any of those. I converted in and saved it locally in document folder. As this is a customised animated sticker.

The first apps which i found which can add the webp file i have prepared but unable to add to whatsapp was Animated Sticker Maker for WA WAStickerApps (by Let Sticker Team). The only issue with this is it could not add my sticker pack to my whatsapp. The rest are ok.

Thank you for highlighting that this platform is for developer. Really appreciate and I realise it since many postings here are talking more jargons which I dont quite understand. It's just I do not know where else to ask. Try to find solution but to no avail. Perhaps anyone here can develop an apps that can help with this. :D.

Thanks again. If there is any solution to this.. please do let me know.

**Comment by X-Brayan-X** [comment]
> > > @darshanip tiene razón. El código de GitHub no es compatible con las pegatinas animadas. Supongo que lanzarán el código en unos días tan pronto como comiencen a implementar la actualización de WhatsApp.
> > 
> > 
> > ¿Podremos utilizar el código fuente anterior o necesitaremos editarlo desde el principio cuando se publique el nuevo código fuente?
> 
> Edité el código fuente antiguo para admitir pegatinas animadas, pequeños cambios. ¡Así que puedes!

Hi, how to make animated sticker app? do u have any source code?

**Comment by Rajeshkumar02** [comment]
> @darshanip is right GitHub code is not supported for animated stickers.i guess they will release the code in few days as soon as they start rolling out the WhatsApp update.

pls release the code as soon as posible..

**Comment by simonzhexu** [comment]
animated sticker support is out, please get the latest from the repo.
