### ISSUE TITLE
insted of webp use other formate for animated stickers 

### ISSUE THREAD

**Issue by SauravDharwadkar** [WhatsApp/stickers#674]
whatsapp app have 300k limitation on sticker and its ok sticker must be efficient to transfer but webp sticker use lot of size if try to make animated sticker on other hand telegram uses own tgs which have 60fps ,  3 sec  limitation , less than 60kb hd stickers nice and smooth 

https://github.com/TelegramMessenger/bodymovin-extension
 i trying to port tsg -> gif -> webp , it loss too much quality / fps , to make size under 300k

**Comment by SauravDharwadkar** [comment]
here update 8kb tgs -> gif -> webp(95% loss quality , 10fps) barely  <300k

**Comment by PeterMX** [comment]
I think AVIFS is a better option than webp. While tgs is small and smooth I would not like it for WA stickers, because tgs posibilities are very limited, and tgs are harder to make than webp or avifs
