### ISSUE TITLE
Animated stickers support [iOS]

### ISSUE THREAD

**Issue by StackHelp** [WhatsApp/stickers#677]
Is there any methods to support animated stickers for iOS. I have checked Android thread and there is a way of doing it but can't find anything in an iOS. Also found one app that adds Whatsapp stickers using some method. So, Is that any way currently?

**Comment by simonzhexu** [comment]
iOS animated sticker support will be similar to Android. We are working on it. Will post out updates when we are ready. Thanks for asking.

**Comment by ckw1** [comment]
any update on the support of ios?

**Comment by spilger** [comment]
When will the option of adding animated stickers be ready?

**Comment by sbarex** [comment]
I try to add support for animated webp stickers but when submitted to whatsapp the program show an error and fail to import.
I suppose the json data require others fields to handle animated stickers.

**Comment by spilger** [comment]
I had the same issue as @sbarex . When will the iOS Version of WhatsApp support the import of animated Stickers?

**Comment by sbarex** [comment]
I seem to guess that whatsapp does not intend to support this feature ...

**Comment by Zandor300** [comment]
@sbarex

> I am actively working on this. When it is out, it will be out. Sorry, I cannot commit the timeframe. But when this is ready, I will post the guidelines, update the this app and I will post to this thread.

See https://github.com/WhatsApp/stickers/issues/732#issuecomment-773682250

**Comment by simonzhexu** [comment]
https://github.com/WhatsApp/stickers/wiki/Animated-Stickers
