### ISSUE TITLE
Add complex issues to hacktoberfest

### ISSUE THREAD

**Issue by pratikbutani** [WhatsApp/stickers#695]
Please add all the issues with label hacktoberfest.

**Comment by MarvinJWendt** [comment]
I'd love that! 😄  
@simonzhexu could you, create a `Hacktoberfest` label? I would then label suitable issues.

More information about Hacktoberfest: https://hacktoberfest.digitalocean.com/

**Comment by pratikbutani** [comment]
> I'd love that! 😄
> @simonzhexu could you create a `Hacktoberfest` label? I would then label suitable issues.
> 
> More information about Hacktoberfest: https://hacktoberfest.digitalocean.com/

It will be a great help from all the developers.

**Comment by simonzhexu** [comment]
Done!

**Comment by pratikbutani** [comment]
> Done!

Done? You haven't given the label `hacktoberfest` to all issues. Give it so everyone can find your issues by searching,

**Comment by MarvinJWendt** [comment]
@pratikbutani Simon added the label to the repository. Now I can add them to the issue, like I said.
I don't think that every issue should have the Hacktoberfest label. I will look which ones fit into Hacktoberfest :)
