### ISSUE TITLE
Android 10 - There's a problem with this sticker pack and it can't be added to WhatsApp

### ISSUE THREAD

**Issue by Nullstr1ng** [WhatsApp/stickers#699]
**Problem Description**  
We had an app in Play Store and in App Store which is called BMoji and now we are getting messages from our end-users that they cannot add the free stickers we provide because it's showing an error message. The app is written in Xamarin.Forms by the way.  
  
![image](https://user-images.githubusercontent.com/260633/95524941-514c4800-0a05-11eb-88c2-0ff5e5ccfc99.png)
  
[Continuation](#continuation) 

**Specifications**  
OS Version: Android 10.0
Device Manufacturer: Not sure if this is really a device specific issue, but ok, It's Xiaomi
WhatsApp version: 2.20.200.22

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ ] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for stickers.

# Continuation
I investigated the issue and I am confused why our stickers can be exported with no issue I use a device with Android 9.0 and when I use a device with Android 10.0 I am getting that error message. Further investigation, I tried exporting the stickers one by one until I reach the the sticker that doesn't work.  
  
i.e. this is one of our stickers  
This works fine in both Android 9 and 10
![image](https://bmojirgproddiag.file.core.windows.net/freebmojis/b37d1cfb-a062-4e6a-bc49-627ec0790223.png?sv=2019-02-02&ss=bfqt&srt=sco&sp=rlap&se=2022-12-30T17:13:47Z&st=2020-01-01T09:13:47Z&spr=https&sig=tqVlq9lmIuXB7%2FdnYG35PUbl1doWVKq31QDxTxqwtl4%3D&637377143494526367)
sticker name: b37d1cfb-a062-4e6a-bc49-627ec0790223Essel.png
https://bmojirgproddiag.file.core.windows.net/freebmojis/b37d1cfb-a062-4e6a-bc49-627ec0790223.png?sv=2019-02-02&ss=bfqt&srt=sco&sp=rlap&se=2022-12-30T17:13:47Z&st=2020-01-01T09:13:47Z&spr=https&sig=tqVlq9lmIuXB7%2FdnYG35PUbl1doWVKq31QDxTxqwtl4%3D&637377143494526367
  
This does not work in Android 10 but I can export it in Android 9
![image](https://bmojirgproddiag.file.core.windows.net/freebmojis/46984000-6953-49e6-9646-2c8243c23941.png?sv=2019-02-02&ss=bfqt&srt=sco&sp=rlap&se=2022-12-30T17:13:47Z&st=2020-01-01T09:13:47Z&spr=https&sig=tqVlq9lmIuXB7%2FdnYG35PUbl1doWVKq31QDxTxqwtl4%3D&637377143494526367)
sticker name: 46984000-6953-49e6-9646-2c8243c23941Palette.png
https://bmojirgproddiag.file.core.windows.net/freebmojis/46984000-6953-49e6-9646-2c8243c23941.png?sv=2019-02-02&ss=bfqt&srt=sco&sp=rlap&se=2022-12-30T17:13:47Z&st=2020-01-01T09:13:47Z&spr=https&sig=tqVlq9lmIuXB7%2FdnYG35PUbl1doWVKq31QDxTxqwtl4%3D&637377143494526367
  
and so much more from our API with the same sticker naming.  
  
**Links**  
Bmoji in Play Store  
https://play.google.com/store/apps/details?id=com.thebmoji.bmojiapp&hl=en_US  
  
Bmoji in App Store  
https://apps.apple.com/us/app/bmoji/id1428776532

What's making it hard is I have no clue what's causing it. I have already enabled all possible messages that could help
![image](https://user-images.githubusercontent.com/260633/95528993-56f95c00-0a0c-11eb-8fca-b9d2d745c52b.png)
  
output verbosity is already set to Diagnostics.
    
Here's the logcat related to WhatsApp
![image](https://user-images.githubusercontent.com/260633/95529830-a2146e80-0a0e-11eb-901f-14294732bf80.png)

**Comment by alex193a** [comment]
The problem is due to the size of one or more stickers which must be less than 100 kB.

**Comment by gkp1** [comment]
> The problem is due to the size of one or more stickers which must be less than 100 kB.

This affirmation is wrong. I have the problem described, in whatsapp business, and none of the 3 stickers I'm adding are over 30kb.

I tried 4 different sticker apps. Android 10

The weird thing is that, after I switched to WBusiness a few days ago, I was able to add stickers and all worked normally. Now adding non-stock packs doesn't work at all.
