### ISSUE TITLE
[Android] Add to whatsapp button unresponsive

### ISSUE THREAD

**Issue by seth-rah** [WhatsApp/stickers#7]
## Summary

Uncertain if this is relevant to the sample app or Whatsapp support

Selecting the add to Whatsapp button is not returning any feedback to me, and I am unable to find the stickerpack in Whatsapp.

The button just registers a press event and does nothing further

Phone used in test: Samsung Galaxy S2
Android version 4.1.2

```java
10-27 12:17:08.901 2137-2205/? I/InputReader: Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.17562 ]
10-27 12:17:08.901 2137-2204/? I/InputDispatcher: Delivering touch to current input target: action: 0x0
10-27 12:17:08.901 2137-2204/? I/InputDispatcher: Delivering touch to current input target: action: 0x0
10-27 12:17:08.901 2137-2204/? I/InputDispatcher: Delivering touch to current input target: action: 0x0
10-27 12:17:08.951 2137-2205/? I/InputReader: Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=]
10-27 12:17:08.951 2137-2204/? I/InputDispatcher: Delivering touch to current input target: action: 0x1
10-27 12:17:08.956 2137-2204/? I/InputDispatcher: Delivering touch to current input target: action: 0x1
10-27 12:17:08.956 2137-2204/? I/InputDispatcher: Delivering touch to current input target: action: 0x1
10-27 12:17:08.961 2137-24031/? I/power: *** acquire_dvfs_lock : lockType : 1  freq : 1000000 
10-27 12:17:08.961 2137-24031/? D/PowerManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1000000  uid : 1000  pid : 2137  tag : ActivityManager
10-27 12:17:08.961 2137-24031/? W/ActivityManager: mDVFSLock.acquire()
10-27 12:17:09.001 2137-2635/? D/WindowManager: PhoneWindowManager: focusChangedLw
10-27 12:17:09.001 2137-2635/? D/KeyguardViewMediator: setHidden false
10-27 12:17:09.001 2137-2635/? D/WindowManager: mInputFocus is not null.
10-27 12:17:09.001 2137-2635/? D/WindowManager: mInputFocus is not null.
10-27 12:17:09.001 2137-2635/? D/WindowManager: mInputFocus is not null.
10-27 12:17:09.016 2137-2879/? D/WindowManager: PhoneWindowManager: focusChangedLw
10-27 12:17:09.016 2137-2879/? D/WindowManager: mInputFocus is not null.
10-27 12:17:09.041 2137-2149/? D/KeyguardViewMediator: setHidden false
10-27 12:17:09.041 2137-2195/? D/KeyguardViewMediator: setHidden false
10-27 12:17:09.041 2137-2340/? W/InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@42c7a008 attribute=null
10-27 12:17:09.056 2137-2195/? D/KeyguardViewMediator: setHidden false
10-27 12:17:09.056 2137-2137/? D/KeyguardViewMediator: setHidden false
10-27 12:17:09.961 2137-2178/? I/power: *** release_dvfs_lock : lockType : 1 
10-27 12:17:09.961 2137-2178/? D/PowerManagerService: releaseDVFSLockLocked : all DVFS_MIN_LIMIT are released 
10-27 12:17:09.961 2137-2178/? W/ActivityManager: mDVFSLock.release()
```

Please assist.

## Edit

Whatsapp beta is required for this to work, however I feel the app should be responsive in telling the user that Beta is required if the install button is being unresponsive.

**Comment by seth-rah** [comment]
When the add to Whatsapp button is selected, the following error is shown in the logs

```java
10-27 16:08:48.272 7599-7599/com.sethdistro.whatsappstickers1 E/dalvikvm: Could not find class 'android.support.v4.app.ActivityCompat$SharedElementCallback21Impl', referenced from method android.support.v4.app.ActivityCompat.setEnterSharedElementCallback
10-27 16:08:48.277 7599-7599/com.sethdistro.whatsappstickers1 E/dalvikvm: Could not find class 'android.support.v4.app.ActivityCompat$SharedElementCallback21Impl', referenced from method android.support.v4.app.ActivityCompat.setExitSharedElementCallback
10-27 16:08:48.342 7599-7599/com.sethdistro.whatsappstickers1 E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
10-27 16:08:48.342 7599-7599/com.sethdistro.whatsappstickers1 E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length```

**Comment by denilchungath** [comment]
For me it shows sending to Whatsapp when I click on add to Whatsapp button but gets stuck there. Nothing further happens and sticker pack does not appear in Whatsapp

**Comment by seth-rah** [comment]
Upon investigation, this repo does not compile unless I am using Android 9 SDK (Latest)

Are some calls being made that require the newest version of Android?

**Comment by falcon283** [comment]
After some pain, I'm new to Android, I was able to build and run on the emulator.
I then tried on a real Device but I confirm that nothing happen when I tap add.

In order to build, latest Android Studio, I renamed the package, updated the Manifest (package), and the build.gradle applicationId. That values have to match.

Any suggest on how to make it work the add button? I'm totally new to Android

**Comment by SamirMokiem** [comment]
I had this problem to. It worked after i updated my whatsapp. If you cant update, sign up for the whatsapp beta (https://play.google.com/apps/testing/com.whatsapp/)

**Comment by seth-rah** [comment]
Whatsapp Beta has allowed the pack to install

Sending stickers seems to be a bit buggy at the moment, but I will leave that as Whatsapps fault.

I will be keeping this issue open though, the documentation for this repository should be updated stating that whatsapp beta is a requirement right now. As nowhere this is mentioned.

**Comment by SamirMokiem** [comment]
i think whatsapp doesn't update the app on all the android devices. but instead do it in waves. (Maybe android 9 first, android 8 second). Someone i am testing this with, didnt need the beta to do it. he could install the update as normal. I (samsung s7) needed to enter to the beta

**Comment by falcon283** [comment]
Oh boy!!! you are right ... I have no Real Device with me so I had to use HockeyApp and a remote tester to verify it actually works!!
There are people on the Play Store that actually complains the lack of stickers. Maybe they are just doing a phased release. Finger crossed

**Comment by andyleekp** [comment]
If you want to make the "Add to whatsapp" button responsive, you have to register to be a whatsapp beta tester in https://play.google.com/apps/testing/com.whatsapp . Then you will receive a update from play store and update to the beta version. The button will be responsive in this whatsapp version.

**Comment by fduraibi** [comment]
> For me it shows sending to Whatsapp when I click on add to Whatsapp button but gets stuck there. Nothing further happens and sticker pack does not appear in Whatsapp
> Tested on Xiaomi Mi A1 running Android Pie (SDK 28)

I had a similar issue, and after further testing I found the problem was caused by some of the webp images I created with GIMP with lossless compression.
After re-saving the same images with 90% compression it worked like a charm
