### ISSUE TITLE
You still have to change some flags in source to get it work , but after that works great

### ISSUE THREAD

**Issue by bimstark** [WhatsApp/stickers#701]
You still have to change some flags in source to get it work , but after that works great

_Originally posted by @SauravDharwadkar in https://github.com/WhatsApp/stickers/pull/666#issuecomment-671933541_

You could say
 what changes did you make to be able to work, i'm trying here for days and i haven't got it yet.

**Comment by SauravDharwadkar** [comment]
Try to downgrade WhatsApp , i haven't checked this in long time

**Comment by SauravDharwadkar** [comment]
https://github.com/WhatsApp/stickers/pull/666/files/8e81a1342af5496293c0f57051165b0926535587

Try this changes maybe it will work
