### ISSUE TITLE
[Android 11] Pure AOSP: Sticker pack not added. If you'd like to add it make sure you update to the latest version of WhatsApp.

### ISSUE THREAD

**Issue by D4rK7355608** [WhatsApp/stickers#707]
**Specifications**  
OS Version: [11 (RD1A.200810.021.A1)]
Device Manufacturer: [Xiaomi]

**Stickers**
- ✓  My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- ✓ My tray icon does comply with the requirements (96x96 and < 50 KB)
- ✓  I am using **WebP** images for stickers.

**Problem Description**  
["Sticker pack not added. If you'd like to add it make sure you update to the latest version of WhatsApp." when I press to add stickers..]

**Links**  
[https://github.com/D4rK7355608/com.d4rk.stickers]

Temp fix: set target SDK to 29.

**Comment by MarcoReckless** [comment]
I had a similar problem, some of my users reported that pressing pressing the '+' button does nothing, only on Android 11.

**Comment by D4rK7355608** [comment]
> I had a similar problem, some of my users reported that pressing pressing the '+' button does nothing, only on Android 11.

Sad... I really don't know what I can do..

**Comment by simonzhexu** [comment]
Have you upgraded your app to API 30?
If so, you need to add this to your manifest


```
<!-- to be able to query the whitelist status in WhatsApp
     https://developer.android.com/training/basics/intents/package-visibility#package-name -->
    <queries>
        <package android:name="com.whatsapp" />
        <package android:name="com.whatsapp.w4b" />
    </queries>
```

**Comment by simonzhexu** [comment]
fixed in ed1ee71cff71bd109a31a630e7a0fc0c2ee0e2db

**Comment by ananddvn04** [comment]
what is the fix?

**Comment by SaifKhanBabar** [comment]
i recently upgraded to API33 and now my sticker pack can not e added, giving me this error. i see answer from @simonzhexu  to add that code in manifest, i am trying to add but studio gives me error, (either i am not placing at correct place, if so kindly teach me how and where to put) or thats not solving the issue. kindly assist me so that i could upload my pack again.
