### ISSUE TITLE
![wasamplesticker](https://user-images.githubusercontent.com/44590877/47685811-13273680-dbe9-11e8-8da4-c5d0279f8942.png)

### ISSUE THREAD

**Issue by hasan8787** [WhatsApp/stickers#71]
_Originally posted by @hasan8787 in https://github.com/WhatsApp/stickers/commit/8465bbc3e7e3001cdb4112d522e1ea0a04088219#commitcomment-31094818_

**Comment by simonzhexu** [comment]
This is an abuse. We have reported.
