### ISSUE TITLE
I got it here, thanks. Now let me tell you, is there a possibility that the stickers will move here on this screen?

### ISSUE THREAD

**Issue by Tarcisiobim** [WhatsApp/stickers#710]
Is there a solution for that? The stickers move on the screen.

I got it here, thanks. Now let me tell you, is there a possibility that the stickers will move here on this screen?
![WhatsApp Image 2020-11-03 at 16 52 49](https://user-images.githubusercontent.com/73193060/98034472-cee15900-1df5-11eb-8674-ea86b0dfa63c.jpeg)

_Originally posted by @bimstark in https://github.com/WhatsApp/stickers/pull/666#issuecomment-721344743_

**Comment by diegulog** [comment]
just add this in StickerPreviewAdapter

```
Drawable drawable = stickerPreviewViewHolder.stickerPreviewView.getDrawable();
 if (drawable instanceof Animatable) {
      ((Animatable) drawable).start();
 }
```

**Comment by Tarcisiobim** [comment]
Thanks. I'll try here, if I did it, I'll come and let you know. Still,
thank you very much, my friend.

Em qui., 5 de nov. de 2020 às 11:44, Diego Guaña <notifications@github.com>
escreveu:

**Comment by Tarcisiobim** [comment]
I'm new to this. Could you help me again? It is showing an error.


[image: image.png]

Em sex., 6 de nov. de 2020 às 13:18, Tarcisio Azevedo <
holistica.tarcisio@gmail.com> escreveu:

**Comment by simonzhexu** [comment]
Official support will come.
