### ISSUE TITLE
Search engine for stickers

### ISSUE THREAD

**Issue by vvHacker007** [WhatsApp/stickers#717]
**Specifications**  
OS Version: [10 (QKQ1.190910.02)]
Device Manufacturer: [Xiamoi]

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for stickers.

**Problem Description**
A search bar for stickers to search stickers with names. We can use appropriate models to classify and caption stickers. This can help in reducing time for scrolling through stickers to find them. Instead the user can just search them thought the search bar.

**Comment by simonzhexu** [comment]
We have launched sticker search, could you tag your sticker with corresponding emojis, https://github.com/WhatsApp/stickers/issues/703#issuecomment-745696947
