### ISSUE TITLE
[Android] [Animated Stickers] total duration should be under 10000 ms 

### ISSUE THREAD

**Issue by santi-petersen** [WhatsApp/stickers#718]
**Specifications**  
OS Version: Android 6.0.1
Device Manufacturer: Samsung SM-G900H

**Animated Stickers**
- [X] My stickers do comply with the **animated** sticker requirements (512x512, < **500 KB** and < **60000 ms**)
- [X] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [X] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
@simonzhexu 
With the latest version of WhatsApp (2.20.205.16) on some devices (Samsung SM-G900H) when I add an animated sticker pack, it always returns **"total duration should be under 60000 ms "**. The animated stickers have 2 or 3 seconds (not more than 60 sec).
The same stickers can be added without errors on other devices or with older versions of WhatsApp.

**Reproduction Steps**  
1) install WhatsApp (2.20.205.16) on a rooted Samsung SM-G900H enabling animated stickers.
2) try to add a valid animated pack

**Comment by santi-petersen** [comment]
@simonzhexu I have more info about the error. The reason for the failure is the webp loop. If the loop is 0 (infinity), it takes the time of the animated sticker as infinity and WhatsApp returns the error of 60000 ms. If I change the loop of the webp to 1, it works.

**Comment by simonzhexu** [comment]
do you mind attaching the webp file?

**Comment by santi-petersen** [comment]
> do you mind attaching the webp file?

I don't know what do you mean with "attaching". The problem is when you try to add the animated pack to WhatsApp. 
I cannot try it any more with the latest version of WhatsApp because now it is not posible to edit the com.whatsapp_references.xml file enabling third_party_animated_sticker.
But, using the WhatsApp version 2.20.205.16 (and newer ones) on some devices, WhatsApp returns the error **"total duration should be under 60000 ms"** (screenshot attached) and there is nothing wrong with the animated webp file. 
The attached screenshot is for a Samsung SM-G900H, the same pack can be imported on many other devices, included the Samsung SM-G900M (very similar device)

![20210125_150403](https://user-images.githubusercontent.com/53949614/105749724-92b82300-5f22-11eb-8835-1fcb542c9542.jpg)

**Comment by santi-petersen** [comment]
> do you mind attaching the webp file?

Sorry, I read in a hurry! Yes, I can attach the sticker of the example, but the problem is with all animated stickers...


[sticker_1_VLP3BO33B9.zip](https://github.com/WhatsApp/stickers/files/5869144/sticker_1_VLP3BO33B9.zip)

**Comment by santi-petersen** [comment]
@simonzhexu This error still occurs in the latest version of WhatsApp (**2.21.2.18**), at least with the device **Samsung SM-G900H**. In my other testing devices works fine.
With the Samsung SM-G900H, it works using an old WhatsApp version (2.20.196.16) in a rooted device and changing the device date -because that version is expired-. But from version 2.20.205.13 or higher it fails.

**Comment by JeremyR34** [comment]
I had exactly the same issue on one device (Samsung J7 - SM-J710N, Android 8.1.0) by testing the sample app.
My WhatsApp version is 2.21.3.20.
I miraculously get rid of the issue, by adding the first packages of stickers (flat ones), then the animated one, it does not generate any issue this time.
I did not have this issue at all on 2 other devices.

**Comment by JeremyR34** [comment]
Additional information: I reproduced the issue on a new brand app containing only animated sticker.
The first try generates the following error:
E/AddStickerPackActivity: Validation failed:total animation duration should be under 10000 ms. sticker: /stickers_asset/emoji_1/1_grinning_face.webp

Second try worked fine. By try I mean clicking on Add to WhatsApp button.

**Comment by santi-petersen** [comment]
> Additional information: I reproduced the issue on a new brand app containing only animated sticker.
> The first try generates the following error:
> E/AddStickerPackActivity: Validation failed:total animation duration should be under 10000 ms. sticker: /stickers_asset/emoji_1/1_grinning_face.webp
> 
> Second try worked fine. By try I mean clicking on Add to WhatsApp button.

In the latest version of WhatsApp (2.21.3.20) the time is 10000 ms (not 60000 ms). I have tested it on many different devices and I can say that:
1) on some devices the error always occurs and there is no way to add the stickers.
2) on other devices it is random and you can fix it by forcing WhatsApp to close and trying again. In a few cases it works trying again without forcing close.
3) and sometimes you can only fix it by reinstalling WhatsApp.

**Comment by santi-petersen** [comment]
@simonzhexu I don't know if it is an error when you guys are trying to measure the duration of the webp animation or if it is the default message in a big switch of error messages. Because measuring the duration of a webp shouldn't be complicated.

**Comment by MarsVard** [comment]
@santi-petersen Maybe you can attach your sticker files here?

**Comment by BattleShipPark** [comment]
same with me. I have the message "total animation duration should be under 10000 ms." from onActivityResult.

1. Galaxy J5 (2017) / Android 8.1.0 / WA 2.21.4.22
[-1311601747.webp.zip](https://github.com/WhatsApp/stickers/files/6088987/-1311601747.webp.zip)

2. Galaxy J6 / Android 10 / WA 2.21.3.19
[-689472034.webp.zip](https://github.com/WhatsApp/stickers/files/6088989/-689472034.webp.zip)

**Comment by simonzhexu** [comment]
OK. Thanks for providing the files and letting me know. I will try to repro.

**Comment by simonzhexu** [comment]
> > Additional information: I reproduced the issue on a new brand app containing only animated sticker.
> > The first try generates the following error:
> > E/AddStickerPackActivity: Validation failed:total animation duration should be under 10000 ms. sticker: /stickers_asset/emoji_1/1_grinning_face.webp
> > Second try worked fine. By try I mean clicking on Add to WhatsApp button.
> 
> In the latest version of WhatsApp (2.21.3.20) the time is 10000 ms (not 60000 ms). I have tested it on many different devices and I can say that:
> 
> 1. on some devices the error always occurs and there is no way to add the stickers.
> 2. on other devices it is random and you can fix it by forcing WhatsApp to close and trying again. In a few cases it works trying again without forcing close.
> 3. and sometimes you can only fix it by reinstalling WhatsApp.



> I had exactly the same issue on one device (Samsung J7 - SM-J710N, Android 8.1.0) by testing the sample app.
> My WhatsApp version is 2.21.3.20.
> I miraculously get rid of the issue, by adding the first packages of stickers (flat ones), then the animated one, it does not generate any issue this time.
> I did not have this issue at all on 2 other devices.

Could you provide the webp file? @JeremyR34

**Comment by JeremyR34** [comment]
Sure here it is.
But I do not think it is related to a specific webp file. When a package failed to be added, it is always the first file in the package that failed; and a second try could work without any change to the file.

[1_grinning_face.webp.zip](https://github.com/WhatsApp/stickers/files/6111066/1_grinning_face.webp.zip)

**Comment by tiagocanto01** [comment]
The same problem here, I'm from Brazil and should be working now. Debugging, I notice that the problem happen even before send the files. If you just turn on the animated_sticker flag, the error happens.

**Comment by santi-petersen** [comment]
Hi @simonzhexu , any progress on this? I get a lot of complaints related to this bug from users with many different devices, usually low-end phones.

**Comment by santi-petersen** [comment]
Some devices with this issue reported by users:

TCT (Alcatel) TETRA
Motorola Moto G (5th Gen)
Motorola moto g fast
Blu Studio J1
Samsung Galaxy A01 Core
Samsung Galaxy J5 Prime
Samsung Galaxy A20

Sometimes the issue starts to occur a day or two after the user stars addidg third-party stickers.

**Comment by JeremyR34** [comment]
@simonzhexu I have a test phone where the problem happens regularly (a Samsung Galaxy J7 - SM-9710FN).
If you want to provide me some test apk, and/or to generate some logs, I will be more than happy to help.
As other developers mentioned I've got lot of complaints from users that was unable to add animated stickers.
Will try to add some analytics here to provide a better map of compiant/problematic device models.

**Comment by santi-petersen** [comment]
Hello @simonzhexu , I add more devices of user reporting this bug in the last few days.

Samsung Galaxy M30s
Samsung Galaxy M01s
Samsung Galaxy Tab A (8.0", 2019)
Samsung Galaxy J6+
Samsung Galaxy J7 Neo
Samsung Galaxy A31
Vivo vivo 1915
TCT (Alcatel) 4047X
LGE LG Q60
LGE LG K8 (2017) Dual
Motorola moto e⁶ˢ


**This problem is having a very negative impact on the rating of our apps.** The users become very furious when they can't add the stickers.
I also offer my help to carry out the tests you need on the devices with the error.
As I said before, this error stated with versions of WhatsApp highers to 2.20.196.16. Probably when you added the duration restrictions (first to 60000ms and then to 10000ms)

**Comment by santi-petersen** [comment]
@simonzhexu , more devices with this error reported by users in the last week:

Samsung Galaxy A11
Samsung Galaxy Tab4 8.0
Samsung Galaxy Note10+
Samsung Galaxy J4 Core
Samsung Galaxy J6
Samsung Galaxy A01 Core
Samsung Galaxy A21s
Samsung Galaxy A30
Huawei HUAWEI P20 Lite
Huawei 荣耀 8X
Motorola moto g(7) play
Motorola moto e(5) plus
Xiaomi Redmi 6 Pro
LGE LG X max
Sky Devices Platinum_J5
POCO X3 NFC
Realme realme 3Pro

**Comment by JeremyR34** [comment]
Here are some first results of a week of analytics.
All these devices have failed to add animated stickers at least twice with the current error.

[Failed_devices.csv](https://github.com/WhatsApp/stickers/files/6383087/Failed_devices.csv)

**Comment by BattleShipPark** [comment]
Any updates?

**Comment by runnableapps** [comment]
Any updates?

**Comment by simonzhexu** [comment]
Sorry for the late updates, have been busy with some internal stuff, I will take a look at this this week.

**Comment by simonzhexu** [comment]
There was a bug in WhatsApp. Sorry guys. The fix has landed yesterday. Beta users will be getting it today, and public release users will be getting that in 10 days or so.

**Comment by simonzhexu** [comment]
We are still a small team, so I have to prioritize many internal things, sorry this was there for so long. I did not know how severe it was and it was only reproducible for some devices, and our QA did not see it either. Sad there isn't a priority thing in github issues, but if things like this happen for many of you, please just keep shouting. Also, you can help by joining WhatsApp:) https://www.facebook.com/careers/jobs/?q=whatsapp

**Comment by BattleShipPark** [comment]
Thanks @simonzhexu . Can I have the version that the fix is included? I need to inform users the specific version.

**Comment by simonzhexu** [comment]
2.21.11.5 will do.
