### ISSUE TITLE
[Android] whatsapp sticker app just getting crushes in android 9.0

### ISSUE THREAD

**Issue by DRMudassar1** [WhatsApp/stickers#720]
**Specifications**  
OS Version: [9.0]
Device Manufacturer: [Android]

**Stickers**
- [ ] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ ] I am using **WebP** images for stickers.

**Problem Description**  
[app is getting crush too much in android 9.0 only. and few other devices. when app started it give crush in on create activity. but app is also working good in my device i have also test on other devices but it working well but i am getting reviews for getting crush. also i have attached the google crush analysis. 
here is my app playstore link: https://play.google.com/store/apps/details?id=com.digitech.whatsappsticker
if anyone know how to solve help me.]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[https://play.google.com/store/apps/details?id=com.digitech.whatsappsticker]
![WhatsApp Image 2020-11-29 at 11 44 51 AM (2)](https://user-images.githubusercontent.com/75196648/100535263-1d3d1880-3239-11eb-9a2c-34b9fe684a49.jpeg)
![WhatsApp Image 2020-11-29 at 11 44 51 AM (1)](https://user-images.githubusercontent.com/75196648/100535264-1f06dc00-3239-11eb-9c62-ba4ca6ba3ac8.jpeg)
![WhatsApp Image 2020-11-29 at 11 44 51 AM](https://user-images.githubusercontent.com/75196648/100535265-20380900-3239-11eb-9044-8de8bd596330.jpeg)

**Comment by simonzhexu** [comment]
is this still an issue @DRMudassar1

**Comment by cpinan** [comment]
Closing this task as there are no repro steps
