### ISSUE TITLE
Boy with hands on wait in surprise...by confidence ogedegbe

### ISSUE THREAD

**Issue by IAmOgedegebe** [WhatsApp/stickers#727]
![dcc5e06c3ce3572c315aaa44a56738ab](https://user-images.githubusercontent.com/63166226/104152147-09133c00-53df-11eb-8007-ac8765fc0b38.jpg)
![66814c7b5d61ddd50067f9823ada21e8](https://user-images.githubusercontent.com/63166226/104152151-0a446900-53df-11eb-9a09-636cb72f7dc4.jpg)
![Uploading 31d81a24d23147de8244215d6ec56e50.jpg…]()

**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [ ] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ ] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
[FILL IN WITH DETAILED DESCRIPTION OF THE PROBLEM]

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN PLAY STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by Zandor300** [comment]
Hi, you have created an empty issue1 in the bug-tracker of this repository2.

The `Issue` tab of repositories on [GitHub](https://github.com) is meant to report problems with the repository or to discuss features of the project. If you have an actual issue with the repository, please [open a new issue](../issues/new) with a decent description.

Have fun exploring this repository 🎉

If you want to know more about how to write good issues, look here: https://guides.github.com/features/issues/

1: Issue ⇾ Bug Report / Feature Request / etc..
2: Repository ⇾ Project
