### ISSUE TITLE
it can't be added to Whatsapp

### ISSUE THREAD

**Issue by iMEiD** [WhatsApp/stickers#73]
**i did everything right but when i want to add stickers to Whatsapp this massage come

anyone can help ?** 

![img_4378](https://user-images.githubusercontent.com/44593286/47689894-f0068200-dbfc-11e8-94f5-85aae2c0834c.jpg)

**Comment by GlowMLG** [comment]
Check the size of the stickers. I had the same error until I compressed them to 10-20KB

**Comment by iMEiD** [comment]
@GlowMLG thank you very much it works now 👍
