### ISSUE TITLE
[iOS] One of the stickers in this sticker pack has an invalid asset

### ISSUE THREAD

**Issue by guidev** [WhatsApp/stickers#730]
**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
I get this error for all webp images.

**Reproduction Steps**  
I've attached a sample project that reproduces the issue constantly (with the latest version of WhatsApp)

**Links**  

https://github.com/guidev/test-whatsapp-stickers

**Comment by guidev** [comment]
@simonzhexu any insight?

**Comment by Zandor300** [comment]
@guidev Some webp exporters aren't supported. In the iOS README, there are some tips on how to solve this. Could you try this and report back with your results?

See https://github.com/WhatsApp/stickers/tree/c91bab995ebc177e3de63c5bbb735ee258b60292/iOS#converting-to-webp

> It is recommended to use the WebP format for your sticker art. We recommend using the tools you're most comfortable with to draw and compose your art, and converting them to WebP using one of a few different tools:
> 
> * Sketch for Mac lets you export files as WebP. Open your sticker art file in Sketch, select a layer, multiple layers, or an artboard, and select Make Exportable in the bottom right. Pick your format as WebP, select Export, and then select the quality/resolution.
> * [Android Studio](https://developer.android.com/studio/) allows you to convert PNGs to WebP. Simply create a New Project in Android Studio, open your PNG and right click on the image and select convert to WebP ([https://developer.android.com/studio/write/convert-webp](https://developer.android.com/studio/write/convert-webp)). Make sure you uncheck the box next to "Skip images with transparency/alpha channel" in the export flow.
> * You can install a [plugin](https://github.com/fnordware/AdobeWebM#download) for Photoshop that converts to WebP. Make sure to uncheck the "Save Metadata" checkbox.
> * Use [cwebp](https://developers.google.com/speed/webp/), a command line tool
> * Use [squoosh](https://squoosh.app/), an online browser tool, by the Google Chrome Labs
> 
> **Important note about using PNG images**
> Xcode does some optimizations to every PNG image that is imported. This can lead to files becoming bigger in size and not passing our image size requirement. To prevent this, select the PNG file from the left sidebar and go to the right sidebar and select the first tab (to the left of the question mark button). On the "Type" drop down menu, select "Data". Do this for all of your PNG images (WebP images don't need this treatment).

**Comment by keremdemirios** [comment]
@guidev I'm having the same problem right now. Can you tell me how you solved it if you did?

**Comment by rnrprime** [comment]
I'm having the same problem right now. Can you tell me how you solved it if you did?
