### ISSUE TITLE
[Android] Adding sticker on runtime does'nt work (Inputstream of tray icon is null) after restart it works.

### ISSUE THREAD

**Issue by MarvinStelter** [WhatsApp/stickers#731]
**Specifications**  
OS Version: 11
Device Manufacturer: Google (Pixel 3a)

**Stickers**
- [ X] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ X] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ X] I am using **WebP** images for stickers.

**Problem Description**  
After adding stickers while runtime (It is a sticker pack maker) the pack can not be added to WhatsApp (Tray image inputstream is null). After reopening the App and try to import again it works perfectly. 
**Reproduction Steps**  
1. Adding Sticker while application is running, update content.json with this sticker.
2. Try to add to WhatsApp -> Error
3. Reopen the App and try again to add -> It is working perfectly

**Comment by MarvinStelter** [comment]
I fixed it
For all people having issues with adding stickers/sticker packs while runtime:

Here you are: https://github.com/MarvinStelter/WhatsAppStickerPackAddWhileRuntime

Code is not well but yeah it works! Tested with Android 11, Pixel 3a

**Comment by amirg1992** [comment]
I also have the same problem.
can you please let me know how did you solve this problem?
my code is much different so I cannot use your project.
