### ISSUE TITLE
Animated stickers 😥

### ISSUE THREAD

**Issue by taskcompleted** [WhatsApp/stickers#732]
Hi,

Animated stickers was supposed to come out right after new years, but had no news so far.
@simonzhexu , I know you guys are busy with new policy issues, but is there any news for animated stickers?

**Comment by malayaliscorner** [comment]
Real sh**

**Comment by devfredoom** [comment]
Im waiting too

**Comment by simonzhexu** [comment]
Yeah, we are working on it. I know it is taking too long, but we have not forgot you. I want this out as much as you do.

**Comment by devfredoom** [comment]
> Yeah, we are working on it. I know it is taking too long, but we have not forgot you. I want this out as much as you do.

Thank you for keeping us up to date, we understand the problems / setbacks that are happening.
It would help us a lot if you gave us the final official guidelines (size, weight, frame limits) and if you provided us with the modified template for the animated stickers.

This is possible? Thank you

**Comment by ars4l4n** [comment]
I wonder what the exact obstacles for implementing it are

**Comment by re-LIFE** [comment]
JUST WAIT KIDS !!!

**Comment by simonzhexu** [comment]
I am actively working on this. When it is out, it will be out. Sorry, I cannot commit the timeframe. But when this is ready, I will post the guidelines, update the this app and I will post to this thread.

**Comment by devfredoom** [comment]
> I am actively working on this. When it is out, it will be out. Sorry, I cannot commit the timeframe. But when this is ready, I will post the guidelines, update the this app and I will post to this thread.

I get it, thanks for keeping us fresh news.

However, can you clarify if you are in the final stage, if there is very little left, what situation are they in? Sorry for the insistence, this helps me to plan my future updates.

**Comment by simonzhexu** [comment]
Android guidelines and code added, but have not turned on ability to import on WhatsApp side yet, you can develop your apps.  Please don't publish your app to apps stores yet as that will create a confusing experience for users. More information will come next week. 

Thanks all!

**Comment by malqerbi** [comment]
First Thank you ✌️

**Comment by simonzhexu** [comment]
Update: Please check this wiki for roll out plan: https://github.com/WhatsApp/stickers/wiki/Animated-Stickers

**Comment by DanielZanchi** [comment]
Hello, 
I submitted the form with my number to enter the beta of animated stickers for iOS. Will we get a message to know when we can test it? @simonzhexu

**Comment by simonzhexu** [comment]
Yeah, I typically send an email after I submit your numbers. I am processing the form everyday. Expect a two day max delay please during weekdays.

> Hello,
> I submitted the form with my number to enter the beta of animated stickers for iOS. Will we get a message to know when we can test it? @simonzhexu

**Comment by adrianorezena** [comment]
Hey @simonzhexu , how are you?

After filling out the form, I received the email confirming the registration, but I still can't send animated stickers on iOS. Will this only work in the beta?

**Comment by DanielZanchi** [comment]
> Hey @simonzhexu , how are you?
> 
> After filling out the form, I received the email confirming the registration, but I still can't send animated stickers on iOS. Will this only work in the beta?

@simonzhexu Same situation form me :( Will it change on iOS?

**Comment by DanielZanchi** [comment]
@adrianorezena Did it change for you?

**Comment by adrianorezena** [comment]
> @adrianorezena Did it change for you?

No, still the same thing.
When WhatsApp opens, instead of loading the stickers, it displays the message: "There's a problem with this sticker pack and it can't be added to WhatsApp". Even with the Cuppy project.

**Comment by DanielZanchi** [comment]
still nothing for me :(

**Comment by DanielZanchi** [comment]
Someone managed to test animated stickers on iOS? Still not possible for me :(

**Comment by spilger** [comment]
No, I get an error during the export. This happens with the example App and with my app.

**Comment by DanielZanchi** [comment]
@simonzhexu I registered again, selecting iOS, on Saturday morning. Still no email, and animated stickers not working. 
Any news?

**Comment by spilger** [comment]
It works fine for me. Also the export of animated stickers from my app worked immediately.

**Comment by simonzhexu** [comment]
Please check https://github.com/WhatsApp/stickers/wiki/Animated-Stickers
