### ISSUE TITLE
[iOS] animation file size limit issue

### ISSUE THREAD

**Issue by gyeongnz** [WhatsApp/stickers#742]
**Specifications**  
OS Version: iOS 14.4
Device Manufacturer: iPhone Xs Max
Whatsapp version: 2.21.30.20

**Stickers**
- [✔ ] My stickers do comply with the sticker requirements (512x512 and **<= 500 KB**)
- [✔] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [✔] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  

File size exceed error occurred with 494KB (506,190 Bytes) webp file when I try to export animation pack.
But it is okay with 474KB (486,386 Bytes) webp animation file.

Could you please check the animation webp file size checking routine regarding 500KB (1024 * 500)?

**Comment by sofyafreyman** [comment]
Hey! Thanks for reporting this. I looked at the code and didn't find anything that seemed off, but do you mind sending the webP file that you're having this issue with to me? My email is sfreyman@fb.com, I'd love to take a closer look and figure out what's wrong in your specific case, and maybe find a bigger problem.

**Comment by adrianorezena** [comment]
I had the same problem, and what I thought, is that WhatsApp is considering the limit size as 500,000 Bytes and not 512,000 Bytes. For now, I'm limiting my stickers to 450Kb to make sure we don't have any problems

**Comment by sofyafreyman** [comment]
Do you get the error when you try to use your sticker through this repo's sample app or when importing into WhatsApp?

**Comment by sofyafreyman** [comment]
If it's the latter, I found the problem. Thank you both for reporting! The fix should be in Monday's beta.

**Comment by gyeongnz** [comment]
It occurred when importing into WhatsApp. 
Thank you for checking this issue @sofyafreyman
