### ISSUE TITLE
WhatsApp animated Sticker

### ISSUE THREAD

**Issue by kavi200** [WhatsApp/stickers#743]
### How to fix this error....

![Screenshot_20210221-073430](https://user-images.githubusercontent.com/79387542/108613419-d87be480-7417-11eb-8613-d4a1f5452940.jpg)

**Comment by coroman** [comment]
@kavi200 May i ask you something? Did you get email that your phone numbers have been added for testing animated stickers on whatsapp?

**Comment by simonzhexu** [comment]
closing for now, please follow the suggestion above.

**Comment by kavi200** [comment]
@coroman 
Noo
