### ISSUE TITLE
Integration with Server to fetch stickers

### ISSUE THREAD

**Issue by psmskywalker** [WhatsApp/stickers#747]
I want to integrate the app with server and pull the stickers from server to App. I don't want to use assets folder. Can you please suggest what's the approach @simonzhexu because we cannot always keep files in asset folder.

**Comment by Dwite** [comment]
@psmskywalker in this case you can implement the server for stickers and implement the communication between app and server as you want, I would suggest server-less solutions such as Firebase or any other technology that you are already familiar with.

**Comment by PeterMX** [comment]
@psmskywalker you can hire me, I will do all the work for you.

**Comment by simonzhexu** [comment]
Hi @psmskywalker it is up to you to implement, unfortunately.

**Comment by psmskywalker** [comment]
@simonzhexu what's the easiest way to do... replacing asset folder with others ?

**Comment by MarvinStelter** [comment]
@psmskywalker I could do, created this: https://play.google.com/store/apps/details?id=com.citroncode.stickermaker works without assets folder
