### ISSUE TITLE
there is a problem with this sticker pack and it can't be added to whatsapp

### ISSUE THREAD

**Issue by sachinTechugo** [WhatsApp/stickers#748]
when we get this error ??,  i am using 3 animated webp file which are in this demo project  and tray image in proper size and dimension

**Comment by NewajShovo** [comment]
I am having this issue as well. When I try to import the animated pack I  found the following error  "There's a problem with this sticker pack and it can't be added to whatsApp."

**Comment by Nikoumouk** [comment]
![Uploading 97F2674D-06AA-47DC-B37A-712E80C5F594.jpeg…]()
