### ISSUE TITLE
ACTIVATE ANIMATED STICKERS REST OF THE WORLD

### ISSUE THREAD

**Issue by DimperX** [WhatsApp/stickers#752]
WHEN WILL IT BE POSSIBLE TO SEND ANIMATED FIGURES TO THE REST OF THE WORLD?
At the moment it is only possible for Brazil, Indonesia and Iran ...

@simonzhexu

**Comment by simonzhexu** [comment]
Today. Please check https://github.com/WhatsApp/stickers/wiki/Animated-Stickers

**Comment by pcegarra** [comment]
Im using WA 2.21.7.2, running the demo of this repo and im getting the error:
AddStickerPackActivity: Validation failed:animated sticker packs are not supported yet

**Comment by plantpurple** [comment]
Getting negative comments from users in countries where WA should have rolled out GIFs yesterday (all beyond the 3 pilot countries). On our side everything is stable, but users can't import animated stickers (importing error from WA). Is WA version supporting animated stickers 2.21.5.17 ?

**Comment by joshuaalexa** [comment]
@simonzhexu   Is WA version supporting animated stickers 2.21.5.17 ? what we have to do to make our app work

**Comment by simonzhexu** [comment]
I imagine there is a little delay with user getting the server capability update. You can add something in your app to ask your users to update their apps to the latest. 

2.21.5.17 and 2.21.7.2 should have the capability. Give it a day.

**Comment by pcegarra** [comment]
Ok now im able to use this demo app and import the stickers to WhatsApp, but my app with the same pack is not working, any idea?

**Comment by simonzhexu** [comment]
I don't have the same information as you do. I think you will have to figure out on your own or ask on stackoverflow. There are error messages in logcat of your app. Please pay attention to those.
