### ISSUE TITLE
[Android] Sticker file might be corrupted or invalid

### ISSUE THREAD

**Issue by BattleShipPark** [WhatsApp/stickers#753]
**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [ ] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ ] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
I have an error in onActivityResult() when I export this sticker: 
[16.webp.zip](https://github.com/WhatsApp/stickers/files/6195436/16.webp.zip)

**Comment by MarvinJWendt** [comment]
Hi @BattleShipPark, please give us more details on what happens :) Error logs etc.
Thanks

**Comment by BattleShipPark** [comment]
Hi @MarvinJWendt 
forget attached 16.webp.zip please. I explain what happens.

I have errors in data.getStringExtra("validation_error") in onActivityResult(), which is "sticker file might be corrupted or invalid". I tried to find out the reason but I could not because I succeed to export the pack in this device even though I fail in that device.
So I want to know when you generate "sticker file might be corrupted or invalid". If you can give some conditions it will help me a lot.

Thanks.

**Comment by BattleShipPark** [comment]
refer to #606 , I realized you have an additional validation code. 
Could you check why this file makes the same error? [10.webp.zip](https://github.com/WhatsApp/stickers/files/6283601/10.webp.zip)
I have so many error from users but I don't know why.

**Comment by BattleShipPark** [comment]
@MarvinJWendt 
[85FKKV-4.webp.zip](https://github.com/WhatsApp/stickers/files/6295306/85FKKV-4.webp.zip)
When I put the image above I have the error "sticker file might be corrupted or invalid"
Galaxy S9, 8.0
Moto e5 play, 8.1.0

**Comment by sudheernaidu53** [comment]
I heard/read somewhere that the name of the stickers can't just be a numeric value?
could you rename the sticker and see what happens?
