### ISSUE TITLE
[Android] App claims the sticker is static despite being animated

### ISSUE THREAD

**Issue by MarcoReckless** [WhatsApp/stickers#755]
**Stickers**
- [X] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [X] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
The app claims my animated stickers are static, and applies the static size limit (100kb instead of 500kb).

![Screenshot_1](https://user-images.githubusercontent.com/13008862/112452162-9ddad400-8d56-11eb-878e-d02b10006409.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/13008862/112452164-9e736a80-8d56-11eb-80cf-3665de6a7940.jpg)

**Head of Commit**
Yes, I have the latest commit.

**Comment by MarvinJWendt** [comment]
Hi @MarcoReckless, could you please upload the sticker here? Thank you :)

**Comment by MarcoReckless** [comment]
I am unable to upload WEBP files so I uploaded it [here](https://we.tl/t-HOsZTCskFg).

**Comment by MarvinJWendt** [comment]
Thank you, I am sure someone will look at this soon, as it seems that the sticker is correctly animated.

BTW: You can upload files inside a zip here ;)

**Comment by simonzhexu** [comment]
I am gonna take a look. Thanks.

**Comment by MarcoReckless** [comment]
> I am gonna take a look. Thanks.

Did you manage to figure something out? I also tried bringing all of them below 100 kb and the error still stands (still claiming that my stickers are static).

**Comment by MarcoReckless** [comment]
Never mind, I'm just dumb! For some reason I didn't have '"animated_sticker_pack": true' as a string in my content.json file, thus it didn't recognize it as animated.
