### ISSUE TITLE
Proposal to enable "GitHub Discussions" for this repo

### ISSUE THREAD

**Issue by MarvinJWendt** [WhatsApp/stickers#756]
Hi, I think it would make sense to enable the new "GitHub Discussions" feature (https://docs.github.com/en/discussions) for this repository.

At the moment, the WhatsApp sticker community is split into several forums and WhatsApp group chats. These are mostly not moderated and are not transparent. I suggest that these types of communication can take place in this repo. The new feature of GitHub adds a new tab (Discussions), which is a kind of forum. Announcements can be posted here in the future, as the interface is better suited than the current GitHub wiki 👍 

We would profit from the fact that the communication with the community can be strengthened, the process "behind the scenes" at WhatsApp could be made more transparent and the most important: The community can exchange new ideas.

I would volunteer to moderate the discussions (like I do with the Issues here 😄)

Have a nice day and stay healthy 😉 

(Somehow I cannot assign anyone on this issue, so I'll tag you here @simonzhexu)

**Comment by simonzhexu** [comment]
Thanks @MarvinJWendt , I am in favor of enabling it. But it seems there isn't a settings on this as mentioned in https://docs.github.com/en/discussions/quickstart. I think it is likely a setting in the Facebook Enterprise. Let me explore and get back to you.

**Comment by simonzhexu** [comment]
Discussions enabled! @MarvinJWendt
