### ISSUE TITLE
Can't add animated stickers to whatsapp

### ISSUE THREAD

**Issue by MarkhorVenom** [WhatsApp/stickers#768]
Can't add animated stickers to whatsapp...

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for stickers.

**Problem Description**  
I can't add animated stickers to WhatsApp

**Comment by simonzhexu** [comment]
please provide enough information for me to reproduce the issue. Which platform are you experiencing the issues with?
