### ISSUE TITLE
[Android] Still issue facing - "There's a problem with this sticker pack and it can't be added to WhatsApp"

### ISSUE THREAD

**Issue by imagetag6608** [WhatsApp/stickers#769]
**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [ ] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ ] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
Many of my users (not all) facing issues with not install stickers in WhatsApp. They all have the latest version of WhatsApp. facing error like there's a problem with this sticker app. 
One thing is common in all use which facing issue is - they have MI phone.
Please help me.

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN PLAY STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by simonzhexu** [comment]
Hi, 

Could you fill the link of the playstore url of your app? There isn't enough information for me to reproduce the issue.

**Comment by imagetag6608** [comment]
@simonzhexu app link - https://play.google.com/store/apps/details?id=com.smiley_animation_sticker
Mi phone :
OS version = android 8
WhatsApp version  = 2.21.6.17

Anyone else facing the same issue. please add comments with more specifications.

**Comment by tiagocanto01** [comment]
This problems, it seems that is only happening with the Mi Phones

**Comment by malayalify-softlab** [comment]
My users are also having this issue, with Galaxy On Max

**Comment by imagetag6608** [comment]
@simonzhexu still facing issue in many phone. even is Samsung. You guys have to check why its happing. please check video file.

https://user-images.githubusercontent.com/80583744/119092159-b4866a00-ba2b-11eb-9861-45340e22032b.mp4

**Comment by jonex41** [comment]
hello, i could add static stickers, but could not add the animated stickers, Please help, Thank in advance
