### ISSUE TITLE
Animated sticker - total animation duration should be under 10000 ms

### ISSUE THREAD

**Issue by runnableapps** [WhatsApp/stickers#773]
Error:
Total animation duration should be under 10000 ms.

Sticker duration less than 1000ms. 
Always shows that first sticker in sticker pack has invalid duration

**Comment by santi-petersen** [comment]
Duplicate of #718. Add your device model and app link or zip with the stickers to the original thread.

**Comment by MarvinJWendt** [comment]
Duplicate of #718
