### ISSUE TITLE
[Android]

### ISSUE THREAD

**Issue by EBDitore** [WhatsApp/stickers#774]
![Screenshot_1618618650](https://user-images.githubusercontent.com/46364320/115097364-05bcae80-9f00-11eb-8ce9-7f499ecf8017.png)

**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [ ] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ ] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
"animated_sticker_pack": true, but doesn't work, help me, please

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN PLAY STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by simonzhexu** [comment]
Make sure to have the latest WhatsApp. what version of WhatsApp are you using?
