### ISSUE TITLE
Possible to have more than 10 Packs in a app?

### ISSUE THREAD

**Issue by ramencorn** [WhatsApp/stickers#775]
**Specifications**  
OS Version: Android and iOS
Device Manufacturer: Both

**Stickers**
- [Y] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [Y] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [Y] I am using **WebP** images for stickers.
- [N] I am using **PNG** images for stickers.

**Problem Description**  
Do not have a problem, from what I read previously on the README it says only allowed maximum of 10 packs per app. Is it possible to include more than that? I would like my app to be worth the money my customers are paying for instead of just a one time 10 packs. Moreover it's also easier to update 1 app than 5 apps etc. Will it have performance issues? Or problem adding the 11th pack onwards?

Im asking this in regards for animated stickers app.

**Reproduction Steps**  
Everything is fine with 10 packs.

**Head of Commit**
Have the latest commit.

**Links**  
NA

**Comment by simonzhexu** [comment]
I think it will be fine.

**Comment by Pippo-creator** [comment]
Inviato da iPhone
