### ISSUE TITLE
[Android]Could not fetch from content provider

### ISSUE THREAD

**Issue by siddhpurakaran** [WhatsApp/stickers#78]
when i installed app it directly shows below message 
Error : could not fetch from content provider, Com.domainname.appname.StickerContentprovider

so how can i overcome this ? :
my logcat displaying following

![screenshot 286](https://user-images.githubusercontent.com/28296673/47701861-37166680-dc41-11e8-84af-b7dc9fd87e26.png)

**Comment by simonzhexu** [comment]
that means your StickerContentProvider returns null in getPackForAllStickerPacks(uri). What changes have you made to the repo?
