### ISSUE TITLE
Show all error

### ISSUE THREAD

**Issue by ralanbiya** [WhatsApp/stickers#789]
Is there a way to show all error and then log to app, rather than found 1 error and log to app?

Example :
I have my animated sticker identifier pack3, file1.webp duration more than 10000. Then I fixed it, try run the app again, and got another error : identifier pack 4, file5.webp duration more than 10000. And so on if there's another error in other pack

So, is there a way like check through all pack, and than log all error rather than just 1 error at a time?

**Comment by simonzhexu** [comment]
this is a open sourced app, you are welcome to make pull request to add this feature.
