### ISSUE TITLE
Please increase sticker size

### ISSUE THREAD

**Issue by runnableapps** [WhatsApp/stickers#790]
Many users reported that stickers looks very small in WhatsApp.
Please increase sticker size.

**Comment by simonzhexu** [comment]
the stickers should 512 by 512. Why are they small?

**Comment by santi-petersen** [comment]
I think compared to Telegram, they look a bit small in chat. Some users have asked me the same thing.

**Comment by runnableapps** [comment]
> 
> 
> the stickers should 512 by 512. Why are they small?

I mean sticker size in WhatsApp chat, not image resolution.  Stickers look a bit small in chat.

**Comment by some28** [comment]
In Telegram, stickers look much better than WhatsApp. Our users also requesting us to increase size in WhatsApp.

**Comment by simonzhexu** [comment]
We will consider that, but we designed the size to match the other content.
