### ISSUE TITLE
[Android]

### ISSUE THREAD

**Issue by thepatriciapop** [WhatsApp/stickers#797]
This app is great, but I really wanted to back it up to save my stickers from it ... Please, seriously! Is it urgent! Please fix me these errors about creating a backup of this ... Get me out of advance access, please! Really! Is it urgent! I don't want this early access there.

**Comment by MarvinJWendt** [comment]
Hi @thepatriciapop, I don't really get what your problem is. This is an app template, that does not need any form of backup. If you used this app template, to create your own app, you should have your stickers locally saved?
This app template does not provide any stickers by itself.

**Comment by thepatriciapop** [comment]
Because you need to save some stuff for another device and cell phone from that...
