### ISSUE TITLE
Sticker file might be corrupted or invalid

### ISSUE THREAD

**Issue by Fasero11** [WhatsApp/stickers#799]
**Specifications**  
OS Version: [Android 10]
Device Manufacturer: [Xiaomi]

**Stickers**
- [X] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [X] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [X] I am using **WebP** images for stickers.

**Problem Description**  
I'm trying to add an animated pack to my sticker app. All stickers are animated .webp, 512 x 512px and less than 500kb. The app launches fine. However, when I click to add the pack to WhatsApp, a pop-up saying there has been an error and that the pack couldn't be added appears. When I close it, another pop-up appears. This one says "Error with the pack. Sticker file might be corrupted or invalid" and the path to the sticker. 

I have tried different methods of compression from GIF to WebP but I haven't been able to fix the issue.

EDIT: From what I have seen, the problem only appears when the sticker is over 100kb (With some stickers; others won't work even if they are less than 100kb). Wasn't the size limit for animated stickers 500kb?

Any ideas on what could be the cause of the problem? 

Thank you so much. 

![WhatsApp Image 2021-06-21 at 23 10 37](https://user-images.githubusercontent.com/86266311/122828518-1285c600-d2e6-11eb-8a05-26adc5af3e23.jpeg)

**Comment by Fasero11** [comment]
I was able to fix the problem by making the animated .webp frame by frame. But I still don't know what the cause was.

**Comment by paktech1** [comment]
did you use AnimatedGifEncoder? for encoding frame by frame, or did you use a third party library, kindly share it here.

**Comment by viyyan** [comment]
> I was able to fix the problem by making the animated .webp frame by frame. But I still don't know what the cause was.

Hi did you use AnimatedGifEncoder?
