### ISSUE TITLE
[Android] method createFromByteArray in class WebPImage cannot be applied to given types.

### ISSUE THREAD

**Issue by debalparui** [WhatsApp/stickers#808]
stickers-master\Android\app\src\main\java\com\mystickerappname\samplestickerapp\StickerPackValidator.java:145: error: method createFromByteArray in class WebPImage cannot be applied to given types;
                final WebPImage webPImage = WebPImage.createFromByteArray(stickerInBytes);
                                                     ^
  required: byte[],ImageDecodeOptions
  found: byte[]
  reason: actual and formal argument lists differ in length.

**Comment by simonzhexu** [comment]
are you using fresco 2.3.0? or 2.5.0?

**Comment by simonzhexu** [comment]
updated fresco, please pull latest code.
