### ISSUE TITLE
[Android] Error animated stickers. 

### ISSUE THREAD

**Issue by davidsss6** [WhatsApp/stickers#811]
**Specifications**  
OS Version: Windows 10 / Android Studio 4.11
Device Manufacturer: Emulator

**Stickers**
- [ X] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ X] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ X] I am using **WebP** images for stickers.
- [ X] I am using **PNG** images for stickers.

**Problem Description**  
Hi. I'm David from Brazil. I`m very happy to have found your tool. Congratulations on your commitment to this project. Right now I have a doubt.  There are any special configuration to use animated stickers? 
I try to add one animated sticker using the default project, replacing one of the default images with other of my animateds images,  but the error: "pack is not marked as animated pack but contains animated stickers." keeps appearing.  

The Whatsapp testing version is 2.21.16.20
I using the ^1.0.1+5 version of flutter_whatsapp_stickers

Sorry for any missing information or error. This is my first message here in Github

Thank you

David

**Comment by aktech-dev** [comment]
any luck
