### ISSUE TITLE
How to make sticker pack able to be added to GBWhatsApp or other modded WhatsApp

### ISSUE THREAD

**Issue by hacker0id** [WhatsApp/stickers#814]
**Specifications**  
OS Version: [FILL IN]
Device Manufacturer: [FILL IN]

**Stickers**
- [ ] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
[FILL IN WITH DETAILED DESCRIPTION OF THE PROBLEM]

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN PLAY STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by MarvinJWendt** [comment]
We do not support modded WhatsApp versions, as they violate the [Terms of Service](https://faq.whatsapp.com/general/security-and-privacy/which-terms-of-service-apply-to-you).

**Comment by sarankumar-ns** [comment]
(For educational purposes only)

In `WhitelistCheck` file add GB WhatsApp along with Consumer WhatApp and WhatsApp Business

    var GB_WHATSAPP_PACKAGE_NAME = "com.gbwhatsapp"

    fun isWhitelisted(context: Context, identifier: String): Boolean {
        return try {
            if (!isWhatsAppConsumerAppInstalled(context.packageManager) && !isWhatsAppSmbAppInstalled(context.packageManager) && !isWhatsAppGBAppInstalled(context.packageManager)) {
                return false
            }
            val consumerResult = isStickerPackWhitelistedInWhatsAppConsumer(context, identifier)
            val smbResult = isStickerPackWhitelistedInWhatsAppSmb(context, identifier)
            val gbResult = isStickerPackWhitelistedInWhatsAppGB(context, identifier)
            consumerResult && smbResult && gbResult
        } catch (e: Exception) {
            false
        }
    }
    fun isWhatsAppGBAppInstalled(packageManager: PackageManager): Boolean {
        Log.e("TAG", "IS Whatsapp GB installed" + isPackageInstalled(GB_WHATSAPP_PACKAGE_NAME, packageManager))
        return isPackageInstalled(GB_WHATSAPP_PACKAGE_NAME, packageManager)
    }

    fun isStickerPackWhitelistedInWhatsAppGB(context: Context, identifier: String): Boolean {
        return isWhitelistedFromProvider(context, identifier, GB_WHATSAPP_PACKAGE_NAME)
    }


In `AddStickerPackActivity`'s `addStickerPackToWhatsApp()` function 

            if (!WhitelistCheck.isWhatsAppConsumerAppInstalled(requireContext().packageManager) && !WhitelistCheck.isWhatsAppSmbAppInstalled(requireContext().packageManager) && !WhitelistCheck.isWhatsAppGBAppInstalled(requireContext().packageManager)) {
                Toast.makeText(context, R.string.error_adding_sticker_pack, Toast.LENGTH_LONG).show()
                return
            }
            val stickerPackWhitelistedInWhatsAppConsumer = WhitelistCheck.isStickerPackWhitelistedInWhatsAppConsumer(requireContext(), identifier!!)
            val stickerPackWhitelistedInWhatsAppSmb = WhitelistCheck.isStickerPackWhitelistedInWhatsAppSmb(requireContext(), identifier)
            val stickerPackWhitelistedInWhatsAppGB = WhitelistCheck.isStickerPackWhitelistedInWhatsAppGB(requireContext(), identifier)
            if (!stickerPackWhitelistedInWhatsAppConsumer && !stickerPackWhitelistedInWhatsAppSmb && !stickerPackWhitelistedInWhatsAppGB) {
                //ask users which app to add the pack to.
                launchIntentToAddPackToChooser(identifier, stickerPackName)
            } else if (!stickerPackWhitelistedInWhatsAppConsumer) {
                launchIntentToAddPackToSpecificPackage(identifier, stickerPackName, WhitelistCheck.CONSUMER_WHATSAPP_PACKAGE_NAME)
            } else if (!stickerPackWhitelistedInWhatsAppSmb) {
                launchIntentToAddPackToSpecificPackage(identifier, stickerPackName, WhitelistCheck.SMB_WHATSAPP_PACKAGE_NAME)
            } else if (!stickerPackWhitelistedInWhatsAppGB) {
                launchIntentToAddPackToSpecificPackage(identifier, stickerPackName, WhitelistCheck.GB_WHATSAPP_PACKAGE_NAME)
            } else {
                Log.e("TAG", "Error on checking whatsapp installed.")
                Toast.makeText(context, R.string.error_adding_sticker_pack, Toast.LENGTH_LONG).show()
            }
and in `AndroidManifest` file add 
`<package android:name="com.gbwhatsapp" />`
inside `<queries>` tag

Note: These all are kotlin code and **not tested** but hope it will work.

**Comment by simonzhexu** [comment]
WhatsApp does not recommend users using GBWhatsApp.

**Comment by hacker0id** [comment]
> violation

thankyou brother
