### ISSUE TITLE
[Android] Stickers are deleted from WhatsApp after the phone is turned off and on. The problem is only with Android 11

### ISSUE THREAD

**Issue by Pat-Tech-App** [WhatsApp/stickers#826]
**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
The problem is only with Android 11

Stickers are deleted from WhatsApp:
1. After the phone is turned off and on.
2. When updating the app.

Therefore it׳s necessary to add the stickers to WhatsApp every time.

**Links**  
https://play.google.com/store/apps/details?id=il.co.pat.WhatsAppStickersIL

**Comment by osamz** [comment]
Also, our users complain about same issue, on:
- Galaxy S20FE 5G, Android 11, updated WhatsApp.
- Galaxy A12. Android 11, updated WhatsApp.

till writing this, no one complain on Android 10.

**Comment by BattleShipPark** [comment]
We are having the same issue.
Many users are reporting 'packs are deleted'. I don't know the steps to reproduce but ALL of them are using Android 11
@simonzhexu

**Comment by JeremyR34** [comment]
Same complaints from our users.

**Comment by BattleShipPark** [comment]
@Pat-Tech-App @svenvdz @some28 @osamz @JeremyR34 
Hi guys, let's mention @simonzhexu to notify him this critical issue.

**Comment by BattleShipPark** [comment]
any updates? @simonzhexu

**Comment by simonzhexu** [comment]
Hi, I tried to repro on Android 11 or 12. but I could not. Can you?

**Comment by BattleShipPark** [comment]
@simonzhexu 
I'm trying too but I have failed to repro.
I am not sure but I am suspecting my targetSdkVersion. After I changed it to 30, user complaints started.
You guys can check this for your apps? @Pat-Tech-App @svenvdz @some28 @osamz @JeremyR34

**Comment by osamz** [comment]
I cannot reproduce it on my AVD's yet, and I didn't have android 10, 11, 12 devices (: to check.

**Comment by JeremyR34** [comment]
I can't reproduce it either, complaints come from users but no way to reproduce it on any device...

**Comment by BattleShipPark** [comment]
This should not be closed. Complaints keep coming.
