### ISSUE TITLE
How does a sticker pack get featured on Whatsapp Stickers section?

### ISSUE THREAD

**Issue by sofiaqiriazi** [WhatsApp/stickers#828]
When initiating the keyboard, pressing the sticker icon and then the + sign, you can reach the Featured Stickers window. My question is why are there specific sticker packs featured? What are the metrics WhatsApp has for selecting these packs to feature them?

**Comment by simonzhexu** [comment]
These stickers are WhatsApp's own sticker packs. It is different from the stickers developers are building. We are not featuring developer stickers at the moment. Sorry.
