### ISSUE TITLE
[Android] "Please update your WhatsApp to the latest version for add stickers"

### ISSUE THREAD

**Issue by imkuroneko** [WhatsApp/stickers#833]
**Specifications**  
OS Version: `11 RKQ1.201004.002  (MIUI Global 12.0.2.0 RCOMIXM)`
Device Manufacturer: `Xiaomi`
WhatsApp Version: `2.21.21.17`

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
After updating the S.O. to the above mentioned, the app still installed but both sticker packages was deleted from WhatsApp and now says "If you want to add this stickers package, update your WhatsApp to the latest version".
Even tried reinstalling WhatsApp and the stickers app.

**Reproduction Steps** 
Upgrade to the above version mentioned and just that; even with some app updates since that, it gives the above error mentioned.

**Head of Commit**
Latest version available 2a99c36

**Links**  
https://play.google.com/store/apps/details?id=com.kuroneko.whatsapp.sticker&hl=es_PY&gl=US

**Comment by khushbuvadi** [comment]
Hi @imkuroneko, I have same issue. some stickers are added and some are not. my icontray size - 96*96 < 50 kb and stickers size - 512*512 < 100 kb.

**Comment by jeroen1602** [comment]
If you are targeting Android 11 (API level 30) or higher then you have to add Whatsapp to a list so that your app is allowed to communicate with it.

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <application>
     ...
    </application>
    <queries>
        <!-- Tell Android that we will be communicating with Whatsapp and Whatsapp 4 business -->
        <package android:name="com.whatsapp" />
        <package android:name="com.whatsapp.w4b" />
    </queries>
</manifest>
```

**Comment by cpinan** [comment]
Closing this issue, given that it was solved
