### ISSUE TITLE
[Android] Toast message after package adding, is wrong encoding

### ISSUE THREAD

**Issue by elihaidv** [WhatsApp/stickers#838]
**Specifications**  
OS Version: 10
Device Manufaturer: Xiaomi

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for stickers.

**Problem Description**  
After added a package with UTF-8 name, such as Hebrew name. The message didn't displayed correctly. The special 
characters showed as number: &#1490

Image attached
![WhatsApp Image 2021-11-07 at 3 15 04 PM](https://user-images.githubusercontent.com/11449032/140646497-93e700af-faad-4ebf-9430-2c972e80d1f3.jpeg)

**Reproduction Steps**  
Change package name to Hebrew, for Example: "חבילה".
You can change the name in `contents.json` file.
Try add it to WhatsApp

**Head of Commit**
Yes. Cloned the latest commit

It seems like the bug in WhatsApp itself

**Comment by simonzhexu** [comment]
Thanks for letting me know. We will take a look.

**Comment by simonzhexu** [comment]
Should be fixed now.
