### ISSUE TITLE
Less than three stickers in pack

### ISSUE THREAD

**Issue by mwolffalonso** [WhatsApp/stickers#860]
Hello,

I would like to create an app that has the feature for the user to select a sticker and add it individually to WhatsApp. In the documentation it says the lower limit is three stickers in a pack, but I have seen some apps that actually do this somehow. Have not tried yet adding two bogus stickers with the selected one and after that removing those two and updating the pack (increase image version). Appreciate any guidelines,
Thanks,
Martin.

**Comment by Josepdal** [comment]
Those apps are using transparent stickers 👀

**Comment by mwolffalonso** [comment]
Thank you very much! That's a great revelation, I have just tested it and i could actually send those transparent stickers in a conversation!!

**Comment by mwolffalonso** [comment]
By knowing that there is no solution other than internally add two more stickers (transparent or other interesting stuff) at the initial load I think we can satisfactory close the ticket.
