### ISSUE TITLE
[Android] Your applicationId is currently com.example.samplestickerapp, please change your applicationId to a different string in app/build.gradle in line 10

### ISSUE THREAD

**Issue by sahandileep** [WhatsApp/stickers#868]
hello friends, 

Cuuld you help me fix this error,

Build file 'C:\Users\sahan\Desktop\New folder (2)\stickers-master\stickers-master\Android\app\build.gradle' line: 73

Execution failed for task ':app:checkDebug'.
> Your applicationId is currently com.example.samplestickerapp, please change your applicationId to a different string in app/build.gradle in line 10

**Comment by simonzhexu** [comment]
You need to change your applicationId
