### ISSUE TITLE
[Android] Packs(avoid_cache is true) disappear when the system version is higher than android Q after reboot

### ISSUE THREAD

**Issue by Notsfsssf** [WhatsApp/stickers#870]
**Specifications**  
OS Version: R
Device Manufacturer: MI 10

**Stickers**
- [x] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [x] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [x] I am using **WebP** images for stickers.
- [x] I am using **PNG** images for TRAY.

**Problem Description**  
When the system version is higher than android Q, added packs(`avoid_cache:true`) disappears after reboot the system，but
when I set `avoid_cache` to false, the problem was solved

**Reproduction Steps**  
When the system version is higher than android Q, added packs(`avoid_cache:true`) disappears after reboot the system，but
when I set `avoid_cache` to false, the problem was solved
I didn't have this kind of problem before android10.

**Comment by Korogba** [comment]
Hi @Notsfsssf when caching is disabled, we will fetch stickers similar to adding a pack in the import flow. So you need to ensure your content provider always provides the needed assets. Check https://github.com/WhatsApp/stickers/tree/main/Android#modifying-the-contentsjson-file for use-cases where you might need to enable caching. 

Feel free to re-open if this does not address your issue
