### ISSUE TITLE
[Android]App does not stop loading after clicking on "Add to WhatsApp"

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [WhatsApp/stickers#88]
I made 2 sticker packs and when i try to add any of theese it only shows "Sending to WhatsApp". I let it running an hour and still no result. There is no error in the logs of the app. Android 8.0.

**Comment by amrit-1901** [comment]
Does this happen on iOS or Android?

**Comment by rdvt** [comment]
I have the same issue in iOS 12.1

**Comment by mohdssd** [comment]
![5d67d3cb-a08e-4362-9cc2-ec42182cf76e](https://user-images.githubusercontent.com/44591306/47765573-a93b8980-dcdb-11e8-9fbf-cc5e5f8cab35.png)

**Comment by rdvt** [comment]
> 
> 
> I have the same issue in iOS 12.1

With png image works but webp crash

**Comment by mohdssd** [comment]
Hi

**Comment by SagarRaiyani** [comment]
Same issue in android 8.1.0

**Comment by amrit-1901** [comment]
For iOS, if your app crashes with webp images, you probably forgot to add them to the target. Select the image and on the right side of the window, make sure "WAStickersThirdParty" is selected.
<img width="273" alt="screen shot 2018-11-02 at 10 04 32 am" src="https://user-images.githubusercontent.com/38670811/47929635-dd06e280-de86-11e8-83d7-cfab2eaa8074.png">

**Comment by rdvt** [comment]
Yes the target is correctly marked, and crash whatsapp app

Saludos
________________________________

**Comment by simonzhexu** [comment]
> I made 2 sticker packs and when i try to add any of theese it only shows "Sending to WhatsApp". I let it running an hour and still no result. There is no error in the logs of the app. Android 8.0.

By still no result, do you mean that the progress bar with "Sending to WhatsApp" dialog stays there and not disappearing?

**Comment by ErdbeerbaerLP** [comment]
It does not stop loading and it does not add the stickers to WhatsApp. It does not even ask me to add them.

**Comment by ParaSpl01t** [comment]
any update on this issue?

**Comment by fabio-negri** [comment]
I got it working in Android by importing PNGs into the assets folder and then converting them to WebP using Android Studio.

![image](https://user-images.githubusercontent.com/11914212/48675448-bcea4b00-eb37-11e8-9c71-d7575fca07f0.png)

**Comment by simonzhexu** [comment]
Please reopen if this still happens.
