### ISSUE TITLE
[Android] a working code for dynamically added external storage stickers

### ISSUE THREAD

**Issue by thewayur** [WhatsApp/stickers#885]
I have read almost all issues, comments, documentations here, in stackoverflow and medium.

But while combining all methods with parameters, it looks confusing for newbie or at least to me.

so can someone please paste a working flow of StickerContentProvider for all future newbies? please

i have spend more than a week :D 

My Goal:
1. My stickers are well organized in folders
2. I might use multple CONTENT_FILE_NAME . json as per categories

thanks a lot in advance!

**Comment by MarvinStelter** [comment]
Hi,

I've an respository for that. Just copy the code from it!

**Comment by Korogba** [comment]
There's an example in the sample app: https://github.com/WhatsApp/stickers/blob/main/Android/app/src/main/java/com/example/samplestickerapp/StickerContentProvider.java
