### ISSUE TITLE
INFRINGEMENT NOTICE FROM APPDETEX ON BEHALF OF WHATSAPP (SUSPENSION OF APP)

### ISSUE THREAD

**Issue by attaullahpro** [WhatsApp/stickers#897]
**App status: Suspended**
Your app has been suspended and removed due to alleged trademark infringement. 

**Contact Person:**
Alexis Meghrouni Rivas
**Company Name:**
WhatsApp LLC
**Contact Email:**
enf.whatsapp.1899378@enfappdetex.com
**Relationship:**
tm_owner

**Clarifications:**
The app uses the trademarks, logos, badges and/or banners of WhatsApp, without authorization. In this instance, the developer has titled the app using and **“for WhatsApp”** in a manner that causes confusion and creates the impression that the app is associated with WhatsApp. This confusion is compounded by the use of imagery similar to WhatsApp’s logo, wallpaper and/or other designs, and/or other uses of the **word “WhatsApp”** in the marketing pages in the app store. The developer’s use of WhatsApp's trademarks implies an association or other relationship that is neither authorized nor endorsed by WhatsApp.

Our App is suspended only using word **for WhatsApp** as suffix, at least you need to notify or reject or remove the app until to fixed the issue. why you people appeal for suspended etc. and **Mr. Alexis Meghrouni Rivas** not even replay of our email. really disappointed such behavior.

**Comment by MarvinJWendt** [comment]
Hi @attaullahpro, sorry for the inconvenience. It is stated in the README that you may not use "WhatsApp" in the title of your app.

> When naming your app, it is strongly advised you do not use "WhatsApp" anywhere in the name of your app or in the name field of your app listing. However, when preparing your app for submission in Google Play Store/App Store, you'll have the option to add description associated with your app and it's okay to mention WhatsApp in the description. Make sure you use "WhatsApp" as a brand name, with "W" and "A" capitalized with no space between letters. More information on WhatsApp Brand(https://www.facebook.com/brand/resources/whatsapp/whatsapp-brand).

There is nothing that we can do, sadly.

Also see: #150, #190
