### ISSUE TITLE
> Please don't create app with more than 10 packs, it is bad experience for user. They may want only one pack out of your 100 packs. But you are occupying 100 packs of disk space for them. You can have separate apps.

### ISSUE THREAD

**Issue by sanidhya711** [WhatsApp/stickers#905]
> Please don't create app with more than 10 packs, it is bad experience for user. They may want only one pack out of your 100 packs. But you are occupying 100 packs of disk space for them. You can have separate apps.

but what if we fetch the stickers from web in our app? then we wont need to store anything on the users device and download only those that the user wants to use.

_Originally posted by @sanidhya711 in https://github.com/WhatsApp/stickers/issues/180#issuecomment-1284131529_

**Comment by Korogba** [comment]
This should be fine I think. I guess you'd also want to clear the fetched packs from time to time
