### ISSUE TITLE
Sticker pack not added, if you'd like to add it, nake sure you update to latest version of whatsapp

### ISSUE THREAD

**Issue by ywramn** [WhatsApp/stickers#907]
**Specifications**  
OS Version: [Android 11]
Device Manufacturer: [Samsung]

**Stickers**
- [ ] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [ ] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [ ] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
[Using the sample code and guidelines I have successfully created sticker pack, app successfully installs in phone, and opens up and shows my created stickers. But the problem is when I try to add those stickers to whatsapp via **add to whatsapp button]** it throws "Sticker pack not added, if you'd like to add it, nake sure you update to latest version of whatsapp". I have checked I am on latest version of whataspp. Can anyone guide me where I am making a mistake?

**Reproduction Steps**  
[FILL IN WITH DETAILED REPRODUCTION STEPS]

**Head of Commit**
[Do you have the latest commit from master? If not, please update your repo to the latest commit in master, and try again. If issue still occurs, please note down the commit hash (from this repo) here:]
[Commit hash]

**Links**  
[FILL IN PLAY STORE LINK AND/OR LINK TO SOURCE CODE ON GIT]

**Comment by Korogba** [comment]
Closing this since it is likely fixed and I am able to import packs using apps like sticker.ly. @ywramn please feel free to re-open if you are still facing this
