### ISSUE TITLE
The add button doesn't work

### ISSUE THREAD

**Issue by GlowMLG** [WhatsApp/stickers#91]
I finished my app and in my Redmi Note 3 it works perfectly, but a couple friends who can access the closed beta have told me that the add button (both the + icon and the "Add to whatsapp" green button) does nothing. No error and no effect. Anyone else has this issue?

**Comment by simonzhexu** [comment]
Make sure they can see sticker picker and being able to send stickers.

**Comment by mudi256** [comment]
Not working
