### ISSUE TITLE
imageDimensions crash

### ISSUE THREAD

**Issue by lwangeli** [WhatsApp/stickers#92]
Hi Guys,

I'm trying to install my first iOS Stickers for whatsapp and it crashes with the next thread:
Thread 3: Fatal error: logo_words.png: (512.0, 512.0) is not compliant with tray dimensions requirements, (96.0, 96.0).

Can you help me? Thanks

**Comment by edwinmacalopu** [comment]
the logo_words.png must have the dimensions of 96x96 pixels
