### ISSUE TITLE
[Android] [WhatsApp Bug] Added packs disappear in WhatsApp

### ISSUE THREAD

**Issue by santi-petersen** [WhatsApp/stickers#932]
**Specifications**  
OS Version: Android
Device Manufacturer: Unknown

**Stickers**
- [X] My stickers do comply with the sticker requirements (512x512 and < 100 KB)
- [X] My tray icon does comply with the requirements (96x96 and < 50 KB)
- [X] I am using **WebP** images for stickers.
- [ ] I am using **PNG** images for stickers.

**Problem Description**  
Probably a bug in the latest version of WhatsApp.
During the last week I had many users reporting that packs disappear from WhatsApp. I haven't made any changes to my app, but reviews and emails constantly inform me of this bug.

I checked the latest reviews on other popular sticker apps and found the same kind of reviews: “Packs disappear in WhatsApp”

**Reproduction Steps**  
Probably when WhatsApp is updated. Some users report that if they clear the WhatsApp cache, the packages disappear as well. I couldn't reproduce that in my devices but an user sent me a video.

**Comment by santi-petersen** [comment]
I attach a video sent by an user where packs disappear from WhatsApp after clearing cache [0:32]


https://user-images.githubusercontent.com/53949614/226151524-656d707a-5c6e-43e0-8e9a-bbb51bcb3881.mp4

**Comment by santi-petersen** [comment]
I attach some reviews of users reporting the bug.

![Screenshot from 2023-03-18 22-59-18](https://user-images.githubusercontent.com/53949614/226151566-c5d3aea3-04e2-49f3-b7c4-bee87ebf9cc5.png)
![Screenshot from 2023-03-18 22-58-01](https://user-images.githubusercontent.com/53949614/226151567-3a3be54e-71ac-4240-b21e-95b8f897863d.png)
![Screenshot from 2023-03-18 22-57-26](https://user-images.githubusercontent.com/53949614/226151568-d22ada8a-ddbc-47ed-9e89-12b673660940.png)

**Comment by xcodeBn** [comment]
think that's a problem with how **WhatsApp** is saving stickers rather than the stickers  app itself

**Comment by santi-petersen** [comment]
> think that's a problem with how **WhatsApp** is saving stickers rather than the stickers app itself

Exactly... that's why I tagged as [WhatsApp Bug]. Because the admins of this project are also part of the WhatsApp development team. 
However, I notice less number of complaints of this kind. I guess some fix was made in WhatsApp.

**Comment by Korogba** [comment]
Hi @santi-petersen, I am unable to reproduce this. Should we close this if you are no longer getting reports of this?

**Comment by santi-petersen** [comment]
> Hi @santi-petersen, I am unable to reproduce this. Should we close this if you are no longer getting reports of this?

Yes, we can close it. It was an old bug, there were no new reports from users.
