### ISSUE TITLE
[Android] I cannot build src

### ISSUE THREAD

**Issue by williamvietnam** [WhatsApp/stickers#951]
I pull src to build in my computer on Android Studio Flamingo | 2022.1 Patch 1
Step 1: Android Studio require I change gradle from 6.5 to 7.2
Step 2: I remove code snippet         if (android.defaultConfig.applicationId == "com.example.samplestickerapp") {
            throw new GradleException("Your applicationId is currently com.example.samplestickerapp, please change your applicationId to a different string in app/build.gradle in line 10")
        }       in build.gralde(app)
After display error: Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @52639e65

Can you help me please

**Comment by williamvietnam** [comment]
I resolved this problem

**Comment by amit-ilan** [comment]
@williamvietnam Can you please share your insights?

**Comment by amit-ilan** [comment]
A possible quick fix is to explicitly open the java.io package to app module by adding a JVM argument to `gradle.properties` like this: 
`org.gradle.jvmargs=-Xmx1536m --add-opens=java.base/java.io=ALL-UNNAMED`
