### ISSUE TITLE
WhatsApp onetime photo privacy 

### ISSUE THREAD

**Issue by themanoftalent** [WhatsApp/stickers#954]
WhatsApp Developer Team,

My name is Mehmet Akif Cifci, and I am a computer scientist. I wanted to bring to your attention a bug I have encountered in WhatsApp regarding the "WhatsApp onetime sent photo" feature. When a photo is sent for one time and is then pressed and left, it can be turned into a sticker. Then the photo can be sent to another contact as a sticker.

I believe this issue could be affecting the user privacy, and I wanted to report it to you for further investigation and potential resolution. If you require any additional information or further clarification, please let me know. 

Thank you for your attention to this matter.

Best regards,
Mehmet Akif Cifci

**Comment by MarvinJWendt** [comment]
Hi @themanoftalent, thanks for reporting this. I think this might not be the right place tho. WhatsApp employees are not regularly checking this repository out. You might even be able to qualify for Metas bug bounty program: https://www.whatsapp.com/security/advisories.

Please see here, how to submit a report: https://www.facebook.com/whitehat

By any chance, maybe @simonzhexu or @amrit-1901 will see it here, but submitting trough the bug bounty program is definitely worth a shot.

**Comment by themanoftalent** [comment]
Thanks
