### ISSUE TITLE
App detects I have 0 stickers

### ISSUE THREAD

**Issue by 0smaK** [WhatsApp/stickers#96]
Hi! I added 7 stickers to my pack but when I try to add to whatsapp an error appear
`Third Party sticker pack sticker count should be between 3 to 30 inclusive, it currently has 0...`

my **contents.json**

`{
  "android_play_store_link": "",
  "ios_app_store_link": "",
  "sticker_packs": [
    {
      "identifier": "1",
      "name": "stkname",
      "publisher": "osmvk",
      "tray_image_file": "img.png",
      "publisher_email":"example@email.com",
      "publisher_website": "https://github.com/0smaK/Whatsapp-Stickers-Kubistas",
      "privacy_policy_website": "",
      "license_agreement_website": "",
      "stickers": [
        {
          "image_file": "01_kubo.webp",
          "emojis": ["🗑️","💩"]
        },
        {
          "image_file": "02_pollo.webp",
          "emojis": ["🐔","🍗"]
        },
        {
          "image_file": "03_pollo-face.webp",
          "emojis": ["🐔","😲"]
        },
        {
          "image_file": "04_kubistas-duchense.webp",
          "emojis": ["🚿","💩"]
        },
        {
          "image_file": "05_kubistas-hdp.webp",
          "emojis": ["🤬","😤"]
        },
        {
          "image_file": "06_nug.webp",
          "emojis": ["🍁","☘️"]
        },
        {
          "image_file": "07_tabako-joako.webp",
          "emojis": ["🚬","🔥"]
        }
      ]
    }
  ]
}
`

**Comment by shineeasley** [comment]
Please change the application name and signature. Then render it and run it, you should select "Install anyway" If not, check ... / assets / 1. Could be name error

**Comment by 0smaK** [comment]
I fixed it, removing the webp images and converting the png images with android studio, and now it works
