### ISSUE TITLE
[Android] Please, update the code to match new Google Play politics

### ISSUE THREAD

**Issue by mediapinta** [WhatsApp/stickers#982]
Hi,

I'm a total n00b and last year I was able to create an Android Stickers App for WhatsApp just making a couple of changes in the code. But this year the same process was a hell of errors, trial and error of partial solutions from Stackoverflow, and starting again too much times...

I think the problem come from the new politics Google Play set in August 2023¹. Some parts of the code from here doesn't fit the new requirements.

As I said, I'm a n00b and I can't understand most of the errors Android Studio or Google Play Console give to me. I'm sorry I can't give more details.

Greetings,
ifrit

¹ https://support.google.com/googleplay/android-developer/answer/11926878

**Comment by MarvinStelter** [comment]
These requirments will change every year and basically you just need to increase the target api

**Comment by MarvinStelter** [comment]
These requirements will change every year, you basically just need to set the target api in the build gradle to 33 or 34
